2018-09-29 01:05:26.592 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:05:26.596 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:06:26.593 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:06:26.598 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:07:10.369 1891 DEBUG oslo_concurrency.lockutils [req-c5524293-98d8-4043-af77-75e63e731517 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:07:11.474 1891 DEBUG neutron.agent.dhcp.agent [req-296540ce-2b47-465a-b0f3-67a9cdec53e5 - - - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: enable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:07:11.475 1891 DEBUG neutron.agent.linux.utils [req-296540ce-2b47-465a-b0f3-67a9cdec53e5 - - - - -] Unable to access /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:11.475 1891 DEBUG neutron.agent.linux.dhcp [req-296540ce-2b47-465a-b0f3-67a9cdec53e5 - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-f33a12f2-6181-4426-bf72-7b3410029c1c on network f33a12f2-6181-4426-bf72-7b3410029c1c does not yet exist. Checking for a reserved port. _setup_reserved_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1272
2018-09-29 01:07:11.476 1891 DEBUG neutron.agent.linux.dhcp [req-296540ce-2b47-465a-b0f3-67a9cdec53e5 - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-f33a12f2-6181-4426-bf72-7b3410029c1c on network f33a12f2-6181-4426-bf72-7b3410029c1c does not yet exist. Creating new one. _setup_new_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1293
2018-09-29 01:07:14.724 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.745 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'add', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.763 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'sysctl', '-w', 'net.ipv4.conf.all.promote_secondaries=1'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.783 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', 'link', 'set', 'lo', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.796 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'sysctl', '-w', 'net.ipv6.conf.default.accept_ra=0'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.812 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', 'link', 'set', 'tapda0c0b39-0e', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.839 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-o', 'link', 'show', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.856 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-09-29 01:07:14.876 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=None, port=tapda0c0b39-0e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 01:07:14.878 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Transaction caused no change do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:114
2018-09-29 01:07:14.879 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): AddPortCommand(bridge=br-int, may_exist=False, port=tapda0c0b39-0e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 01:07:14.880 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=1): DbSetCommand(table=Port, col_values=(('tag', 4095),), record=tapda0c0b39-0e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 01:07:14.881 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=2): DbSetCommand(table=Interface, col_values=(('type', 'internal'), ('external_ids', {'iface-id': u'da0c0b39-0e40-402c-8d70-00218fc6db14', 'iface-status': 'active', 'attached-mac': u'fa:16:3e:8a:eb:69'})), record=tapda0c0b39-0e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 01:07:14.913 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tapda0c0b39-0e', 'address', 'fa:16:3e:8a:eb:69'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.942 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.953 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tapda0c0b39-0e', 'netns', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.973 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', 'link', 'set', 'tapda0c0b39-0e', 'mtu', '1450'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:14.986 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', 'link', 'set', 'tapda0c0b39-0e', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.001 1891 DEBUG oslo_concurrency.lockutils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Acquired semaphore "iptables-qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:07:15.002 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'iptables-save'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.026 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'iptables-restore', '-n'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.047 1891 DEBUG neutron.agent.linux.iptables_manager [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] IPTablesManager.apply completed with success. 56 iptables commands were issued _apply_synchronized /usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py:601
2018-09-29 01:07:15.049 1891 DEBUG oslo_concurrency.lockutils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Releasing semaphore "iptables-qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:07:15.050 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-o', 'link', 'show', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.065 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', 'addr', 'show', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.079 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'addr', 'add', '11.11.1.2/24', 'scope', 'global', 'dev', 'tapda0c0b39-0e', 'brd', '11.11.1.255'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.094 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.108 1891 DEBUG neutron.agent.linux.dhcp [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Setting IPv4 gateway for dhcp netns on net f33a12f2-6181-4426-bf72-7b3410029c1c to 11.11.1.1 _set_default_route_ip_version /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1169
2018-09-29 01:07:15.110 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'replace', 'default', 'via', '11.11.1.1', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.125 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.138 1891 DEBUG neutron.agent.linux.dhcp [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Cleaning stale devices for network f33a12f2-6181-4426-bf72-7b3410029c1c _cleanup_stale_devices /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1374
2018-09-29 01:07:15.139 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.149 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'find', '/sys/class/net', '-maxdepth', '1', '-type', 'l', '-printf', '%f '] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.163 1891 DEBUG neutron.agent.linux.dhcp [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Building initial lease file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/leases _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:626
2018-09-29 01:07:15.165 1891 DEBUG neutron.agent.linux.dhcp [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Done building initial lease file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/leases with contents:
1538284035 fa:16:3e:8a:eb:69 11.11.1.2 * *
 _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:654
2018-09-29 01:07:15.166 1891 DEBUG neutron.agent.linux.dhcp [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:07:15.168 1891 DEBUG neutron.agent.linux.dhcp [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:07:15.171 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Unable to access /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:15.172 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'dnsmasq', '--no-hosts', '--no-resolv', '--strict-order', '--except-interface=lo', '--pid-file=/var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/pid', '--dhcp-hostsfile=/var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host', '--addn-hosts=/var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/addn_hosts', '--dhcp-optsfile=/var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/opts', '--dhcp-leasefile=/var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/leases', '--dhcp-match=set:ipxe,175', '--bind-interfaces', '--interface=tapda0c0b39-0e', '--dhcp-range=set:tag0,11.11.1.0,static,255.255.255.0,86400s', '--dhcp-option-force=option:mtu,1450', '--dhcp-lease-max=256', '--conf-file=', '--domain=openstacklocal'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.199 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:15.200 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:15.201 1891 DEBUG neutron.agent.linux.external_process [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:07:15.201 1891 DEBUG oslo_concurrency.lockutils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:07:15.203 1891 DEBUG oslo_concurrency.lockutils [req-c5524293-98d8-4043-af77-75e63e731517 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:07:15.677 1891 DEBUG neutron.agent.dhcp.agent [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:07:15.679 1891 DEBUG neutron.agent.linux.dhcp [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:07:15.682 1891 DEBUG neutron.agent.linux.dhcp [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:07:15.689 1891 DEBUG neutron.agent.linux.utils [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.703 1891 DEBUG neutron.agent.linux.dhcp [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:07:15.705 1891 DEBUG neutron.agent.linux.utils [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.718 1891 DEBUG neutron.agent.linux.utils [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.733 1891 DEBUG neutron.agent.linux.utils [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:15.734 1891 DEBUG neutron.agent.linux.utils [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:15.735 1891 DEBUG neutron.agent.linux.external_process [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:07:15.737 1891 DEBUG oslo_concurrency.lockutils [req-1332e6d2-ed18-4197-90cc-bfe0fb0b2069 - - - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:07:15.738 1891 DEBUG oslo_concurrency.lockutils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:07:15.739 1891 DEBUG neutron.agent.dhcp.agent [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Discarding stale port update: admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T05:07:11Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-f33a12f2-6181-4426-bf72-7b3410029c1c, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'a42c4c2e-3199-45bc-b2f7-9b0aa65ec395', u'ip_address': u'11.11.1.2'}], id=da0c0b39-0e40-402c-8d70-00218fc6db14, mac_address=fa:16:3e:8a:eb:69, name=, network_id=f33a12f2-6181-4426-bf72-7b3410029c1c, port_security_enabled=False, project_id=65191f795ad643a8973b96e970e0a037, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=65191f795ad643a8973b96e970e0a037, updated_at=2018-09-29T05:07:12Z port_update_end /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:410
2018-09-29 01:07:15.740 1891 DEBUG oslo_concurrency.lockutils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:07:15.741 1891 DEBUG oslo_concurrency.lockutils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:07:15.742 1891 INFO neutron.agent.dhcp.agent [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-29T05:07:11Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-f33a12f2-6181-4426-bf72-7b3410029c1c, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'a42c4c2e-3199-45bc-b2f7-9b0aa65ec395', u'ip_address': u'11.11.1.2'}], id=da0c0b39-0e40-402c-8d70-00218fc6db14, mac_address=fa:16:3e:8a:eb:69, name=, network_id=f33a12f2-6181-4426-bf72-7b3410029c1c, port_security_enabled=False, project_id=65191f795ad643a8973b96e970e0a037, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=65191f795ad643a8973b96e970e0a037, updated_at=2018-09-29T05:07:14Z
2018-09-29 01:07:15.743 1891 DEBUG neutron.agent.dhcp.agent [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:07:15.745 1891 DEBUG neutron.agent.linux.dhcp [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:07:15.752 1891 DEBUG neutron.agent.linux.dhcp [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:07:15.757 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.778 1891 DEBUG neutron.agent.linux.dhcp [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:07:15.780 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.795 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:15.812 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:15.812 1891 DEBUG neutron.agent.linux.utils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:15.813 1891 DEBUG neutron.agent.linux.external_process [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:07:15.814 1891 DEBUG oslo_concurrency.lockutils [req-99b9e3b1-2984-4f7d-90b3-c971eca3f3a9 - - - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:07:26.593 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:07:26.597 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:07:51.920 1891 DEBUG oslo_concurrency.lockutils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:07:51.921 1891 INFO neutron.agent.dhcp.agent [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T05:07:50Z, description=, device_id=d17382f2-ce65-4ee3-92c1-d19df28c610e, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'a42c4c2e-3199-45bc-b2f7-9b0aa65ec395', u'ip_address': u'11.11.1.1'}], id=bfc880fc-72e9-4d11-ac3f-f7e0d3c4ff3e, mac_address=fa:16:3e:67:30:95, name=, network_id=f33a12f2-6181-4426-bf72-7b3410029c1c, port_security_enabled=False, project_id=65191f795ad643a8973b96e970e0a037, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=65191f795ad643a8973b96e970e0a037, updated_at=2018-09-29T05:07:51Z
2018-09-29 01:07:51.924 1891 DEBUG neutron.agent.dhcp.agent [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:07:51.928 1891 DEBUG neutron.agent.linux.dhcp [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:07:51.933 1891 DEBUG neutron.agent.linux.dhcp [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:07:51.942 1891 DEBUG neutron.agent.linux.utils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:51.970 1891 DEBUG neutron.agent.linux.dhcp [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:07:51.972 1891 DEBUG neutron.agent.linux.utils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:51.998 1891 DEBUG neutron.agent.linux.utils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:52.023 1891 DEBUG neutron.agent.linux.utils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:52.025 1891 DEBUG neutron.agent.linux.utils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:52.026 1891 DEBUG neutron.agent.linux.external_process [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:07:52.028 1891 DEBUG oslo_concurrency.lockutils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:07:53.907 1891 DEBUG oslo_concurrency.lockutils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:07:53.908 1891 INFO neutron.agent.dhcp.agent [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T05:07:50Z, description=, device_id=d17382f2-ce65-4ee3-92c1-d19df28c610e, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'a42c4c2e-3199-45bc-b2f7-9b0aa65ec395', u'ip_address': u'11.11.1.1'}], id=bfc880fc-72e9-4d11-ac3f-f7e0d3c4ff3e, mac_address=fa:16:3e:67:30:95, name=, network_id=f33a12f2-6181-4426-bf72-7b3410029c1c, port_security_enabled=False, project_id=65191f795ad643a8973b96e970e0a037, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=65191f795ad643a8973b96e970e0a037, updated_at=2018-09-29T05:07:51Z
2018-09-29 01:07:53.911 1891 DEBUG neutron.agent.dhcp.agent [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:07:53.914 1891 DEBUG neutron.agent.linux.dhcp [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:07:53.919 1891 DEBUG neutron.agent.linux.dhcp [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:07:53.926 1891 DEBUG neutron.agent.linux.utils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:53.944 1891 DEBUG neutron.agent.linux.dhcp [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:07:53.946 1891 DEBUG neutron.agent.linux.utils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:53.963 1891 DEBUG neutron.agent.linux.utils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:53.980 1891 DEBUG neutron.agent.linux.utils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:53.981 1891 DEBUG neutron.agent.linux.utils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:53.982 1891 DEBUG neutron.agent.linux.external_process [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:07:53.983 1891 DEBUG oslo_concurrency.lockutils [req-013fbd16-acee-4f4f-a098-f23127f2b7d8 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:07:57.158 1891 DEBUG oslo_concurrency.lockutils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:07:57.159 1891 INFO neutron.agent.dhcp.agent [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T05:07:50Z, description=, device_id=d17382f2-ce65-4ee3-92c1-d19df28c610e, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'a42c4c2e-3199-45bc-b2f7-9b0aa65ec395', u'ip_address': u'11.11.1.1'}], id=bfc880fc-72e9-4d11-ac3f-f7e0d3c4ff3e, mac_address=fa:16:3e:67:30:95, name=, network_id=f33a12f2-6181-4426-bf72-7b3410029c1c, port_security_enabled=False, project_id=65191f795ad643a8973b96e970e0a037, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=65191f795ad643a8973b96e970e0a037, updated_at=2018-09-29T05:07:52Z
2018-09-29 01:07:57.160 1891 DEBUG neutron.agent.dhcp.agent [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:07:57.161 1891 DEBUG neutron.agent.linux.dhcp [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:07:57.164 1891 DEBUG neutron.agent.linux.dhcp [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:07:57.170 1891 DEBUG neutron.agent.linux.utils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:57.183 1891 DEBUG neutron.agent.linux.dhcp [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:07:57.184 1891 DEBUG neutron.agent.linux.utils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:57.201 1891 DEBUG neutron.agent.linux.utils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:57.219 1891 DEBUG neutron.agent.linux.utils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:57.221 1891 DEBUG neutron.agent.linux.utils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:57.221 1891 DEBUG neutron.agent.linux.external_process [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:07:57.222 1891 DEBUG oslo_concurrency.lockutils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:07:58.108 1891 DEBUG oslo_concurrency.lockutils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:07:58.109 1891 INFO neutron.agent.dhcp.agent [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-29T05:07:50Z, description=, device_id=d17382f2-ce65-4ee3-92c1-d19df28c610e, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'a42c4c2e-3199-45bc-b2f7-9b0aa65ec395', u'ip_address': u'11.11.1.1'}], id=bfc880fc-72e9-4d11-ac3f-f7e0d3c4ff3e, mac_address=fa:16:3e:67:30:95, name=, network_id=f33a12f2-6181-4426-bf72-7b3410029c1c, port_security_enabled=False, project_id=65191f795ad643a8973b96e970e0a037, revision_number=6, security_groups=[], status=DOWN, tags=[], tenant_id=65191f795ad643a8973b96e970e0a037, updated_at=2018-09-29T05:07:57Z
2018-09-29 01:07:58.110 1891 DEBUG neutron.agent.dhcp.agent [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:07:58.112 1891 DEBUG neutron.agent.linux.dhcp [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:07:58.119 1891 DEBUG neutron.agent.linux.dhcp [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:07:58.125 1891 DEBUG neutron.agent.linux.utils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:58.140 1891 DEBUG neutron.agent.linux.dhcp [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:07:58.141 1891 DEBUG neutron.agent.linux.utils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:58.156 1891 DEBUG neutron.agent.linux.utils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:07:58.173 1891 DEBUG neutron.agent.linux.utils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:58.174 1891 DEBUG neutron.agent.linux.utils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:07:58.175 1891 DEBUG neutron.agent.linux.external_process [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:07:58.176 1891 DEBUG oslo_concurrency.lockutils [req-58ffa154-235e-4f62-a7e1-9c84ddecb72f - - - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:08:05.644 1891 DEBUG oslo_concurrency.lockutils [req-55398650-d9dc-488a-815f-55cfdd30ca16 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Acquired semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:08:05.647 1891 DEBUG oslo_concurrency.lockutils [req-55398650-d9dc-488a-815f-55cfdd30ca16 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Releasing semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:08:09.142 1891 DEBUG oslo_concurrency.lockutils [req-57895b68-b178-459c-9d8c-6a5b3cf2e2aa - - - - -] Acquired semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:08:09.144 1891 DEBUG oslo_concurrency.lockutils [req-57895b68-b178-459c-9d8c-6a5b3cf2e2aa - - - - -] Releasing semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:08:09.975 1891 DEBUG oslo_concurrency.lockutils [req-57895b68-b178-459c-9d8c-6a5b3cf2e2aa - - - - -] Acquired semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:08:09.976 1891 DEBUG oslo_concurrency.lockutils [req-57895b68-b178-459c-9d8c-6a5b3cf2e2aa - - - - -] Releasing semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:08:26.594 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:08:26.597 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:08:30.024 1891 DEBUG oslo_concurrency.lockutils [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:08:30.025 1891 INFO neutron.agent.dhcp.agent [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T05:08:28Z, description=, device_id=4d15add6-9a19-4420-b0ef-6b9e6ef14997, device_owner=, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'a42c4c2e-3199-45bc-b2f7-9b0aa65ec395', u'ip_address': u'11.11.1.3'}], id=2b3a60b8-0dd1-47e5-ade4-82e80de4e604, mac_address=fa:16:3e:93:43:a9, name=, network_id=f33a12f2-6181-4426-bf72-7b3410029c1c, port_security_enabled=True, project_id=65191f795ad643a8973b96e970e0a037, revision_number=3, security_groups=[u'd5844138-3b82-4b59-949f-8d9dbdb7a71a'], status=DOWN, tags=[], tenant_id=65191f795ad643a8973b96e970e0a037, updated_at=2018-09-29T05:08:29Z
2018-09-29 01:08:30.027 1891 DEBUG neutron.agent.dhcp.agent [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:08:30.028 1891 DEBUG neutron.agent.linux.dhcp [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:08:30.034 1891 DEBUG neutron.agent.linux.dhcp [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:08:30.040 1891 DEBUG neutron.agent.linux.utils [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:08:30.056 1891 DEBUG neutron.agent.linux.dhcp [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:08:30.057 1891 DEBUG neutron.agent.linux.utils [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:08:30.073 1891 DEBUG neutron.agent.linux.utils [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:08:30.086 1891 DEBUG neutron.agent.linux.utils [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:08:30.087 1891 DEBUG neutron.agent.linux.utils [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:08:30.087 1891 DEBUG neutron.agent.linux.external_process [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:08:30.088 1891 DEBUG oslo_concurrency.lockutils [req-5a236632-fb8c-483d-abe1-5f84dc232bd5 106d3364e83242f1b616535fe6901cbb 65191f795ad643a8973b96e970e0a037 - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:08:31.634 1891 DEBUG oslo_concurrency.lockutils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:08:31.635 1891 INFO neutron.agent.dhcp.agent [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T05:08:28Z, description=, device_id=4d15add6-9a19-4420-b0ef-6b9e6ef14997, device_owner=compute:nova, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'a42c4c2e-3199-45bc-b2f7-9b0aa65ec395', u'ip_address': u'11.11.1.3'}], id=2b3a60b8-0dd1-47e5-ade4-82e80de4e604, mac_address=fa:16:3e:93:43:a9, name=, network_id=f33a12f2-6181-4426-bf72-7b3410029c1c, port_security_enabled=True, project_id=65191f795ad643a8973b96e970e0a037, revision_number=4, security_groups=[u'd5844138-3b82-4b59-949f-8d9dbdb7a71a'], status=DOWN, tags=[], tenant_id=65191f795ad643a8973b96e970e0a037, updated_at=2018-09-29T05:08:30Z
2018-09-29 01:08:31.637 1891 DEBUG neutron.agent.dhcp.agent [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:08:31.638 1891 DEBUG neutron.agent.linux.dhcp [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:08:31.645 1891 DEBUG neutron.agent.linux.dhcp [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:08:31.651 1891 DEBUG neutron.agent.linux.utils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:08:31.663 1891 DEBUG neutron.agent.linux.dhcp [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:08:31.664 1891 DEBUG neutron.agent.linux.utils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:08:31.675 1891 DEBUG neutron.agent.linux.utils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:08:31.688 1891 DEBUG neutron.agent.linux.utils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:08:31.690 1891 DEBUG neutron.agent.linux.utils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:08:31.690 1891 DEBUG neutron.agent.linux.external_process [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:08:31.691 1891 DEBUG oslo_concurrency.lockutils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:08:32.428 1891 DEBUG oslo_concurrency.lockutils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:08:32.429 1891 INFO neutron.agent.dhcp.agent [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-29T05:08:28Z, description=, device_id=4d15add6-9a19-4420-b0ef-6b9e6ef14997, device_owner=compute:nova, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'a42c4c2e-3199-45bc-b2f7-9b0aa65ec395', u'ip_address': u'11.11.1.3'}], id=2b3a60b8-0dd1-47e5-ade4-82e80de4e604, mac_address=fa:16:3e:93:43:a9, name=, network_id=f33a12f2-6181-4426-bf72-7b3410029c1c, port_security_enabled=True, project_id=65191f795ad643a8973b96e970e0a037, revision_number=5, security_groups=[u'd5844138-3b82-4b59-949f-8d9dbdb7a71a'], status=DOWN, tags=[], tenant_id=65191f795ad643a8973b96e970e0a037, updated_at=2018-09-29T05:08:32Z
2018-09-29 01:08:32.431 1891 DEBUG neutron.agent.dhcp.agent [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:08:32.432 1891 DEBUG neutron.agent.linux.dhcp [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:08:32.434 1891 DEBUG neutron.agent.linux.dhcp [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:08:32.438 1891 DEBUG neutron.agent.linux.utils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:08:32.454 1891 DEBUG neutron.agent.linux.dhcp [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:08:32.456 1891 DEBUG neutron.agent.linux.utils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:08:32.472 1891 DEBUG neutron.agent.linux.utils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:08:32.490 1891 DEBUG neutron.agent.linux.utils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:08:32.491 1891 DEBUG neutron.agent.linux.utils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:08:32.492 1891 DEBUG neutron.agent.linux.external_process [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:08:32.494 1891 DEBUG oslo_concurrency.lockutils [req-d2a8fb3b-267a-4b37-9046-4284812441c3 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:08:55.965 1891 DEBUG oslo_concurrency.lockutils [req-962976b1-c1d9-4f92-a5d7-daf60b30cffa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:08:55.967 1891 DEBUG oslo_concurrency.lockutils [req-962976b1-c1d9-4f92-a5d7-daf60b30cffa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Releasing semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:08:57.048 1891 DEBUG oslo_concurrency.lockutils [req-962976b1-c1d9-4f92-a5d7-daf60b30cffa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:08:57.050 1891 DEBUG oslo_concurrency.lockutils [req-962976b1-c1d9-4f92-a5d7-daf60b30cffa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Releasing semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:09:26.594 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:09:26.599 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:10:26.594 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:10:26.598 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:11:26.594 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:11:26.600 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:12:26.595 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:12:26.601 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.007s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:13:16.959 1891 DEBUG oslo_concurrency.lockutils [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:13:16.960 1891 DEBUG neutron.agent.dhcp.agent [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:13:16.963 1891 DEBUG neutron.agent.linux.utils [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'dhcp_release', 'tapda0c0b39-0e', '11.11.1.3', 'fa:16:3e:93:43:a9'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:13:16.992 1891 DEBUG neutron.agent.linux.dhcp [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:13:17.000 1891 DEBUG neutron.agent.linux.dhcp [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:13:17.011 1891 DEBUG neutron.agent.linux.utils [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:13:17.027 1891 DEBUG neutron.agent.linux.dhcp [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:13:17.029 1891 DEBUG neutron.agent.linux.utils [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:13:17.050 1891 DEBUG neutron.agent.linux.utils [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:13:17.067 1891 DEBUG neutron.agent.linux.utils [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:13:17.067 1891 DEBUG neutron.agent.linux.utils [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:13:17.068 1891 DEBUG neutron.agent.linux.external_process [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:13:17.069 1891 DEBUG oslo_concurrency.lockutils [req-b9e7beb8-f38e-441d-b1ee-af58efb39dfa 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:13:26.595 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:13:26.599 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:14:09.362 1891 DEBUG oslo_concurrency.lockutils [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:14:09.364 1891 DEBUG neutron.agent.dhcp.agent [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:14:09.367 1891 DEBUG neutron.agent.linux.utils [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'dhcp_release', 'tapda0c0b39-0e', '11.11.1.1', 'fa:16:3e:67:30:95'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:09.392 1891 DEBUG neutron.agent.linux.dhcp [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:14:09.404 1891 DEBUG neutron.agent.linux.dhcp [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:14:09.423 1891 DEBUG neutron.agent.linux.utils [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:09.437 1891 DEBUG neutron.agent.linux.dhcp [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:14:09.441 1891 DEBUG neutron.agent.linux.utils [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:09.456 1891 DEBUG neutron.agent.linux.utils [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tapda0c0b39-0e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:09.475 1891 DEBUG neutron.agent.linux.utils [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:09.477 1891 DEBUG neutron.agent.linux.utils [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:09.479 1891 DEBUG neutron.agent.linux.external_process [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:14:09.480 1891 DEBUG oslo_concurrency.lockutils [req-f31c7836-6f4f-4193-a675-2dd99231935a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:14:26.595 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:14:26.600 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:14:39.129 1891 DEBUG oslo_concurrency.lockutils [req-9bfbc524-b5f4-491a-a728-1246f674ca12 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:14:39.131 1891 DEBUG neutron.agent.dhcp.agent [req-9bfbc524-b5f4-491a-a728-1246f674ca12 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:14:39.135 1891 DEBUG neutron.agent.linux.utils [req-9bfbc524-b5f4-491a-a728-1246f674ca12 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['kill', '-9', '10334'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:39.160 1891 DEBUG neutron.agent.linux.utils [req-9bfbc524-b5f4-491a-a728-1246f674ca12 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-09-29 01:14:39.198 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=br-int, port=tapda0c0b39-0e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 01:14:39.300 1891 DEBUG neutron.agent.linux.utils [req-00fd76a5-b022-4bf7-b223-d3d63c80948a - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:39.318 1891 DEBUG neutron.agent.linux.utils [req-00fd76a5-b022-4bf7-b223-d3d63c80948a - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'delete', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:39.334 1891 DEBUG oslo_concurrency.lockutils [req-00fd76a5-b022-4bf7-b223-d3d63c80948a - - - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:14:47.057 1891 DEBUG neutron.agent.dhcp.agent [req-0eb831c2-4a7c-420c-8cc4-d2f9e8c4ea5d - - - - -] resync (f33a12f2-6181-4426-bf72-7b3410029c1c): ['Agent port was deleted'] _periodic_resync_helper /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:256
2018-09-29 01:14:47.059 1891 INFO neutron.agent.dhcp.agent [req-0eb831c2-4a7c-420c-8cc4-d2f9e8c4ea5d - - - - -] Synchronizing state
2018-09-29 01:14:47.937 1891 INFO neutron.agent.dhcp.agent [req-b47638dd-09f6-46d1-8934-b8629ad4b376 - - - - -] All active networks have been fetched through RPC.
2018-09-29 01:14:47.939 1891 INFO neutron.agent.dhcp.agent [-] Starting network 7fc29900-2b68-444d-aebd-eb83e6248a3d dhcp configuration
2018-09-29 01:14:47.940 1891 INFO neutron.agent.dhcp.agent [-] Finished network 7fc29900-2b68-444d-aebd-eb83e6248a3d dhcp configuration
2018-09-29 01:14:47.940 1891 INFO neutron.agent.dhcp.agent [-] Starting network f33a12f2-6181-4426-bf72-7b3410029c1c dhcp configuration
2018-09-29 01:14:47.941 1891 DEBUG neutron.agent.dhcp.agent [-] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: enable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:14:47.943 1891 DEBUG neutron.agent.linux.utils [-] Unable to access /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:47.944 1891 DEBUG neutron.agent.linux.dhcp [-] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-f33a12f2-6181-4426-bf72-7b3410029c1c on network f33a12f2-6181-4426-bf72-7b3410029c1c does not yet exist. Checking for a reserved port. _setup_reserved_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1272
2018-09-29 01:14:47.945 1891 DEBUG neutron.agent.linux.dhcp [-] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-f33a12f2-6181-4426-bf72-7b3410029c1c on network f33a12f2-6181-4426-bf72-7b3410029c1c does not yet exist. Creating new one. _setup_new_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1293
2018-09-29 01:14:50.982 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.003 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'add', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.019 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'sysctl', '-w', 'net.ipv4.conf.all.promote_secondaries=1'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.047 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', 'link', 'set', 'lo', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.069 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'sysctl', '-w', 'net.ipv6.conf.default.accept_ra=0'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.102 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', 'link', 'set', 'tap5468ea8e-49', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.141 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-o', 'link', 'show', 'tap5468ea8e-49'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.170 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-09-29 01:14:51.203 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=None, port=tap5468ea8e-49) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 01:14:51.206 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Transaction caused no change do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:114
2018-09-29 01:14:51.208 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): AddPortCommand(bridge=br-int, may_exist=False, port=tap5468ea8e-49) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 01:14:51.210 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=1): DbSetCommand(table=Port, col_values=(('tag', 4095),), record=tap5468ea8e-49) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 01:14:51.211 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=2): DbSetCommand(table=Interface, col_values=(('type', 'internal'), ('external_ids', {'iface-id': u'5468ea8e-4956-4c07-8133-6db4bd21a9e8', 'iface-status': 'active', 'attached-mac': u'fa:16:3e:1c:68:41'})), record=tap5468ea8e-49) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 01:14:51.257 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tap5468ea8e-49', 'address', 'fa:16:3e:1c:68:41'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.276 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.293 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tap5468ea8e-49', 'netns', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.318 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', 'link', 'set', 'tap5468ea8e-49', 'mtu', '1450'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.337 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', 'link', 'set', 'tap5468ea8e-49', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.362 1891 DEBUG oslo_concurrency.lockutils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Acquired semaphore "iptables-qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:14:51.364 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'iptables-save'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.389 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'iptables-restore', '-n'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.415 1891 DEBUG neutron.agent.linux.iptables_manager [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] IPTablesManager.apply completed with success. 56 iptables commands were issued _apply_synchronized /usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py:601
2018-09-29 01:14:51.416 1891 DEBUG oslo_concurrency.lockutils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Releasing semaphore "iptables-qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:14:51.418 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-o', 'link', 'show', 'tap5468ea8e-49'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.435 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', 'addr', 'show', 'tap5468ea8e-49'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.452 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'addr', 'add', '11.11.1.2/24', 'scope', 'global', 'dev', 'tap5468ea8e-49', 'brd', '11.11.1.255'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.467 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tap5468ea8e-49'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.485 1891 DEBUG neutron.agent.linux.dhcp [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Setting IPv4 gateway for dhcp netns on net f33a12f2-6181-4426-bf72-7b3410029c1c to 11.11.1.1 _set_default_route_ip_version /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1169
2018-09-29 01:14:51.487 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'replace', 'default', 'via', '11.11.1.1', 'dev', 'tap5468ea8e-49'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.506 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tap5468ea8e-49'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.524 1891 DEBUG neutron.agent.linux.dhcp [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Cleaning stale devices for network f33a12f2-6181-4426-bf72-7b3410029c1c _cleanup_stale_devices /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1374
2018-09-29 01:14:51.525 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.538 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'find', '/sys/class/net', '-maxdepth', '1', '-type', 'l', '-printf', '%f '] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.561 1891 DEBUG neutron.agent.linux.dhcp [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Building initial lease file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/leases _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:626
2018-09-29 01:14:51.562 1891 DEBUG neutron.agent.linux.dhcp [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Done building initial lease file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/leases with contents:
1538284491 fa:16:3e:1c:68:41 11.11.1.2 * *
 _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:654
2018-09-29 01:14:51.564 1891 DEBUG neutron.agent.linux.dhcp [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:14:51.567 1891 DEBUG neutron.agent.linux.dhcp [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:14:51.571 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Unable to access /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:51.574 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'dnsmasq', '--no-hosts', '--no-resolv', '--strict-order', '--except-interface=lo', '--pid-file=/var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/pid', '--dhcp-hostsfile=/var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host', '--addn-hosts=/var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/addn_hosts', '--dhcp-optsfile=/var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/opts', '--dhcp-leasefile=/var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/leases', '--dhcp-match=set:ipxe,175', '--bind-interfaces', '--interface=tap5468ea8e-49', '--dhcp-range=set:tag0,11.11.1.0,static,255.255.255.0,86400s', '--dhcp-option-force=option:mtu,1450', '--dhcp-lease-max=256', '--conf-file=', '--domain=openstacklocal'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.610 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:51.611 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:51.612 1891 DEBUG neutron.agent.linux.external_process [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:14:51.613 1891 INFO neutron.agent.dhcp.agent [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Finished network f33a12f2-6181-4426-bf72-7b3410029c1c dhcp configuration
2018-09-29 01:14:51.614 1891 INFO neutron.agent.dhcp.agent [req-b47638dd-09f6-46d1-8934-b8629ad4b376 - - - - -] Synchronizing state complete
2018-09-29 01:14:51.616 1891 DEBUG oslo_concurrency.lockutils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:14:51.617 1891 INFO neutron.agent.dhcp.agent [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T05:14:48Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-f33a12f2-6181-4426-bf72-7b3410029c1c, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'a42c4c2e-3199-45bc-b2f7-9b0aa65ec395', u'ip_address': u'11.11.1.2'}], id=5468ea8e-4956-4c07-8133-6db4bd21a9e8, mac_address=fa:16:3e:1c:68:41, name=, network_id=f33a12f2-6181-4426-bf72-7b3410029c1c, port_security_enabled=False, project_id=65191f795ad643a8973b96e970e0a037, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=65191f795ad643a8973b96e970e0a037, updated_at=2018-09-29T05:14:49Z
2018-09-29 01:14:51.618 1891 DEBUG neutron.agent.dhcp.agent [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:14:51.630 1891 DEBUG neutron.agent.linux.dhcp [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Building host file: /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 01:14:51.639 1891 DEBUG neutron.agent.linux.dhcp [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Done building host file /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 01:14:51.652 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '13613'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.669 1891 DEBUG neutron.agent.linux.dhcp [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Reloading allocations for network: f33a12f2-6181-4426-bf72-7b3410029c1c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 01:14:51.671 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-4', 'route', 'list', 'dev', 'tap5468ea8e-49'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.687 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c', 'ip', '-6', 'route', 'list', 'dev', 'tap5468ea8e-49'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.708 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:51.709 1891 DEBUG neutron.agent.linux.utils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:51.710 1891 DEBUG neutron.agent.linux.external_process [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:14:51.713 1891 DEBUG oslo_concurrency.lockutils [req-e3549ebe-ae64-4412-843e-3f73d0b11abe - - - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:14:51.715 1891 DEBUG oslo_concurrency.lockutils [req-55042ff0-b677-449b-bef1-f984745dc833 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:14:51.716 1891 DEBUG neutron.agent.dhcp.agent [req-55042ff0-b677-449b-bef1-f984745dc833 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:14:51.719 1891 DEBUG neutron.agent.linux.utils [req-55042ff0-b677-449b-bef1-f984745dc833 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['kill', '-9', '13613'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.737 1891 DEBUG neutron.agent.linux.utils [req-55042ff0-b677-449b-bef1-f984745dc833 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-09-29 01:14:51.764 1891 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=br-int, port=tap5468ea8e-49) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 01:14:51.862 1891 DEBUG neutron.agent.linux.utils [req-d9928140-a998-4441-8747-472bbd52978c - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.875 1891 DEBUG neutron.agent.linux.utils [req-d9928140-a998-4441-8747-472bbd52978c - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'delete', 'qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:51.889 1891 DEBUG oslo_concurrency.lockutils [req-d9928140-a998-4441-8747-472bbd52978c - - - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:14:52.727 1891 DEBUG oslo_concurrency.lockutils [req-55042ff0-b677-449b-bef1-f984745dc833 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:14:53.143 1891 DEBUG neutron.agent.linux.utils [req-3abd0378-dae4-4f52-8314-2587a1495f29 - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:53.144 1891 DEBUG neutron.agent.linux.utils [req-3abd0378-dae4-4f52-8314-2587a1495f29 - - - - -] Unable to access /var/lib/neutron/external/pids/f33a12f2-6181-4426-bf72-7b3410029c1c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:53.146 1891 DEBUG neutron.agent.linux.external_process [req-3abd0378-dae4-4f52-8314-2587a1495f29 - - - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:14:53.147 1891 DEBUG neutron.agent.dhcp.agent [req-3abd0378-dae4-4f52-8314-2587a1495f29 - - - - -] Calling driver for network: f33a12f2-6181-4426-bf72-7b3410029c1c action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 01:14:53.149 1891 DEBUG neutron.agent.linux.utils [req-3abd0378-dae4-4f52-8314-2587a1495f29 - - - - -] Unable to access /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:53.150 1891 DEBUG neutron.agent.linux.utils [req-3abd0378-dae4-4f52-8314-2587a1495f29 - - - - -] Unable to access /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 01:14:53.151 1891 DEBUG neutron.agent.linux.external_process [req-3abd0378-dae4-4f52-8314-2587a1495f29 - - - - -] No process started for f33a12f2-6181-4426-bf72-7b3410029c1c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 01:14:53.152 1891 DEBUG neutron.agent.linux.dhcp [req-3abd0378-dae4-4f52-8314-2587a1495f29 - - - - -] Unable to access /var/lib/neutron/dhcp/f33a12f2-6181-4426-bf72-7b3410029c1c/interface _get_value_from_conf_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:271
2018-09-29 01:14:53.153 1891 DEBUG neutron.agent.linux.dhcp [req-3abd0378-dae4-4f52-8314-2587a1495f29 - - - - -] No interface exists for network f33a12f2-6181-4426-bf72-7b3410029c1c destroy /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1487
2018-09-29 01:14:53.198 1891 DEBUG neutron.agent.linux.utils [req-bbe615ce-137a-45e7-8218-864f85c55fe9 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 01:14:53.216 1891 DEBUG neutron.agent.linux.dhcp [req-bbe615ce-137a-45e7-8218-864f85c55fe9 - - - - -] Namespace already deleted: qdhcp-f33a12f2-6181-4426-bf72-7b3410029c1c _destroy_namespace_and_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:249
2018-09-29 01:14:53.219 1891 DEBUG oslo_concurrency.lockutils [req-bbe615ce-137a-45e7-8218-864f85c55fe9 - - - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:14:54.687 1891 DEBUG oslo_concurrency.lockutils [req-55042ff0-b677-449b-bef1-f984745dc833 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 01:14:54.688 1891 DEBUG oslo_concurrency.lockutils [req-55042ff0-b677-449b-bef1-f984745dc833 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Releasing semaphore "dhcp-agent-network-lock-f33a12f2-6181-4426-bf72-7b3410029c1c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 01:15:21.616 1891 DEBUG neutron.agent.dhcp.agent [req-b47638dd-09f6-46d1-8934-b8629ad4b376 - - - - -] resync (f33a12f2-6181-4426-bf72-7b3410029c1c): ['Agent port was deleted'] _periodic_resync_helper /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:256
2018-09-29 01:15:21.618 1891 INFO neutron.agent.dhcp.agent [req-b47638dd-09f6-46d1-8934-b8629ad4b376 - - - - -] Synchronizing state
2018-09-29 01:15:22.473 1891 INFO neutron.agent.dhcp.agent [req-4c1bb19b-0a94-40ed-836b-ce1b948120a0 - - - - -] All active networks have been fetched through RPC.
2018-09-29 01:15:22.475 1891 INFO neutron.agent.dhcp.agent [-] Starting network 7fc29900-2b68-444d-aebd-eb83e6248a3d dhcp configuration
2018-09-29 01:15:22.476 1891 INFO neutron.agent.dhcp.agent [-] Finished network 7fc29900-2b68-444d-aebd-eb83e6248a3d dhcp configuration
2018-09-29 01:15:22.476 1891 INFO neutron.agent.dhcp.agent [req-4c1bb19b-0a94-40ed-836b-ce1b948120a0 - - - - -] Synchronizing state complete
2018-09-29 01:15:26.595 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:15:26.600 1891 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
