2018-09-30 06:55:05.528 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 06:55:05.532 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 06:55:05.579 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 06:55:05.581 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 06:55:05.583 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:55:06.827 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.245s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:55:06.833 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:55:07.803 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 0.972s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:55:07.807 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:55:08.919 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.112s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:55:08.922 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:55:10.235 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.313s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:56:05.529 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 06:56:05.533 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 06:56:05.574 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 06:56:05.575 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 06:56:05.577 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:56:06.702 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.125s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:56:06.709 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:56:07.703 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 0.994s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:56:07.706 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:56:08.972 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.267s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:56:08.977 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:56:10.298 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.321s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:57:05.533 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 06:57:05.537 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 06:57:05.571 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 06:57:05.572 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 06:57:05.574 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:57:06.852 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.278s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:57:06.856 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:57:07.750 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 0.894s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:57:07.753 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:57:08.635 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 0.883s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:57:08.638 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:57:09.701 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.063s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:58:05.534 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 06:58:05.536 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 06:58:05.575 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 06:58:05.576 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 06:58:05.577 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:58:06.633 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.055s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:58:06.636 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:58:07.599 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 0.963s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:58:07.602 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:58:08.487 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 0.886s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:58:08.490 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:58:09.519 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.028s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:05.533 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 06:59:05.537 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 06:59:05.599 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 06:59:05.600 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 06:59:05.603 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:06.620 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.018s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:06.622 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:07.461 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 0.839s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:07.464 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:08.433 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 0.970s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:08.437 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:09.465 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.029s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:43.114 5486 DEBUG cinder.volume.flows.manager.create_volume [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Volume reschedule parameters: True retry: {u'num_attempts': 1, u'backends': [u'localhost.localdomain@lvm#lvm'], u'hosts': [u'localhost.localdomain@lvm#lvm']} get_flow /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:1126
2018-09-30 06:59:43.155 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Flow 'volume_create_manager' (88be4a71-55e4-4f54-b21e-1254414278de) transitioned into state 'RUNNING' from state 'PENDING' _flow_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:145
2018-09-30 06:59:43.161 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeRefTask;volume:create' (6894a94a-6db9-4e25-a279-6f4be59df7ce) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-30 06:59:43.203 5486 DEBUG oslo_db.sqlalchemy.engines [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 06:59:43.266 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeRefTask;volume:create' (6894a94a-6db9-4e25-a279-6f4be59df7ce) transitioned into state 'SUCCESS' from state 'RUNNING' with result 'Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2018-09-30T10:59:42Z,deleted=False,deleted_at=None,display_description=None,display_name='tempest-VOLUME_SAMPLE-1538304870',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='localhost.localdomain@lvm#lvm',id=4c12957e-62e7-49b2-90c7-87f67ea303b2,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='525ed35e0cfd44efad9c6bd864714413',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2018-09-30T10:59:42Z,size=1,snapshot_id=None,snapshots=<?>,source_volid=None,status='creating',terminated_at=None,updated_at=2018-09-30T10:59:42Z,user_id='6560e183015f4f0696d2c69498bdbf6c',volume_attachment=<?>,volume_type=VolumeType(d9c60c05-9188-4fa8-885a-e4f8424aa313),volume_type_id=d9c60c05-9188-4fa8-885a-e4f8424aa313)' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-30 06:59:43.273 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.OnFailureRescheduleTask;volume:create' (855d8106-ce28-47f2-b043-67abe38ccf9b) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-30 06:59:43.279 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.OnFailureRescheduleTask;volume:create' (855d8106-ce28-47f2-b043-67abe38ccf9b) transitioned into state 'SUCCESS' from state 'RUNNING' with result 'None' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-30 06:59:43.286 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeSpecTask;volume:create' (5bf5dfb0-2b10-4275-8baa-61a377f39645) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-30 06:59:43.291 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}d5341ac55b9854107ed3477ca6738e561b1208a0' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49' http://10.0.20.25:9292/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-30 06:59:43.431 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] GET call to image for http://10.0.20.25:9292/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc used request id req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-30 06:59:43.433 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] 
HTTP/1.1 200 OK
Content-Length: 616
Content-Type: application/json
X-Openstack-Request-Id: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49
Date: Sun, 30 Sep 2018 10:59:43 GMT
Connection: keep-alive

{"status": "active", "name": "tempest-cirros-0.4.0-x86_64-1538304870", "tags": [], "container_format": "bare", "created_at": "2018-09-30T10:55:25Z", "size": 12716032, "disk_format": "qcow2", "updated_at": "2018-09-30T10:55:25Z", "visibility": "public", "self": "/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc", "min_disk": 0, "protected": false, "id": "b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc", "file": "/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc/file", "checksum": "443b7623e27ecf03dc9e01ee93f67afe", "owner": "bd8a53962fd64ffeab7f2932b0e688c5", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-30 06:59:43.435 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}d5341ac55b9854107ed3477ca6738e561b1208a0' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49' http://10.0.20.25:9292/v2/schemas/image log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-30 06:59:43.457 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] GET call to image for http://10.0.20.25:9292/v2/schemas/image used request id req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-30 06:59:43.465 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49
Date: Sun, 30 Sep 2018 10:59:43 GMT
Connection: keep-alive

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-30 06:59:43.469 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}d5341ac55b9854107ed3477ca6738e561b1208a0' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49' http://10.0.20.25:9292/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-30 06:59:44.128 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] GET call to image for http://10.0.20.25:9292/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc used request id req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-30 06:59:44.130 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] 
HTTP/1.1 200 OK
Content-Length: 616
Content-Type: application/json
X-Openstack-Request-Id: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49
Date: Sun, 30 Sep 2018 10:59:44 GMT
Connection: keep-alive

{"status": "active", "name": "tempest-cirros-0.4.0-x86_64-1538304870", "tags": [], "container_format": "bare", "created_at": "2018-09-30T10:55:25Z", "size": 12716032, "disk_format": "qcow2", "updated_at": "2018-09-30T10:55:25Z", "visibility": "public", "self": "/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc", "min_disk": 0, "protected": false, "id": "b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc", "file": "/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc/file", "checksum": "443b7623e27ecf03dc9e01ee93f67afe", "owner": "bd8a53962fd64ffeab7f2932b0e688c5", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-30 06:59:44.132 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}d5341ac55b9854107ed3477ca6738e561b1208a0' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49' http://10.0.20.25:9292/v2/schemas/image log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-30 06:59:44.152 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] GET call to image for http://10.0.20.25:9292/v2/schemas/image used request id req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-30 06:59:44.154 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49
Date: Sun, 30 Sep 2018 10:59:44 GMT
Connection: keep-alive

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-30 06:59:44.159 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}d5341ac55b9854107ed3477ca6738e561b1208a0' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49' http://10.0.20.25:9292/v2/schemas/image log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-30 06:59:44.815 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] GET call to image for http://10.0.20.25:9292/v2/schemas/image used request id req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-30 06:59:44.818 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49
Date: Sun, 30 Sep 2018 10:59:44 GMT
Connection: keep-alive

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-30 06:59:44.824 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeSpecTask;volume:create' (5bf5dfb0-2b10-4275-8baa-61a377f39645) transitioned into state 'SUCCESS' from state 'RUNNING' with result '{'status': u'creating', 'image_location': (None, None), 'image_id': u'b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc', 'volume_id': u'4c12957e-62e7-49b2-90c7-87f67ea303b2', 'volume_size': 1, 'image_service': <cinder.image.glance.GlanceImageService object at 0x7fb7850c46d0>, 'image_meta': {u'status': u'active', u'name': u'tempest-cirros-0.4.0-x86_64-1538304870', u'tags': [], u'container_format': u'bare', u'created_at': datetime.datetime(2018, 9, 30, 10, 55, 25, tzinfo=<iso8601.Utc>), u'disk_format': u'qcow2', u'updated_at': datetime.datetime(2018, 9, 30, 10, 55, 25, tzinfo=<iso8601.Utc>), u'visibility': u'public', 'properties': {}, u'owner': u'bd8a53962fd64ffeab7f2932b0e688c5', u'protected': False, u'id': u'b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc', u'file': u'/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc/file', u'checksum': u'443b7623e27ecf03dc9e01ee93f67afe', u'min_disk': 0, u'virtual_size': None, u'min_ram': 0, u'size': 12716032}, 'volume_name': u'volume-4c12957e-62e7-49b2-90c7-87f67ea303b2', 'type': 'image'}' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-30 06:59:44.831 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.NotifyVolumeActionTask;volume:create, create.start' (39d06110-c919-442a-88a0-dfa75fdbb90c) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-30 06:59:44.894 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.NotifyVolumeActionTask;volume:create, create.start' (39d06110-c919-442a-88a0-dfa75fdbb90c) transitioned into state 'SUCCESS' from state 'RUNNING' with result 'None' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-30 06:59:44.899 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (2c440c9a-eaab-4eaa-b2fb-c7a52f788eb6) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-30 06:59:44.902 5486 INFO cinder.volume.flows.manager.create_volume [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Volume 4c12957e-62e7-49b2-90c7-87f67ea303b2: being created as image with specification: {'status': u'creating', 'image_location': (None, None), 'volume_size': 1, 'volume_name': u'volume-4c12957e-62e7-49b2-90c7-87f67ea303b2', 'image_id': u'b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc', 'image_service': <cinder.image.glance.GlanceImageService object at 0x7fb7850c46d0>, 'image_meta': {u'status': u'active', u'name': u'tempest-cirros-0.4.0-x86_64-1538304870', u'tags': [], u'container_format': u'bare', u'created_at': datetime.datetime(2018, 9, 30, 10, 55, 25, tzinfo=<iso8601.Utc>), u'disk_format': u'qcow2', u'updated_at': datetime.datetime(2018, 9, 30, 10, 55, 25, tzinfo=<iso8601.Utc>), u'visibility': u'public', 'properties': {}, u'owner': u'bd8a53962fd64ffeab7f2932b0e688c5', u'protected': False, u'id': u'b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc', u'file': u'/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc/file', u'checksum': u'443b7623e27ecf03dc9e01ee93f67afe', u'min_disk': 0, u'virtual_size': None, u'min_ram': 0, u'size': 12716032}}
2018-09-30 06:59:44.903 5486 DEBUG cinder.volume.flows.manager.create_volume [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Cloning 4c12957e-62e7-49b2-90c7-87f67ea303b2 from image b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc  at location (None, None). _create_from_image /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:896
2018-09-30 06:59:44.910 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}d5341ac55b9854107ed3477ca6738e561b1208a0' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49' http://10.0.20.25:9292/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc/file log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-30 06:59:45.626 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] GET call to image for http://10.0.20.25:9292/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc/file used request id req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-30 06:59:45.627 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] 
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Content-Md5: 443b7623e27ecf03dc9e01ee93f67afe
Content-Length: 12716032
X-Openstack-Request-Id: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49
Date: Sun, 30 Sep 2018 10:59:45 GMT
Connection: keep-alive
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-30 06:59:45.806 5486 DEBUG cinder.image.image_utils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Image fetch details: dest /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm, size 12.00 MB, duration 1.00 sec fetch /usr/lib/python2.7/site-packages/cinder/image/image_utils.py:247
2018-09-30 06:59:45.808 5486 INFO cinder.image.image_utils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Image download 12.00 MB at 12.00 MB/s
2018-09-30 06:59:45.811 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}d5341ac55b9854107ed3477ca6738e561b1208a0' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49' http://10.0.20.25:9292/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-30 06:59:45.887 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] GET call to image for http://10.0.20.25:9292/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc used request id req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-30 06:59:45.889 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] 
HTTP/1.1 200 OK
Content-Length: 616
Content-Type: application/json
X-Openstack-Request-Id: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49
Date: Sun, 30 Sep 2018 10:59:45 GMT
Connection: keep-alive

{"status": "active", "name": "tempest-cirros-0.4.0-x86_64-1538304870", "tags": [], "container_format": "bare", "created_at": "2018-09-30T10:55:25Z", "size": 12716032, "disk_format": "qcow2", "updated_at": "2018-09-30T10:55:25Z", "visibility": "public", "self": "/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc", "min_disk": 0, "protected": false, "id": "b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc", "file": "/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc/file", "checksum": "443b7623e27ecf03dc9e01ee93f67afe", "owner": "bd8a53962fd64ffeab7f2932b0e688c5", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-30 06:59:45.891 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}d5341ac55b9854107ed3477ca6738e561b1208a0' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49' http://10.0.20.25:9292/v2/schemas/image log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-30 06:59:45.932 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] GET call to image for http://10.0.20.25:9292/v2/schemas/image used request id req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-30 06:59:45.936 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49
Date: Sun, 30 Sep 2018 10:59:45 GMT
Connection: keep-alive

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-30 06:59:45.943 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:47.376 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm" returned: 0 in 1.434s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:47.379 5486 DEBUG cinder.image.image_utils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Temporary image b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc is fetched for user 6560e183015f4f0696d2c69498bdbf6c. fetch /usr/lib/python2.7/site-packages/cinder/image/image_utils.py:672
2018-09-30 06:59:47.382 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:48.607 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm" returned: 0 in 1.225s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:48.612 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvcreate -T -V 1g -n volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:50.118 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvcreate -T -V 1g -n volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.507s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:50.159 5486 DEBUG cinder.volume.flows.manager.create_volume [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Attempting download of b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc ((None, None)) to volume 4c12957e-62e7-49b2-90c7-87f67ea303b2. _copy_image_to_volume /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:536
2018-09-30 06:59:50.163 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}d5341ac55b9854107ed3477ca6738e561b1208a0' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49' http://10.0.20.25:9292/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-30 06:59:50.206 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] GET call to image for http://10.0.20.25:9292/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc used request id req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-30 06:59:50.209 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] 
HTTP/1.1 200 OK
Content-Length: 616
Content-Type: application/json
X-Openstack-Request-Id: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49
Date: Sun, 30 Sep 2018 10:59:50 GMT
Connection: keep-alive

{"status": "active", "name": "tempest-cirros-0.4.0-x86_64-1538304870", "tags": [], "container_format": "bare", "created_at": "2018-09-30T10:55:25Z", "size": 12716032, "disk_format": "qcow2", "updated_at": "2018-09-30T10:55:25Z", "visibility": "public", "self": "/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc", "min_disk": 0, "protected": false, "id": "b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc", "file": "/v2/images/b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc/file", "checksum": "443b7623e27ecf03dc9e01ee93f67afe", "owner": "bd8a53962fd64ffeab7f2932b0e688c5", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-30 06:59:50.210 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}d5341ac55b9854107ed3477ca6738e561b1208a0' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49' http://10.0.20.25:9292/v2/schemas/image log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-30 06:59:50.229 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] GET call to image for http://10.0.20.25:9292/v2/schemas/image used request id req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-30 06:59:50.232 5486 DEBUG glanceclient.common.http [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49
Date: Sun, 30 Sep 2018 10:59:50 GMT
Connection: keep-alive

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-30 06:59:50.239 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpKtb_iU execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:51.374 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpKtb_iU" returned: 0 in 1.135s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:51.378 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:52.840 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm" returned: 0 in 1.462s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:52.844 5486 DEBUG cinder.image.image_utils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc was qcow2, converting to raw  fetch_to_volume_format /usr/lib/python2.7/site-packages/cinder/image/image_utils.py:417
2018-09-30 06:59:52.847 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf dd count=0 if=/var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm of=/dev/mapper/cinder--volumes2-volume--4c12957e--62e7--49b2--90c7--87f67ea303b2 oflag=direct execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:54.080 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf dd count=0 if=/var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm of=/dev/mapper/cinder--volumes2-volume--4c12957e--62e7--49b2--90c7--87f67ea303b2 oflag=direct" returned: 0 in 1.234s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:54.083 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf qemu-img convert -t none -f qcow2 -O raw /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm /dev/mapper/cinder--volumes2-volume--4c12957e--62e7--49b2--90c7--87f67ea303b2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:56.374 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf qemu-img convert -t none -f qcow2 -O raw /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm /dev/mapper/cinder--volumes2-volume--4c12957e--62e7--49b2--90c7--87f67ea303b2" returned: 0 in 2.291s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:56.379 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 06:59:57.937 5486 DEBUG oslo_concurrency.processutils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm" returned: 0 in 1.557s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 06:59:57.940 5486 DEBUG cinder.image.image_utils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Image conversion details: src /var/lib/cinder/conversion/tmpPKqKUGlocalhost.localdomain@lvm, size 44.00 MB, duration 2.30 sec, destination /dev/mapper/cinder--volumes2-volume--4c12957e--62e7--49b2--90c7--87f67ea303b2 _convert_image /usr/lib/python2.7/site-packages/cinder/image/image_utils.py:190
2018-09-30 06:59:57.943 5486 INFO cinder.image.image_utils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Converted 44.00 MB image at 19.17 MB/s
2018-09-30 06:59:57.944 5486 DEBUG cinder.volume.flows.manager.create_volume [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Downloaded image b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc ((None, None)) to volume 4c12957e-62e7-49b2-90c7-87f67ea303b2 successfully. _copy_image_to_volume /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:582
2018-09-30 06:59:57.950 5486 DEBUG cinder.image.image_utils [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Temporary image b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc for user 6560e183015f4f0696d2c69498bdbf6c is deleted. fetch /usr/lib/python2.7/site-packages/cinder/image/image_utils.py:676
2018-09-30 06:59:57.952 5486 DEBUG cinder.volume.flows.manager.create_volume [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Marking volume 4c12957e-62e7-49b2-90c7-87f67ea303b2 as bootable. _enable_bootable_flag /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:479
2018-09-30 06:59:57.986 5486 DEBUG cinder.volume.flows.manager.create_volume [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Copying metadata from image b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc to 4c12957e-62e7-49b2-90c7-87f67ea303b2. _handle_bootable_volume_glance_meta /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:437
2018-09-30 06:59:57.988 5486 DEBUG cinder.volume.flows.manager.create_volume [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Creating volume glance metadata for volume 4c12957e-62e7-49b2-90c7-87f67ea303b2 backed by image b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc with: {'container_format': u'bare', 'min_ram': 0, 'disk_format': u'qcow2', 'image_name': u'tempest-cirros-0.4.0-x86_64-1538304870', 'image_id': u'b30fe830-1c0b-4b5b-9bc9-dbeb0511e0bc', 'checksum': u'443b7623e27ecf03dc9e01ee93f67afe', 'min_disk': 0, 'size': 12716032}. _capture_volume_image_metadata /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:616
2018-09-30 06:59:58.175 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (2c440c9a-eaab-4eaa-b2fb-c7a52f788eb6) transitioned into state 'SUCCESS' from state 'RUNNING' with result 'None' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-30 06:59:58.180 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeOnFinishTask;volume:create, create.end' (64660df0-26c9-45ed-b57b-414e206cb20c) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-30 06:59:58.274 5486 INFO cinder.volume.flows.manager.create_volume [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Volume volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 (4c12957e-62e7-49b2-90c7-87f67ea303b2): created successfully
2018-09-30 06:59:58.280 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeOnFinishTask;volume:create, create.end' (64660df0-26c9-45ed-b57b-414e206cb20c) transitioned into state 'SUCCESS' from state 'RUNNING' with result 'None' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-30 06:59:58.286 5486 DEBUG cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Flow 'volume_create_manager' (88be4a71-55e4-4f54-b21e-1254414278de) transitioned into state 'SUCCESS' from state 'RUNNING' _flow_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:145
2018-09-30 06:59:58.289 5486 INFO cinder.volume.manager [req-f5d8e4d4-3f2c-4036-bbab-7e66af59ff49 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Created volume successfully.
2018-09-30 07:00:05.539 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:00:05.541 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 07:00:05.594 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:00:05.596 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 07:00:05.598 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:00:06.702 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.104s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:00:06.704 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:00:08.061 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.357s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:00:08.065 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:00:09.282 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.217s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:00:09.285 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:00:10.704 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.419s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:00:38.805 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K cinder-volumes2/volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:00:40.179 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K cinder-volumes2/volume-4c12957e-62e7-49b2-90c7-87f67ea303b2" returned: 0 in 1.374s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:00:40.293 5486 INFO cinder.volume.targets.lio [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Creating iscsi_target for volume: volume-4c12957e-62e7-49b2-90c7-87f67ea303b2
2018-09-30 07:00:40.297 5486 DEBUG oslo_concurrency.lockutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:00:40.300 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool create /dev/cinder-volumes2/volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 iqn.2010-10.org.openstack:volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 mRxP3qQqfunSS4qDc7NU SwqNHsEf7LtyWGV9 False -p3260 -a10.0.20.25 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:00:43.054 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool create /dev/cinder-volumes2/volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 iqn.2010-10.org.openstack:volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 mRxP3qQqfunSS4qDc7NU SwqNHsEf7LtyWGV9 False -p3260 -a10.0.20.25" returned: 0 in 2.755s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:00:43.057 5486 DEBUG oslo_concurrency.lockutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.760s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:00:43.059 5486 DEBUG oslo_concurrency.lockutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:00:43.060 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:00:45.716 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets" returned: 0 in 2.656s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:00:45.721 5486 DEBUG oslo_concurrency.lockutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.662s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:00:45.724 5486 DEBUG oslo_concurrency.lockutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:00:45.726 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:00:48.392 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save" returned: 0 in 2.667s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:00:48.395 5486 DEBUG oslo_concurrency.lockutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.672s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:00:48.397 5486 DEBUG cinder.volume.targets.iscsi [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Set provider_location to: 10.0.20.25:3260,iqn.2010-10.org.openstack:volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 iqn.2010-10.org.openstack:volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 0 create_export /usr/lib/python2.7/site-packages/cinder/volume/targets/iscsi.py:215
2018-09-30 07:00:48.420 5486 DEBUG oslo_concurrency.lockutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:00:48.422 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool add-initiator iqn.2010-10.org.openstack:volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 mRxP3qQqfunSS4qDc7NU SwqNHsEf7LtyWGV9 iqn.1994-05.com.redhat:f393eeb713 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:00:50.925 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool add-initiator iqn.2010-10.org.openstack:volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 mRxP3qQqfunSS4qDc7NU SwqNHsEf7LtyWGV9 iqn.1994-05.com.redhat:f393eeb713" returned: 0 in 2.502s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:00:50.927 5486 DEBUG oslo_concurrency.lockutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.508s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:00:50.929 5486 DEBUG oslo_concurrency.lockutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:00:50.931 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:00:53.694 5486 DEBUG oslo_concurrency.processutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save" returned: 0 in 2.764s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:00:53.697 5486 DEBUG oslo_concurrency.lockutils [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.768s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:00:53.754 5486 INFO cinder.volume.manager [req-4cf18729-1825-4808-b869-fa3dffff943c 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Initialize volume connection completed successfully.
2018-09-30 07:00:59.329 5486 DEBUG cinder.coordination [req-39e99761-5e63-4b38-bc66-6f71c0abb4af 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "/var/lib/cinder/cinder-4c12957e-62e7-49b2-90c7-87f67ea303b2" acquired by "attach_volume" :: waited 0.003s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:175
2018-09-30 07:00:59.558 5486 INFO cinder.volume.manager [req-39e99761-5e63-4b38-bc66-6f71c0abb4af 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Attaching volume 4c12957e-62e7-49b2-90c7-87f67ea303b2 to instance 32256481-3bfc-427c-a700-c803637de4d4 at mountpoint /dev/vdb on host None.
2018-09-30 07:00:59.821 5486 INFO cinder.volume.manager [req-39e99761-5e63-4b38-bc66-6f71c0abb4af 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Attach volume completed successfully.
2018-09-30 07:00:59.823 5486 DEBUG cinder.coordination [req-39e99761-5e63-4b38-bc66-6f71c0abb4af 6560e183015f4f0696d2c69498bdbf6c 525ed35e0cfd44efad9c6bd864714413 - 349c40de010b415b9b1f350040f667f9 349c40de010b415b9b1f350040f667f9] Lock "/var/lib/cinder/cinder-4c12957e-62e7-49b2-90c7-87f67ea303b2" released by "attach_volume" :: held 0.495s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:187
2018-09-30 07:01:05.539 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:01:05.541 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 07:01:05.580 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:01:05.582 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 07:01:05.585 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:01:06.576 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 0.993s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:01:06.578 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:01:07.703 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.125s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:01:07.706 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:01:08.880 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.174s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:01:08.883 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:01:10.122 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.239s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:02:05.536 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:02:05.539 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 07:02:05.584 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:02:05.586 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 07:02:05.588 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:02:06.928 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.341s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:02:06.931 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:02:08.073 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.142s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:02:08.075 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:02:08.847 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 0.772s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:02:08.851 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:02:09.766 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 0.915s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:05.539 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:03:05.542 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 07:03:05.589 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:03:05.591 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 07:03:05.592 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:06.830 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.238s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:06.833 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:07.746 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 0.913s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:07.751 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:08.515 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 0.765s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:08.518 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:09.680 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.163s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:12.467 5486 DEBUG oslo_concurrency.lockutils [req-4796baf0-69ff-4225-b0f8-6188ced48ee7 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:03:12.469 5486 DEBUG oslo_concurrency.processutils [req-4796baf0-69ff-4225-b0f8-6188ced48ee7 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool delete-initiator iqn.2010-10.org.openstack:volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 iqn.1994-05.com.redhat:f393eeb713 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:14.989 5486 DEBUG oslo_concurrency.processutils [req-4796baf0-69ff-4225-b0f8-6188ced48ee7 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool delete-initiator iqn.2010-10.org.openstack:volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 iqn.1994-05.com.redhat:f393eeb713" returned: 0 in 2.520s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:14.996 5486 DEBUG oslo_concurrency.lockutils [req-4796baf0-69ff-4225-b0f8-6188ced48ee7 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.526s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:03:14.999 5486 DEBUG oslo_concurrency.lockutils [req-4796baf0-69ff-4225-b0f8-6188ced48ee7 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:03:15.003 5486 DEBUG oslo_concurrency.processutils [req-4796baf0-69ff-4225-b0f8-6188ced48ee7 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:17.327 5486 DEBUG oslo_concurrency.processutils [req-4796baf0-69ff-4225-b0f8-6188ced48ee7 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save" returned: 0 in 2.326s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:17.330 5486 DEBUG oslo_concurrency.lockutils [req-4796baf0-69ff-4225-b0f8-6188ced48ee7 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.331s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:03:17.332 5486 INFO cinder.volume.manager [req-4796baf0-69ff-4225-b0f8-6188ced48ee7 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Terminate volume connection completed successfully.
2018-09-30 07:03:17.764 5486 DEBUG cinder.coordination [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "/var/lib/cinder/cinder-4c12957e-62e7-49b2-90c7-87f67ea303b2-detach_volume" acquired by "detach_volume" :: waited 0.001s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:175
2018-09-30 07:03:17.861 5486 INFO cinder.volume.manager [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Detaching volume 4c12957e-62e7-49b2-90c7-87f67ea303b2 from instance 32256481-3bfc-427c-a700-c803637de4d4.
2018-09-30 07:03:17.864 5486 DEBUG oslo_concurrency.lockutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:03:17.866 5486 DEBUG oslo_concurrency.processutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:20.325 5486 DEBUG oslo_concurrency.processutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets" returned: 0 in 2.459s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:20.328 5486 DEBUG oslo_concurrency.lockutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.464s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:03:20.330 5486 INFO cinder.volume.targets.lio [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Removing iscsi_target: 4c12957e-62e7-49b2-90c7-87f67ea303b2
2018-09-30 07:03:20.332 5486 DEBUG oslo_concurrency.lockutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:03:20.334 5486 DEBUG oslo_concurrency.processutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool delete iqn.2010-10.org.openstack:volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:22.913 5486 DEBUG oslo_concurrency.processutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool delete iqn.2010-10.org.openstack:volume-4c12957e-62e7-49b2-90c7-87f67ea303b2" returned: 0 in 2.579s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:22.916 5486 DEBUG oslo_concurrency.lockutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.584s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:03:22.918 5486 DEBUG oslo_concurrency.lockutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:03:22.920 5486 DEBUG oslo_concurrency.processutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:25.384 5486 DEBUG oslo_concurrency.processutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save" returned: 0 in 2.464s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:25.387 5486 DEBUG oslo_concurrency.lockutils [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.469s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:03:25.653 5486 INFO cinder.volume.manager [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Detach volume completed successfully.
2018-09-30 07:03:25.655 5486 DEBUG cinder.coordination [req-1d02b19e-932b-44a2-9429-7988654b8e9e c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "/var/lib/cinder/cinder-4c12957e-62e7-49b2-90c7-87f67ea303b2-detach_volume" released by "detach_volume" :: held 7.890s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:187
2018-09-30 07:03:35.963 5486 DEBUG cinder.coordination [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "/var/lib/cinder/cinder-4c12957e-62e7-49b2-90c7-87f67ea303b2-delete_volume" acquired by "delete_volume" :: waited 0.002s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:175
2018-09-30 07:03:36.139 5486 DEBUG oslo_concurrency.lockutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 07:03:36.141 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:38.509 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets" returned: 0 in 2.369s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:38.512 5486 DEBUG oslo_concurrency.lockutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.374s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 07:03:38.513 5486 INFO cinder.volume.targets.iscsi [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Skipping remove_export. No iscsi_target is presently exported for volume: 4c12957e-62e7-49b2-90c7-87f67ea303b2
2018-09-30 07:03:38.516 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2/volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:39.915 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2/volume-4c12957e-62e7-49b2-90c7-87f67ea303b2" returned: 0 in 1.399s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:39.920 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvdisplay --noheading -C -o Attr cinder-volumes2/volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:41.365 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvdisplay --noheading -C -o Attr cinder-volumes2/volume-4c12957e-62e7-49b2-90c7-87f67ea303b2" returned: 0 in 1.445s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:41.370 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvremove --config activation { retry_deactivation = 1}  -f cinder-volumes2/volume-4c12957e-62e7-49b2-90c7-87f67ea303b2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:42.605 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvremove --config activation { retry_deactivation = 1}  -f cinder-volumes2/volume-4c12957e-62e7-49b2-90c7-87f67ea303b2" returned: 0 in 1.235s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:42.607 5486 INFO cinder.volume.drivers.lvm [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Successfully deleted volume: 4c12957e-62e7-49b2-90c7-87f67ea303b2
2018-09-30 07:03:42.705 5486 DEBUG cinder.quota [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Created reservations ['81581be5-ee7a-4ab1-9e6b-f42d822d5a83', '6a93d6d5-cac5-441b-8fa0-ead0cc5fef27', 'd5e37c46-e75e-4dca-8788-53819d9c3025', 'd465ecb4-48f8-47d3-89e5-9113019934ea'] reserve /usr/lib/python2.7/site-packages/cinder/quota.py:1029
2018-09-30 07:03:42.774 5486 DEBUG cinder.volume.utils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Can not find volume 4c12957e-62e7-49b2-90c7-87f67ea303b2 at notify usage _usage_from_volume /usr/lib/python2.7/site-packages/cinder/volume/utils.py:99
2018-09-30 07:03:42.841 5486 DEBUG cinder.volume.drivers.lvm [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 07:03:42.843 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:43.834 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 0.991s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:43.838 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:44.988 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.151s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:44.991 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:46.216 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.225s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:46.220 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:03:47.470 5486 DEBUG oslo_concurrency.processutils [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.250s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:03:47.474 5486 DEBUG cinder.manager [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 07:03:47.695 5486 INFO cinder.volume.manager [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Deleted volume successfully.
2018-09-30 07:03:47.728 5486 DEBUG cinder.coordination [req-bbe7a6c1-1baf-456e-a4e1-296004f20f04 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "/var/lib/cinder/cinder-4c12957e-62e7-49b2-90c7-87f67ea303b2-delete_volume" released by "delete_volume" :: held 11.765s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:187
2018-09-30 07:04:05.534 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:04:05.538 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 07:04:05.581 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:04:05.582 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 07:04:05.584 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:04:06.833 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.250s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:04:06.837 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:04:08.043 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.206s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:04:08.046 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:04:09.564 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.519s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:04:09.569 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:04:11.055 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.487s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:05:05.531 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:05:05.534 5486 DEBUG cinder.manager [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-30 07:05:05.575 5486 DEBUG oslo_service.periodic_task [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-30 07:05:05.576 5486 DEBUG cinder.volume.drivers.lvm [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-30 07:05:05.578 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:05:06.671 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.094s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:05:06.674 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:05:07.839 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.165s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:05:07.842 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:05:08.896 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.054s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-30 07:05:08.899 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-30 07:05:10.013 5486 DEBUG oslo_concurrency.processutils [req-5d5008eb-f68a-4ec8-843e-5762179fb3f4 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.114s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
