2018-09-29 01:44:58.254 16175 DEBUG oslo_db.sqlalchemy.engines [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 01:45:02.190 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:45:02.198 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.009s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:45:02.247 16175 DEBUG oslo_db.sqlalchemy.engines [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 01:45:02.582 16175 DEBUG nova.context [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),67252e7f-1b17-4ebb-bf9b-a60e066d5ace(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-09-29 01:45:02.585 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:45:02.589 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:45:02.592 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:45:02.593 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:45:02.638 16175 DEBUG oslo_db.sqlalchemy.engines [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 01:45:02.683 16175 DEBUG nova.quota [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Getting quotas for project d09000bee1c14b18822533269e609194. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-29 01:45:02.693 16175 DEBUG nova.quota [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Getting quotas for user e8ffca3721694569b7786959d2b3f5d0 and project d09000bee1c14b18822533269e609194. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-29 01:45:02.730 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:45:02.730 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:45:02.731 16175 WARNING nova.image.glance [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] No protocol specified in for api_server 'http://10.0.20.22:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-29 01:45:02.812 16175 DEBUG nova.notifications.objects.base [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-29 01:45:02.816 16175 DEBUG nova.objects.instance [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lazy-loading 'tags' on Instance uuid d43197e3-1c89-4125-8332-43faa672b6f1 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-29 01:45:02.919 16175 DEBUG nova.conductor.manager [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] [instance: d43197e3-1c89-4125-8332-43faa672b6f1] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='8ed916d6-16fb-4ace-88fa-bf9fcb0aca11',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _create_block_device_mapping /usr/lib/python2.7/site-packages/nova/conductor/manager.py:968
2018-09-29 01:45:02.924 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:45:02.925 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:45:03.088 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 01:45:03.090 16175 DEBUG oslo_concurrency.lockutils [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Lock "67252e7f-1b17-4ebb-bf9b-a60e066d5ace" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 01:45:03.643 16178 WARNING nova.image.glance [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] No protocol specified in for api_server 'http://10.0.20.22:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-29 01:45:03.744 16178 DEBUG nova.notifications.objects.base [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-29 01:45:04.331 16181 WARNING nova.image.glance [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] No protocol specified in for api_server 'http://10.0.20.22:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-29 01:45:04.438 16181 DEBUG nova.notifications.objects.base [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-29 01:45:05.193 16176 WARNING nova.image.glance [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] No protocol specified in for api_server 'http://10.0.20.22:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-29 01:45:05.357 16176 DEBUG nova.notifications.objects.base [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-29 01:45:06.019 16175 WARNING nova.image.glance [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] No protocol specified in for api_server 'http://10.0.20.22:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-29 01:45:06.050 16175 DEBUG nova.notifications.objects.base [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-29 01:45:06.711 16173 WARNING nova.image.glance [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] No protocol specified in for api_server 'http://10.0.20.22:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-29 01:45:06.843 16173 DEBUG nova.notifications.objects.base [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-29 01:45:20.662 16173 WARNING nova.image.glance [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] No protocol specified in for api_server 'http://10.0.20.22:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-29 01:45:20.684 16173 DEBUG nova.notifications.objects.base [req-5db29286-eba8-4a6c-99ba-813cef6009cf e8ffca3721694569b7786959d2b3f5d0 d09000bee1c14b18822533269e609194 - 100b1ee281dc4e25900ca58838fe6088 100b1ee281dc4e25900ca58838fe6088] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
