2018-06-30 09:02:34.491 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:02:34.494 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-30 09:03:34.491 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:03:34.495 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-30 09:04:34.491 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:04:34.495 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-30 09:04:34.588 31911 DEBUG oslo_concurrency.lockutils [req-7dff3ff1-5eeb-4e00-97ce-1cfda77b9268 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:04:35.312 31911 DEBUG neutron.agent.dhcp.agent [req-e8788122-3724-48ad-9d9c-2b18590d8d84 - - - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: enable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:04:35.313 31911 DEBUG neutron.agent.linux.utils [req-e8788122-3724-48ad-9d9c-2b18590d8d84 - - - - -] Unable to access /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:04:35.314 31911 DEBUG neutron.agent.linux.dhcp [req-e8788122-3724-48ad-9d9c-2b18590d8d84 - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-5ce11b1a-6768-4ff1-ad36-060502981129 on network 5ce11b1a-6768-4ff1-ad36-060502981129 does not yet exist. Checking for a reserved port. _setup_reserved_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1267
2018-06-30 09:04:35.315 31911 DEBUG neutron.agent.linux.dhcp [req-e8788122-3724-48ad-9d9c-2b18590d8d84 - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-5ce11b1a-6768-4ff1-ad36-060502981129 on network 5ce11b1a-6768-4ff1-ad36-060502981129 does not yet exist. Creating new one. _setup_new_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1288
2018-06-30 09:04:38.586 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.608 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'add', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.652 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'sysctl', '-w', 'net.ipv4.conf.all.promote_secondaries=1'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.671 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', 'link', 'set', 'lo', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.687 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'sysctl', '-w', 'net.ipv6.conf.default.accept_ra=0'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.712 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', 'link', 'set', 'tapa29291d5-9d', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.742 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-o', 'link', 'show', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.760 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-06-30 09:04:38.789 31911 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=None, port=tapa29291d5-9d) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-06-30 09:04:38.792 31911 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Transaction caused no change do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:114
2018-06-30 09:04:38.794 31911 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): AddPortCommand(bridge=br-int, may_exist=False, port=tapa29291d5-9d) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-06-30 09:04:38.796 31911 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=1): DbSetCommand(table=Interface, col_values=(('type', 'internal'), ('external_ids', {'iface-id': u'a29291d5-9d94-4bb0-ae79-45f7d68b5ce3', 'iface-status': 'active', 'attached-mac': u'fa:16:3e:ae:a9:c8'})), record=tapa29291d5-9d) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-06-30 09:04:38.840 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tapa29291d5-9d', 'address', 'fa:16:3e:ae:a9:c8'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.869 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.884 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tapa29291d5-9d', 'netns', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.936 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', 'link', 'set', 'tapa29291d5-9d', 'mtu', '1450'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.955 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', 'link', 'set', 'tapa29291d5-9d', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:38.971 31911 DEBUG oslo_concurrency.lockutils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Acquired semaphore "iptables-qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:04:38.974 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'iptables-save'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.012 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'iptables-restore', '-n'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.039 31911 DEBUG neutron.agent.linux.iptables_manager [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] IPTablesManager.apply completed with success. 56 iptables commands were issued _apply_synchronized /usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py:601
2018-06-30 09:04:39.042 31911 DEBUG oslo_concurrency.lockutils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Releasing semaphore "iptables-qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:04:39.043 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-o', 'link', 'show', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.063 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', 'addr', 'show', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.079 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'addr', 'add', '11.227.1.2/24', 'scope', 'global', 'dev', 'tapa29291d5-9d', 'brd', '11.227.1.255'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.101 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.121 31911 DEBUG neutron.agent.linux.dhcp [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Setting IPv4 gateway for dhcp netns on net 5ce11b1a-6768-4ff1-ad36-060502981129 to 11.227.1.1 _set_default_route_ip_version /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1164
2018-06-30 09:04:39.122 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'replace', 'default', 'via', '11.227.1.1', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.141 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.167 31911 DEBUG neutron.agent.linux.dhcp [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Cleaning stale devices for network 5ce11b1a-6768-4ff1-ad36-060502981129 _cleanup_stale_devices /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1369
2018-06-30 09:04:39.169 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.188 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'find', '/sys/class/net', '-maxdepth', '1', '-type', 'l', '-printf', '%f '] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.213 31911 DEBUG neutron.agent.linux.dhcp [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Building initial lease file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/leases _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:623
2018-06-30 09:04:39.216 31911 DEBUG neutron.agent.linux.dhcp [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Done building initial lease file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/leases with contents:
1530428679 fa:16:3e:ae:a9:c8 11.227.1.2 * *
 _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:651
2018-06-30 09:04:39.217 31911 DEBUG neutron.agent.linux.dhcp [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:04:39.219 31911 DEBUG neutron.agent.linux.dhcp [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:04:39.222 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Unable to access /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:04:39.224 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'dnsmasq', '--no-hosts', '--no-resolv', '--strict-order', '--except-interface=lo', '--pid-file=/var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/pid', '--dhcp-hostsfile=/var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host', '--addn-hosts=/var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/addn_hosts', '--dhcp-optsfile=/var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/opts', '--dhcp-leasefile=/var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/leases', '--dhcp-match=set:ipxe,175', '--bind-interfaces', '--interface=tapa29291d5-9d', '--dhcp-range=set:tag0,11.227.1.0,static,255.255.255.0,86400s', '--dhcp-option-force=option:mtu,1450', '--dhcp-lease-max=256', '--conf-file=', '--domain=openstacklocal'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:39.286 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:04:39.288 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:04:39.289 31911 DEBUG neutron.agent.linux.external_process [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:04:39.290 31911 DEBUG oslo_concurrency.lockutils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:04:39.300 31911 DEBUG oslo_concurrency.lockutils [req-7dff3ff1-5eeb-4e00-97ce-1cfda77b9268 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:04:39.977 31911 DEBUG neutron.agent.dhcp.agent [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:04:39.980 31911 DEBUG neutron.agent.linux.dhcp [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:04:39.985 31911 DEBUG neutron.agent.linux.dhcp [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:04:39.996 31911 DEBUG neutron.agent.linux.utils [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:40.022 31911 DEBUG neutron.agent.linux.dhcp [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:04:40.024 31911 DEBUG neutron.agent.linux.utils [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:40.067 31911 DEBUG neutron.agent.linux.utils [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:40.096 31911 DEBUG neutron.agent.linux.utils [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:04:40.097 31911 DEBUG neutron.agent.linux.utils [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:04:40.098 31911 DEBUG neutron.agent.linux.external_process [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:04:40.099 31911 DEBUG oslo_concurrency.lockutils [req-98110d6d-930e-40d2-9415-fe1910764482 - - - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:04:40.104 31911 DEBUG oslo_concurrency.lockutils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:04:40.112 31911 DEBUG neutron.agent.dhcp.agent [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Discarding stale port update: admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-06-30T07:04:36Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-5ce11b1a-6768-4ff1-ad36-060502981129, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'338526c3-c1a3-4380-a832-88064fbafeec', u'ip_address': u'11.227.1.2'}], id=a29291d5-9d94-4bb0-ae79-45f7d68b5ce3, mac_address=fa:16:3e:ae:a9:c8, name=, network_id=5ce11b1a-6768-4ff1-ad36-060502981129, port_security_enabled=False, project_id=aa4495286f8041ee848481ba08cd964e, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=aa4495286f8041ee848481ba08cd964e, updated_at=2018-06-30T07:04:36Z port_update_end /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:409
2018-06-30 09:04:40.114 31911 DEBUG oslo_concurrency.lockutils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:04:40.129 31911 DEBUG oslo_concurrency.lockutils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:04:40.139 31911 INFO neutron.agent.dhcp.agent [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-06-30T07:04:36Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-5ce11b1a-6768-4ff1-ad36-060502981129, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'338526c3-c1a3-4380-a832-88064fbafeec', u'ip_address': u'11.227.1.2'}], id=a29291d5-9d94-4bb0-ae79-45f7d68b5ce3, mac_address=fa:16:3e:ae:a9:c8, name=, network_id=5ce11b1a-6768-4ff1-ad36-060502981129, port_security_enabled=False, project_id=aa4495286f8041ee848481ba08cd964e, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=aa4495286f8041ee848481ba08cd964e, updated_at=2018-06-30T07:04:37Z
2018-06-30 09:04:40.141 31911 DEBUG neutron.agent.dhcp.agent [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:04:40.144 31911 DEBUG neutron.agent.linux.dhcp [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:04:40.146 31911 DEBUG neutron.agent.linux.dhcp [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:04:40.151 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:40.215 31911 DEBUG neutron.agent.linux.dhcp [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:04:40.217 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:40.248 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:04:40.271 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:04:40.272 31911 DEBUG neutron.agent.linux.utils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:04:40.273 31911 DEBUG neutron.agent.linux.external_process [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:04:40.274 31911 DEBUG oslo_concurrency.lockutils [req-718e0f7b-0b57-491d-9dc7-e099ee3e1138 - - - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:05:16.584 31911 DEBUG oslo_concurrency.lockutils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:05:16.585 31911 INFO neutron.agent.dhcp.agent [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-06-30T07:05:15Z, description=, device_id=00864e7d-8138-47b9-a923-56f0fec07676, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'338526c3-c1a3-4380-a832-88064fbafeec', u'ip_address': u'11.227.1.1'}], id=fd57bcb5-7b36-4750-bccb-9821a7415134, mac_address=fa:16:3e:a9:3b:61, name=, network_id=5ce11b1a-6768-4ff1-ad36-060502981129, port_security_enabled=False, project_id=aa4495286f8041ee848481ba08cd964e, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=aa4495286f8041ee848481ba08cd964e, updated_at=2018-06-30T07:05:15Z
2018-06-30 09:05:16.586 31911 DEBUG neutron.agent.dhcp.agent [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:05:16.587 31911 DEBUG neutron.agent.linux.dhcp [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:05:16.590 31911 DEBUG neutron.agent.linux.dhcp [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:05:16.595 31911 DEBUG neutron.agent.linux.utils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:16.608 31911 DEBUG neutron.agent.linux.dhcp [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:05:16.609 31911 DEBUG neutron.agent.linux.utils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:16.623 31911 DEBUG neutron.agent.linux.utils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:16.635 31911 DEBUG neutron.agent.linux.utils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:16.636 31911 DEBUG neutron.agent.linux.utils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:16.637 31911 DEBUG neutron.agent.linux.external_process [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:05:16.637 31911 DEBUG oslo_concurrency.lockutils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:05:17.463 31911 DEBUG oslo_concurrency.lockutils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:05:17.464 31911 INFO neutron.agent.dhcp.agent [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-06-30T07:05:15Z, description=, device_id=00864e7d-8138-47b9-a923-56f0fec07676, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'338526c3-c1a3-4380-a832-88064fbafeec', u'ip_address': u'11.227.1.1'}], id=fd57bcb5-7b36-4750-bccb-9821a7415134, mac_address=fa:16:3e:a9:3b:61, name=, network_id=5ce11b1a-6768-4ff1-ad36-060502981129, port_security_enabled=False, project_id=aa4495286f8041ee848481ba08cd964e, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=aa4495286f8041ee848481ba08cd964e, updated_at=2018-06-30T07:05:15Z
2018-06-30 09:05:17.465 31911 DEBUG neutron.agent.dhcp.agent [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:05:17.466 31911 DEBUG neutron.agent.linux.dhcp [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:05:17.468 31911 DEBUG neutron.agent.linux.dhcp [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:05:17.471 31911 DEBUG neutron.agent.linux.utils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:17.482 31911 DEBUG neutron.agent.linux.dhcp [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:05:17.484 31911 DEBUG neutron.agent.linux.utils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:17.493 31911 DEBUG neutron.agent.linux.utils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:17.505 31911 DEBUG neutron.agent.linux.utils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:17.506 31911 DEBUG neutron.agent.linux.utils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:17.506 31911 DEBUG neutron.agent.linux.external_process [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:05:17.507 31911 DEBUG oslo_concurrency.lockutils [req-52ffb4a7-2156-4fe1-af99-e1e79283f8da 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:05:20.436 31911 DEBUG oslo_concurrency.lockutils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:05:20.437 31911 INFO neutron.agent.dhcp.agent [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-06-30T07:05:15Z, description=, device_id=00864e7d-8138-47b9-a923-56f0fec07676, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'338526c3-c1a3-4380-a832-88064fbafeec', u'ip_address': u'11.227.1.1'}], id=fd57bcb5-7b36-4750-bccb-9821a7415134, mac_address=fa:16:3e:a9:3b:61, name=, network_id=5ce11b1a-6768-4ff1-ad36-060502981129, port_security_enabled=False, project_id=aa4495286f8041ee848481ba08cd964e, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=aa4495286f8041ee848481ba08cd964e, updated_at=2018-06-30T07:05:16Z
2018-06-30 09:05:20.439 31911 DEBUG neutron.agent.dhcp.agent [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:05:20.441 31911 DEBUG neutron.agent.linux.dhcp [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:05:20.443 31911 DEBUG neutron.agent.linux.dhcp [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:05:20.448 31911 DEBUG neutron.agent.linux.utils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:20.466 31911 DEBUG neutron.agent.linux.dhcp [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:05:20.468 31911 DEBUG neutron.agent.linux.utils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:20.489 31911 DEBUG neutron.agent.linux.utils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:20.511 31911 DEBUG neutron.agent.linux.utils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:20.512 31911 DEBUG neutron.agent.linux.utils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:20.513 31911 DEBUG neutron.agent.linux.external_process [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:05:20.514 31911 DEBUG oslo_concurrency.lockutils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:05:21.685 31911 DEBUG oslo_concurrency.lockutils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:05:21.686 31911 INFO neutron.agent.dhcp.agent [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-06-30T07:05:15Z, description=, device_id=00864e7d-8138-47b9-a923-56f0fec07676, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'338526c3-c1a3-4380-a832-88064fbafeec', u'ip_address': u'11.227.1.1'}], id=fd57bcb5-7b36-4750-bccb-9821a7415134, mac_address=fa:16:3e:a9:3b:61, name=, network_id=5ce11b1a-6768-4ff1-ad36-060502981129, port_security_enabled=False, project_id=aa4495286f8041ee848481ba08cd964e, revision_number=6, security_groups=[], status=DOWN, tags=[], tenant_id=aa4495286f8041ee848481ba08cd964e, updated_at=2018-06-30T07:05:21Z
2018-06-30 09:05:21.688 31911 DEBUG neutron.agent.dhcp.agent [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:05:21.689 31911 DEBUG neutron.agent.linux.dhcp [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:05:21.693 31911 DEBUG neutron.agent.linux.dhcp [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:05:21.698 31911 DEBUG neutron.agent.linux.utils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:21.716 31911 DEBUG neutron.agent.linux.dhcp [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:05:21.718 31911 DEBUG neutron.agent.linux.utils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:21.734 31911 DEBUG neutron.agent.linux.utils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:21.749 31911 DEBUG neutron.agent.linux.utils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:21.750 31911 DEBUG neutron.agent.linux.utils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:21.750 31911 DEBUG neutron.agent.linux.external_process [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:05:21.751 31911 DEBUG oslo_concurrency.lockutils [req-a37cf3d8-0681-49ec-99af-f3be95643ced - - - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:05:30.067 31911 DEBUG oslo_concurrency.lockutils [req-30308e6e-061a-4af6-9f32-81fa628d91c0 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Acquired semaphore "dhcp-agent-network-lock-8fa9a212-be1e-480a-988d-8a3f899b6e3c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:05:30.068 31911 DEBUG oslo_concurrency.lockutils [req-30308e6e-061a-4af6-9f32-81fa628d91c0 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Releasing semaphore "dhcp-agent-network-lock-8fa9a212-be1e-480a-988d-8a3f899b6e3c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:05:33.004 31911 DEBUG oslo_concurrency.lockutils [req-d1418ced-4093-44b1-8218-b00abe7124c7 - - - - -] Acquired semaphore "dhcp-agent-network-lock-8fa9a212-be1e-480a-988d-8a3f899b6e3c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:05:33.004 31911 DEBUG oslo_concurrency.lockutils [req-d1418ced-4093-44b1-8218-b00abe7124c7 - - - - -] Releasing semaphore "dhcp-agent-network-lock-8fa9a212-be1e-480a-988d-8a3f899b6e3c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:05:33.648 31911 DEBUG oslo_concurrency.lockutils [req-d1418ced-4093-44b1-8218-b00abe7124c7 - - - - -] Acquired semaphore "dhcp-agent-network-lock-8fa9a212-be1e-480a-988d-8a3f899b6e3c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:05:33.649 31911 DEBUG oslo_concurrency.lockutils [req-d1418ced-4093-44b1-8218-b00abe7124c7 - - - - -] Releasing semaphore "dhcp-agent-network-lock-8fa9a212-be1e-480a-988d-8a3f899b6e3c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:05:34.491 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:05:34.494 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-30 09:05:56.133 31911 DEBUG oslo_concurrency.lockutils [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:05:56.134 31911 INFO neutron.agent.dhcp.agent [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-06-30T07:05:54Z, description=, device_id=d6f79a01-ea9a-4a97-ac32-719de26069f9, device_owner=, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'338526c3-c1a3-4380-a832-88064fbafeec', u'ip_address': u'11.227.1.11'}], id=c79fff3d-79ee-436b-a118-d878d3bece26, mac_address=fa:16:3e:69:4b:f5, name=, network_id=5ce11b1a-6768-4ff1-ad36-060502981129, port_security_enabled=True, project_id=aa4495286f8041ee848481ba08cd964e, revision_number=3, security_groups=[u'86b14804-7136-4dcb-b13d-cac50d3b1857'], status=DOWN, tags=[], tenant_id=aa4495286f8041ee848481ba08cd964e, updated_at=2018-06-30T07:05:54Z
2018-06-30 09:05:56.138 31911 DEBUG neutron.agent.dhcp.agent [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:05:56.141 31911 DEBUG neutron.agent.linux.dhcp [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:05:56.145 31911 DEBUG neutron.agent.linux.dhcp [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:05:56.156 31911 DEBUG neutron.agent.linux.utils [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:56.212 31911 DEBUG neutron.agent.linux.dhcp [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:05:56.214 31911 DEBUG neutron.agent.linux.utils [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:56.235 31911 DEBUG neutron.agent.linux.utils [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:56.254 31911 DEBUG neutron.agent.linux.utils [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:56.256 31911 DEBUG neutron.agent.linux.utils [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:56.257 31911 DEBUG neutron.agent.linux.external_process [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:05:56.258 31911 DEBUG oslo_concurrency.lockutils [req-7f60de2c-8977-47c6-9877-357b097ee082 56c81b20bb7743a087a8179c0026160c aa4495286f8041ee848481ba08cd964e - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:05:59.781 31911 DEBUG oslo_concurrency.lockutils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:05:59.783 31911 INFO neutron.agent.dhcp.agent [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-06-30T07:05:54Z, description=, device_id=d6f79a01-ea9a-4a97-ac32-719de26069f9, device_owner=compute:nova, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'338526c3-c1a3-4380-a832-88064fbafeec', u'ip_address': u'11.227.1.11'}], id=c79fff3d-79ee-436b-a118-d878d3bece26, mac_address=fa:16:3e:69:4b:f5, name=, network_id=5ce11b1a-6768-4ff1-ad36-060502981129, port_security_enabled=True, project_id=aa4495286f8041ee848481ba08cd964e, revision_number=4, security_groups=[u'86b14804-7136-4dcb-b13d-cac50d3b1857'], status=DOWN, tags=[], tenant_id=aa4495286f8041ee848481ba08cd964e, updated_at=2018-06-30T07:05:59Z
2018-06-30 09:05:59.784 31911 DEBUG neutron.agent.dhcp.agent [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:05:59.787 31911 DEBUG neutron.agent.linux.dhcp [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:05:59.789 31911 DEBUG neutron.agent.linux.dhcp [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:05:59.794 31911 DEBUG neutron.agent.linux.utils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:59.809 31911 DEBUG neutron.agent.linux.dhcp [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:05:59.811 31911 DEBUG neutron.agent.linux.utils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:59.828 31911 DEBUG neutron.agent.linux.utils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:05:59.842 31911 DEBUG neutron.agent.linux.utils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:59.843 31911 DEBUG neutron.agent.linux.utils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:05:59.844 31911 DEBUG neutron.agent.linux.external_process [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:05:59.844 31911 DEBUG oslo_concurrency.lockutils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:06:00.609 31911 DEBUG oslo_concurrency.lockutils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:06:00.610 31911 INFO neutron.agent.dhcp.agent [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-06-30T07:05:54Z, description=, device_id=d6f79a01-ea9a-4a97-ac32-719de26069f9, device_owner=compute:nova, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'338526c3-c1a3-4380-a832-88064fbafeec', u'ip_address': u'11.227.1.11'}], id=c79fff3d-79ee-436b-a118-d878d3bece26, mac_address=fa:16:3e:69:4b:f5, name=, network_id=5ce11b1a-6768-4ff1-ad36-060502981129, port_security_enabled=True, project_id=aa4495286f8041ee848481ba08cd964e, revision_number=5, security_groups=[u'86b14804-7136-4dcb-b13d-cac50d3b1857'], status=DOWN, tags=[], tenant_id=aa4495286f8041ee848481ba08cd964e, updated_at=2018-06-30T07:06:00Z
2018-06-30 09:06:00.611 31911 DEBUG neutron.agent.dhcp.agent [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:06:00.613 31911 DEBUG neutron.agent.linux.dhcp [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:06:00.615 31911 DEBUG neutron.agent.linux.dhcp [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:06:00.620 31911 DEBUG neutron.agent.linux.utils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:06:00.644 31911 DEBUG neutron.agent.linux.dhcp [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:06:00.646 31911 DEBUG neutron.agent.linux.utils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:06:00.661 31911 DEBUG neutron.agent.linux.utils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:06:00.675 31911 DEBUG neutron.agent.linux.utils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:06:00.683 31911 DEBUG neutron.agent.linux.utils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:06:00.684 31911 DEBUG neutron.agent.linux.external_process [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:06:00.685 31911 DEBUG oslo_concurrency.lockutils [req-8adaed3b-206c-4307-ba7e-17fb5dc166f1 2381c87c24634e059255e904a45e06ef 0d772b180b3c41e2ae2eba61c236b149 - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:06:34.492 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:06:34.495 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-30 09:06:41.060 31911 DEBUG oslo_concurrency.lockutils [req-05eeeca2-1c26-449e-bb31-80ed593d340d 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Acquired semaphore "dhcp-agent-network-lock-8fa9a212-be1e-480a-988d-8a3f899b6e3c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:06:41.061 31911 DEBUG oslo_concurrency.lockutils [req-05eeeca2-1c26-449e-bb31-80ed593d340d 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Releasing semaphore "dhcp-agent-network-lock-8fa9a212-be1e-480a-988d-8a3f899b6e3c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:06:42.442 31911 DEBUG oslo_concurrency.lockutils [req-05eeeca2-1c26-449e-bb31-80ed593d340d 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Acquired semaphore "dhcp-agent-network-lock-8fa9a212-be1e-480a-988d-8a3f899b6e3c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:06:42.444 31911 DEBUG oslo_concurrency.lockutils [req-05eeeca2-1c26-449e-bb31-80ed593d340d 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Releasing semaphore "dhcp-agent-network-lock-8fa9a212-be1e-480a-988d-8a3f899b6e3c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:07:34.492 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:07:34.497 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-30 09:08:34.492 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:08:34.496 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-30 09:09:34.492 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:09:34.495 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-30 09:10:34.494 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:10:34.501 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.007s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-30 09:10:51.149 31911 DEBUG oslo_concurrency.lockutils [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:10:51.151 31911 DEBUG neutron.agent.dhcp.agent [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:10:51.153 31911 DEBUG neutron.agent.linux.utils [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'dhcp_release', 'tapa29291d5-9d', '11.227.1.11', 'fa:16:3e:69:4b:f5'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:10:51.177 31911 DEBUG neutron.agent.linux.dhcp [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:10:51.186 31911 DEBUG neutron.agent.linux.dhcp [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:10:51.191 31911 DEBUG neutron.agent.linux.utils [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:10:51.202 31911 DEBUG neutron.agent.linux.dhcp [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:10:51.204 31911 DEBUG neutron.agent.linux.utils [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:10:51.219 31911 DEBUG neutron.agent.linux.utils [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:10:51.233 31911 DEBUG neutron.agent.linux.utils [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:10:51.234 31911 DEBUG neutron.agent.linux.utils [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:10:51.235 31911 DEBUG neutron.agent.linux.external_process [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:10:51.236 31911 DEBUG oslo_concurrency.lockutils [req-3ee67bf6-1778-4f69-a7b9-15193240d2a9 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:11:34.494 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:11:34.500 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-30 09:11:46.431 31911 DEBUG oslo_concurrency.lockutils [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:11:46.433 31911 DEBUG neutron.agent.dhcp.agent [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:11:46.434 31911 DEBUG neutron.agent.linux.utils [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'dhcp_release', 'tapa29291d5-9d', '11.227.1.1', 'fa:16:3e:a9:3b:61'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:11:46.455 31911 DEBUG neutron.agent.linux.dhcp [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Building host file: /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-30 09:11:46.462 31911 DEBUG neutron.agent.linux.dhcp [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Done building host file /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-30 09:11:46.467 31911 DEBUG neutron.agent.linux.utils [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:11:46.480 31911 DEBUG neutron.agent.linux.dhcp [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Reloading allocations for network: 5ce11b1a-6768-4ff1-ad36-060502981129 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-30 09:11:46.483 31911 DEBUG neutron.agent.linux.utils [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-4', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:11:46.501 31911 DEBUG neutron.agent.linux.utils [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129', 'ip', '-6', 'route', 'list', 'dev', 'tapa29291d5-9d'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:11:46.522 31911 DEBUG neutron.agent.linux.utils [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:11:46.524 31911 DEBUG neutron.agent.linux.utils [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:11:46.526 31911 DEBUG neutron.agent.linux.external_process [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:11:46.527 31911 DEBUG oslo_concurrency.lockutils [req-fcf8ba16-f600-4eb1-8bdf-ef9c4e4aa251 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:12:13.749 31911 DEBUG oslo_concurrency.lockutils [req-1a1c675f-3a64-46ed-937a-b54e1ba3e279 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:12:13.751 31911 DEBUG neutron.agent.dhcp.agent [req-1a1c675f-3a64-46ed-937a-b54e1ba3e279 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:12:13.753 31911 DEBUG neutron.agent.linux.utils [req-1a1c675f-3a64-46ed-937a-b54e1ba3e279 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Running command (rootwrap daemon): ['kill', '-9', '3604'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:12:13.771 31911 DEBUG neutron.agent.linux.utils [req-1a1c675f-3a64-46ed-937a-b54e1ba3e279 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-06-30 09:12:13.805 31911 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=br-int, port=tapa29291d5-9d) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-06-30 09:12:13.889 31911 DEBUG neutron.agent.linux.utils [req-e2a83946-c858-4afc-b1b7-ce5c7b4537e9 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:12:13.900 31911 DEBUG neutron.agent.linux.utils [req-e2a83946-c858-4afc-b1b7-ce5c7b4537e9 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'delete', 'qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:12:13.910 31911 DEBUG oslo_concurrency.lockutils [req-e2a83946-c858-4afc-b1b7-ce5c7b4537e9 - - - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:12:22.920 31911 DEBUG oslo_concurrency.lockutils [req-247335a8-3cac-4594-b93a-cbe59f643de5 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:12:23.283 31911 DEBUG neutron.agent.linux.utils [req-03d0e087-4297-4eef-a139-c6fffa4adf9e - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:12:23.284 31911 DEBUG neutron.agent.linux.utils [req-03d0e087-4297-4eef-a139-c6fffa4adf9e - - - - -] Unable to access /var/lib/neutron/external/pids/5ce11b1a-6768-4ff1-ad36-060502981129.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:12:23.285 31911 DEBUG neutron.agent.linux.external_process [req-03d0e087-4297-4eef-a139-c6fffa4adf9e - - - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:12:23.286 31911 DEBUG neutron.agent.dhcp.agent [req-03d0e087-4297-4eef-a139-c6fffa4adf9e - - - - -] Calling driver for network: 5ce11b1a-6768-4ff1-ad36-060502981129 action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-30 09:12:23.287 31911 DEBUG neutron.agent.linux.utils [req-03d0e087-4297-4eef-a139-c6fffa4adf9e - - - - -] Unable to access /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:12:23.288 31911 DEBUG neutron.agent.linux.utils [req-03d0e087-4297-4eef-a139-c6fffa4adf9e - - - - -] Unable to access /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-30 09:12:23.289 31911 DEBUG neutron.agent.linux.external_process [req-03d0e087-4297-4eef-a139-c6fffa4adf9e - - - - -] No process started for 5ce11b1a-6768-4ff1-ad36-060502981129 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-30 09:12:23.290 31911 DEBUG neutron.agent.linux.dhcp [req-03d0e087-4297-4eef-a139-c6fffa4adf9e - - - - -] Impossibile accedere a /var/lib/neutron/dhcp/5ce11b1a-6768-4ff1-ad36-060502981129/interface _get_value_from_conf_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:268
2018-06-30 09:12:23.290 31911 DEBUG neutron.agent.linux.dhcp [req-03d0e087-4297-4eef-a139-c6fffa4adf9e - - - - -] No interface exists for network 5ce11b1a-6768-4ff1-ad36-060502981129 destroy /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1482
2018-06-30 09:12:23.336 31911 DEBUG neutron.agent.linux.utils [req-e883dfed-b6ff-49a8-9172-e46675b141a9 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-30 09:12:23.351 31911 DEBUG neutron.agent.linux.dhcp [req-e883dfed-b6ff-49a8-9172-e46675b141a9 - - - - -] Namespace already deleted: qdhcp-5ce11b1a-6768-4ff1-ad36-060502981129 _destroy_namespace_and_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:246
2018-06-30 09:12:23.352 31911 DEBUG oslo_concurrency.lockutils [req-e883dfed-b6ff-49a8-9172-e46675b141a9 - - - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:12:24.490 31911 DEBUG oslo_concurrency.lockutils [req-247335a8-3cac-4594-b93a-cbe59f643de5 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Acquired semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-30 09:12:24.491 31911 DEBUG oslo_concurrency.lockutils [req-247335a8-3cac-4594-b93a-cbe59f643de5 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - - -] Releasing semaphore "dhcp-agent-network-lock-5ce11b1a-6768-4ff1-ad36-060502981129" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-30 09:12:32.308 31911 DEBUG neutron.agent.dhcp.agent [req-c8ec7e37-0459-4f5d-a27b-368f54784a12 - - - - -] resync (5ce11b1a-6768-4ff1-ad36-060502981129): ['Agent port was deleted'] _periodic_resync_helper /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:255
2018-06-30 09:12:32.308 31911 INFO neutron.agent.dhcp.agent [req-c8ec7e37-0459-4f5d-a27b-368f54784a12 - - - - -] Synchronizing state
2018-06-30 09:12:33.137 31911 INFO neutron.agent.dhcp.agent [req-2f8845e2-ba91-4613-9889-3933c99c2d58 - - - - -] All active networks have been fetched through RPC.
2018-06-30 09:12:33.138 31911 INFO neutron.agent.dhcp.agent [-] Starting network 8fa9a212-be1e-480a-988d-8a3f899b6e3c dhcp configuration
2018-06-30 09:12:33.139 31911 INFO neutron.agent.dhcp.agent [-] Finished network 8fa9a212-be1e-480a-988d-8a3f899b6e3c dhcp configuration
2018-06-30 09:12:33.140 31911 INFO neutron.agent.dhcp.agent [req-2f8845e2-ba91-4613-9889-3933c99c2d58 - - - - -] Synchronizing state complete
2018-06-30 09:12:34.494 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-30 09:12:34.496 31911 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
