2018-09-13 21:05:48.184 11218 DEBUG nova.osapi_compute.wsgi.server [req-1c4597ae-929a-4860-8397-389088b26453 02e248cd8f0843eea56830a54be7a7df 194f3e7e9006484dbd7057072756dcfb - default default] (11218) accepted ('10.0.20.24', 60098) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-13 21:05:48.524 11218 DEBUG nova.api.openstack.wsgi [req-98969508-8725-4a83-afc4-57efe32d98f3 f1b283a253ec480b9080aecb563ea03c 347d4a4675444ede83c0ac98fa28a3f6 - 9beef8792a9a476eafe3638d4ec1d7c6 9beef8792a9a476eafe3638d4ec1d7c6] Action: 'create', calling method: <function version_select at 0x7f8703d46aa0>, body: {"keypair": {"public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFxb+jYrUdxvU29HwMjLT0LX2+4/OhUF8ZLQ2MGTR9eUd3d22xwNqCUJl3cMk9ZEI53TgTKgqD4cABocuP/iebbhBaYUWQSW3dQLB74gmh/GL9X14LJmML2ZSqffegt7JJbEBoR0OItJEn8YwahezWmtG51G2Cg5seTqH/7sIQgdcBsVUf3GYKsPVex3I9CHi16hzTPrJhj+N9VLBapKy7QEzbTYjJWtEDSbcsovW3fj1Q/1LhGBuPqt9LXHQo/xusWp3xuJgT+JBT1+uhidvxF97Dyybbsnbinpd6ExJM6Kv6fxsrSHdWN0THHKLj/6ytmvpRIZ+f9dxZpjG+vGyR root@localhost.localdomain\n", "name": "tempest-keypair-1536887066"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-13 21:05:48.650 11218 DEBUG nova.quota [req-98969508-8725-4a83-afc4-57efe32d98f3 f1b283a253ec480b9080aecb563ea03c 347d4a4675444ede83c0ac98fa28a3f6 - 9beef8792a9a476eafe3638d4ec1d7c6 9beef8792a9a476eafe3638d4ec1d7c6] Getting quotas for project 347d4a4675444ede83c0ac98fa28a3f6. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-13 21:05:48.668 11218 DEBUG nova.quota [req-98969508-8725-4a83-afc4-57efe32d98f3 f1b283a253ec480b9080aecb563ea03c 347d4a4675444ede83c0ac98fa28a3f6 - 9beef8792a9a476eafe3638d4ec1d7c6 9beef8792a9a476eafe3638d4ec1d7c6] Getting quotas for user f1b283a253ec480b9080aecb563ea03c and project 347d4a4675444ede83c0ac98fa28a3f6. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-13 21:05:48.837 11218 INFO nova.osapi_compute.wsgi.server [req-98969508-8725-4a83-afc4-57efe32d98f3 f1b283a253ec480b9080aecb563ea03c 347d4a4675444ede83c0ac98fa28a3f6 - 9beef8792a9a476eafe3638d4ec1d7c6 9beef8792a9a476eafe3638d4ec1d7c6] 10.0.20.24 "POST /v2.1/347d4a4675444ede83c0ac98fa28a3f6/os-keypairs HTTP/1.1" status: 200 len: 997 time: 0.6494839
2018-09-13 21:05:57.962 11225 DEBUG nova.osapi_compute.wsgi.server [req-788440fd-ff06-4e99-b5e9-39ac47657e12 - - - - -] (11225) accepted ('10.0.20.24', 60132) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-13 21:05:57.985 11225 WARNING keystonemiddleware.auth_token [req-788440fd-ff06-4e99-b5e9-39ac47657e12 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-13 21:06:00.109 11225 DEBUG nova.api.openstack.wsgi [req-9b1331b7-990f-4b7c-a918-c1c7bbf342b0 f1b283a253ec480b9080aecb563ea03c 347d4a4675444ede83c0ac98fa28a3f6 - 9beef8792a9a476eafe3638d4ec1d7c6 9beef8792a9a476eafe3638d4ec1d7c6] Calling method '<function version_select at 0x7f8703e16320>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-13 21:06:00.152 11225 DEBUG oslo_db.sqlalchemy.engines [req-9b1331b7-990f-4b7c-a918-c1c7bbf342b0 f1b283a253ec480b9080aecb563ea03c 347d4a4675444ede83c0ac98fa28a3f6 - 9beef8792a9a476eafe3638d4ec1d7c6 9beef8792a9a476eafe3638d4ec1d7c6] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-13 21:06:00.168 11225 WARNING oslo_db.sqlalchemy.utils [req-9b1331b7-990f-4b7c-a918-c1c7bbf342b0 f1b283a253ec480b9080aecb563ea03c 347d4a4675444ede83c0ac98fa28a3f6 - 9beef8792a9a476eafe3638d4ec1d7c6 9beef8792a9a476eafe3638d4ec1d7c6] Unique keys not in sort_keys. The sorting order may be unstable.
2018-09-13 21:06:00.193 11225 WARNING oslo_db.sqlalchemy.utils [req-9b1331b7-990f-4b7c-a918-c1c7bbf342b0 f1b283a253ec480b9080aecb563ea03c 347d4a4675444ede83c0ac98fa28a3f6 - 9beef8792a9a476eafe3638d4ec1d7c6 9beef8792a9a476eafe3638d4ec1d7c6] Unique keys not in sort_keys. The sorting order may be unstable.
2018-09-13 21:06:00.211 11225 INFO nova.osapi_compute.wsgi.server [req-9b1331b7-990f-4b7c-a918-c1c7bbf342b0 f1b283a253ec480b9080aecb563ea03c 347d4a4675444ede83c0ac98fa28a3f6 - 9beef8792a9a476eafe3638d4ec1d7c6 9beef8792a9a476eafe3638d4ec1d7c6] 10.0.20.24 "GET /v2.1/347d4a4675444ede83c0ac98fa28a3f6/os-keypairs HTTP/1.1" status: 200 len: 966 time: 2.2383251
2018-09-13 21:06:06.171 11213 DEBUG nova.api.openstack.wsgi [req-670467a6-5bdf-4e9f-b991-4c755eebd37e 0509a4af4ae04f458ff6255b643a48c1 a6274edd06114a55b9dc116852780190 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8704407690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-13 21:06:06.179 11213 DEBUG nova.compute.api [req-670467a6-5bdf-4e9f-b991-4c755eebd37e 0509a4af4ae04f458ff6255b643a48c1 a6274edd06114a55b9dc116852780190 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 9, 14, 1, 1, 7, 418621, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-13 21:06:06.227 11213 DEBUG oslo_concurrency.lockutils [req-670467a6-5bdf-4e9f-b991-4c755eebd37e 0509a4af4ae04f458ff6255b643a48c1 a6274edd06114a55b9dc116852780190 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-13 21:06:06.229 11213 DEBUG oslo_concurrency.lockutils [req-670467a6-5bdf-4e9f-b991-4c755eebd37e 0509a4af4ae04f458ff6255b643a48c1 a6274edd06114a55b9dc116852780190 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-13 21:06:06.358 11213 DEBUG nova.compute.api [req-670467a6-5bdf-4e9f-b991-4c755eebd37e 0509a4af4ae04f458ff6255b643a48c1 a6274edd06114a55b9dc116852780190 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-13 21:06:06.359 11213 DEBUG nova.compute.api [req-670467a6-5bdf-4e9f-b991-4c755eebd37e 0509a4af4ae04f458ff6255b643a48c1 a6274edd06114a55b9dc116852780190 - default default] Listing 1000 instances in cell 0dfb75e5-6834-4e0b-b55a-d61c751537ce(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-13 21:06:06.361 11213 DEBUG oslo_concurrency.lockutils [req-670467a6-5bdf-4e9f-b991-4c755eebd37e 0509a4af4ae04f458ff6255b643a48c1 a6274edd06114a55b9dc116852780190 - default default] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-13 21:06:06.362 11213 DEBUG oslo_concurrency.lockutils [req-670467a6-5bdf-4e9f-b991-4c755eebd37e 0509a4af4ae04f458ff6255b643a48c1 a6274edd06114a55b9dc116852780190 - default default] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-13 21:06:06.518 11213 DEBUG nova.policy [req-670467a6-5bdf-4e9f-b991-4c755eebd37e 0509a4af4ae04f458ff6255b643a48c1 a6274edd06114a55b9dc116852780190 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'0509a4af4ae04f458ff6255b643a48c1', 'roles': [u'ResellerAdmin', u'admin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'a6274edd06114a55b9dc116852780190', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-13 21:06:06.522 11213 INFO nova.osapi_compute.wsgi.server [req-670467a6-5bdf-4e9f-b991-4c755eebd37e 0509a4af4ae04f458ff6255b643a48c1 a6274edd06114a55b9dc116852780190 - default default] 10.0.20.24 "GET /v2.1/a6274edd06114a55b9dc116852780190/servers/detail?all_tenants=True&changes-since=2018-09-14T01%3A01%3A07.418621%2B00%3A00 HTTP/1.1" status: 200 len: 413 time: 0.3724260
