2018-09-30 03:21:04.473 1117 DEBUG nova.osapi_compute.wsgi.server [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] (1117) accepted ('10.0.20.25', 59532) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:21:04.486 1117 WARNING keystonemiddleware.auth_token [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-30 03:21:06.653 1117 DEBUG nova.api.openstack.wsgi [req-0e1b592b-4eb4-4dc6-b4f6-1485ebd27c5a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Action: 'create', calling method: <function version_select at 0x7f98329928c0>, body: {"keypair": {"public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdKIoqqu2m/dsjufcKbpHlF+P/uyUAS15t04gg0y4KY1wX8QAFZAQSS/ZMQ//laX4bDWSO1g5kLlua8mDuC2rjIMck5XrqW+XwSoBhpWtPeuwWv+VBNigqhkUlU65HGZAueYwosDkNvsjo4EvqvfA3aY3+RSEyoqIQuUr4FuktghtUuhYOu6R3I6trjFeep5fksXIDQe9AIGzjWSuVYSc0IwOHB8JipV8ObVkWqbPJGaXAz+QJONY+ikfJw9fBl5R/0q5murY55rY8rZXfFyIdqSyV6Gz6lwTHkK1UEft4HAX3YNHPWrMeltA/RqAVvZtF/vf9+hdE/HL8aKiGmrch root@localhost.localdomain\n", "name": "tempest-keypair-1538291991"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-30 03:21:06.770 1117 DEBUG oslo_db.sqlalchemy.engines [req-0e1b592b-4eb4-4dc6-b4f6-1485ebd27c5a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:21:06.836 1117 DEBUG nova.quota [req-0e1b592b-4eb4-4dc6-b4f6-1485ebd27c5a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Getting quotas for project 0d30b19deced442cb8288aefeb26f6be. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-30 03:21:06.848 1117 DEBUG nova.quota [req-0e1b592b-4eb4-4dc6-b4f6-1485ebd27c5a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Getting quotas for user 3179b9bb4ef54103975d4ec2ed1913ff and project 0d30b19deced442cb8288aefeb26f6be. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-30 03:21:06.977 1117 INFO nova.osapi_compute.wsgi.server [req-0e1b592b-4eb4-4dc6-b4f6-1485ebd27c5a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "POST /v2.1/0d30b19deced442cb8288aefeb26f6be/os-keypairs HTTP/1.1" status: 200 len: 997 time: 2.4984350
2018-09-30 03:21:14.811 1118 DEBUG nova.osapi_compute.wsgi.server [req-e592ba46-d6f3-4e59-bbf7-a489ebc570f7 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] (1118) accepted ('10.0.20.25', 59570) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:21:15.275 1118 DEBUG nova.api.openstack.wsgi [req-51f79e54-7294-4dcb-b86a-a8e0a944e0ef 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<function version_select at 0x7f98328bd2a8>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:21:15.313 1118 DEBUG oslo_db.sqlalchemy.engines [req-51f79e54-7294-4dcb-b86a-a8e0a944e0ef 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:21:15.321 1118 WARNING oslo_db.sqlalchemy.utils [req-51f79e54-7294-4dcb-b86a-a8e0a944e0ef 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Unique keys not in sort_keys. The sorting order may be unstable.
2018-09-30 03:21:15.336 1118 WARNING oslo_db.sqlalchemy.utils [req-51f79e54-7294-4dcb-b86a-a8e0a944e0ef 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Unique keys not in sort_keys. The sorting order may be unstable.
2018-09-30 03:21:15.350 1118 INFO nova.osapi_compute.wsgi.server [req-51f79e54-7294-4dcb-b86a-a8e0a944e0ef 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/os-keypairs HTTP/1.1" status: 200 len: 966 time: 0.5343931
2018-09-30 03:22:33.017 1112 DEBUG nova.api.openstack.wsgi [req-af577b83-e7f5-4c9e-a522-ee14d4418cde bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832fad690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:22:33.025 1112 DEBUG nova.compute.api [req-af577b83-e7f5-4c9e-a522-ee14d4418cde bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 9, 30, 7, 17, 36, 210043, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-30 03:22:33.053 1112 DEBUG oslo_concurrency.lockutils [req-af577b83-e7f5-4c9e-a522-ee14d4418cde bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:22:33.055 1112 DEBUG oslo_concurrency.lockutils [req-af577b83-e7f5-4c9e-a522-ee14d4418cde bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:22:33.183 1112 DEBUG nova.compute.api [req-af577b83-e7f5-4c9e-a522-ee14d4418cde bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-30 03:22:33.184 1112 DEBUG nova.compute.api [req-af577b83-e7f5-4c9e-a522-ee14d4418cde bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-30 03:22:33.186 1112 DEBUG oslo_concurrency.lockutils [req-af577b83-e7f5-4c9e-a522-ee14d4418cde bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:22:33.186 1112 DEBUG oslo_concurrency.lockutils [req-af577b83-e7f5-4c9e-a522-ee14d4418cde bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:22:33.316 1112 DEBUG nova.policy [req-af577b83-e7f5-4c9e-a522-ee14d4418cde bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'bae51265fb0f4505a811a9fab7e142f1', 'roles': [u'ResellerAdmin', u'admin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'671ea1986554476bbcaa620e00697d23', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-30 03:22:33.328 1112 INFO nova.osapi_compute.wsgi.server [req-af577b83-e7f5-4c9e-a522-ee14d4418cde bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] 10.0.20.25 "GET /v2.1/671ea1986554476bbcaa620e00697d23/servers/detail?all_tenants=True&changes-since=2018-09-30T07%3A17%3A36.210043%2B00%3A00 HTTP/1.1" status: 200 len: 413 time: 0.3225100
2018-09-30 03:22:42.456 1112 DEBUG nova.api.openstack.wsgi [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832fad690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:22:42.462 1112 DEBUG nova.compute.api [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 9, 30, 7, 17, 42, 914073, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-30 03:22:42.487 1112 DEBUG oslo_concurrency.lockutils [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:22:42.488 1112 DEBUG oslo_concurrency.lockutils [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:22:42.583 1112 DEBUG nova.compute.api [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-30 03:22:42.584 1112 DEBUG nova.compute.api [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-30 03:22:42.585 1112 DEBUG oslo_concurrency.lockutils [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:22:42.586 1112 DEBUG oslo_concurrency.lockutils [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:22:42.682 1112 DEBUG nova.policy [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'bae51265fb0f4505a811a9fab7e142f1', 'roles': [u'ResellerAdmin', u'admin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'671ea1986554476bbcaa620e00697d23', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-30 03:22:42.686 1112 INFO nova.osapi_compute.wsgi.server [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] 10.0.20.25 "GET /v2.1/671ea1986554476bbcaa620e00697d23/servers/detail?all_tenants=True&changes-since=2018-09-30T07%3A17%3A42.914073%2B00%3A00 HTTP/1.1" status: 200 len: 413 time: 0.6616349
2018-09-30 03:23:47.885 1117 DEBUG nova.osapi_compute.wsgi.server [req-0e1b592b-4eb4-4dc6-b4f6-1485ebd27c5a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] (1117) accepted ('10.0.20.25', 34874) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:23:48.422 1117 DEBUG nova.api.openstack.wsgi [req-7ee96e3a-897d-42eb-b91e-c6e2ef30c1aa 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f9833337090>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:23:48.512 1117 INFO nova.api.openstack.wsgi [req-7ee96e3a-897d-42eb-b91e-c6e2ef30c1aa 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] HTTP exception thrown: Flavor m1.tiny could not be found.
2018-09-30 03:23:48.515 1117 DEBUG nova.api.openstack.wsgi [req-7ee96e3a-897d-42eb-b91e-c6e2ef30c1aa 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Returning 404 to user: Flavor m1.tiny could not be found. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-30 03:23:48.518 1117 INFO nova.osapi_compute.wsgi.server [req-7ee96e3a-897d-42eb-b91e-c6e2ef30c1aa 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/flavors/m1.tiny HTTP/1.1" status: 404 len: 500 time: 0.6287222
2018-09-30 03:23:48.549 1117 DEBUG nova.api.openstack.wsgi [req-bf3210f5-b6e1-498f-b1a6-f16592cb9d89 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method FlavorsController.index of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f98333ac850>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:23:48.641 1117 INFO nova.osapi_compute.wsgi.server [req-bf3210f5-b6e1-498f-b1a6-f16592cb9d89 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/flavors HTTP/1.1" status: 200 len: 2106 time: 0.1003079
2018-09-30 03:23:48.677 1117 DEBUG nova.api.openstack.wsgi [req-5ab8a0e4-85dc-4d6f-a2cc-7a8517b8ce7f 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f9833337090>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:23:48.712 1117 INFO nova.osapi_compute.wsgi.server [req-5ab8a0e4-85dc-4d6f-a2cc-7a8517b8ce7f 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0444679
2018-09-30 03:23:50.298 1117 DEBUG nova.api.openstack.wsgi [req-b7940e0d-1488-4b0a-adde-7f910680650c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Action: 'create', calling method: <bound method ServersController.create of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832fc2450>>, body: {"server": {"name": "tempest-INSTANCE_SAMPLE-1538291991", "imageRef": "f8637e40-b644-4124-a14f-8ae96d2f795d", "key_name": "tempest-keypair-1538291991", "flavorRef": "1", "max_count": 1, "min_count": 1, "networks": [{"uuid": "ebb1d9cf-75aa-43e5-bbf0-6af70529fcf8"}], "security_groups": [{"name": "3aded53e-ef1f-4cac-b029-8986b924bd67"}]}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-30 03:23:50.668 1117 DEBUG oslo_concurrency.lockutils [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:23:50.670 1117 DEBUG oslo_concurrency.lockutils [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:23:50.696 1117 DEBUG oslo_db.sqlalchemy.engines [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:23:50.713 1117 DEBUG oslo_concurrency.lockutils [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:23:50.717 1117 DEBUG oslo_concurrency.lockutils [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:23:50.742 1117 DEBUG oslo_db.sqlalchemy.engines [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:23:50.782 1117 WARNING nova.image.glance [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] No protocol specified in for api_server 'http://10.0.20.25:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-30 03:23:54.333 1117 DEBUG nova.network.neutronv2.api [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] validate_networks() for [(u'ebb1d9cf-75aa-43e5-bbf0-6af70529fcf8', None, None, None)] validate_networks /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1692
2018-09-30 03:23:54.864 1117 DEBUG nova.virt.hardware [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] emulator threads policy constraint: None get_emulator_threads_constraint /usr/lib/python2.7/site-packages/nova/virt/hardware.py:1289
2018-09-30 03:23:54.898 1117 DEBUG nova.quota [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Getting quotas for project 0d30b19deced442cb8288aefeb26f6be. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-30 03:23:54.907 1117 DEBUG nova.quota [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Getting quotas for user 3179b9bb4ef54103975d4ec2ed1913ff and project 0d30b19deced442cb8288aefeb26f6be. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-30 03:23:54.956 1117 DEBUG nova.quota [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Getting quotas for project 0d30b19deced442cb8288aefeb26f6be. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-30 03:23:54.965 1117 DEBUG nova.quota [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Getting quotas for user 3179b9bb4ef54103975d4ec2ed1913ff and project 0d30b19deced442cb8288aefeb26f6be. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-30 03:23:55.000 1117 DEBUG nova.quota [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Getting quotas for project 0d30b19deced442cb8288aefeb26f6be. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-30 03:23:55.009 1117 DEBUG nova.quota [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Getting quotas for user 3179b9bb4ef54103975d4ec2ed1913ff and project 0d30b19deced442cb8288aefeb26f6be. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-30 03:23:55.048 1117 DEBUG nova.context [req-2555fb97-0e22-40d6-81b3-8206b0d5a398 - - - - -] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-09-30 03:23:55.050 1117 DEBUG oslo_concurrency.lockutils [req-b7940e0d-1488-4b0a-adde-7f910680650c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:23:55.052 1117 DEBUG oslo_concurrency.lockutils [req-b7940e0d-1488-4b0a-adde-7f910680650c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:23:55.054 1117 DEBUG oslo_concurrency.lockutils [req-b7940e0d-1488-4b0a-adde-7f910680650c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:23:55.056 1117 DEBUG oslo_concurrency.lockutils [req-b7940e0d-1488-4b0a-adde-7f910680650c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:23:55.093 1117 DEBUG nova.quota [req-b7940e0d-1488-4b0a-adde-7f910680650c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Getting quotas for project 0d30b19deced442cb8288aefeb26f6be. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-30 03:23:55.100 1117 DEBUG nova.quota [req-b7940e0d-1488-4b0a-adde-7f910680650c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Getting quotas for user 3179b9bb4ef54103975d4ec2ed1913ff and project 0d30b19deced442cb8288aefeb26f6be. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-30 03:23:55.125 1117 DEBUG nova.compute.api [req-b7940e0d-1488-4b0a-adde-7f910680650c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Going to run 1 instances... _provision_instances /usr/lib/python2.7/site-packages/nova/compute/api.py:891
2018-09-30 03:23:55.165 1117 DEBUG nova.compute.api [req-b7940e0d-1488-4b0a-adde-7f910680650c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] [instance: e21e4f9c-7876-429f-9d1a-aba60a8556c2] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='f8637e40-b644-4124-a14f-8ae96d2f795d',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _bdm_validate_set_size_and_instance /usr/lib/python2.7/site-packages/nova/compute/api.py:1268
2018-09-30 03:23:55.473 1117 INFO nova.osapi_compute.wsgi.server [req-b7940e0d-1488-4b0a-adde-7f910680650c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "POST /v2.1/0d30b19deced442cb8288aefeb26f6be/servers HTTP/1.1" status: 202 len: 989 time: 5.1827979
2018-09-30 03:23:55.504 1117 DEBUG nova.api.openstack.wsgi [req-4a80fac7-dd51-45b0-bca7-e791e10d8da6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832ecd9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:23:55.506 1117 DEBUG nova.compute.api [req-4a80fac7-dd51-45b0-bca7-e791e10d8da6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] [instance: e21e4f9c-7876-429f-9d1a-aba60a8556c2] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-30 03:23:55.573 1117 DEBUG nova.policy [req-4a80fac7-dd51-45b0-bca7-e791e10d8da6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'3179b9bb4ef54103975d4ec2ed1913ff', 'roles': [u'admin'], 'user_domain_id': u'67da957ff7b7481da3e4a56887a03b3e', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'0d30b19deced442cb8288aefeb26f6be', 'project_domain_id': u'67da957ff7b7481da3e4a56887a03b3e'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-30 03:23:55.688 1117 INFO nova.osapi_compute.wsgi.server [req-4a80fac7-dd51-45b0-bca7-e791e10d8da6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers/e21e4f9c-7876-429f-9d1a-aba60a8556c2 HTTP/1.1" status: 200 len: 1857 time: 0.1940689
2018-09-30 03:23:55.787 1117 DEBUG nova.api.openstack.wsgi [req-55923c3b-9b03-4143-b568-2910af27ab33 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f9833337090>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:23:55.827 1117 INFO nova.osapi_compute.wsgi.server [req-55923c3b-9b03-4143-b568-2910af27ab33 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0494862
2018-09-30 03:24:02.808 1112 DEBUG nova.osapi_compute.wsgi.server [req-1a1034ca-9fb4-439c-b688-a432f8644ce8 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] (1112) accepted ('10.0.20.25', 34968) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:24:03.498 1112 INFO nova.osapi_compute.wsgi.server [req-db1118eb-ef15-4565-9ccf-1865ad39792e 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be HTTP/1.1" status: 404 len: 382 time: 0.6869380
2018-09-30 03:24:03.518 1112 DEBUG nova.api.openstack.wsgi [req-dd4515bb-f058-4c6d-9e7a-2d8ae53ed4a2 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f98333ac4d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:24:03.522 1112 INFO nova.osapi_compute.wsgi.server [req-dd4515bb-f058-4c6d-9e7a-2d8ae53ed4a2 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0123420
2018-09-30 03:24:03.928 1112 DEBUG nova.api.openstack.wsgi [req-5af62521-ed34-4488-977a-18aa02fcbde6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832ff6550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:24:03.931 1112 DEBUG nova.compute.api [req-5af62521-ed34-4488-977a-18aa02fcbde6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Searching by: {'deleted': False, 'project_id': u'0d30b19deced442cb8288aefeb26f6be', u'name': u'tempest-INSTANCE_SAMPLE-1538291991'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-30 03:24:03.953 1112 DEBUG oslo_concurrency.lockutils [req-5af62521-ed34-4488-977a-18aa02fcbde6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:03.953 1112 DEBUG oslo_concurrency.lockutils [req-5af62521-ed34-4488-977a-18aa02fcbde6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:04.040 1112 DEBUG nova.compute.api [req-5af62521-ed34-4488-977a-18aa02fcbde6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-30 03:24:04.041 1112 DEBUG nova.compute.api [req-5af62521-ed34-4488-977a-18aa02fcbde6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-30 03:24:04.044 1112 DEBUG oslo_concurrency.lockutils [req-5af62521-ed34-4488-977a-18aa02fcbde6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:04.045 1112 DEBUG oslo_concurrency.lockutils [req-5af62521-ed34-4488-977a-18aa02fcbde6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:04.161 1112 INFO nova.osapi_compute.wsgi.server [req-5af62521-ed34-4488-977a-18aa02fcbde6 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers?name=tempest-INSTANCE_SAMPLE-1538291991 HTTP/1.1" status: 200 len: 786 time: 0.2435291
2018-09-30 03:24:04.188 1112 DEBUG nova.api.openstack.wsgi [req-014c5afe-521d-418b-905c-b7277e84d944 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832ecd9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:24:04.192 1112 DEBUG nova.compute.api [req-014c5afe-521d-418b-905c-b7277e84d944 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] [instance: e21e4f9c-7876-429f-9d1a-aba60a8556c2] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-30 03:24:04.233 1112 DEBUG oslo_concurrency.lockutils [req-014c5afe-521d-418b-905c-b7277e84d944 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:04.234 1112 DEBUG oslo_concurrency.lockutils [req-014c5afe-521d-418b-905c-b7277e84d944 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:04.420 1112 DEBUG nova.objects.instance [req-014c5afe-521d-418b-905c-b7277e84d944 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lazy-loading 'services' on Instance uuid e21e4f9c-7876-429f-9d1a-aba60a8556c2 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-30 03:24:04.540 1112 DEBUG nova.policy [req-014c5afe-521d-418b-905c-b7277e84d944 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'3179b9bb4ef54103975d4ec2ed1913ff', 'roles': [u'admin'], 'user_domain_id': u'67da957ff7b7481da3e4a56887a03b3e', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'0d30b19deced442cb8288aefeb26f6be', 'project_domain_id': u'67da957ff7b7481da3e4a56887a03b3e'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-30 03:24:07.686 1112 INFO nova.osapi_compute.wsgi.server [req-014c5afe-521d-418b-905c-b7277e84d944 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers/e21e4f9c-7876-429f-9d1a-aba60a8556c2 HTTP/1.1" status: 200 len: 2434 time: 3.5059431
2018-09-30 03:24:12.227 1118 DEBUG nova.osapi_compute.wsgi.server [req-51f79e54-7294-4dcb-b86a-a8e0a944e0ef 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] (1118) accepted ('10.0.20.25', 35092) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:24:12.714 1118 DEBUG nova.api.openstack.wsgi [req-3cd5a745-cee8-4b20-b4a4-af373bbe55d0 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7f983317d810>>, body: {"events": [{"tag": "222f74f7-d153-4fad-a80e-ba5bdb082905", "name": "network-changed", "server_uuid": "e21e4f9c-7876-429f-9d1a-aba60a8556c2"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-30 03:24:12.768 1118 DEBUG oslo_concurrency.lockutils [req-3cd5a745-cee8-4b20-b4a4-af373bbe55d0 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:12.776 1118 DEBUG oslo_concurrency.lockutils [req-3cd5a745-cee8-4b20-b4a4-af373bbe55d0 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.008s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:12.805 1118 DEBUG oslo_db.sqlalchemy.engines [req-3cd5a745-cee8-4b20-b4a4-af373bbe55d0 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:24:12.877 1118 INFO nova.api.openstack.compute.server_external_events [req-3cd5a745-cee8-4b20-b4a4-af373bbe55d0 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Creating event network-changed:222f74f7-d153-4fad-a80e-ba5bdb082905 for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 on localhost.localdomain
2018-09-30 03:24:13.168 1118 INFO nova.osapi_compute.wsgi.server [req-3cd5a745-cee8-4b20-b4a4-af373bbe55d0 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] 10.0.20.25 "POST /v2.1/671ea1986554476bbcaa620e00697d23/os-server-external-events HTTP/1.1" status: 200 len: 578 time: 0.9382172
2018-09-30 03:24:16.342 1118 DEBUG nova.osapi_compute.wsgi.server [req-3cd5a745-cee8-4b20-b4a4-af373bbe55d0 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] (1118) accepted ('10.0.20.25', 35114) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:24:16.946 1118 INFO nova.osapi_compute.wsgi.server [req-6e248fa0-15ec-4d48-9355-4bbdc6da1a87 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be HTTP/1.1" status: 404 len: 382 time: 0.5986061
2018-09-30 03:24:16.970 1118 DEBUG nova.api.openstack.wsgi [req-da5e98fe-9efd-4119-97b6-ee90bd844526 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f98333ac4d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:24:16.973 1118 INFO nova.osapi_compute.wsgi.server [req-da5e98fe-9efd-4119-97b6-ee90bd844526 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0094061
2018-09-30 03:24:17.478 1118 DEBUG nova.api.openstack.wsgi [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832ff6550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:24:17.483 1118 DEBUG nova.compute.api [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Searching by: {'deleted': False, 'project_id': u'0d30b19deced442cb8288aefeb26f6be', u'name': u'tempest-INSTANCE_SAMPLE-1538291991'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-30 03:24:17.996 1118 DEBUG oslo_concurrency.lockutils [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:17.998 1118 DEBUG oslo_concurrency.lockutils [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:18.026 1118 DEBUG oslo_db.sqlalchemy.engines [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:24:18.161 1118 DEBUG nova.compute.api [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-30 03:24:18.163 1118 DEBUG nova.compute.api [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-30 03:24:18.164 1118 DEBUG nova.compute.api [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-30 03:24:18.167 1118 DEBUG oslo_concurrency.lockutils [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:18.168 1118 DEBUG oslo_concurrency.lockutils [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:18.291 1118 INFO nova.osapi_compute.wsgi.server [req-c09ccae5-8a34-4f49-b4a9-d036b6cf77e1 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers?name=tempest-INSTANCE_SAMPLE-1538291991 HTTP/1.1" status: 200 len: 786 time: 0.8269250
2018-09-30 03:24:18.323 1118 DEBUG nova.api.openstack.wsgi [req-29f6ac82-2e68-446f-a8d5-2acf39edd6ce 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832ecd9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:24:18.326 1118 DEBUG nova.compute.api [req-29f6ac82-2e68-446f-a8d5-2acf39edd6ce 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] [instance: e21e4f9c-7876-429f-9d1a-aba60a8556c2] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-30 03:24:18.358 1118 DEBUG oslo_concurrency.lockutils [req-29f6ac82-2e68-446f-a8d5-2acf39edd6ce 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:18.359 1118 DEBUG oslo_concurrency.lockutils [req-29f6ac82-2e68-446f-a8d5-2acf39edd6ce 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:18.584 1118 DEBUG nova.objects.instance [req-29f6ac82-2e68-446f-a8d5-2acf39edd6ce 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lazy-loading 'services' on Instance uuid e21e4f9c-7876-429f-9d1a-aba60a8556c2 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-30 03:24:18.708 1124 DEBUG nova.osapi_compute.wsgi.server [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] (1124) accepted ('10.0.20.25', 35150) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:24:18.722 1124 WARNING keystonemiddleware.auth_token [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-30 03:24:18.727 1118 DEBUG nova.policy [req-29f6ac82-2e68-446f-a8d5-2acf39edd6ce 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'3179b9bb4ef54103975d4ec2ed1913ff', 'roles': [u'admin'], 'user_domain_id': u'67da957ff7b7481da3e4a56887a03b3e', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'0d30b19deced442cb8288aefeb26f6be', 'project_domain_id': u'67da957ff7b7481da3e4a56887a03b3e'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-30 03:24:20.171 1118 INFO nova.osapi_compute.wsgi.server [req-29f6ac82-2e68-446f-a8d5-2acf39edd6ce 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers/e21e4f9c-7876-429f-9d1a-aba60a8556c2 HTTP/1.1" status: 200 len: 2581 time: 1.8614969
2018-09-30 03:24:20.825 1124 DEBUG nova.api.openstack.wsgi [req-21515d79-6f14-41a8-9788-dc73782155a5 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7f983317d810>>, body: {"events": [{"status": "completed", "tag": "222f74f7-d153-4fad-a80e-ba5bdb082905", "name": "network-vif-plugged", "server_uuid": "e21e4f9c-7876-429f-9d1a-aba60a8556c2"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-30 03:24:20.861 1124 DEBUG oslo_db.sqlalchemy.engines [req-21515d79-6f14-41a8-9788-dc73782155a5 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:24:20.916 1124 DEBUG oslo_concurrency.lockutils [req-21515d79-6f14-41a8-9788-dc73782155a5 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:20.922 1124 DEBUG oslo_concurrency.lockutils [req-21515d79-6f14-41a8-9788-dc73782155a5 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.007s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:20.946 1124 DEBUG oslo_db.sqlalchemy.engines [req-21515d79-6f14-41a8-9788-dc73782155a5 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:24:21.004 1124 INFO nova.api.openstack.compute.server_external_events [req-21515d79-6f14-41a8-9788-dc73782155a5 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Creating event network-vif-plugged:222f74f7-d153-4fad-a80e-ba5bdb082905 for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 on localhost.localdomain
2018-09-30 03:24:21.248 1124 INFO nova.osapi_compute.wsgi.server [req-21515d79-6f14-41a8-9788-dc73782155a5 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] 10.0.20.25 "POST /v2.1/671ea1986554476bbcaa620e00697d23/os-server-external-events HTTP/1.1" status: 200 len: 582 time: 2.5362871
2018-09-30 03:24:31.763 1117 DEBUG nova.osapi_compute.wsgi.server [req-55923c3b-9b03-4143-b568-2910af27ab33 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] (1117) accepted ('10.0.20.25', 35210) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:24:32.088 1117 INFO nova.osapi_compute.wsgi.server [req-c45b9296-4052-4c69-a004-ea6a1877d19c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be HTTP/1.1" status: 404 len: 382 time: 0.3222990
2018-09-30 03:24:32.111 1117 DEBUG nova.api.openstack.wsgi [req-cc6ee3bb-745d-474c-a49a-46b9ce2f5b58 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f98333ac4d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:24:32.114 1117 INFO nova.osapi_compute.wsgi.server [req-cc6ee3bb-745d-474c-a49a-46b9ce2f5b58 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0103760
2018-09-30 03:24:32.545 1117 DEBUG nova.api.openstack.wsgi [req-0a6259fe-0db9-403d-8251-8c3b2eb4680a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832ff6550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:24:32.550 1117 DEBUG nova.compute.api [req-0a6259fe-0db9-403d-8251-8c3b2eb4680a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Searching by: {'deleted': False, 'project_id': u'0d30b19deced442cb8288aefeb26f6be', u'name': u'tempest-INSTANCE_SAMPLE-1538291991'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-30 03:24:32.570 1117 DEBUG oslo_concurrency.lockutils [req-0a6259fe-0db9-403d-8251-8c3b2eb4680a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:32.571 1117 DEBUG oslo_concurrency.lockutils [req-0a6259fe-0db9-403d-8251-8c3b2eb4680a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:32.660 1117 DEBUG nova.compute.api [req-0a6259fe-0db9-403d-8251-8c3b2eb4680a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-30 03:24:32.661 1117 DEBUG nova.compute.api [req-0a6259fe-0db9-403d-8251-8c3b2eb4680a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-30 03:24:32.662 1117 DEBUG nova.compute.api [req-0a6259fe-0db9-403d-8251-8c3b2eb4680a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-30 03:24:32.664 1117 DEBUG oslo_concurrency.lockutils [req-0a6259fe-0db9-403d-8251-8c3b2eb4680a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:32.666 1117 DEBUG oslo_concurrency.lockutils [req-0a6259fe-0db9-403d-8251-8c3b2eb4680a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:32.769 1117 INFO nova.osapi_compute.wsgi.server [req-0a6259fe-0db9-403d-8251-8c3b2eb4680a 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers?name=tempest-INSTANCE_SAMPLE-1538291991 HTTP/1.1" status: 200 len: 786 time: 0.2365701
2018-09-30 03:24:32.797 1117 DEBUG nova.api.openstack.wsgi [req-33af3c0d-ba6f-4cfc-ba87-5b1c0650cf1c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832ecd9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:24:32.799 1117 DEBUG nova.compute.api [req-33af3c0d-ba6f-4cfc-ba87-5b1c0650cf1c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] [instance: e21e4f9c-7876-429f-9d1a-aba60a8556c2] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-30 03:24:32.811 1117 DEBUG oslo_concurrency.lockutils [req-33af3c0d-ba6f-4cfc-ba87-5b1c0650cf1c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:32.812 1117 DEBUG oslo_concurrency.lockutils [req-33af3c0d-ba6f-4cfc-ba87-5b1c0650cf1c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:33.040 1117 DEBUG nova.objects.instance [req-33af3c0d-ba6f-4cfc-ba87-5b1c0650cf1c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lazy-loading 'services' on Instance uuid e21e4f9c-7876-429f-9d1a-aba60a8556c2 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-30 03:24:33.182 1117 DEBUG nova.policy [req-33af3c0d-ba6f-4cfc-ba87-5b1c0650cf1c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'3179b9bb4ef54103975d4ec2ed1913ff', 'roles': [u'admin'], 'user_domain_id': u'67da957ff7b7481da3e4a56887a03b3e', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'0d30b19deced442cb8288aefeb26f6be', 'project_domain_id': u'67da957ff7b7481da3e4a56887a03b3e'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-30 03:24:34.119 1117 INFO nova.osapi_compute.wsgi.server [req-33af3c0d-ba6f-4cfc-ba87-5b1c0650cf1c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers/e21e4f9c-7876-429f-9d1a-aba60a8556c2 HTTP/1.1" status: 200 len: 2598 time: 1.3307569
2018-09-30 03:24:56.346 1151 DEBUG nova.metadata.wsgi.server [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] (1151) accepted ('10.0.20.25', 46920) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:24:56.411 1151 DEBUG oslo_db.sqlalchemy.engines [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:24:56.490 1151 DEBUG oslo_concurrency.lockutils [req-434a0309-657f-42ba-a3c0-2ab2da4ed455 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:56.500 1151 DEBUG oslo_concurrency.lockutils [req-434a0309-657f-42ba-a3c0-2ab2da4ed455 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.010s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:56.535 1151 DEBUG oslo_db.sqlalchemy.engines [req-434a0309-657f-42ba-a3c0-2ab2da4ed455 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:24:59.166 1151 WARNING oslo_config.cfg [req-434a0309-657f-42ba-a3c0-2ab2da4ed455 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-30 03:24:59.170 1151 INFO nova.metadata.wsgi.server [req-434a0309-657f-42ba-a3c0-2ab2da4ed455 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/instance-id HTTP/1.1" status: 200 len: 127 time: 2.8159781
2018-09-30 03:24:59.575 1153 DEBUG nova.metadata.wsgi.server [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] (1153) accepted ('10.0.20.25', 46934) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:24:59.630 1153 DEBUG oslo_db.sqlalchemy.engines [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:24:59.707 1153 DEBUG oslo_concurrency.lockutils [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:24:59.715 1153 DEBUG oslo_concurrency.lockutils [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.008s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:24:59.740 1153 DEBUG oslo_db.sqlalchemy.engines [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:02.300 1153 WARNING oslo_config.cfg [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-30 03:25:02.304 1153 INFO nova.metadata.wsgi.server [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/public-keys HTTP/1.1" status: 200 len: 152 time: 2.7235041
2018-09-30 03:25:02.984 1142 DEBUG nova.metadata.wsgi.server [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] (1142) accepted ('10.0.20.25', 46948) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:03.032 1142 DEBUG oslo_db.sqlalchemy.engines [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:03.086 1142 DEBUG oslo_concurrency.lockutils [req-f9573f26-ae6f-4d2f-a0e4-e6b86e639e22 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:03.098 1142 DEBUG oslo_concurrency.lockutils [req-f9573f26-ae6f-4d2f-a0e4-e6b86e639e22 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.012s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:03.131 1142 DEBUG oslo_db.sqlalchemy.engines [req-f9573f26-ae6f-4d2f-a0e4-e6b86e639e22 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:04.983 1142 WARNING oslo_config.cfg [req-f9573f26-ae6f-4d2f-a0e4-e6b86e639e22 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-30 03:25:04.985 1142 INFO nova.metadata.wsgi.server [req-f9573f26-ae6f-4d2f-a0e4-e6b86e639e22 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/public-keys/0/openssh-key HTTP/1.1" status: 200 len: 526 time: 1.9941630
2018-09-30 03:25:05.920 1161 DEBUG nova.metadata.wsgi.server [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] (1161) accepted ('10.0.20.25', 46970) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:05.966 1161 DEBUG oslo_db.sqlalchemy.engines [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:06.039 1161 DEBUG oslo_concurrency.lockutils [req-c426ebda-47e1-4981-a723-46d286c24701 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:06.048 1161 DEBUG oslo_concurrency.lockutils [req-c426ebda-47e1-4981-a723-46d286c24701 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.009s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:06.077 1161 DEBUG oslo_db.sqlalchemy.engines [req-c426ebda-47e1-4981-a723-46d286c24701 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:06.751 1117 DEBUG nova.osapi_compute.wsgi.server [req-33af3c0d-ba6f-4cfc-ba87-5b1c0650cf1c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] (1117) accepted ('10.0.20.25', 36408) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:07.199 1117 DEBUG nova.api.openstack.wsgi [req-31e1bf7f-87d9-4b6c-b692-5f10e9777b23 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832ecd9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:25:07.201 1117 DEBUG nova.compute.api [req-31e1bf7f-87d9-4b6c-b692-5f10e9777b23 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Failed to fetch instance by id tempest-INSTANCE_SAMPLE-1538291991 get /usr/lib/python2.7/site-packages/nova/compute/api.py:2329
2018-09-30 03:25:07.202 1117 INFO nova.api.openstack.wsgi [req-31e1bf7f-87d9-4b6c-b692-5f10e9777b23 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] HTTP exception thrown: Instance tempest-INSTANCE_SAMPLE-1538291991 could not be found.
2018-09-30 03:25:07.204 1117 DEBUG nova.api.openstack.wsgi [req-31e1bf7f-87d9-4b6c-b692-5f10e9777b23 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Returning 404 to user: Instance tempest-INSTANCE_SAMPLE-1538291991 could not be found. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-30 03:25:07.205 1117 INFO nova.osapi_compute.wsgi.server [req-31e1bf7f-87d9-4b6c-b692-5f10e9777b23 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers/tempest-INSTANCE_SAMPLE-1538291991 HTTP/1.1" status: 404 len: 530 time: 0.4530931
2018-09-30 03:25:07.230 1117 DEBUG nova.api.openstack.wsgi [req-f3d5f715-ad7d-4e46-b9ac-60550c85540c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832ff6550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:25:07.232 1117 DEBUG nova.compute.api [req-f3d5f715-ad7d-4e46-b9ac-60550c85540c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Searching by: {'deleted': False, 'project_id': u'0d30b19deced442cb8288aefeb26f6be', u'name': u'tempest-INSTANCE_SAMPLE-1538291991'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-30 03:25:07.246 1117 DEBUG oslo_concurrency.lockutils [req-f3d5f715-ad7d-4e46-b9ac-60550c85540c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:07.247 1117 DEBUG oslo_concurrency.lockutils [req-f3d5f715-ad7d-4e46-b9ac-60550c85540c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:07.298 1117 DEBUG nova.compute.api [req-f3d5f715-ad7d-4e46-b9ac-60550c85540c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-30 03:25:07.299 1117 DEBUG nova.compute.api [req-f3d5f715-ad7d-4e46-b9ac-60550c85540c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-30 03:25:07.300 1117 DEBUG oslo_concurrency.lockutils [req-f3d5f715-ad7d-4e46-b9ac-60550c85540c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:07.301 1117 DEBUG oslo_concurrency.lockutils [req-f3d5f715-ad7d-4e46-b9ac-60550c85540c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:07.380 1117 INFO nova.osapi_compute.wsgi.server [req-f3d5f715-ad7d-4e46-b9ac-60550c85540c 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers?name=tempest-INSTANCE_SAMPLE-1538291991 HTTP/1.1" status: 200 len: 784 time: 0.1556530
2018-09-30 03:25:07.413 1117 DEBUG nova.api.openstack.wsgi [req-5cc5be89-ca2e-4cc9-b6d3-d8bb347bd143 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832ecd9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:25:07.414 1117 DEBUG nova.compute.api [req-5cc5be89-ca2e-4cc9-b6d3-d8bb347bd143 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] [instance: e21e4f9c-7876-429f-9d1a-aba60a8556c2] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-30 03:25:07.434 1117 DEBUG oslo_concurrency.lockutils [req-5cc5be89-ca2e-4cc9-b6d3-d8bb347bd143 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:07.435 1117 DEBUG oslo_concurrency.lockutils [req-5cc5be89-ca2e-4cc9-b6d3-d8bb347bd143 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:07.597 1117 DEBUG nova.policy [req-5cc5be89-ca2e-4cc9-b6d3-d8bb347bd143 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'3179b9bb4ef54103975d4ec2ed1913ff', 'roles': [u'admin'], 'user_domain_id': u'67da957ff7b7481da3e4a56887a03b3e', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'0d30b19deced442cb8288aefeb26f6be', 'project_domain_id': u'67da957ff7b7481da3e4a56887a03b3e'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-30 03:25:07.693 1161 WARNING oslo_config.cfg [req-c426ebda-47e1-4981-a723-46d286c24701 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-30 03:25:07.695 1161 INFO nova.metadata.wsgi.server [req-c426ebda-47e1-4981-a723-46d286c24701 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/instance-id HTTP/1.1" status: 200 len: 127 time: 1.7682679
2018-09-30 03:25:08.365 1117 INFO nova.osapi_compute.wsgi.server [req-5cc5be89-ca2e-4cc9-b6d3-d8bb347bd143 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers/e21e4f9c-7876-429f-9d1a-aba60a8556c2 HTTP/1.1" status: 200 len: 2205 time: 0.9629612
2018-09-30 03:25:08.403 1117 DEBUG nova.api.openstack.wsgi [req-c44f7464-b6a8-4787-aa2c-709d2bdadbdd 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Action: 'action', calling method: <function version_select at 0x7f9832f1fb18>, body: {"addFloatingIp": {"address": "172.24.4.6"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-30 03:25:08.406 1117 DEBUG nova.compute.api [req-c44f7464-b6a8-4787-aa2c-709d2bdadbdd 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] [instance: e21e4f9c-7876-429f-9d1a-aba60a8556c2] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-30 03:25:08.430 1117 DEBUG oslo_concurrency.lockutils [req-c44f7464-b6a8-4787-aa2c-709d2bdadbdd 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:08.431 1117 DEBUG oslo_concurrency.lockutils [req-c44f7464-b6a8-4787-aa2c-709d2bdadbdd 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:08.535 1117 DEBUG oslo_concurrency.lockutils [req-c44f7464-b6a8-4787-aa2c-709d2bdadbdd 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Acquired semaphore "refresh_cache-e21e4f9c-7876-429f-9d1a-aba60a8556c2" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 03:25:08.806 1153 DEBUG nova.metadata.wsgi.server [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] (1153) accepted ('10.0.20.25', 47004) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:08.811 1153 DEBUG nova.api.metadata.handler [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] Using cached metadata for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-30 03:25:08.814 1153 INFO nova.metadata.wsgi.server [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/ami-launch-index HTTP/1.1" status: 200 len: 117 time: 0.0040531
2018-09-30 03:25:09.837 1153 DEBUG nova.metadata.wsgi.server [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] (1153) accepted ('10.0.20.25', 47014) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:09.839 1153 DEBUG nova.api.metadata.handler [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] Using cached metadata for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-30 03:25:09.840 1153 INFO nova.metadata.wsgi.server [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/instance-type HTTP/1.1" status: 200 len: 123 time: 0.0016091
2018-09-30 03:25:10.150 1153 DEBUG nova.metadata.wsgi.server [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] (1153) accepted ('10.0.20.25', 47016) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:10.153 1153 DEBUG nova.api.metadata.handler [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] Using cached metadata for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-30 03:25:10.156 1153 INFO nova.metadata.wsgi.server [req-2144163f-493e-4040-8849-f54c2d03f3c2 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/local-ipv4 HTTP/1.1" status: 200 len: 125 time: 0.0036371
2018-09-30 03:25:10.406 1117 DEBUG nova.network.neutronv2.api [req-c44f7464-b6a8-4787-aa2c-709d2bdadbdd 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] [instance: e21e4f9c-7876-429f-9d1a-aba60a8556c2] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1315
2018-09-30 03:25:11.547 1142 DEBUG nova.metadata.wsgi.server [req-f9573f26-ae6f-4d2f-a0e4-e6b86e639e22 - - - - -] (1142) accepted ('10.0.20.25', 47032) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:11.553 1142 DEBUG nova.api.metadata.handler [req-f9573f26-ae6f-4d2f-a0e4-e6b86e639e22 - - - - -] Using cached metadata for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-30 03:25:11.556 1142 INFO nova.metadata.wsgi.server [req-f9573f26-ae6f-4d2f-a0e4-e6b86e639e22 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/public-ipv4 HTTP/1.1" status: 200 len: 116 time: 0.0031531
2018-09-30 03:25:11.818 1124 DEBUG nova.osapi_compute.wsgi.server [req-21515d79-6f14-41a8-9788-dc73782155a5 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] (1124) accepted ('10.0.20.25', 36464) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:12.239 1145 DEBUG nova.metadata.wsgi.server [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] (1145) accepted ('10.0.20.25', 47044) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:12.293 1145 DEBUG oslo_db.sqlalchemy.engines [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:12.340 1145 DEBUG oslo_concurrency.lockutils [req-fa96c28e-9212-453f-b811-37115d5a06d4 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:12.347 1145 DEBUG oslo_concurrency.lockutils [req-fa96c28e-9212-453f-b811-37115d5a06d4 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.007s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:12.371 1145 DEBUG oslo_db.sqlalchemy.engines [req-fa96c28e-9212-453f-b811-37115d5a06d4 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:12.457 1124 DEBUG nova.api.openstack.wsgi [req-dc8018e4-a9c5-4c88-bdf1-6044149479f2 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7f983317d810>>, body: {"events": [{"tag": "222f74f7-d153-4fad-a80e-ba5bdb082905", "name": "network-changed", "server_uuid": "e21e4f9c-7876-429f-9d1a-aba60a8556c2"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-30 03:25:12.482 1124 DEBUG oslo_concurrency.lockutils [req-dc8018e4-a9c5-4c88-bdf1-6044149479f2 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:12.483 1124 DEBUG oslo_concurrency.lockutils [req-dc8018e4-a9c5-4c88-bdf1-6044149479f2 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:12.875 1124 INFO nova.api.openstack.compute.server_external_events [req-dc8018e4-a9c5-4c88-bdf1-6044149479f2 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Creating event network-changed:222f74f7-d153-4fad-a80e-ba5bdb082905 for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 on localhost.localdomain
2018-09-30 03:25:12.907 1124 INFO nova.osapi_compute.wsgi.server [req-dc8018e4-a9c5-4c88-bdf1-6044149479f2 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] 10.0.20.25 "POST /v2.1/671ea1986554476bbcaa620e00697d23/os-server-external-events HTTP/1.1" status: 200 len: 578 time: 1.0860400
2018-09-30 03:25:13.175 1117 DEBUG nova.network.base_api [req-c44f7464-b6a8-4787-aa2c-709d2bdadbdd 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] [instance: e21e4f9c-7876-429f-9d1a-aba60a8556c2] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "222f74f7-d153-4fad-a80e-ba5bdb082905", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [{"meta": {}, "version": 4, "type": "floating", "address": "172.24.4.6"}], "address": "11.20.1.4"}], "version": 4, "meta": {"dhcp_server": "11.20.1.2"}, "dns": [{"meta": {}, "version": 4, "type": "dns", "address": "8.8.4.4"}], "routes": [], "cidr": "11.20.1.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "11.20.1.1"}}], "meta": {"injected": false, "tenant_id": "0d30b19deced442cb8288aefeb26f6be", "mtu": 1450}, "id": "ebb1d9cf-75aa-43e5-bbf0-6af70529fcf8", "label": "tempest-private-1538291991"}, "devname": "tap222f74f7-d1", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "datapath_type": "system", "ovs_hybrid_plug": true}, "address": "fa:16:3e:fa:c0:76", "active": true, "type": "ovs", "id": "222f74f7-d153-4fad-a80e-ba5bdb082905", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2018-09-30 03:25:13.214 1117 DEBUG oslo_concurrency.lockutils [req-c44f7464-b6a8-4787-aa2c-709d2bdadbdd 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Releasing semaphore "refresh_cache-e21e4f9c-7876-429f-9d1a-aba60a8556c2" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 03:25:13.216 1117 INFO nova.osapi_compute.wsgi.server [req-c44f7464-b6a8-4787-aa2c-709d2bdadbdd 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "POST /v2.1/0d30b19deced442cb8288aefeb26f6be/servers/e21e4f9c-7876-429f-9d1a-aba60a8556c2/action HTTP/1.1" status: 202 len: 411 time: 4.8253388
2018-09-30 03:25:14.510 1145 WARNING oslo_config.cfg [req-fa96c28e-9212-453f-b811-37115d5a06d4 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-30 03:25:14.514 1145 INFO nova.metadata.wsgi.server [req-fa96c28e-9212-453f-b811-37115d5a06d4 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/hostname HTTP/1.1" status: 200 len: 161 time: 2.2633440
2018-09-30 03:25:14.776 1163 DEBUG nova.metadata.wsgi.server [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] (1163) accepted ('10.0.20.25', 47068) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:14.830 1163 DEBUG oslo_db.sqlalchemy.engines [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:14.902 1163 DEBUG oslo_concurrency.lockutils [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:14.913 1163 DEBUG oslo_concurrency.lockutils [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.011s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:14.938 1163 DEBUG oslo_db.sqlalchemy.engines [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:16.852 1163 WARNING oslo_config.cfg [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-30 03:25:16.857 1163 INFO nova.metadata.wsgi.server [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/local-hostname HTTP/1.1" status: 200 len: 161 time: 2.0752261
2018-09-30 03:25:18.078 1163 DEBUG nova.metadata.wsgi.server [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] (1163) accepted ('10.0.20.25', 47098) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:18.083 1163 DEBUG nova.api.metadata.handler [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] Using cached metadata for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-30 03:25:18.088 1163 INFO nova.metadata.wsgi.server [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/user-data HTTP/1.1" status: 404 len: 176 time: 0.0065141
2018-09-30 03:25:18.393 1154 DEBUG nova.metadata.wsgi.server [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] (1154) accepted ('10.0.20.25', 47102) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:18.440 1154 DEBUG oslo_db.sqlalchemy.engines [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:18.499 1154 DEBUG oslo_concurrency.lockutils [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:18.508 1154 DEBUG oslo_concurrency.lockutils [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.009s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:18.537 1154 DEBUG oslo_db.sqlalchemy.engines [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:21.230 1154 WARNING oslo_config.cfg [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-30 03:25:21.233 1154 INFO nova.metadata.wsgi.server [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/block-device-mapping HTTP/1.1" status: 200 len: 124 time: 2.8304071
2018-09-30 03:25:21.841 1163 DEBUG nova.metadata.wsgi.server [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] (1163) accepted ('10.0.20.25', 47120) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:21.845 1163 DEBUG nova.api.metadata.handler [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] Using cached metadata for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-30 03:25:21.849 1163 INFO nova.metadata.wsgi.server [req-a0cb4937-beaa-40e1-b119-5dcea66b0d9d - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/block-device-mapping/ami HTTP/1.1" status: 200 len: 119 time: 0.0043619
2018-09-30 03:25:22.526 1154 DEBUG nova.metadata.wsgi.server [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] (1154) accepted ('10.0.20.25', 47126) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:22.532 1154 DEBUG nova.api.metadata.handler [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] Using cached metadata for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-30 03:25:22.534 1154 INFO nova.metadata.wsgi.server [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/block-device-mapping/root HTTP/1.1" status: 200 len: 124 time: 0.0043449
2018-09-30 03:25:23.234 1154 DEBUG nova.metadata.wsgi.server [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] (1154) accepted ('10.0.20.25', 47134) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:23.238 1154 DEBUG nova.api.metadata.handler [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] Using cached metadata for instance e21e4f9c-7876-429f-9d1a-aba60a8556c2 get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-30 03:25:23.241 1154 INFO nova.metadata.wsgi.server [req-a2654572-fb80-4746-a50c-e636a4e4d312 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/public-hostname HTTP/1.1" status: 200 len: 161 time: 0.0034080
2018-09-30 03:25:23.583 1152 DEBUG nova.metadata.wsgi.server [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] (1152) accepted ('10.0.20.25', 47136) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:23.639 1152 DEBUG oslo_db.sqlalchemy.engines [req-e951a9b5-025c-46f0-8301-fe8be679a1e7 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:23.688 1152 DEBUG oslo_concurrency.lockutils [req-e83d6be2-b695-436a-a7bf-d525623c2613 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:23.697 1152 DEBUG oslo_concurrency.lockutils [req-e83d6be2-b695-436a-a7bf-d525623c2613 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.009s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:23.733 1152 DEBUG oslo_db.sqlalchemy.engines [req-e83d6be2-b695-436a-a7bf-d525623c2613 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:24.220 1124 DEBUG nova.osapi_compute.wsgi.server [req-dc8018e4-a9c5-4c88-bdf1-6044149479f2 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] (1124) accepted ('10.0.20.25', 36572) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-30 03:25:24.753 1124 INFO nova.osapi_compute.wsgi.server [req-4dc1d9cf-5dd4-4464-bdd8-bee9b706ee45 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be HTTP/1.1" status: 404 len: 382 time: 0.5285051
2018-09-30 03:25:24.770 1124 DEBUG nova.api.openstack.wsgi [req-12d371cf-ca69-4e8a-8f83-8ee080404e03 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f98333ac4d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:25:24.773 1124 INFO nova.osapi_compute.wsgi.server [req-12d371cf-ca69-4e8a-8f83-8ee080404e03 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0099149
2018-09-30 03:25:25.102 1124 DEBUG nova.api.openstack.wsgi [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f9832fad690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-30 03:25:25.105 1124 DEBUG nova.compute.api [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Searching by: {'deleted': False, 'project_id': u'0d30b19deced442cb8288aefeb26f6be'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-30 03:25:25.121 1124 DEBUG oslo_concurrency.lockutils [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:25.123 1124 DEBUG oslo_concurrency.lockutils [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:25.141 1124 DEBUG oslo_db.sqlalchemy.engines [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-30 03:25:25.234 1124 DEBUG nova.compute.api [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-30 03:25:25.235 1124 DEBUG nova.compute.api [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-30 03:25:25.235 1124 DEBUG nova.compute.api [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-30 03:25:25.236 1124 DEBUG oslo_concurrency.lockutils [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:25.237 1124 DEBUG oslo_concurrency.lockutils [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:25.445 1124 DEBUG oslo_concurrency.lockutils [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 03:25:25.446 1124 DEBUG oslo_concurrency.lockutils [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 03:25:25.467 1124 DEBUG nova.policy [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'3179b9bb4ef54103975d4ec2ed1913ff', 'roles': [u'admin'], 'user_domain_id': u'67da957ff7b7481da3e4a56887a03b3e', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'0d30b19deced442cb8288aefeb26f6be', 'project_domain_id': u'67da957ff7b7481da3e4a56887a03b3e'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-30 03:25:25.736 1152 WARNING oslo_config.cfg [req-e83d6be2-b695-436a-a7bf-d525623c2613 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-30 03:25:25.739 1152 INFO nova.metadata.wsgi.server [req-e83d6be2-b695-436a-a7bf-d525623c2613 - - - - -] 11.20.1.4,10.0.20.25 "GET /2009-04-04/meta-data/placement/availability-zone HTTP/1.1" status: 200 len: 120 time: 2.1453381
2018-09-30 03:25:27.012 1124 INFO nova.osapi_compute.wsgi.server [req-0e0886c3-b411-468f-8085-7b9f54e96343 3179b9bb4ef54103975d4ec2ed1913ff 0d30b19deced442cb8288aefeb26f6be - 67da957ff7b7481da3e4a56887a03b3e 67da957ff7b7481da3e4a56887a03b3e] 10.0.20.25 "GET /v2.1/0d30b19deced442cb8288aefeb26f6be/servers/detail HTTP/1.1" status: 200 len: 2718 time: 1.9178789
