2018-09-30 12:33:28.134 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:33:28.138 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 12:34:28.135 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:34:28.139 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 12:35:18.882 9404 DEBUG oslo_concurrency.lockutils [req-9ffeff95-6626-4e0d-88ce-eb237f94cba6 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:35:19.522 9404 DEBUG neutron.agent.dhcp.agent [req-1cffc37c-5d08-475e-b2bc-34efbc7c0ee8 - - - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: enable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:35:19.525 9404 DEBUG neutron.agent.linux.utils [req-1cffc37c-5d08-475e-b2bc-34efbc7c0ee8 - - - - -] Unable to access /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:35:19.528 9404 DEBUG neutron.agent.linux.dhcp [req-1cffc37c-5d08-475e-b2bc-34efbc7c0ee8 - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-36e12e28-b5bb-40eb-ab60-1914f0862788 on network 36e12e28-b5bb-40eb-ab60-1914f0862788 does not yet exist. Checking for a reserved port. _setup_reserved_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1272
2018-09-30 12:35:19.529 9404 DEBUG neutron.agent.linux.dhcp [req-1cffc37c-5d08-475e-b2bc-34efbc7c0ee8 - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-36e12e28-b5bb-40eb-ab60-1914f0862788 on network 36e12e28-b5bb-40eb-ab60-1914f0862788 does not yet exist. Creating new one. _setup_new_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1293
2018-09-30 12:35:23.280 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.304 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'add', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.324 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'sysctl', '-w', 'net.ipv4.conf.all.promote_secondaries=1'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.351 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', 'link', 'set', 'lo', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.367 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'sysctl', '-w', 'net.ipv6.conf.default.accept_ra=0'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.389 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', 'link', 'set', 'tapc11ca9b1-5e', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.418 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-o', 'link', 'show', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.439 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-09-30 12:35:23.478 9404 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=None, port=tapc11ca9b1-5e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-30 12:35:23.481 9404 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Transaction caused no change do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:114
2018-09-30 12:35:23.483 9404 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): AddPortCommand(bridge=br-int, may_exist=False, port=tapc11ca9b1-5e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-30 12:35:23.485 9404 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=1): DbSetCommand(table=Port, col_values=(('tag', 4095),), record=tapc11ca9b1-5e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-30 12:35:23.487 9404 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=2): DbSetCommand(table=Interface, col_values=(('type', 'internal'), ('external_ids', {'iface-id': u'c11ca9b1-5eb1-4ecf-9733-713da9d8f7e3', 'iface-status': 'active', 'attached-mac': u'fa:16:3e:d8:04:b5'})), record=tapc11ca9b1-5e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-30 12:35:23.534 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tapc11ca9b1-5e', 'address', 'fa:16:3e:d8:04:b5'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.547 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.561 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tapc11ca9b1-5e', 'netns', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.584 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', 'link', 'set', 'tapc11ca9b1-5e', 'mtu', '1450'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.599 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', 'link', 'set', 'tapc11ca9b1-5e', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.619 9404 DEBUG oslo_concurrency.lockutils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Acquired semaphore "iptables-qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:35:23.620 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'iptables-save'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.647 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'iptables-restore', '-n'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.670 9404 DEBUG neutron.agent.linux.iptables_manager [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] IPTablesManager.apply completed with success. 56 iptables commands were issued _apply_synchronized /usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py:601
2018-09-30 12:35:23.671 9404 DEBUG oslo_concurrency.lockutils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Releasing semaphore "iptables-qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:35:23.672 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-o', 'link', 'show', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.689 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', 'addr', 'show', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.703 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'addr', 'add', '11.229.1.2/24', 'scope', 'global', 'dev', 'tapc11ca9b1-5e', 'brd', '11.229.1.255'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.721 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.736 9404 DEBUG neutron.agent.linux.dhcp [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Setting IPv4 gateway for dhcp netns on net 36e12e28-b5bb-40eb-ab60-1914f0862788 to 11.229.1.1 _set_default_route_ip_version /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1169
2018-09-30 12:35:23.738 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'replace', 'default', 'via', '11.229.1.1', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.753 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.768 9404 DEBUG neutron.agent.linux.dhcp [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Cleaning stale devices for network 36e12e28-b5bb-40eb-ab60-1914f0862788 _cleanup_stale_devices /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1374
2018-09-30 12:35:23.770 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.782 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'find', '/sys/class/net', '-maxdepth', '1', '-type', 'l', '-printf', '%f '] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.799 9404 DEBUG neutron.agent.linux.dhcp [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Building initial lease file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/leases _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:626
2018-09-30 12:35:23.802 9404 DEBUG neutron.agent.linux.dhcp [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Done building initial lease file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/leases with contents:
1538411723 fa:16:3e:d8:04:b5 11.229.1.2 * *
 _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:654
2018-09-30 12:35:23.803 9404 DEBUG neutron.agent.linux.dhcp [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:35:23.805 9404 DEBUG neutron.agent.linux.dhcp [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:35:23.809 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Unable to access /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:35:23.811 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'dnsmasq', '--no-hosts', '--no-resolv', '--strict-order', '--except-interface=lo', '--pid-file=/var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/pid', '--dhcp-hostsfile=/var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host', '--addn-hosts=/var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/addn_hosts', '--dhcp-optsfile=/var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/opts', '--dhcp-leasefile=/var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/leases', '--dhcp-match=set:ipxe,175', '--bind-interfaces', '--interface=tapc11ca9b1-5e', '--dhcp-range=set:tag0,11.229.1.0,static,255.255.255.0,86400s', '--dhcp-option-force=option:mtu,1450', '--dhcp-lease-max=256', '--conf-file=', '--domain=openstacklocal'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:23.857 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:35:23.865 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:35:23.866 9404 DEBUG neutron.agent.linux.external_process [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:35:23.868 9404 DEBUG oslo_concurrency.lockutils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:35:23.870 9404 DEBUG oslo_concurrency.lockutils [req-9ffeff95-6626-4e0d-88ce-eb237f94cba6 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:35:24.460 9404 DEBUG neutron.agent.dhcp.agent [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:35:24.463 9404 DEBUG neutron.agent.linux.dhcp [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:35:24.469 9404 DEBUG neutron.agent.linux.dhcp [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:35:24.477 9404 DEBUG neutron.agent.linux.utils [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:24.495 9404 DEBUG neutron.agent.linux.dhcp [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:35:24.497 9404 DEBUG neutron.agent.linux.utils [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:24.515 9404 DEBUG neutron.agent.linux.utils [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:24.532 9404 DEBUG neutron.agent.linux.utils [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:35:24.533 9404 DEBUG neutron.agent.linux.utils [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:35:24.534 9404 DEBUG neutron.agent.linux.external_process [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:35:24.535 9404 DEBUG oslo_concurrency.lockutils [req-3861ebf0-6633-499f-9846-65edcf0ecf73 - - - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:35:24.536 9404 DEBUG oslo_concurrency.lockutils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:35:24.537 9404 DEBUG neutron.agent.dhcp.agent [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Discarding stale port update: admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-30T16:35:19Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-36e12e28-b5bb-40eb-ab60-1914f0862788, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'f3621b97-a66c-454e-bf1b-de0c210b1958', u'ip_address': u'11.229.1.2'}], id=c11ca9b1-5eb1-4ecf-9733-713da9d8f7e3, mac_address=fa:16:3e:d8:04:b5, name=, network_id=36e12e28-b5bb-40eb-ab60-1914f0862788, port_security_enabled=False, project_id=35e01571f04d431da89e1f8c7e256548, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=35e01571f04d431da89e1f8c7e256548, updated_at=2018-09-30T16:35:20Z port_update_end /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:410
2018-09-30 12:35:24.538 9404 DEBUG oslo_concurrency.lockutils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:35:24.540 9404 DEBUG oslo_concurrency.lockutils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:35:24.541 9404 INFO neutron.agent.dhcp.agent [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-30T16:35:19Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-36e12e28-b5bb-40eb-ab60-1914f0862788, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'f3621b97-a66c-454e-bf1b-de0c210b1958', u'ip_address': u'11.229.1.2'}], id=c11ca9b1-5eb1-4ecf-9733-713da9d8f7e3, mac_address=fa:16:3e:d8:04:b5, name=, network_id=36e12e28-b5bb-40eb-ab60-1914f0862788, port_security_enabled=False, project_id=35e01571f04d431da89e1f8c7e256548, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=35e01571f04d431da89e1f8c7e256548, updated_at=2018-09-30T16:35:22Z
2018-09-30 12:35:24.543 9404 DEBUG neutron.agent.dhcp.agent [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:35:24.546 9404 DEBUG neutron.agent.linux.dhcp [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:35:24.548 9404 DEBUG neutron.agent.linux.dhcp [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:35:24.553 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:24.578 9404 DEBUG neutron.agent.linux.dhcp [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:35:24.580 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:24.597 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:35:24.624 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:35:24.625 9404 DEBUG neutron.agent.linux.utils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:35:24.626 9404 DEBUG neutron.agent.linux.external_process [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:35:24.628 9404 DEBUG oslo_concurrency.lockutils [req-fb05787a-64f2-44f7-80ad-f849657763ed - - - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:35:28.135 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:35:28.138 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 12:36:01.228 9404 DEBUG oslo_concurrency.lockutils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:36:01.229 9404 INFO neutron.agent.dhcp.agent [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-30T16:35:59Z, description=, device_id=b542dd47-ead9-45f6-93d2-34f1d3c13987, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'f3621b97-a66c-454e-bf1b-de0c210b1958', u'ip_address': u'11.229.1.1'}], id=13369993-cebc-4d5d-a5fa-9eaa10c779c9, mac_address=fa:16:3e:ab:76:05, name=, network_id=36e12e28-b5bb-40eb-ab60-1914f0862788, port_security_enabled=False, project_id=35e01571f04d431da89e1f8c7e256548, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=35e01571f04d431da89e1f8c7e256548, updated_at=2018-09-30T16:36:00Z
2018-09-30 12:36:01.231 9404 DEBUG neutron.agent.dhcp.agent [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:36:01.233 9404 DEBUG neutron.agent.linux.dhcp [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:36:01.240 9404 DEBUG neutron.agent.linux.dhcp [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:36:01.247 9404 DEBUG neutron.agent.linux.utils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:01.266 9404 DEBUG neutron.agent.linux.dhcp [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:36:01.268 9404 DEBUG neutron.agent.linux.utils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:01.288 9404 DEBUG neutron.agent.linux.utils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:01.308 9404 DEBUG neutron.agent.linux.utils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:01.309 9404 DEBUG neutron.agent.linux.utils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:01.310 9404 DEBUG neutron.agent.linux.external_process [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:36:01.311 9404 DEBUG oslo_concurrency.lockutils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:36:03.246 9404 DEBUG oslo_concurrency.lockutils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:36:03.247 9404 INFO neutron.agent.dhcp.agent [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-30T16:35:59Z, description=, device_id=b542dd47-ead9-45f6-93d2-34f1d3c13987, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'f3621b97-a66c-454e-bf1b-de0c210b1958', u'ip_address': u'11.229.1.1'}], id=13369993-cebc-4d5d-a5fa-9eaa10c779c9, mac_address=fa:16:3e:ab:76:05, name=, network_id=36e12e28-b5bb-40eb-ab60-1914f0862788, port_security_enabled=False, project_id=35e01571f04d431da89e1f8c7e256548, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=35e01571f04d431da89e1f8c7e256548, updated_at=2018-09-30T16:36:00Z
2018-09-30 12:36:03.249 9404 DEBUG neutron.agent.dhcp.agent [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:36:03.251 9404 DEBUG neutron.agent.linux.dhcp [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:36:03.253 9404 DEBUG neutron.agent.linux.dhcp [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:36:03.258 9404 DEBUG neutron.agent.linux.utils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:03.278 9404 DEBUG neutron.agent.linux.dhcp [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:36:03.281 9404 DEBUG neutron.agent.linux.utils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:03.300 9404 DEBUG neutron.agent.linux.utils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:03.316 9404 DEBUG neutron.agent.linux.utils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:03.319 9404 DEBUG neutron.agent.linux.utils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:03.323 9404 DEBUG neutron.agent.linux.external_process [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:36:03.325 9404 DEBUG oslo_concurrency.lockutils [req-6db39d12-6c5a-4378-b1e9-b99f4d144e0d 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:36:06.264 9404 DEBUG oslo_concurrency.lockutils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:36:06.265 9404 INFO neutron.agent.dhcp.agent [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-30T16:35:59Z, description=, device_id=b542dd47-ead9-45f6-93d2-34f1d3c13987, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'f3621b97-a66c-454e-bf1b-de0c210b1958', u'ip_address': u'11.229.1.1'}], id=13369993-cebc-4d5d-a5fa-9eaa10c779c9, mac_address=fa:16:3e:ab:76:05, name=, network_id=36e12e28-b5bb-40eb-ab60-1914f0862788, port_security_enabled=False, project_id=35e01571f04d431da89e1f8c7e256548, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=35e01571f04d431da89e1f8c7e256548, updated_at=2018-09-30T16:36:02Z
2018-09-30 12:36:06.266 9404 DEBUG neutron.agent.dhcp.agent [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:36:06.268 9404 DEBUG neutron.agent.linux.dhcp [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:36:06.270 9404 DEBUG neutron.agent.linux.dhcp [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:36:06.273 9404 DEBUG neutron.agent.linux.utils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:06.291 9404 DEBUG neutron.agent.linux.dhcp [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:36:06.293 9404 DEBUG neutron.agent.linux.utils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:06.310 9404 DEBUG neutron.agent.linux.utils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:06.326 9404 DEBUG neutron.agent.linux.utils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:06.328 9404 DEBUG neutron.agent.linux.utils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:06.330 9404 DEBUG neutron.agent.linux.external_process [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:36:06.331 9404 DEBUG oslo_concurrency.lockutils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:36:07.071 9404 DEBUG oslo_concurrency.lockutils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:36:07.072 9404 INFO neutron.agent.dhcp.agent [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-30T16:35:59Z, description=, device_id=b542dd47-ead9-45f6-93d2-34f1d3c13987, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'f3621b97-a66c-454e-bf1b-de0c210b1958', u'ip_address': u'11.229.1.1'}], id=13369993-cebc-4d5d-a5fa-9eaa10c779c9, mac_address=fa:16:3e:ab:76:05, name=, network_id=36e12e28-b5bb-40eb-ab60-1914f0862788, port_security_enabled=False, project_id=35e01571f04d431da89e1f8c7e256548, revision_number=6, security_groups=[], status=DOWN, tags=[], tenant_id=35e01571f04d431da89e1f8c7e256548, updated_at=2018-09-30T16:36:06Z
2018-09-30 12:36:07.073 9404 DEBUG neutron.agent.dhcp.agent [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:36:07.075 9404 DEBUG neutron.agent.linux.dhcp [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:36:07.077 9404 DEBUG neutron.agent.linux.dhcp [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:36:07.081 9404 DEBUG neutron.agent.linux.utils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:07.094 9404 DEBUG neutron.agent.linux.dhcp [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:36:07.095 9404 DEBUG neutron.agent.linux.utils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:07.107 9404 DEBUG neutron.agent.linux.utils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:07.120 9404 DEBUG neutron.agent.linux.utils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:07.121 9404 DEBUG neutron.agent.linux.utils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:07.122 9404 DEBUG neutron.agent.linux.external_process [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:36:07.123 9404 DEBUG oslo_concurrency.lockutils [req-1a5829ec-f1eb-496c-b63d-c809595683aa - - - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:36:15.403 9404 DEBUG oslo_concurrency.lockutils [req-c68ce1fc-f870-44f3-a252-3f661e0e84c3 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Acquired semaphore "dhcp-agent-network-lock-40fff4bc-a326-419b-b1c1-a7aa26b2d41a" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:36:15.404 9404 DEBUG oslo_concurrency.lockutils [req-c68ce1fc-f870-44f3-a252-3f661e0e84c3 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Releasing semaphore "dhcp-agent-network-lock-40fff4bc-a326-419b-b1c1-a7aa26b2d41a" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:36:19.673 9404 DEBUG oslo_concurrency.lockutils [req-6f1fa41f-8e8e-45e8-ad7c-eeecdde1b15a - - - - -] Acquired semaphore "dhcp-agent-network-lock-40fff4bc-a326-419b-b1c1-a7aa26b2d41a" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:36:19.673 9404 DEBUG oslo_concurrency.lockutils [req-6f1fa41f-8e8e-45e8-ad7c-eeecdde1b15a - - - - -] Releasing semaphore "dhcp-agent-network-lock-40fff4bc-a326-419b-b1c1-a7aa26b2d41a" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:36:20.695 9404 DEBUG oslo_concurrency.lockutils [req-6f1fa41f-8e8e-45e8-ad7c-eeecdde1b15a - - - - -] Acquired semaphore "dhcp-agent-network-lock-40fff4bc-a326-419b-b1c1-a7aa26b2d41a" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:36:20.696 9404 DEBUG oslo_concurrency.lockutils [req-6f1fa41f-8e8e-45e8-ad7c-eeecdde1b15a - - - - -] Releasing semaphore "dhcp-agent-network-lock-40fff4bc-a326-419b-b1c1-a7aa26b2d41a" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:36:28.135 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:36:28.139 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 12:36:41.715 9404 DEBUG oslo_concurrency.lockutils [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:36:41.716 9404 INFO neutron.agent.dhcp.agent [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-30T16:36:39Z, description=, device_id=4cb5f7a9-ad33-40ed-82f1-e3097606ca69, device_owner=, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'f3621b97-a66c-454e-bf1b-de0c210b1958', u'ip_address': u'11.229.1.12'}], id=ac045142-b91f-4cd3-8bc6-9b6c27f0426c, mac_address=fa:16:3e:e8:e5:73, name=, network_id=36e12e28-b5bb-40eb-ab60-1914f0862788, port_security_enabled=True, project_id=35e01571f04d431da89e1f8c7e256548, revision_number=3, security_groups=[u'ab5b9554-fa49-4947-bbf4-e0fcbd768dec'], status=DOWN, tags=[], tenant_id=35e01571f04d431da89e1f8c7e256548, updated_at=2018-09-30T16:36:40Z
2018-09-30 12:36:41.718 9404 DEBUG neutron.agent.dhcp.agent [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:36:41.720 9404 DEBUG neutron.agent.linux.dhcp [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:36:41.725 9404 DEBUG neutron.agent.linux.dhcp [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:36:41.731 9404 DEBUG neutron.agent.linux.utils [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:41.748 9404 DEBUG neutron.agent.linux.dhcp [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:36:41.750 9404 DEBUG neutron.agent.linux.utils [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:41.765 9404 DEBUG neutron.agent.linux.utils [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:41.780 9404 DEBUG neutron.agent.linux.utils [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:41.781 9404 DEBUG neutron.agent.linux.utils [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:41.782 9404 DEBUG neutron.agent.linux.external_process [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:36:41.783 9404 DEBUG oslo_concurrency.lockutils [req-bb3e42ea-0b14-4ca8-8d74-fb37c24fd00e 965c2c59770945b9a5e20bc213fda8ba 35e01571f04d431da89e1f8c7e256548 - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:36:43.935 9404 DEBUG oslo_concurrency.lockutils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:36:43.936 9404 INFO neutron.agent.dhcp.agent [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-30T16:36:39Z, description=, device_id=4cb5f7a9-ad33-40ed-82f1-e3097606ca69, device_owner=compute:nova, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'f3621b97-a66c-454e-bf1b-de0c210b1958', u'ip_address': u'11.229.1.12'}], id=ac045142-b91f-4cd3-8bc6-9b6c27f0426c, mac_address=fa:16:3e:e8:e5:73, name=, network_id=36e12e28-b5bb-40eb-ab60-1914f0862788, port_security_enabled=True, project_id=35e01571f04d431da89e1f8c7e256548, revision_number=4, security_groups=[u'ab5b9554-fa49-4947-bbf4-e0fcbd768dec'], status=DOWN, tags=[], tenant_id=35e01571f04d431da89e1f8c7e256548, updated_at=2018-09-30T16:36:42Z
2018-09-30 12:36:43.938 9404 DEBUG neutron.agent.dhcp.agent [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:36:43.940 9404 DEBUG neutron.agent.linux.dhcp [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:36:43.943 9404 DEBUG neutron.agent.linux.dhcp [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:36:43.950 9404 DEBUG neutron.agent.linux.utils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:43.967 9404 DEBUG neutron.agent.linux.dhcp [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:36:43.970 9404 DEBUG neutron.agent.linux.utils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:43.987 9404 DEBUG neutron.agent.linux.utils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:44.006 9404 DEBUG neutron.agent.linux.utils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:44.008 9404 DEBUG neutron.agent.linux.utils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:44.008 9404 DEBUG neutron.agent.linux.external_process [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:36:44.009 9404 DEBUG oslo_concurrency.lockutils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:36:44.810 9404 DEBUG oslo_concurrency.lockutils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:36:44.811 9404 INFO neutron.agent.dhcp.agent [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-30T16:36:39Z, description=, device_id=4cb5f7a9-ad33-40ed-82f1-e3097606ca69, device_owner=compute:nova, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'f3621b97-a66c-454e-bf1b-de0c210b1958', u'ip_address': u'11.229.1.12'}], id=ac045142-b91f-4cd3-8bc6-9b6c27f0426c, mac_address=fa:16:3e:e8:e5:73, name=, network_id=36e12e28-b5bb-40eb-ab60-1914f0862788, port_security_enabled=True, project_id=35e01571f04d431da89e1f8c7e256548, revision_number=5, security_groups=[u'ab5b9554-fa49-4947-bbf4-e0fcbd768dec'], status=DOWN, tags=[], tenant_id=35e01571f04d431da89e1f8c7e256548, updated_at=2018-09-30T16:36:44Z
2018-09-30 12:36:44.815 9404 DEBUG neutron.agent.dhcp.agent [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:36:44.818 9404 DEBUG neutron.agent.linux.dhcp [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:36:44.822 9404 DEBUG neutron.agent.linux.dhcp [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:36:44.827 9404 DEBUG neutron.agent.linux.utils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:44.846 9404 DEBUG neutron.agent.linux.dhcp [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:36:44.848 9404 DEBUG neutron.agent.linux.utils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:44.866 9404 DEBUG neutron.agent.linux.utils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:36:44.881 9404 DEBUG neutron.agent.linux.utils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:44.883 9404 DEBUG neutron.agent.linux.utils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:36:44.884 9404 DEBUG neutron.agent.linux.external_process [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:36:44.885 9404 DEBUG oslo_concurrency.lockutils [req-395bbfc7-734b-4bc0-828f-52aadc910ea5 6041b01c631d425d829cf96874ce50bf 671ea1986554476bbcaa620e00697d23 - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:37:09.727 9404 DEBUG oslo_concurrency.lockutils [req-0e42120f-9246-4ac4-8716-b7956b0c615d c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Acquired semaphore "dhcp-agent-network-lock-40fff4bc-a326-419b-b1c1-a7aa26b2d41a" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:37:09.728 9404 DEBUG oslo_concurrency.lockutils [req-0e42120f-9246-4ac4-8716-b7956b0c615d c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Releasing semaphore "dhcp-agent-network-lock-40fff4bc-a326-419b-b1c1-a7aa26b2d41a" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:37:11.152 9404 DEBUG oslo_concurrency.lockutils [req-0e42120f-9246-4ac4-8716-b7956b0c615d c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Acquired semaphore "dhcp-agent-network-lock-40fff4bc-a326-419b-b1c1-a7aa26b2d41a" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:37:11.153 9404 DEBUG oslo_concurrency.lockutils [req-0e42120f-9246-4ac4-8716-b7956b0c615d c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Releasing semaphore "dhcp-agent-network-lock-40fff4bc-a326-419b-b1c1-a7aa26b2d41a" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:37:28.136 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:37:28.140 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 12:38:28.136 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:38:28.141 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 12:39:28.137 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:39:28.141 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 12:40:28.137 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:40:28.141 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 12:41:28.137 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:41:28.141 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 12:41:43.751 9404 DEBUG oslo_concurrency.lockutils [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:41:43.753 9404 DEBUG neutron.agent.dhcp.agent [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:41:43.756 9404 DEBUG neutron.agent.linux.utils [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'dhcp_release', 'tapc11ca9b1-5e', '11.229.1.12', 'fa:16:3e:e8:e5:73'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:41:43.784 9404 DEBUG neutron.agent.linux.dhcp [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:41:43.815 9404 DEBUG neutron.agent.linux.dhcp [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:41:43.824 9404 DEBUG neutron.agent.linux.utils [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:41:43.842 9404 DEBUG neutron.agent.linux.dhcp [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:41:43.844 9404 DEBUG neutron.agent.linux.utils [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:41:43.863 9404 DEBUG neutron.agent.linux.utils [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:41:43.878 9404 DEBUG neutron.agent.linux.utils [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:41:43.879 9404 DEBUG neutron.agent.linux.utils [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:41:43.880 9404 DEBUG neutron.agent.linux.external_process [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:41:43.881 9404 DEBUG oslo_concurrency.lockutils [req-5a2465af-8a00-4295-8f80-8af12cd0716a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:42:28.137 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:42:28.142 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-30 12:42:38.280 9404 DEBUG oslo_concurrency.lockutils [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:42:38.281 9404 DEBUG neutron.agent.dhcp.agent [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:42:38.283 9404 DEBUG neutron.agent.linux.utils [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'dhcp_release', 'tapc11ca9b1-5e', '11.229.1.1', 'fa:16:3e:ab:76:05'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:42:38.304 9404 DEBUG neutron.agent.linux.dhcp [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Building host file: /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-30 12:42:38.308 9404 DEBUG neutron.agent.linux.dhcp [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Done building host file /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-30 12:42:38.313 9404 DEBUG neutron.agent.linux.utils [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:42:38.329 9404 DEBUG neutron.agent.linux.dhcp [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Reloading allocations for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-30 12:42:38.331 9404 DEBUG neutron.agent.linux.utils [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-4', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:42:38.348 9404 DEBUG neutron.agent.linux.utils [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788', 'ip', '-6', 'route', 'list', 'dev', 'tapc11ca9b1-5e'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:42:38.368 9404 DEBUG neutron.agent.linux.utils [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:42:38.370 9404 DEBUG neutron.agent.linux.utils [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:42:38.371 9404 DEBUG neutron.agent.linux.external_process [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:42:38.372 9404 DEBUG oslo_concurrency.lockutils [req-0e71b4e7-c462-493e-9131-a9554909eb9a c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:43:09.137 9404 DEBUG oslo_concurrency.lockutils [req-c4170c94-53e0-4dd0-a0c6-d4f501b3ac0b c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:43:09.139 9404 DEBUG neutron.agent.dhcp.agent [req-c4170c94-53e0-4dd0-a0c6-d4f501b3ac0b c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:43:09.144 9404 DEBUG neutron.agent.linux.utils [req-c4170c94-53e0-4dd0-a0c6-d4f501b3ac0b c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Running command (rootwrap daemon): ['kill', '-9', '18198'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:43:09.171 9404 DEBUG neutron.agent.linux.utils [req-c4170c94-53e0-4dd0-a0c6-d4f501b3ac0b c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-09-30 12:43:09.216 9404 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=br-int, port=tapc11ca9b1-5e) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-30 12:43:09.334 9404 DEBUG neutron.agent.linux.utils [req-12d896a1-6712-4f81-9b44-c0d3f9c4c5db - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:43:09.352 9404 DEBUG neutron.agent.linux.utils [req-12d896a1-6712-4f81-9b44-c0d3f9c4c5db - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'delete', 'qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:43:09.368 9404 DEBUG oslo_concurrency.lockutils [req-12d896a1-6712-4f81-9b44-c0d3f9c4c5db - - - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:43:19.907 9404 DEBUG oslo_concurrency.lockutils [req-dfe35055-9511-4aab-83fa-2670230f5572 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:43:20.293 9404 DEBUG neutron.agent.linux.utils [req-e52e52d7-1173-4c2c-9a43-88a9bdd03fcf - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:43:20.296 9404 DEBUG neutron.agent.linux.utils [req-e52e52d7-1173-4c2c-9a43-88a9bdd03fcf - - - - -] Unable to access /var/lib/neutron/external/pids/36e12e28-b5bb-40eb-ab60-1914f0862788.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:43:20.298 9404 DEBUG neutron.agent.linux.external_process [req-e52e52d7-1173-4c2c-9a43-88a9bdd03fcf - - - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:43:20.300 9404 DEBUG neutron.agent.dhcp.agent [req-e52e52d7-1173-4c2c-9a43-88a9bdd03fcf - - - - -] Calling driver for network: 36e12e28-b5bb-40eb-ab60-1914f0862788 action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-30 12:43:20.302 9404 DEBUG neutron.agent.linux.utils [req-e52e52d7-1173-4c2c-9a43-88a9bdd03fcf - - - - -] Unable to access /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:43:20.303 9404 DEBUG neutron.agent.linux.utils [req-e52e52d7-1173-4c2c-9a43-88a9bdd03fcf - - - - -] Unable to access /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-30 12:43:20.304 9404 DEBUG neutron.agent.linux.external_process [req-e52e52d7-1173-4c2c-9a43-88a9bdd03fcf - - - - -] No process started for 36e12e28-b5bb-40eb-ab60-1914f0862788 disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-30 12:43:20.305 9404 DEBUG neutron.agent.linux.dhcp [req-e52e52d7-1173-4c2c-9a43-88a9bdd03fcf - - - - -] Unable to access /var/lib/neutron/dhcp/36e12e28-b5bb-40eb-ab60-1914f0862788/interface _get_value_from_conf_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:271
2018-09-30 12:43:20.306 9404 DEBUG neutron.agent.linux.dhcp [req-e52e52d7-1173-4c2c-9a43-88a9bdd03fcf - - - - -] No interface exists for network 36e12e28-b5bb-40eb-ab60-1914f0862788 destroy /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1487
2018-09-30 12:43:20.360 9404 DEBUG neutron.agent.linux.utils [req-5f9c82e1-31be-4e81-aefd-9bf053c60600 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-30 12:43:20.381 9404 DEBUG neutron.agent.linux.dhcp [req-5f9c82e1-31be-4e81-aefd-9bf053c60600 - - - - -] Namespace already deleted: qdhcp-36e12e28-b5bb-40eb-ab60-1914f0862788 _destroy_namespace_and_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:249
2018-09-30 12:43:20.383 9404 DEBUG oslo_concurrency.lockutils [req-5f9c82e1-31be-4e81-aefd-9bf053c60600 - - - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:43:22.382 9404 DEBUG oslo_concurrency.lockutils [req-dfe35055-9511-4aab-83fa-2670230f5572 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Acquired semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-30 12:43:22.384 9404 DEBUG oslo_concurrency.lockutils [req-dfe35055-9511-4aab-83fa-2670230f5572 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - - -] Releasing semaphore "dhcp-agent-network-lock-36e12e28-b5bb-40eb-ab60-1914f0862788" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-30 12:43:23.884 9404 DEBUG neutron.agent.dhcp.agent [req-64db4b50-8515-45aa-8a53-4666d6109f24 - - - - -] resync (36e12e28-b5bb-40eb-ab60-1914f0862788): ['Agent port was deleted'] _periodic_resync_helper /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:256
2018-09-30 12:43:23.886 9404 INFO neutron.agent.dhcp.agent [req-64db4b50-8515-45aa-8a53-4666d6109f24 - - - - -] Synchronizing state
2018-09-30 12:43:24.676 9404 INFO neutron.agent.dhcp.agent [req-cea7cb01-8b94-47d4-a0d1-cc3a69201759 - - - - -] All active networks have been fetched through RPC.
2018-09-30 12:43:24.678 9404 INFO neutron.agent.dhcp.agent [-] Starting network 40fff4bc-a326-419b-b1c1-a7aa26b2d41a dhcp configuration
2018-09-30 12:43:24.679 9404 INFO neutron.agent.dhcp.agent [-] Finished network 40fff4bc-a326-419b-b1c1-a7aa26b2d41a dhcp configuration
2018-09-30 12:43:24.680 9404 INFO neutron.agent.dhcp.agent [req-cea7cb01-8b94-47d4-a0d1-cc3a69201759 - - - - -] Synchronizing state complete
2018-09-30 12:43:28.137 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-30 12:43:28.141 9404 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
