2018-09-13 12:35:14.500 31883 DEBUG neutron_lib.callbacks.manager [req-5fb062bf-7aec-4a30-ab42-1d4cb2783ce2 - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:35:14.524 31886 DEBUG neutron_lib.callbacks.manager [req-89dbae29-fa02-4c44-94b2-bbadd971a565 - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:35:15.351 31884 DEBUG neutron_lib.callbacks.manager [req-7040c77a-021c-4d12-80fe-5298e7d55d29 - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:35:25.803 31880 DEBUG neutron_lib.callbacks.manager [req-3b339432-1cb0-4c2c-9082-ff4198111acc - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:35:30.550 31882 DEBUG neutron_lib.callbacks.manager [req-2261b007-c58a-4810-9768-0d5c3148494e - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:35:32.253 31888 DEBUG neutron.db.agents_db [req-82208704-9954-412c-8378-82b21ffbda00 - - - - -] Agent healthcheck: found 5 active agents agent_health_check /usr/lib/python2.7/site-packages/neutron/db/agents_db.py:281
2018-09-13 12:35:40.822 31877 DEBUG neutron.wsgi [-] (31877) accepted ('10.0.20.22', 52824) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-13 12:35:40.827 31877 INFO neutron.wsgi [-] 10.0.20.22 "GET / HTTP/1.1" status: 200  len: 252 time: 0.0024009
2018-09-13 12:35:41.386 31877 DEBUG neutron.pecan_wsgi.hooks.policy_enforcement [req-da8c2337-5443-4e69-a5df-0d01fe089a92 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Attributes excluded by policy engine: [u'shared'] _exclude_attributes_by_policy /usr/lib/python2.7/site-packages/neutron/pecan_wsgi/hooks/policy_enforcement.py:256
2018-09-13 12:35:41.387 31877 DEBUG neutron.pecan_wsgi.hooks.policy_enforcement [req-da8c2337-5443-4e69-a5df-0d01fe089a92 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Attributes excluded by policy engine: [u'shared'] _exclude_attributes_by_policy /usr/lib/python2.7/site-packages/neutron/pecan_wsgi/hooks/policy_enforcement.py:256
2018-09-13 12:35:41.389 31877 INFO neutron.wsgi [req-da8c2337-5443-4e69-a5df-0d01fe089a92 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] 10.0.20.22 "GET /v2.0/subnets HTTP/1.1" status: 200  len: 1419 time: 0.5577011
2018-09-13 12:35:44.489 31879 DEBUG neutron_lib.callbacks.manager [req-0d801662-9fcd-4555-8907-cefa7efef68b - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:35:44.508 31881 DEBUG neutron_lib.callbacks.manager [req-89dbae29-fa02-4c44-94b2-bbadd971a565 - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:35:45.354 31885 DEBUG neutron_lib.callbacks.manager [req-cb5060e3-8a3a-47a8-8d4a-e0f4882eb156 - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:35:55.810 31887 DEBUG neutron_lib.callbacks.manager [req-3b339432-1cb0-4c2c-9082-ff4198111acc - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:00.499 31883 DEBUG neutron_lib.callbacks.manager [req-2261b007-c58a-4810-9768-0d5c3148494e - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:09.265 31888 DEBUG neutron.db.agents_db [req-82208704-9954-412c-8378-82b21ffbda00 - - - - -] Agent healthcheck: found 5 active agents agent_health_check /usr/lib/python2.7/site-packages/neutron/db/agents_db.py:281
2018-09-13 12:36:14.502 31886 DEBUG neutron_lib.callbacks.manager [req-f0911c27-9f4e-4f4b-879b-9e79def08689 - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:14.540 31884 DEBUG neutron_lib.callbacks.manager [req-89dbae29-fa02-4c44-94b2-bbadd971a565 - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:15.360 31880 DEBUG neutron_lib.callbacks.manager [req-f97e8760-dbe2-495b-958d-ed4927c3ee6a - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:25.789 31882 DEBUG neutron_lib.callbacks.manager [req-3b339432-1cb0-4c2c-9082-ff4198111acc - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:25.944 31875 DEBUG neutron.wsgi [-] (31875) accepted ('10.0.20.22', 53738) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-13 12:36:25.959 31875 INFO neutron.wsgi [-] 10.0.20.22 "GET / HTTP/1.1" status: 200  len: 252 time: 0.0098572
2018-09-13 12:36:25.968 31875 WARNING keystonemiddleware.auth_token [-] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-13 12:36:27.419 31875 DEBUG oslo_policy._cache_handler [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Reloading cached file /etc/neutron/policy.json read_cached_file /usr/lib/python2.7/site-packages/oslo_policy/_cache_handler.py:40
2018-09-13 12:36:27.460 31875 DEBUG oslo_policy.policy [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Reloaded policy file: /etc/neutron/policy.json _load_policy_file /usr/lib/python2.7/site-packages/oslo_policy/policy.py:685
2018-09-13 12:36:27.878 31875 DEBUG neutron.api.v2.base [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Request body: {u'security_group': {u'name': u'tempest-SECURITY_GROUP_SAMPLE-1536856507', u'description': u'tempest-SECURITY_GROUP_SAMPLE-1536856507'}} prepare_request_body /usr/lib/python2.7/site-packages/neutron/api/v2/base.py:695
2018-09-13 12:36:27.880 31875 DEBUG oslo_policy._cache_handler [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Reloading cached file /etc/neutron/policy.json read_cached_file /usr/lib/python2.7/site-packages/oslo_policy/_cache_handler.py:40
2018-09-13 12:36:27.900 31875 DEBUG oslo_policy.policy [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Reloaded policy file: /etc/neutron/policy.json _load_policy_file /usr/lib/python2.7/site-packages/oslo_policy/policy.py:685
2018-09-13 12:36:27.906 31875 INFO neutron.quota [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Loaded quota_driver: <neutron.db.quota.driver.DbQuotaDriver object at 0x7f7158d1b650>.
2018-09-13 12:36:27.977 31875 DEBUG neutron.db.quota.driver [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Resources subnetpool have unlimited quota limit. It is not required to calculate headroom  make_reservation /usr/lib/python2.7/site-packages/neutron/db/quota/driver.py:223
2018-09-13 12:36:27.990 31875 DEBUG neutron.quota.resource [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Usage tracker for resource:security_group and tenant:730cc4d401834213a241b41611184c96 is out of sync, need to count used quota count_used /usr/lib/python2.7/site-packages/neutron/quota/resource.py:274
2018-09-13 12:36:28.002 31875 DEBUG neutron.quota.resource [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Quota usage for security_group was recalculated. Used quota:0. count_used /usr/lib/python2.7/site-packages/neutron/quota/resource.py:293
2018-09-13 12:36:28.015 31875 DEBUG neutron.db.quota.driver [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Attempting to reserve 1 items for resource security_group. Total usage: 0; quota limit: 10; headroom:10 make_reservation /usr/lib/python2.7/site-packages/neutron/db/quota/driver.py:255
2018-09-13 12:36:28.055 31875 DEBUG neutron_lib.callbacks.manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks [] for security_group, before_create _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:28.090 31875 DEBUG neutron_lib.callbacks.manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks [] for security_group, before_create _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:28.373 31875 DEBUG neutron_lib.callbacks.manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks [] for security_group, precommit_create _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:28.380 31875 DEBUG neutron_lib.callbacks.manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks ['neutron.plugins.ml2.ovo_rpc._ObjectChangeHandler.handle_event-1031420'] for security_group, after_create _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:28.389 31875 DEBUG oslo_concurrency.lockutils [-] Lock "event-dispatch" acquired by "neutron.plugins.ml2.ovo_rpc.dispatch_events" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-13 12:36:28.747 31875 DEBUG neutron.api.rpc.handlers.resources_rpc [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] neutron.api.rpc.handlers.resources_rpc.ResourcesPushRpcApi method push called with arguments (<neutron_lib.context.Context object at 0x7f7158bab1d0>, [SecurityGroup(created_at=2018-09-13T16:36:28Z,description='Default security group',id=d7382c29-d255-4a83-b0f5-51fc8ad08af0,is_default=True,name='default',project_id='730cc4d401834213a241b41611184c96',revision_number=4,rules=[SecurityGroupRule(2a188a62-6a7e-425d-aa59-89dcbbbcfe18),SecurityGroupRule(46a68845-2ddd-43ef-a369-8548e5680f67),SecurityGroupRule(7cca1f9f-82af-40d4-80c1-8fbf030b241f),SecurityGroupRule(fee231a5-3ec3-48d3-999a-cdbc0131bc5a)],updated_at=2018-09-13T16:36:28Z)], 'updated') {} wrapper /usr/lib/python2.7/site-packages/oslo_log/helpers.py:66
2018-09-13 12:36:28.774 31875 DEBUG neutron.api.rpc.callbacks.version_manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Version for resource type Subnet changed None to 1.0 on consumer Open vSwitch agent@localhost.localdomain _set_version /usr/lib/python2.7/site-packages/neutron/api/rpc/callbacks/version_manager.py:119
2018-09-13 12:36:28.774 31875 DEBUG neutron.api.rpc.callbacks.version_manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Version for resource type Network changed None to 1.0 on consumer Open vSwitch agent@localhost.localdomain _set_version /usr/lib/python2.7/site-packages/neutron/api/rpc/callbacks/version_manager.py:119
2018-09-13 12:36:28.775 31875 DEBUG neutron.api.rpc.callbacks.version_manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Version for resource type SubPort changed None to 1.0 on consumer Open vSwitch agent@localhost.localdomain _set_version /usr/lib/python2.7/site-packages/neutron/api/rpc/callbacks/version_manager.py:119
2018-09-13 12:36:28.775 31875 DEBUG neutron.api.rpc.callbacks.version_manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Version for resource type SecurityGroup changed None to 1.0 on consumer Open vSwitch agent@localhost.localdomain _set_version /usr/lib/python2.7/site-packages/neutron/api/rpc/callbacks/version_manager.py:119
2018-09-13 12:36:28.776 31875 DEBUG neutron.api.rpc.callbacks.version_manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Version for resource type SecurityGroupRule changed None to 1.0 on consumer Open vSwitch agent@localhost.localdomain _set_version /usr/lib/python2.7/site-packages/neutron/api/rpc/callbacks/version_manager.py:119
2018-09-13 12:36:28.776 31875 DEBUG neutron.api.rpc.callbacks.version_manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Version for resource type Trunk changed None to 1.1 on consumer Open vSwitch agent@localhost.localdomain _set_version /usr/lib/python2.7/site-packages/neutron/api/rpc/callbacks/version_manager.py:119
2018-09-13 12:36:28.777 31875 DEBUG neutron.api.rpc.callbacks.version_manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Version for resource type QosPolicy changed None to 1.6 on consumer Open vSwitch agent@localhost.localdomain _set_version /usr/lib/python2.7/site-packages/neutron/api/rpc/callbacks/version_manager.py:119
2018-09-13 12:36:28.778 31875 DEBUG neutron.api.rpc.callbacks.version_manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Version for resource type Port changed None to 1.1 on consumer Open vSwitch agent@localhost.localdomain _set_version /usr/lib/python2.7/site-packages/neutron/api/rpc/callbacks/version_manager.py:119
2018-09-13 12:36:28.778 31875 DEBUG neutron.api.rpc.callbacks.version_manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Version for resource type Log changed None to 1.0 on consumer Open vSwitch agent@localhost.localdomain _set_version /usr/lib/python2.7/site-packages/neutron/api/rpc/callbacks/version_manager.py:119
2018-09-13 12:36:28.780 31875 DEBUG neutron.api.rpc.callbacks.version_manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Tracked resource versions report:
pushed versions:
{   'Log': set(['1.0']),
    'Network': set(['1.0']),
    'Port': set(['1.1']),
    'QosPolicy': set(['1.6']),
    'SecurityGroup': set(['1.0']),
    'SecurityGroupRule': set(['1.0']),
    'SubPort': set(['1.0']),
    'Subnet': set(['1.0']),
    'Trunk': set(['1.1'])}

consumer versions:
{   DHCP agent@localhost.localdomain: {   },
    L3 agent@localhost.localdomain: {   },
    Metadata agent@localhost.localdomain: {   },
    Metering agent@localhost.localdomain: {   },
    Open vSwitch agent@localhost.localdomain: {   u'Log': u'1.0',
                                                  u'Network': u'1.0',
                                                  u'Port': u'1.1',
                                                  u'QosPolicy': u'1.6',
                                                  u'SecurityGroup': u'1.0',
                                                  u'SecurityGroupRule': u'1.0',
                                                  u'SubPort': u'1.0',
                                                  u'Subnet': u'1.0',
                                                  u'Trunk': u'1.1'}}
 report /usr/lib/python2.7/site-packages/neutron/api/rpc/callbacks/version_manager.py:178
2018-09-13 12:36:28.826 31875 DEBUG oslo_concurrency.lockutils [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Lock "event-dispatch" released by "neutron.plugins.ml2.ovo_rpc.dispatch_events" :: held 0.438s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-13 12:36:28.899 31875 DEBUG neutron_lib.callbacks.manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks [] for security_group, precommit_create _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:28.908 31875 DEBUG neutron_lib.callbacks.manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks ['neutron.plugins.ml2.ovo_rpc._ObjectChangeHandler.handle_event-1031420'] for security_group, after_create _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:28.920 31875 DEBUG oslo_concurrency.lockutils [-] Lock "event-dispatch" acquired by "neutron.plugins.ml2.ovo_rpc.dispatch_events" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-13 12:36:28.999 31875 DEBUG neutron.quota.resource [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Persisted dirty status for tenant:730cc4d401834213a241b41611184c96 on resource:security_group_rule mark_dirty /usr/lib/python2.7/site-packages/neutron/quota/resource.py:207
2018-09-13 12:36:29.014 31875 DEBUG neutron.quota.resource [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Persisted dirty status for tenant:730cc4d401834213a241b41611184c96 on resource:security_group mark_dirty /usr/lib/python2.7/site-packages/neutron/quota/resource.py:207
2018-09-13 12:36:29.017 31875 DEBUG neutron.api.rpc.handlers.resources_rpc [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] neutron.api.rpc.handlers.resources_rpc.ResourcesPushRpcApi method push called with arguments (<neutron_lib.context.Context object at 0x7f7158b50390>, [SecurityGroup(created_at=2018-09-13T16:36:28Z,description='tempest-SECURITY_GROUP_SAMPLE-1536856507',id=5c4320b1-20e8-4a11-abb2-715fadc4c77c,is_default=False,name='tempest-SECURITY_GROUP_SAMPLE-1536856507',project_id='730cc4d401834213a241b41611184c96',revision_number=2,rules=[SecurityGroupRule(6e31b41c-18b1-4415-9d7e-07b05c208e9c),SecurityGroupRule(d82e679a-c392-4795-b88d-09c2a889c3e3)],updated_at=2018-09-13T16:36:28Z)], 'updated') {} wrapper /usr/lib/python2.7/site-packages/oslo_log/helpers.py:66
2018-09-13 12:36:29.025 31875 DEBUG oslo_concurrency.lockutils [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Lock "event-dispatch" released by "neutron.plugins.ml2.ovo_rpc.dispatch_events" :: held 0.105s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-13 12:36:29.027 31875 DEBUG neutron_lib.callbacks.manager [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks [] for security_group, before_response _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:29.029 31875 INFO neutron.wsgi [req-c53780ae-265c-42b8-be43-3ec40c708b69 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] 10.0.20.22 "POST /v2.0/security-groups HTTP/1.1" status: 201  len: 1617 time: 3.0651920
2018-09-13 12:36:30.494 31879 DEBUG neutron_lib.callbacks.manager [req-2261b007-c58a-4810-9768-0d5c3148494e - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:35.435 31875 DEBUG neutron.wsgi [-] (31875) accepted ('10.0.20.22', 53754) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-13 12:36:35.439 31875 INFO neutron.wsgi [-] 10.0.20.22 "GET / HTTP/1.1" status: 200  len: 252 time: 0.0019531
2018-09-13 12:36:35.893 31875 INFO neutron.api.v2.resource [req-688ce73a-095a-4294-a02e-2d3b35acd1ba c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] show failed (client error): The resource could not be found.
2018-09-13 12:36:35.895 31875 INFO neutron.wsgi [req-688ce73a-095a-4294-a02e-2d3b35acd1ba c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] 10.0.20.22 "GET /v2.0/security-groups/tempest-SECURITY_GROUP_SAMPLE-1536856507 HTTP/1.1" status: 404  len: 356 time: 0.4508190
2018-09-13 12:36:36.060 31875 DEBUG neutron.quota.resource [req-7197cebf-24f3-49df-9ad2-5b70246319c4 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Synchronizing usage tracker for tenant:730cc4d401834213a241b41611184c96 on resource:security_group resync /usr/lib/python2.7/site-packages/neutron/quota/resource.py:245
2018-09-13 12:36:36.097 31875 DEBUG neutron.quota.resource [req-7197cebf-24f3-49df-9ad2-5b70246319c4 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Unset dirty status for tenant:730cc4d401834213a241b41611184c96 on resource:security_group _resync /usr/lib/python2.7/site-packages/neutron/quota/resource.py:237
2018-09-13 12:36:36.099 31875 INFO neutron.wsgi [req-7197cebf-24f3-49df-9ad2-5b70246319c4 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] 10.0.20.22 "GET /v2.0/security-groups HTTP/1.1" status: 200  len: 20600 time: 0.1981320
2018-09-13 12:36:36.120 31875 DEBUG neutron.api.v2.base [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Request body: {u'security_group_rule': {u'direction': u'ingress', u'protocol': u'tcp', u'ethertype': u'IPv4', u'port_range_max': 22, u'security_group_id': u'5c4320b1-20e8-4a11-abb2-715fadc4c77c', u'port_range_min': 22, u'remote_ip_prefix': u'0.0.0.0/0'}} prepare_request_body /usr/lib/python2.7/site-packages/neutron/api/v2/base.py:695
2018-09-13 12:36:36.128 31875 DEBUG neutron.db.quota.driver [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Resources subnetpool have unlimited quota limit. It is not required to calculate headroom  make_reservation /usr/lib/python2.7/site-packages/neutron/db/quota/driver.py:223
2018-09-13 12:36:36.135 31875 DEBUG neutron.quota.resource [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Usage tracker for resource:security_group_rule and tenant:730cc4d401834213a241b41611184c96 is out of sync, need to count used quota count_used /usr/lib/python2.7/site-packages/neutron/quota/resource.py:274
2018-09-13 12:36:36.150 31875 DEBUG neutron.quota.resource [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Quota usage for security_group_rule was recalculated. Used quota:6. count_used /usr/lib/python2.7/site-packages/neutron/quota/resource.py:293
2018-09-13 12:36:36.165 31875 DEBUG neutron.db.quota.driver [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Attempting to reserve 1 items for resource security_group_rule. Total usage: 6; quota limit: 100; headroom:94 make_reservation /usr/lib/python2.7/site-packages/neutron/db/quota/driver.py:255
2018-09-13 12:36:36.263 31875 DEBUG neutron_lib.callbacks.manager [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks [] for security_group_rule, before_create _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:36.344 31875 DEBUG neutron_lib.callbacks.manager [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks [] for security_group_rule, precommit_create _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:36.349 31875 DEBUG neutron_lib.callbacks.manager [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks ['neutron.plugins.ml2.ovo_rpc._ObjectChangeHandler.handle_event-1031372'] for security_group_rule, after_create _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:36.351 31875 DEBUG oslo_concurrency.lockutils [-] Lock "event-dispatch" acquired by "neutron.plugins.ml2.ovo_rpc.dispatch_events" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-13 12:36:36.391 31875 DEBUG neutron.api.rpc.handlers.resources_rpc [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] neutron.api.rpc.handlers.resources_rpc.ResourcesPushRpcApi method push called with arguments (<neutron_lib.context.Context object at 0x7f71589e29d0>, [SecurityGroupRule(created_at=2018-09-13T16:36:36Z,description='',direction='ingress',ethertype='IPv4',id=76a3178d-be33-4340-8789-0bf35c690a69,port_range_max=22,port_range_min=22,project_id='730cc4d401834213a241b41611184c96',protocol='tcp',remote_group_id=<?>,remote_ip_prefix=0.0.0.0/0,revision_number=0,security_group_id=5c4320b1-20e8-4a11-abb2-715fadc4c77c,updated_at=2018-09-13T16:36:36Z)], 'updated') {} wrapper /usr/lib/python2.7/site-packages/oslo_log/helpers.py:66
2018-09-13 12:36:36.401 31875 DEBUG neutron.quota.resource [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Persisted dirty status for tenant:730cc4d401834213a241b41611184c96 on resource:security_group_rule mark_dirty /usr/lib/python2.7/site-packages/neutron/quota/resource.py:207
2018-09-13 12:36:36.404 31875 DEBUG oslo_concurrency.lockutils [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - - -] Lock "event-dispatch" released by "neutron.plugins.ml2.ovo_rpc.dispatch_events" :: held 0.052s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-13 12:36:36.418 31875 DEBUG neutron_lib.callbacks.manager [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Notify callbacks [] for security_group_rule, before_response _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:36.421 31875 INFO neutron.wsgi [req-6311baa3-7fdb-490e-b7c8-007867c905c0 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] 10.0.20.22 "POST /v2.0/security-group-rules HTTP/1.1" status: 201  len: 718 time: 0.3098691
2018-09-13 12:36:42.252 31873 DEBUG neutron.wsgi [-] (31873) accepted ('10.0.20.22', 54020) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-13 12:36:42.272 31873 INFO neutron.wsgi [-] 10.0.20.22 "GET / HTTP/1.1" status: 200  len: 252 time: 0.0131578
2018-09-13 12:36:42.285 31873 WARNING keystonemiddleware.auth_token [-] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-13 12:36:43.646 31873 DEBUG oslo_policy._cache_handler [req-143bb47d-77bc-445d-b98c-fad4a9dc739e c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Reloading cached file /etc/neutron/policy.json read_cached_file /usr/lib/python2.7/site-packages/oslo_policy/_cache_handler.py:40
2018-09-13 12:36:43.694 31873 DEBUG oslo_policy.policy [req-143bb47d-77bc-445d-b98c-fad4a9dc739e c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Reloaded policy file: /etc/neutron/policy.json _load_policy_file /usr/lib/python2.7/site-packages/oslo_policy/policy.py:685
2018-09-13 12:36:44.043 31873 DEBUG oslo_policy._cache_handler [req-143bb47d-77bc-445d-b98c-fad4a9dc739e c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Reloading cached file /etc/neutron/policy.json read_cached_file /usr/lib/python2.7/site-packages/oslo_policy/_cache_handler.py:40
2018-09-13 12:36:44.072 31873 DEBUG oslo_policy.policy [req-143bb47d-77bc-445d-b98c-fad4a9dc739e c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Reloaded policy file: /etc/neutron/policy.json _load_policy_file /usr/lib/python2.7/site-packages/oslo_policy/policy.py:685
2018-09-13 12:36:44.339 31873 INFO neutron.wsgi [req-143bb47d-77bc-445d-b98c-fad4a9dc739e c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] 10.0.20.22 "GET /v2.0/security-groups HTTP/1.1" status: 200  len: 21103 time: 2.0612929
2018-09-13 12:36:44.498 31881 DEBUG neutron_lib.callbacks.manager [req-c75bdb7b-f9c9-4fc5-9932-2936f06921fe - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:44.515 31885 DEBUG neutron_lib.callbacks.manager [req-89dbae29-fa02-4c44-94b2-bbadd971a565 - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:45.343 31887 DEBUG neutron_lib.callbacks.manager [req-b9f8707a-d3ee-4352-ada4-9c3e3bbdb1ff - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:36:46.257 31888 DEBUG neutron.db.agents_db [req-82208704-9954-412c-8378-82b21ffbda00 - - - - -] Agent healthcheck: found 5 active agents agent_health_check /usr/lib/python2.7/site-packages/neutron/db/agents_db.py:281
2018-09-13 12:36:53.087 31873 DEBUG neutron.wsgi [-] (31873) accepted ('10.0.20.22', 54030) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-13 12:36:53.091 31873 INFO neutron.wsgi [-] 10.0.20.22 "GET / HTTP/1.1" status: 200  len: 252 time: 0.0020730
2018-09-13 12:36:53.622 31873 INFO neutron.pecan_wsgi.hooks.translation [req-4557ebe6-e13e-482b-bff1-18618d0b5d73 aade3447accb4ba6835bc5ec3454f5a6 892b3d52c94348d8a7355f6390963dca - default default] GET failed (client error): The resource could not be found.
2018-09-13 12:36:53.624 31873 INFO neutron.wsgi [req-4557ebe6-e13e-482b-bff1-18618d0b5d73 aade3447accb4ba6835bc5ec3454f5a6 892b3d52c94348d8a7355f6390963dca - default default] 10.0.20.22 "GET /v2.0/networks/public HTTP/1.1" status: 404  len: 314 time: 0.5275052
2018-09-13 12:36:54.172 31873 DEBUG neutron.pecan_wsgi.hooks.policy_enforcement [req-60818715-8f0a-4919-92db-0fd116945487 aade3447accb4ba6835bc5ec3454f5a6 892b3d52c94348d8a7355f6390963dca - default default] Attributes excluded by policy engine: [u'vlan_transparent'] _exclude_attributes_by_policy /usr/lib/python2.7/site-packages/neutron/pecan_wsgi/hooks/policy_enforcement.py:256
2018-09-13 12:36:54.173 31873 DEBUG neutron.pecan_wsgi.hooks.policy_enforcement [req-60818715-8f0a-4919-92db-0fd116945487 aade3447accb4ba6835bc5ec3454f5a6 892b3d52c94348d8a7355f6390963dca - default default] Attributes excluded by policy engine: [u'vlan_transparent'] _exclude_attributes_by_policy /usr/lib/python2.7/site-packages/neutron/pecan_wsgi/hooks/policy_enforcement.py:256
2018-09-13 12:36:54.176 31873 INFO neutron.wsgi [req-60818715-8f0a-4919-92db-0fd116945487 aade3447accb4ba6835bc5ec3454f5a6 892b3d52c94348d8a7355f6390963dca - default default] 10.0.20.22 "GET /v2.0/networks HTTP/1.1" status: 200  len: 1542 time: 0.5444350
2018-09-13 12:36:55.809 31883 DEBUG neutron_lib.callbacks.manager [req-3b339432-1cb0-4c2c-9082-ff4198111acc - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:37:00.106 31874 DEBUG neutron.wsgi [-] (31874) accepted ('10.0.20.22', 54036) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-13 12:37:00.111 31874 INFO neutron.wsgi [-] 10.0.20.22 "GET / HTTP/1.1" status: 200  len: 252 time: 0.0025120
2018-09-13 12:37:00.483 31886 DEBUG neutron_lib.callbacks.manager [req-2261b007-c58a-4810-9768-0d5c3148494e - - - - -] Notify callbacks ['neutron.services.segments.db._update_segment_host_mapping_for_agent--9223363279054128327'] for agent, after_update _notify_loop /usr/lib/python2.7/site-packages/neutron_lib/callbacks/manager.py:167
2018-09-13 12:37:00.506 31874 DEBUG neutron.api.v2.base [req-bdef0a10-60d1-4ef9-acc4-581a51abd336 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Request body: {u'network': {u'name': u'tempest-private-1536856507', u'admin_state_up': True}} prepare_request_body /usr/lib/python2.7/site-packages/neutron/api/v2/base.py:695
2018-09-13 12:37:00.508 31874 INFO neutron.quota [req-bdef0a10-60d1-4ef9-acc4-581a51abd336 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Loaded quota_driver: <neutron.db.quota.driver.DbQuotaDriver object at 0x7f7158cd0a90>.
2018-09-13 12:37:00.519 31874 DEBUG neutron.db.quota.driver [req-bdef0a10-60d1-4ef9-acc4-581a51abd336 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Resources subnetpool have unlimited quota limit. It is not required to calculate headroom  make_reservation /usr/lib/python2.7/site-packages/neutron/db/quota/driver.py:223
2018-09-13 12:37:00.540 31874 DEBUG neutron.quota.resource [req-bdef0a10-60d1-4ef9-acc4-581a51abd336 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Usage tracker for resource:network and tenant:730cc4d401834213a241b41611184c96 is out of sync, need to count used quota count_used /usr/lib/python2.7/site-packages/neutron/quota/resource.py:274
2018-09-13 12:37:00.551 31874 DEBUG neutron.quota.resource [req-bdef0a10-60d1-4ef9-acc4-581a51abd336 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Quota usage for network was recalculated. Used quota:0. count_used /usr/lib/python2.7/site-packages/neutron/quota/resource.py:293
2018-09-13 12:37:00.563 31874 DEBUG neutron.db.quota.driver [req-bdef0a10-60d1-4ef9-acc4-581a51abd336 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Attempting to reserve 1 items for resource network. Total usage: 0; quota limit: 100; headroom:100 make_reservation /usr/lib/python2.7/site-packages/neutron/db/quota/driver.py:255
2018-09-13 12:37:00.588 31874 DEBUG neutron.pecan_wsgi.hooks.quota_enforcement [req-bdef0a10-60d1-4ef9-acc4-581a51abd336 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] Made reservation on behalf of 730cc4d401834213a241b41611184c96 for: {'network': 1} before /usr/lib/python2.7/site-packages/neutron/pecan_wsgi/hooks/quota_enforcement.py:55
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation [req-bdef0a10-60d1-4ef9-acc4-581a51abd336 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] POST failed.: Exception
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation Traceback (most recent call last):
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/pecan/core.py", line 678, in __call__
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     self.invoke_controller(controller, args, kwargs, state)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/pecan/core.py", line 569, in invoke_controller
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     result = controller(*args, **kwargs)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/db/api.py", line 93, in wrapped
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     setattr(e, '_RETRY_EXCEEDED', True)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     self.force_reraise()
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     six.reraise(self.type_, self.value, self.tb)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/db/api.py", line 89, in wrapped
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return f(*args, **kwargs)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 150, in wrapper
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     ectxt.value = e.inner_exc
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     self.force_reraise()
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     six.reraise(self.type_, self.value, self.tb)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 138, in wrapper
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return f(*args, **kwargs)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/db/api.py", line 128, in wrapped
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     LOG.debug("Retry wrapper got retriable exception: %s", e)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     self.force_reraise()
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     six.reraise(self.type_, self.value, self.tb)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/db/api.py", line 124, in wrapped
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return f(*dup_args, **dup_kwargs)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/pecan_wsgi/controllers/utils.py", line 76, in wrapped
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return f(*args, **kwargs)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/pecan_wsgi/controllers/resource.py", line 159, in post
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return self.create(resources)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/pecan_wsgi/controllers/resource.py", line 177, in create
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return {key: creator(*creator_args, **creator_kwargs)}
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/common/utils.py", line 674, in inner
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return f(self, context, *args, **kwargs)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/db/api.py", line 163, in wrapped
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return method(*args, **kwargs)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/db/api.py", line 93, in wrapped
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     setattr(e, '_RETRY_EXCEEDED', True)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     self.force_reraise()
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     six.reraise(self.type_, self.value, self.tb)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/db/api.py", line 89, in wrapped
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return f(*args, **kwargs)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 150, in wrapper
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     ectxt.value = e.inner_exc
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     self.force_reraise()
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     six.reraise(self.type_, self.value, self.tb)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 138, in wrapper
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return f(*args, **kwargs)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/db/api.py", line 128, in wrapped
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     LOG.debug("Retry wrapper got retriable exception: %s", e)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     self.force_reraise()
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     six.reraise(self.type_, self.value, self.tb)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/db/api.py", line 124, in wrapped
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     return f(*dup_args, **dup_kwargs)
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 530, in create_network
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation     raise Exception
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation Exception
2018-09-13 12:37:00.640 31874 ERROR neutron.pecan_wsgi.hooks.translation 
2018-09-13 12:37:00.646 31874 DEBUG neutron.pecan_wsgi.hooks.notifier [req-bdef0a10-60d1-4ef9-acc4-581a51abd336 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] No notification will be sent due to unsuccessful status code: 500 after /usr/lib/python2.7/site-packages/neutron/pecan_wsgi/hooks/notifier.py:79
2018-09-13 12:37:00.686 31874 INFO neutron.wsgi [req-bdef0a10-60d1-4ef9-acc4-581a51abd336 c3015c3992fd4b3a9ca367e1361a0c2d 730cc4d401834213a241b41611184c96 - 1a883fa29467444d82544fefbe407bde 1a883fa29467444d82544fefbe407bde] 10.0.20.22 "POST /v2.0/networks HTTP/1.1" status: 500  len: 368 time: 0.5712352
