2018-09-28 17:10:56.624 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:10:56.627 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:10:56.666 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:10:56.668 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:10:56.670 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:10:58.113 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.444s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:10:58.117 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:10:59.447 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.330s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:10:59.451 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:11:00.840 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.390s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:11:00.846 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:11:02.119 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.274s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:11:56.626 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:11:56.629 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:11:56.666 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:11:56.668 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:11:56.669 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:11:58.191 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.522s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:11:58.194 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:11:59.339 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.145s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:11:59.342 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:12:00.480 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.139s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:12:00.483 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:12:01.830 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.347s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:12:56.623 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:12:56.625 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:12:56.671 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:12:56.672 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:12:56.673 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:12:57.599 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 0.926s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:12:57.602 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:12:58.634 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.033s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:12:58.636 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:12:59.558 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 0.922s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:12:59.561 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:13:00.536 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 0.975s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:13:56.620 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:13:56.623 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:13:56.665 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:13:56.666 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:13:56.669 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:13:58.319 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.650s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:13:58.322 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:13:59.478 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.157s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:13:59.481 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:14:00.402 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 0.922s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:14:00.404 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:14:01.300 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 0.896s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:14:56.623 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:14:56.628 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:14:56.676 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:14:56.677 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:14:56.678 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:14:57.929 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.252s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:14:57.932 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:14:59.263 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.331s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:14:59.267 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:00.385 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.118s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:00.391 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:01.823 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.433s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:40.723 7258 DEBUG cinder.volume.flows.manager.create_volume [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Volume reschedule parameters: True retry: {u'num_attempts': 1, u'backends': [u'localhost.localdomain@lvm#lvm'], u'hosts': [u'localhost.localdomain@lvm#lvm']} get_flow /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:1126
2018-09-28 17:15:40.789 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Flow 'volume_create_manager' (90baaf11-760c-4238-a972-5a0f4115e888) transitioned into state 'RUNNING' from state 'PENDING' _flow_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:145
2018-09-28 17:15:40.795 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeRefTask;volume:create' (4953bc3f-3fa7-49f6-8d9c-867307ae7bec) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-28 17:15:40.829 7258 DEBUG oslo_db.sqlalchemy.engines [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 17:15:40.893 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeRefTask;volume:create' (4953bc3f-3fa7-49f6-8d9c-867307ae7bec) transitioned into state 'SUCCESS' from state 'RUNNING' with result 'Volume(_name_id=None,admin_metadata={},attach_status='detached',availability_zone='nova',bootable=False,cluster=<?>,cluster_name=None,consistencygroup=<?>,consistencygroup_id=None,created_at=2018-09-28T21:15:39Z,deleted=False,deleted_at=None,display_description=None,display_name='tempest-VOLUME_SAMPLE-1538169015',ec2_id=None,encryption_key_id=None,glance_metadata=<?>,group=<?>,group_id=None,host='localhost.localdomain@lvm#lvm',id=3e3eccff-306e-4d4a-853f-7e2e09db949c,launched_at=None,metadata={},migration_status=None,multiattach=False,previous_status=None,project_id='ddc73f58665f48e48715bb23db4b3024',provider_auth=None,provider_geometry=None,provider_id=None,provider_location=None,replication_driver_data=None,replication_extended_status=None,replication_status=None,scheduled_at=2018-09-28T21:15:40Z,size=1,snapshot_id=None,snapshots=<?>,source_volid=None,status='creating',terminated_at=None,updated_at=2018-09-28T21:15:40Z,user_id='78a7c9c48316457dadb02fd8e7fc5436',volume_attachment=<?>,volume_type=VolumeType(d9c60c05-9188-4fa8-885a-e4f8424aa313),volume_type_id=d9c60c05-9188-4fa8-885a-e4f8424aa313)' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-28 17:15:40.901 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.OnFailureRescheduleTask;volume:create' (97738c26-14f5-4f3c-8d13-378f1b3f144d) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-28 17:15:40.906 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.OnFailureRescheduleTask;volume:create' (97738c26-14f5-4f3c-8d13-378f1b3f144d) transitioned into state 'SUCCESS' from state 'RUNNING' with result 'None' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-28 17:15:40.911 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeSpecTask;volume:create' (04895667-40f5-4e53-9af3-1e1e4d24181f) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-28 17:15:40.931 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}966676c1b1fc77d7ebdd94b95109e2270dce392c' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2' http://10.0.20.25:9292/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2 log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-28 17:15:40.971 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] GET call to image for http://10.0.20.25:9292/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2 used request id req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-28 17:15:40.973 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 
HTTP/1.1 200 OK
Content-Length: 616
Content-Type: application/json
X-Openstack-Request-Id: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2
Date: Fri, 28 Sep 2018 21:15:40 GMT
Connection: keep-alive

{"status": "active", "name": "tempest-cirros-0.4.0-x86_64-1538169015", "tags": [], "container_format": "bare", "created_at": "2018-09-28T21:11:05Z", "size": 12716032, "disk_format": "qcow2", "updated_at": "2018-09-28T21:11:05Z", "visibility": "public", "self": "/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2", "min_disk": 0, "protected": false, "id": "168c83fb-4d41-4a13-94a1-f50223dc17e2", "file": "/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2/file", "checksum": "443b7623e27ecf03dc9e01ee93f67afe", "owner": "bd8a53962fd64ffeab7f2932b0e688c5", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-28 17:15:40.974 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}966676c1b1fc77d7ebdd94b95109e2270dce392c' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2' http://10.0.20.25:9292/v2/schemas/image log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-28 17:15:40.989 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] GET call to image for http://10.0.20.25:9292/v2/schemas/image used request id req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-28 17:15:40.992 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2
Date: Fri, 28 Sep 2018 21:15:40 GMT
Connection: keep-alive

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-28 17:15:40.999 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}966676c1b1fc77d7ebdd94b95109e2270dce392c' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2' http://10.0.20.25:9292/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2 log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-28 17:15:41.025 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] GET call to image for http://10.0.20.25:9292/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2 used request id req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-28 17:15:41.026 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 
HTTP/1.1 200 OK
Content-Length: 616
Content-Type: application/json
X-Openstack-Request-Id: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2
Date: Fri, 28 Sep 2018 21:15:41 GMT
Connection: keep-alive

{"status": "active", "name": "tempest-cirros-0.4.0-x86_64-1538169015", "tags": [], "container_format": "bare", "created_at": "2018-09-28T21:11:05Z", "size": 12716032, "disk_format": "qcow2", "updated_at": "2018-09-28T21:11:05Z", "visibility": "public", "self": "/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2", "min_disk": 0, "protected": false, "id": "168c83fb-4d41-4a13-94a1-f50223dc17e2", "file": "/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2/file", "checksum": "443b7623e27ecf03dc9e01ee93f67afe", "owner": "bd8a53962fd64ffeab7f2932b0e688c5", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-28 17:15:41.027 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}966676c1b1fc77d7ebdd94b95109e2270dce392c' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2' http://10.0.20.25:9292/v2/schemas/image log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-28 17:15:41.039 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] GET call to image for http://10.0.20.25:9292/v2/schemas/image used request id req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-28 17:15:41.041 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2
Date: Fri, 28 Sep 2018 21:15:41 GMT
Connection: keep-alive

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-28 17:15:41.044 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}966676c1b1fc77d7ebdd94b95109e2270dce392c' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2' http://10.0.20.25:9292/v2/schemas/image log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-28 17:15:41.066 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] GET call to image for http://10.0.20.25:9292/v2/schemas/image used request id req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-28 17:15:41.069 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2
Date: Fri, 28 Sep 2018 21:15:41 GMT
Connection: keep-alive

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-28 17:15:41.074 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.ExtractVolumeSpecTask;volume:create' (04895667-40f5-4e53-9af3-1e1e4d24181f) transitioned into state 'SUCCESS' from state 'RUNNING' with result '{'status': u'creating', 'image_location': (None, None), 'image_id': u'168c83fb-4d41-4a13-94a1-f50223dc17e2', 'volume_id': u'3e3eccff-306e-4d4a-853f-7e2e09db949c', 'volume_size': 1, 'image_service': <cinder.image.glance.GlanceImageService object at 0x7f4e79710350>, 'image_meta': {u'status': u'active', u'name': u'tempest-cirros-0.4.0-x86_64-1538169015', u'tags': [], u'container_format': u'bare', u'created_at': datetime.datetime(2018, 9, 28, 21, 11, 5, tzinfo=<iso8601.Utc>), u'disk_format': u'qcow2', u'updated_at': datetime.datetime(2018, 9, 28, 21, 11, 5, tzinfo=<iso8601.Utc>), u'visibility': u'public', 'properties': {}, u'owner': u'bd8a53962fd64ffeab7f2932b0e688c5', u'protected': False, u'id': u'168c83fb-4d41-4a13-94a1-f50223dc17e2', u'file': u'/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2/file', u'checksum': u'443b7623e27ecf03dc9e01ee93f67afe', u'min_disk': 0, u'virtual_size': None, u'min_ram': 0, u'size': 12716032}, 'volume_name': u'volume-3e3eccff-306e-4d4a-853f-7e2e09db949c', 'type': 'image'}' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-28 17:15:41.079 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.NotifyVolumeActionTask;volume:create, create.start' (08477d7a-dce8-4bb0-9850-3c2f567acf12) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-28 17:15:41.202 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.NotifyVolumeActionTask;volume:create, create.start' (08477d7a-dce8-4bb0-9850-3c2f567acf12) transitioned into state 'SUCCESS' from state 'RUNNING' with result 'None' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-28 17:15:41.209 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (a32f61fd-5a8a-4d1c-bcab-d0e21acdc0f9) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-28 17:15:41.210 7258 INFO cinder.volume.flows.manager.create_volume [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Volume 3e3eccff-306e-4d4a-853f-7e2e09db949c: being created as image with specification: {'status': u'creating', 'image_location': (None, None), 'volume_size': 1, 'volume_name': u'volume-3e3eccff-306e-4d4a-853f-7e2e09db949c', 'image_id': u'168c83fb-4d41-4a13-94a1-f50223dc17e2', 'image_service': <cinder.image.glance.GlanceImageService object at 0x7f4e79710350>, 'image_meta': {u'status': u'active', u'name': u'tempest-cirros-0.4.0-x86_64-1538169015', u'tags': [], u'container_format': u'bare', u'created_at': datetime.datetime(2018, 9, 28, 21, 11, 5, tzinfo=<iso8601.Utc>), u'disk_format': u'qcow2', u'updated_at': datetime.datetime(2018, 9, 28, 21, 11, 5, tzinfo=<iso8601.Utc>), u'visibility': u'public', 'properties': {}, u'owner': u'bd8a53962fd64ffeab7f2932b0e688c5', u'protected': False, u'id': u'168c83fb-4d41-4a13-94a1-f50223dc17e2', u'file': u'/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2/file', u'checksum': u'443b7623e27ecf03dc9e01ee93f67afe', u'min_disk': 0, u'virtual_size': None, u'min_ram': 0, u'size': 12716032}}
2018-09-28 17:15:41.211 7258 DEBUG cinder.volume.flows.manager.create_volume [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Cloning 3e3eccff-306e-4d4a-853f-7e2e09db949c from image 168c83fb-4d41-4a13-94a1-f50223dc17e2  at location (None, None). _create_from_image /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:896
2018-09-28 17:15:41.215 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}966676c1b1fc77d7ebdd94b95109e2270dce392c' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2' http://10.0.20.25:9292/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2/file log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-28 17:15:41.860 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] GET call to image for http://10.0.20.25:9292/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2/file used request id req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-28 17:15:41.862 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Content-Md5: 443b7623e27ecf03dc9e01ee93f67afe
Content-Length: 12716032
X-Openstack-Request-Id: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2
Date: Fri, 28 Sep 2018 21:15:41 GMT
Connection: keep-alive
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-28 17:15:42.553 7258 DEBUG cinder.image.image_utils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Image fetch details: dest /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm, size 12.00 MB, duration 1.34 sec fetch /usr/lib/python2.7/site-packages/cinder/image/image_utils.py:247
2018-09-28 17:15:42.568 7258 INFO cinder.image.image_utils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Image download 12.00 MB at 8.96 MB/s
2018-09-28 17:15:42.572 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}966676c1b1fc77d7ebdd94b95109e2270dce392c' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2' http://10.0.20.25:9292/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2 log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-28 17:15:42.630 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] GET call to image for http://10.0.20.25:9292/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2 used request id req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-28 17:15:42.632 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 
HTTP/1.1 200 OK
Content-Length: 616
Content-Type: application/json
X-Openstack-Request-Id: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2
Date: Fri, 28 Sep 2018 21:15:42 GMT
Connection: keep-alive

{"status": "active", "name": "tempest-cirros-0.4.0-x86_64-1538169015", "tags": [], "container_format": "bare", "created_at": "2018-09-28T21:11:05Z", "size": 12716032, "disk_format": "qcow2", "updated_at": "2018-09-28T21:11:05Z", "visibility": "public", "self": "/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2", "min_disk": 0, "protected": false, "id": "168c83fb-4d41-4a13-94a1-f50223dc17e2", "file": "/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2/file", "checksum": "443b7623e27ecf03dc9e01ee93f67afe", "owner": "bd8a53962fd64ffeab7f2932b0e688c5", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-28 17:15:42.633 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}966676c1b1fc77d7ebdd94b95109e2270dce392c' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2' http://10.0.20.25:9292/v2/schemas/image log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-28 17:15:42.658 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] GET call to image for http://10.0.20.25:9292/v2/schemas/image used request id req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-28 17:15:42.662 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2
Date: Fri, 28 Sep 2018 21:15:42 GMT
Connection: keep-alive

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-28 17:15:42.670 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:43.942 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm" returned: 0 in 1.272s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:43.945 7258 DEBUG cinder.image.image_utils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Temporary image 168c83fb-4d41-4a13-94a1-f50223dc17e2 is fetched for user 78a7c9c48316457dadb02fd8e7fc5436. fetch /usr/lib/python2.7/site-packages/cinder/image/image_utils.py:672
2018-09-28 17:15:43.946 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:44.933 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm" returned: 0 in 0.987s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:44.937 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvcreate -T -V 1g -n volume-3e3eccff-306e-4d4a-853f-7e2e09db949c cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:46.097 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvcreate -T -V 1g -n volume-3e3eccff-306e-4d4a-853f-7e2e09db949c cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.161s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:46.155 7258 DEBUG cinder.volume.flows.manager.create_volume [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Attempting download of 168c83fb-4d41-4a13-94a1-f50223dc17e2 ((None, None)) to volume 3e3eccff-306e-4d4a-853f-7e2e09db949c. _copy_image_to_volume /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:536
2018-09-28 17:15:46.159 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}966676c1b1fc77d7ebdd94b95109e2270dce392c' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2' http://10.0.20.25:9292/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2 log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-28 17:15:47.832 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] GET call to image for http://10.0.20.25:9292/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2 used request id req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-28 17:15:47.837 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 
HTTP/1.1 200 OK
Content-Length: 616
Content-Type: application/json
X-Openstack-Request-Id: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2
Date: Fri, 28 Sep 2018 21:15:47 GMT
Connection: keep-alive

{"status": "active", "name": "tempest-cirros-0.4.0-x86_64-1538169015", "tags": [], "container_format": "bare", "created_at": "2018-09-28T21:11:05Z", "size": 12716032, "disk_format": "qcow2", "updated_at": "2018-09-28T21:11:05Z", "visibility": "public", "self": "/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2", "min_disk": 0, "protected": false, "id": "168c83fb-4d41-4a13-94a1-f50223dc17e2", "file": "/v2/images/168c83fb-4d41-4a13-94a1-f50223dc17e2/file", "checksum": "443b7623e27ecf03dc9e01ee93f67afe", "owner": "bd8a53962fd64ffeab7f2932b0e688c5", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-28 17:15:47.839 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'X-Auth-Token: {SHA1}966676c1b1fc77d7ebdd94b95109e2270dce392c' -H 'Connection: keep-alive' -H 'User-Agent: python-glanceclient' -H 'Content-Type: application/octet-stream' -H 'X-OpenStack-Request-ID: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2' http://10.0.20.25:9292/v2/schemas/image log_curl_request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-09-28 17:15:47.858 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] GET call to image for http://10.0.20.25:9292/v2/schemas/image used request id req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 _request /usr/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-09-28 17:15:47.860 7258 DEBUG glanceclient.common.http [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-84449e2a-54ba-4cb4-bd1c-0a0984790da2
Date: Fri, 28 Sep 2018 21:15:47 GMT
Connection: keep-alive

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /usr/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-09-28 17:15:47.869 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmp2K0dWC execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:49.350 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmp2K0dWC" returned: 0 in 1.482s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:49.355 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:50.635 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm" returned: 0 in 1.280s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:50.638 7258 DEBUG cinder.image.image_utils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] 168c83fb-4d41-4a13-94a1-f50223dc17e2 was qcow2, converting to raw  fetch_to_volume_format /usr/lib/python2.7/site-packages/cinder/image/image_utils.py:417
2018-09-28 17:15:50.641 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf dd count=0 if=/var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm of=/dev/mapper/cinder--volumes2-volume--3e3eccff--306e--4d4a--853f--7e2e09db949c oflag=direct execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:51.775 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf dd count=0 if=/var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm of=/dev/mapper/cinder--volumes2-volume--3e3eccff--306e--4d4a--853f--7e2e09db949c oflag=direct" returned: 0 in 1.135s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:51.780 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf qemu-img convert -t none -f qcow2 -O raw /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm /dev/mapper/cinder--volumes2-volume--3e3eccff--306e--4d4a--853f--7e2e09db949c execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:54.393 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf qemu-img convert -t none -f qcow2 -O raw /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm /dev/mapper/cinder--volumes2-volume--3e3eccff--306e--4d4a--853f--7e2e09db949c" returned: 0 in 2.615s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:54.397 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:55.853 7258 DEBUG oslo_concurrency.processutils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C qemu-img info /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm" returned: 0 in 1.457s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:55.855 7258 DEBUG cinder.image.image_utils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Image conversion details: src /var/lib/cinder/conversion/tmpODBVfZlocalhost.localdomain@lvm, size 44.00 MB, duration 2.62 sec, destination /dev/mapper/cinder--volumes2-volume--3e3eccff--306e--4d4a--853f--7e2e09db949c _convert_image /usr/lib/python2.7/site-packages/cinder/image/image_utils.py:190
2018-09-28 17:15:55.855 7258 INFO cinder.image.image_utils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Converted 44.00 MB image at 16.81 MB/s
2018-09-28 17:15:55.856 7258 DEBUG cinder.volume.flows.manager.create_volume [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Downloaded image 168c83fb-4d41-4a13-94a1-f50223dc17e2 ((None, None)) to volume 3e3eccff-306e-4d4a-853f-7e2e09db949c successfully. _copy_image_to_volume /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:582
2018-09-28 17:15:55.861 7258 DEBUG cinder.image.image_utils [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Temporary image 168c83fb-4d41-4a13-94a1-f50223dc17e2 for user 78a7c9c48316457dadb02fd8e7fc5436 is deleted. fetch /usr/lib/python2.7/site-packages/cinder/image/image_utils.py:676
2018-09-28 17:15:55.863 7258 DEBUG cinder.volume.flows.manager.create_volume [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Marking volume 3e3eccff-306e-4d4a-853f-7e2e09db949c as bootable. _enable_bootable_flag /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:479
2018-09-28 17:15:55.894 7258 DEBUG cinder.volume.flows.manager.create_volume [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Copying metadata from image 168c83fb-4d41-4a13-94a1-f50223dc17e2 to 3e3eccff-306e-4d4a-853f-7e2e09db949c. _handle_bootable_volume_glance_meta /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:437
2018-09-28 17:15:55.895 7258 DEBUG cinder.volume.flows.manager.create_volume [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Creating volume glance metadata for volume 3e3eccff-306e-4d4a-853f-7e2e09db949c backed by image 168c83fb-4d41-4a13-94a1-f50223dc17e2 with: {'container_format': u'bare', 'min_ram': 0, 'disk_format': u'qcow2', 'image_name': u'tempest-cirros-0.4.0-x86_64-1538169015', 'image_id': u'168c83fb-4d41-4a13-94a1-f50223dc17e2', 'checksum': u'443b7623e27ecf03dc9e01ee93f67afe', 'min_disk': 0, 'size': 12716032}. _capture_volume_image_metadata /usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py:616
2018-09-28 17:15:56.019 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (a32f61fd-5a8a-4d1c-bcab-d0e21acdc0f9) transitioned into state 'SUCCESS' from state 'RUNNING' with result 'None' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-28 17:15:56.023 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeOnFinishTask;volume:create, create.end' (e52ff7a2-c9d2-4029-bd2b-7a0c9edd8959) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:194
2018-09-28 17:15:56.083 7258 INFO cinder.volume.flows.manager.create_volume [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Volume volume-3e3eccff-306e-4d4a-853f-7e2e09db949c (3e3eccff-306e-4d4a-853f-7e2e09db949c): created successfully
2018-09-28 17:15:56.086 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeOnFinishTask;volume:create, create.end' (e52ff7a2-c9d2-4029-bd2b-7a0c9edd8959) transitioned into state 'SUCCESS' from state 'RUNNING' with result 'None' _task_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:183
2018-09-28 17:15:56.092 7258 DEBUG cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Flow 'volume_create_manager' (90baaf11-760c-4238-a972-5a0f4115e888) transitioned into state 'SUCCESS' from state 'RUNNING' _flow_receiver /usr/lib/python2.7/site-packages/taskflow/listeners/logging.py:145
2018-09-28 17:15:56.095 7258 INFO cinder.volume.manager [req-84449e2a-54ba-4cb4-bd1c-0a0984790da2 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Created volume successfully.
2018-09-28 17:15:56.628 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:15:56.630 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:15:56.667 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:15:56.668 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:15:56.669 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:57.866 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.197s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:57.870 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:15:59.160 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.290s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:15:59.163 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:16:00.259 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.096s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:16:00.262 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:16:01.437 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.175s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:16:53.467 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K cinder-volumes2/volume-3e3eccff-306e-4d4a-853f-7e2e09db949c execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:16:54.594 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K cinder-volumes2/volume-3e3eccff-306e-4d4a-853f-7e2e09db949c" returned: 0 in 1.128s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:16:54.936 7258 INFO cinder.volume.targets.lio [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Creating iscsi_target for volume: volume-3e3eccff-306e-4d4a-853f-7e2e09db949c
2018-09-28 17:16:54.939 7258 DEBUG oslo_concurrency.lockutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:16:54.941 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool create /dev/cinder-volumes2/volume-3e3eccff-306e-4d4a-853f-7e2e09db949c iqn.2010-10.org.openstack:volume-3e3eccff-306e-4d4a-853f-7e2e09db949c SiK7mxxmV3k3LKN79VA8 89D9bLPbzKYRZe6N False -p3260 -a10.0.20.25 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:16:56.632 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:16:56.634 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:16:56.681 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:16:56.682 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:16:56.684 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:16:56.880 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool create /dev/cinder-volumes2/volume-3e3eccff-306e-4d4a-853f-7e2e09db949c iqn.2010-10.org.openstack:volume-3e3eccff-306e-4d4a-853f-7e2e09db949c SiK7mxxmV3k3LKN79VA8 89D9bLPbzKYRZe6N False -p3260 -a10.0.20.25" returned: 0 in 1.939s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:16:56.882 7258 DEBUG oslo_concurrency.lockutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 1.943s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:16:56.884 7258 DEBUG oslo_concurrency.lockutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:16:56.886 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:16:57.502 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 0.819s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:16:57.505 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:16:58.561 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.057s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:16:58.564 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:16:58.613 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets" returned: 0 in 1.727s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:16:58.618 7258 DEBUG oslo_concurrency.lockutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 1.733s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:16:58.620 7258 DEBUG oslo_concurrency.lockutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:16:58.623 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:16:59.607 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.044s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:16:59.610 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:17:00.623 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save" returned: 0 in 2.001s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:17:00.626 7258 DEBUG oslo_concurrency.lockutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:17:00.628 7258 DEBUG cinder.volume.targets.iscsi [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Set provider_location to: 10.0.20.25:3260,iqn.2010-10.org.openstack:volume-3e3eccff-306e-4d4a-853f-7e2e09db949c iqn.2010-10.org.openstack:volume-3e3eccff-306e-4d4a-853f-7e2e09db949c 0 create_export /usr/lib/python2.7/site-packages/cinder/volume/targets/iscsi.py:215
2018-09-28 17:17:00.697 7258 DEBUG oslo_concurrency.lockutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:17:00.698 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool add-initiator iqn.2010-10.org.openstack:volume-3e3eccff-306e-4d4a-853f-7e2e09db949c SiK7mxxmV3k3LKN79VA8 89D9bLPbzKYRZe6N iqn.1994-05.com.redhat:f393eeb713 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:17:00.777 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.167s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:17:03.057 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool add-initiator iqn.2010-10.org.openstack:volume-3e3eccff-306e-4d4a-853f-7e2e09db949c SiK7mxxmV3k3LKN79VA8 89D9bLPbzKYRZe6N iqn.1994-05.com.redhat:f393eeb713" returned: 0 in 2.359s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:17:03.060 7258 DEBUG oslo_concurrency.lockutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.363s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:17:03.061 7258 DEBUG oslo_concurrency.lockutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:17:03.062 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:17:05.121 7258 DEBUG oslo_concurrency.processutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save" returned: 0 in 2.059s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:17:05.124 7258 DEBUG oslo_concurrency.lockutils [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.063s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:17:05.163 7258 INFO cinder.volume.manager [req-e4681d2d-22d6-4081-ac70-c9e74f566574 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Initialize volume connection completed successfully.
2018-09-28 17:17:07.427 7258 DEBUG cinder.coordination [req-9c897a89-8310-40e3-9db5-4437bd5d30ef 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "/var/lib/cinder/cinder-3e3eccff-306e-4d4a-853f-7e2e09db949c" acquired by "attach_volume" :: waited 0.001s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:175
2018-09-28 17:17:07.614 7258 INFO cinder.volume.manager [req-9c897a89-8310-40e3-9db5-4437bd5d30ef 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Attaching volume 3e3eccff-306e-4d4a-853f-7e2e09db949c to instance 6bfc0850-ab4b-47a5-a60d-b492c80b4db4 at mountpoint /dev/vdb on host None.
2018-09-28 17:17:07.825 7258 INFO cinder.volume.manager [req-9c897a89-8310-40e3-9db5-4437bd5d30ef 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Attach volume completed successfully.
2018-09-28 17:17:07.826 7258 DEBUG cinder.coordination [req-9c897a89-8310-40e3-9db5-4437bd5d30ef 78a7c9c48316457dadb02fd8e7fc5436 ddc73f58665f48e48715bb23db4b3024 - 0c719d86fb264aeba71a483e10ade6b2 0c719d86fb264aeba71a483e10ade6b2] Lock "/var/lib/cinder/cinder-3e3eccff-306e-4d4a-853f-7e2e09db949c" released by "attach_volume" :: held 0.399s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:187
2018-09-28 17:17:56.632 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:17:56.634 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:17:56.666 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:17:56.668 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:17:56.669 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:17:57.744 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.075s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:17:57.746 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:17:58.772 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.026s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:17:58.774 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:17:59.658 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 0.884s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:17:59.662 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:18:00.654 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 0.993s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:18:56.629 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:18:56.631 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:18:56.681 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:18:56.682 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:18:56.684 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:18:57.837 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.153s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:18:57.839 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:18:59.009 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.170s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:18:59.012 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:00.259 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.247s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:00.262 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:01.323 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.061s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:14.149 7258 DEBUG oslo_concurrency.lockutils [req-60395392-493d-4289-af26-3f2d79616f89 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:19:14.152 7258 DEBUG oslo_concurrency.processutils [req-60395392-493d-4289-af26-3f2d79616f89 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool delete-initiator iqn.2010-10.org.openstack:volume-3e3eccff-306e-4d4a-853f-7e2e09db949c iqn.1994-05.com.redhat:f393eeb713 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:16.176 7258 DEBUG oslo_concurrency.processutils [req-60395392-493d-4289-af26-3f2d79616f89 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool delete-initiator iqn.2010-10.org.openstack:volume-3e3eccff-306e-4d4a-853f-7e2e09db949c iqn.1994-05.com.redhat:f393eeb713" returned: 0 in 2.025s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:16.179 7258 DEBUG oslo_concurrency.lockutils [req-60395392-493d-4289-af26-3f2d79616f89 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.030s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:19:16.181 7258 DEBUG oslo_concurrency.lockutils [req-60395392-493d-4289-af26-3f2d79616f89 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:19:16.183 7258 DEBUG oslo_concurrency.processutils [req-60395392-493d-4289-af26-3f2d79616f89 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:18.025 7258 DEBUG oslo_concurrency.processutils [req-60395392-493d-4289-af26-3f2d79616f89 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save" returned: 0 in 1.842s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:18.027 7258 DEBUG oslo_concurrency.lockutils [req-60395392-493d-4289-af26-3f2d79616f89 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 1.846s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:19:18.028 7258 INFO cinder.volume.manager [req-60395392-493d-4289-af26-3f2d79616f89 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Terminate volume connection completed successfully.
2018-09-28 17:19:18.427 7258 DEBUG cinder.coordination [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "/var/lib/cinder/cinder-3e3eccff-306e-4d4a-853f-7e2e09db949c-detach_volume" acquired by "detach_volume" :: waited 0.001s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:175
2018-09-28 17:19:18.524 7258 INFO cinder.volume.manager [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Detaching volume 3e3eccff-306e-4d4a-853f-7e2e09db949c from instance 6bfc0850-ab4b-47a5-a60d-b492c80b4db4.
2018-09-28 17:19:18.528 7258 DEBUG oslo_concurrency.lockutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:19:18.530 7258 DEBUG oslo_concurrency.processutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:21.101 7258 DEBUG oslo_concurrency.processutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets" returned: 0 in 2.572s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:21.103 7258 DEBUG oslo_concurrency.lockutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.575s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:19:21.105 7258 INFO cinder.volume.targets.lio [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Removing iscsi_target: 3e3eccff-306e-4d4a-853f-7e2e09db949c
2018-09-28 17:19:21.107 7258 DEBUG oslo_concurrency.lockutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:19:21.109 7258 DEBUG oslo_concurrency.processutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool delete iqn.2010-10.org.openstack:volume-3e3eccff-306e-4d4a-853f-7e2e09db949c execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:22.936 7258 DEBUG oslo_concurrency.processutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool delete iqn.2010-10.org.openstack:volume-3e3eccff-306e-4d4a-853f-7e2e09db949c" returned: 0 in 1.827s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:22.938 7258 DEBUG oslo_concurrency.lockutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 1.831s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:19:22.940 7258 DEBUG oslo_concurrency.lockutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:19:22.942 7258 DEBUG oslo_concurrency.processutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:25.294 7258 DEBUG oslo_concurrency.processutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool save" returned: 0 in 2.352s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:25.299 7258 DEBUG oslo_concurrency.lockutils [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.359s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:19:25.588 7258 INFO cinder.volume.manager [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Detach volume completed successfully.
2018-09-28 17:19:25.589 7258 DEBUG cinder.coordination [req-c2a62bfd-dbdb-4c48-9e4f-e24e675753c1 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "/var/lib/cinder/cinder-3e3eccff-306e-4d4a-853f-7e2e09db949c-detach_volume" released by "detach_volume" :: held 7.162s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:187
2018-09-28 17:19:36.957 7258 DEBUG cinder.coordination [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "/var/lib/cinder/cinder-3e3eccff-306e-4d4a-853f-7e2e09db949c-delete_volume" acquired by "delete_volume" :: waited 0.001s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:175
2018-09-28 17:19:37.157 7258 DEBUG oslo_concurrency.lockutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" acquired by "cinder.volume.targets.lio._execute" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 17:19:37.159 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:39.773 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf cinder-rtstool get-targets" returned: 0 in 2.614s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:39.777 7258 DEBUG oslo_concurrency.lockutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "lioadm" released by "cinder.volume.targets.lio._execute" :: held 2.620s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 17:19:39.778 7258 INFO cinder.volume.targets.iscsi [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Skipping remove_export. No iscsi_target is presently exported for volume: 3e3eccff-306e-4d4a-853f-7e2e09db949c
2018-09-28 17:19:39.781 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2/volume-3e3eccff-306e-4d4a-853f-7e2e09db949c execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:40.970 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2/volume-3e3eccff-306e-4d4a-853f-7e2e09db949c" returned: 0 in 1.190s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:40.976 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvdisplay --noheading -C -o Attr cinder-volumes2/volume-3e3eccff-306e-4d4a-853f-7e2e09db949c execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:42.105 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvdisplay --noheading -C -o Attr cinder-volumes2/volume-3e3eccff-306e-4d4a-853f-7e2e09db949c" returned: 0 in 1.129s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:42.112 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvremove --config activation { retry_deactivation = 1}  -f cinder-volumes2/volume-3e3eccff-306e-4d4a-853f-7e2e09db949c execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:43.323 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvremove --config activation { retry_deactivation = 1}  -f cinder-volumes2/volume-3e3eccff-306e-4d4a-853f-7e2e09db949c" returned: 0 in 1.211s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:43.326 7258 INFO cinder.volume.drivers.lvm [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Successfully deleted volume: 3e3eccff-306e-4d4a-853f-7e2e09db949c
2018-09-28 17:19:43.392 7258 WARNING cinder.quota [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Deprecated: Default quota for resource: gigabytes_iscsi is set by the default quota flag: quota_gigabytes_iscsi, it is now deprecated. Please use the default quota class for default quota.
2018-09-28 17:19:43.394 7258 WARNING cinder.quota [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Deprecated: Default quota for resource: volumes_iscsi is set by the default quota flag: quota_volumes_iscsi, it is now deprecated. Please use the default quota class for default quota.
2018-09-28 17:19:43.450 7258 DEBUG cinder.quota [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Created reservations ['64dc7a74-b473-4b99-93eb-0f87b20fcb79', '36745499-1b41-43c1-b776-0c22d6e52c9d', '48d978af-06b2-49dc-9aa8-555f06b550f3', 'bb1b5873-0b77-4b6c-a6c7-df8c8d864d2c'] reserve /usr/lib/python2.7/site-packages/cinder/quota.py:1029
2018-09-28 17:19:43.563 7258 DEBUG cinder.volume.utils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Can not find volume 3e3eccff-306e-4d4a-853f-7e2e09db949c at notify usage _usage_from_volume /usr/lib/python2.7/site-packages/cinder/volume/utils.py:99
2018-09-28 17:19:43.640 7258 DEBUG cinder.volume.drivers.lvm [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:19:43.642 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:44.687 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.045s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:44.690 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:45.913 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.224s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:45.918 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:47.083 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.166s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:47.086 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:48.289 7258 DEBUG oslo_concurrency.processutils [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.203s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:48.294 7258 DEBUG cinder.manager [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:19:48.497 7258 INFO cinder.volume.manager [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Deleted volume successfully.
2018-09-28 17:19:48.511 7258 DEBUG cinder.coordination [req-575aaeb8-b01f-42b0-b09b-e98f2472be67 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] Lock "/var/lib/cinder/cinder-3e3eccff-306e-4d4a-853f-7e2e09db949c-delete_volume" released by "delete_volume" :: held 11.554s _synchronized /usr/lib/python2.7/site-packages/cinder/coordination.py:187
2018-09-28 17:19:56.626 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:19:56.628 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:19:56.660 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:19:56.662 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:19:56.663 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:58.066 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.403s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:58.070 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:19:59.356 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.287s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:19:59.360 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:20:00.715 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.356s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:20:00.718 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:20:02.171 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.453s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:20:56.625 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._publish_service_capabilities run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:20:56.628 7258 DEBUG cinder.manager [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Notifying Schedulers of capabilities ... _publish_service_capabilities /usr/lib/python2.7/site-packages/cinder/manager.py:189
2018-09-28 17:20:56.668 7258 DEBUG oslo_service.periodic_task [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running periodic task VolumeManager._report_driver_status run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-09-28 17:20:56.668 7258 DEBUG cinder.volume.drivers.lvm [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Updating volume stats _update_volume_stats /usr/lib/python2.7/site-packages/cinder/volume/drivers/lvm.py:205
2018-09-28 17:20:56.671 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:20:57.989 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix cinder-volumes2" returned: 0 in 1.319s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:20:57.994 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:20:59.312 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.318s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:20:59.316 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:21:00.544 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/cinder-volumes2/cinder-volumes2-pool" returned: 0 in 1.229s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-09-28 17:21:00.548 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-09-28 17:21:01.746 7258 DEBUG oslo_concurrency.processutils [req-6c898e5d-1c74-42cb-acad-ec342dfc3d58 - - - - -] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix cinder-volumes2" returned: 0 in 1.199s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
