2018-09-28 16:35:05.808 21849 DEBUG oslo_db.sqlalchemy.engines [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 16:35:09.488 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "b4cf805b-f6f1-4a21-9579-857adb7abc84" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 16:35:09.494 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "b4cf805b-f6f1-4a21-9579-857adb7abc84" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 16:35:09.526 21849 DEBUG oslo_db.sqlalchemy.engines [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 16:35:09.858 21849 DEBUG nova.context [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),b4cf805b-f6f1-4a21-9579-857adb7abc84(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-09-28 16:35:09.860 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 16:35:09.861 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 16:35:09.864 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "b4cf805b-f6f1-4a21-9579-857adb7abc84" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 16:35:09.864 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "b4cf805b-f6f1-4a21-9579-857adb7abc84" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 16:35:09.899 21849 DEBUG oslo_db.sqlalchemy.engines [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-28 16:35:09.937 21849 DEBUG nova.quota [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Getting quotas for project 6fb7fed9903f4367bea67981d0c3a9c0. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-28 16:35:09.947 21849 DEBUG nova.quota [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Getting quotas for user fa392e292d9542d2b93923e429daa51b and project 6fb7fed9903f4367bea67981d0c3a9c0. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-28 16:35:09.975 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "b4cf805b-f6f1-4a21-9579-857adb7abc84" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 16:35:09.977 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "b4cf805b-f6f1-4a21-9579-857adb7abc84" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 16:35:09.978 21849 WARNING nova.image.glance [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] No protocol specified in for api_server 'http://10.0.20.27:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 16:35:10.001 21849 DEBUG nova.notifications.objects.base [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 16:35:10.005 21849 DEBUG nova.objects.instance [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lazy-loading 'tags' on Instance uuid db97e639-05f6-4f7d-ba2a-ad7d375732c6 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-28 16:35:10.072 21849 DEBUG nova.conductor.manager [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] [instance: db97e639-05f6-4f7d-ba2a-ad7d375732c6] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='9e1a480a-8423-467f-bb28-ca575abb573e',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _create_block_device_mapping /usr/lib/python2.7/site-packages/nova/conductor/manager.py:968
2018-09-28 16:35:10.078 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "b4cf805b-f6f1-4a21-9579-857adb7abc84" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 16:35:10.080 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "b4cf805b-f6f1-4a21-9579-857adb7abc84" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 16:35:10.220 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "b4cf805b-f6f1-4a21-9579-857adb7abc84" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-28 16:35:10.221 21849 DEBUG oslo_concurrency.lockutils [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Lock "b4cf805b-f6f1-4a21-9579-857adb7abc84" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-28 16:35:10.597 21861 WARNING nova.image.glance [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] No protocol specified in for api_server 'http://10.0.20.27:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 16:35:10.624 21861 DEBUG nova.notifications.objects.base [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 16:35:11.057 21864 WARNING nova.image.glance [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] No protocol specified in for api_server 'http://10.0.20.27:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 16:35:11.140 21864 DEBUG nova.notifications.objects.base [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 16:35:11.699 21859 WARNING nova.image.glance [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] No protocol specified in for api_server 'http://10.0.20.27:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 16:35:11.778 21859 DEBUG nova.notifications.objects.base [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 16:35:12.150 21860 WARNING nova.image.glance [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] No protocol specified in for api_server 'http://10.0.20.27:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 16:35:12.218 21860 DEBUG nova.notifications.objects.base [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 16:35:12.572 21863 WARNING nova.image.glance [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] No protocol specified in for api_server 'http://10.0.20.27:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 16:35:12.652 21863 DEBUG nova.notifications.objects.base [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-28 16:35:26.819 21860 WARNING nova.image.glance [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] No protocol specified in for api_server 'http://10.0.20.27:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-28 16:35:26.844 21860 DEBUG nova.notifications.objects.base [req-d1e0fd82-4d23-4688-8003-be0c05ff8fce fa392e292d9542d2b93923e429daa51b 6fb7fed9903f4367bea67981d0c3a9c0 - d7980c8785cd47e2bb58b44220bb5eac d7980c8785cd47e2bb58b44220bb5eac] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
