2018-06-26 13:45:23.759 3189 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-26 13:45:23.761 3189 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-26 13:46:23.759 3189 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-26 13:46:23.764 3189 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-26 13:47:23.759 3189 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-26 13:47:23.761 3189 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-26 13:47:50.118 3189 DEBUG oslo_concurrency.lockutils [req-3986cc55-acb5-4e19-9f43-824af2c602cb 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Acquired semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:47:51.155 3189 DEBUG neutron.agent.dhcp.agent [req-0d51eb87-d3a9-4991-90ac-bc4f3c56e22d - - - - -] Calling driver for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc action: enable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-26 13:47:51.157 3189 DEBUG neutron.agent.linux.utils [req-0d51eb87-d3a9-4991-90ac-bc4f3c56e22d - - - - -] Unable to access /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:47:51.159 3189 DEBUG neutron.agent.linux.dhcp [req-0d51eb87-d3a9-4991-90ac-bc4f3c56e22d - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc on network fa8b09ff-2ceb-47c6-940b-b3c51ea6addc does not yet exist. Checking for a reserved port. _setup_reserved_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1267
2018-06-26 13:47:51.159 3189 DEBUG neutron.agent.linux.dhcp [req-0d51eb87-d3a9-4991-90ac-bc4f3c56e22d - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc on network fa8b09ff-2ceb-47c6-940b-b3c51ea6addc does not yet exist. Creating new one. _setup_new_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1288
2018-06-26 13:47:53.892 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:53.912 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'add', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:53.926 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'sysctl', '-w', 'net.ipv4.conf.all.promote_secondaries=1'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:53.952 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', 'link', 'set', 'lo', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:53.967 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'sysctl', '-w', 'net.ipv6.conf.default.accept_ra=0'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:53.983 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', 'link', 'set', 'tap29b08087-71', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.011 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-o', 'link', 'show', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.028 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-06-26 13:47:54.254 3189 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=None, port=tap29b08087-71) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-06-26 13:47:54.255 3189 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Transaction caused no change do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:114
2018-06-26 13:47:54.256 3189 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): AddPortCommand(bridge=br-int, may_exist=False, port=tap29b08087-71) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-06-26 13:47:54.257 3189 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=1): DbSetCommand(table=Interface, col_values=(('type', 'internal'), ('external_ids', {'iface-id': u'29b08087-71d5-4afd-b556-75b356f418f2', 'iface-status': 'active', 'attached-mac': u'fa:16:3e:41:fc:38'})), record=tap29b08087-71) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-06-26 13:47:54.286 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tap29b08087-71', 'address', 'fa:16:3e:41:fc:38'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.297 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.310 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tap29b08087-71', 'netns', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.330 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', 'link', 'set', 'tap29b08087-71', 'mtu', '1450'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.342 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', 'link', 'set', 'tap29b08087-71', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.357 3189 DEBUG oslo_concurrency.lockutils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Acquired semaphore "iptables-qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:47:54.359 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'iptables-save'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.378 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'iptables-restore', '-n'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.394 3189 DEBUG neutron.agent.linux.iptables_manager [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] IPTablesManager.apply completed with success. 56 iptables commands were issued _apply_synchronized /usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py:601
2018-06-26 13:47:54.395 3189 DEBUG oslo_concurrency.lockutils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Releasing semaphore "iptables-qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:47:54.397 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-o', 'link', 'show', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.410 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', 'addr', 'show', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.432 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-4', 'addr', 'add', '11.237.1.2/24', 'scope', 'global', 'dev', 'tap29b08087-71', 'brd', '11.237.1.255'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.446 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-4', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.455 3189 DEBUG neutron.agent.linux.dhcp [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Setting IPv4 gateway for dhcp netns on net fa8b09ff-2ceb-47c6-940b-b3c51ea6addc to 11.237.1.1 _set_default_route_ip_version /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1164
2018-06-26 13:47:54.457 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-4', 'route', 'replace', 'default', 'via', '11.237.1.1', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.468 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-6', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.479 3189 DEBUG neutron.agent.linux.dhcp [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Cleaning stale devices for network fa8b09ff-2ceb-47c6-940b-b3c51ea6addc _cleanup_stale_devices /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1369
2018-06-26 13:47:54.480 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.490 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'find', '/sys/class/net', '-maxdepth', '1', '-type', 'l', '-printf', '%f '] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.505 3189 DEBUG neutron.agent.linux.dhcp [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Building initial lease file: /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/leases _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:623
2018-06-26 13:47:54.507 3189 DEBUG neutron.agent.linux.dhcp [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Done building initial lease file /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/leases with contents:
1530100074 fa:16:3e:41:fc:38 11.237.1.2 * *
 _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:651
2018-06-26 13:47:54.508 3189 DEBUG neutron.agent.linux.dhcp [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Building host file: /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-26 13:47:54.509 3189 DEBUG neutron.agent.linux.dhcp [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Done building host file /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-26 13:47:54.512 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Unable to access /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:47:54.513 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'dnsmasq', '--no-hosts', '--no-resolv', '--strict-order', '--except-interface=lo', '--pid-file=/var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/pid', '--dhcp-hostsfile=/var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host', '--addn-hosts=/var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/addn_hosts', '--dhcp-optsfile=/var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/opts', '--dhcp-leasefile=/var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/leases', '--dhcp-match=set:ipxe,175', '--bind-interfaces', '--interface=tap29b08087-71', '--dhcp-range=set:tag0,11.237.1.0,static,255.255.255.0,86400s', '--dhcp-option-force=option:mtu,1450', '--dhcp-lease-max=256', '--conf-file=', '--domain=openstacklocal'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:54.541 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:47:54.543 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:47:54.544 3189 DEBUG neutron.agent.linux.external_process [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] No process started for fa8b09ff-2ceb-47c6-940b-b3c51ea6addc disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-26 13:47:54.545 3189 DEBUG oslo_concurrency.lockutils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Releasing semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:47:54.561 3189 DEBUG oslo_concurrency.lockutils [req-3986cc55-acb5-4e19-9f43-824af2c602cb 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Acquired semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:47:55.449 3189 DEBUG neutron.agent.dhcp.agent [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] Calling driver for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-26 13:47:55.451 3189 DEBUG neutron.agent.linux.dhcp [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] Building host file: /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-26 13:47:55.455 3189 DEBUG neutron.agent.linux.dhcp [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] Done building host file /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-26 13:47:55.459 3189 DEBUG neutron.agent.linux.utils [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '7540'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:55.487 3189 DEBUG neutron.agent.linux.dhcp [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] Reloading allocations for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-26 13:47:55.489 3189 DEBUG neutron.agent.linux.utils [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-4', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:55.513 3189 DEBUG neutron.agent.linux.utils [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-6', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:55.588 3189 DEBUG neutron.agent.linux.utils [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:47:55.590 3189 DEBUG neutron.agent.linux.utils [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:47:55.592 3189 DEBUG neutron.agent.linux.external_process [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] No process started for fa8b09ff-2ceb-47c6-940b-b3c51ea6addc disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-26 13:47:55.596 3189 DEBUG oslo_concurrency.lockutils [req-857f1e68-72ee-4b38-adfa-b9dc60cc676b - - - - -] Releasing semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:47:55.597 3189 DEBUG oslo_concurrency.lockutils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Acquired semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:47:55.599 3189 DEBUG neutron.agent.dhcp.agent [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Discarding stale port update: admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-06-26T11:47:51Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'ff889f61-c119-4ed8-b0b2-a93e5a53e158', u'ip_address': u'11.237.1.2'}], id=29b08087-71d5-4afd-b556-75b356f418f2, mac_address=fa:16:3e:41:fc:38, name=, network_id=fa8b09ff-2ceb-47c6-940b-b3c51ea6addc, port_security_enabled=False, project_id=eca78b8359a74f9db5a1121725dbc3ec, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=eca78b8359a74f9db5a1121725dbc3ec, updated_at=2018-06-26T11:47:52Z port_update_end /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:409
2018-06-26 13:47:55.600 3189 DEBUG oslo_concurrency.lockutils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Releasing semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:47:55.606 3189 DEBUG oslo_concurrency.lockutils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Acquired semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:47:55.607 3189 INFO neutron.agent.dhcp.agent [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-06-26T11:47:51Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'ff889f61-c119-4ed8-b0b2-a93e5a53e158', u'ip_address': u'11.237.1.2'}], id=29b08087-71d5-4afd-b556-75b356f418f2, mac_address=fa:16:3e:41:fc:38, name=, network_id=fa8b09ff-2ceb-47c6-940b-b3c51ea6addc, port_security_enabled=False, project_id=eca78b8359a74f9db5a1121725dbc3ec, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=eca78b8359a74f9db5a1121725dbc3ec, updated_at=2018-06-26T11:47:53Z
2018-06-26 13:47:55.612 3189 DEBUG neutron.agent.dhcp.agent [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Calling driver for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-26 13:47:55.614 3189 DEBUG neutron.agent.linux.dhcp [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Building host file: /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-26 13:47:55.617 3189 DEBUG neutron.agent.linux.dhcp [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Done building host file /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-26 13:47:55.624 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '7540'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:55.673 3189 DEBUG neutron.agent.linux.dhcp [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Reloading allocations for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-26 13:47:55.682 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-4', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:55.715 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-6', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:47:55.751 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:47:55.752 3189 DEBUG neutron.agent.linux.utils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:47:55.758 3189 DEBUG neutron.agent.linux.external_process [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] No process started for fa8b09ff-2ceb-47c6-940b-b3c51ea6addc disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-26 13:47:55.760 3189 DEBUG oslo_concurrency.lockutils [req-61dfa182-98ea-41dc-a58b-eff8ab84c8a1 - - - - -] Releasing semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:48:23.759 3189 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-26 13:48:23.762 3189 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-26 13:48:27.050 3189 DEBUG oslo_concurrency.lockutils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Acquired semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:48:27.051 3189 INFO neutron.agent.dhcp.agent [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-06-26T11:48:26Z, description=, device_id=9f2f85d1-cc5e-4d5c-a713-7ca0bc1e7819, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'ff889f61-c119-4ed8-b0b2-a93e5a53e158', u'ip_address': u'11.237.1.1'}], id=ecfb57fb-b610-4b45-8c4b-5d299d66bdb3, mac_address=fa:16:3e:96:4c:b8, name=, network_id=fa8b09ff-2ceb-47c6-940b-b3c51ea6addc, port_security_enabled=False, project_id=eca78b8359a74f9db5a1121725dbc3ec, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=eca78b8359a74f9db5a1121725dbc3ec, updated_at=2018-06-26T11:48:26Z
2018-06-26 13:48:27.052 3189 DEBUG neutron.agent.dhcp.agent [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Calling driver for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-26 13:48:27.053 3189 DEBUG neutron.agent.linux.dhcp [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Building host file: /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-26 13:48:27.063 3189 DEBUG neutron.agent.linux.dhcp [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Done building host file /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-26 13:48:27.067 3189 DEBUG neutron.agent.linux.utils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Running command (rootwrap daemon): ['kill', '-HUP', '7540'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:27.084 3189 DEBUG neutron.agent.linux.dhcp [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Reloading allocations for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-26 13:48:27.085 3189 DEBUG neutron.agent.linux.utils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-4', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:27.100 3189 DEBUG neutron.agent.linux.utils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-6', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:27.112 3189 DEBUG neutron.agent.linux.utils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:48:27.113 3189 DEBUG neutron.agent.linux.utils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:48:27.114 3189 DEBUG neutron.agent.linux.external_process [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] No process started for fa8b09ff-2ceb-47c6-940b-b3c51ea6addc disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-26 13:48:27.115 3189 DEBUG oslo_concurrency.lockutils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Releasing semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:48:28.040 3189 DEBUG oslo_concurrency.lockutils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Acquired semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:48:28.041 3189 INFO neutron.agent.dhcp.agent [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-06-26T11:48:26Z, description=, device_id=9f2f85d1-cc5e-4d5c-a713-7ca0bc1e7819, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'ff889f61-c119-4ed8-b0b2-a93e5a53e158', u'ip_address': u'11.237.1.1'}], id=ecfb57fb-b610-4b45-8c4b-5d299d66bdb3, mac_address=fa:16:3e:96:4c:b8, name=, network_id=fa8b09ff-2ceb-47c6-940b-b3c51ea6addc, port_security_enabled=False, project_id=eca78b8359a74f9db5a1121725dbc3ec, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=eca78b8359a74f9db5a1121725dbc3ec, updated_at=2018-06-26T11:48:26Z
2018-06-26 13:48:28.042 3189 DEBUG neutron.agent.dhcp.agent [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Calling driver for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-26 13:48:28.043 3189 DEBUG neutron.agent.linux.dhcp [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Building host file: /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-26 13:48:28.049 3189 DEBUG neutron.agent.linux.dhcp [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Done building host file /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-26 13:48:28.053 3189 DEBUG neutron.agent.linux.utils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Running command (rootwrap daemon): ['kill', '-HUP', '7540'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:28.064 3189 DEBUG neutron.agent.linux.dhcp [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Reloading allocations for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-26 13:48:28.065 3189 DEBUG neutron.agent.linux.utils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-4', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:28.076 3189 DEBUG neutron.agent.linux.utils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-6', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:28.086 3189 DEBUG neutron.agent.linux.utils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:48:28.086 3189 DEBUG neutron.agent.linux.utils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:48:28.087 3189 DEBUG neutron.agent.linux.external_process [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] No process started for fa8b09ff-2ceb-47c6-940b-b3c51ea6addc disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-26 13:48:28.088 3189 DEBUG oslo_concurrency.lockutils [req-8358a37f-5b09-4322-b50c-12bbfdd6da4e 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Releasing semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:48:30.940 3189 DEBUG oslo_concurrency.lockutils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Acquired semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:48:30.941 3189 INFO neutron.agent.dhcp.agent [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-06-26T11:48:26Z, description=, device_id=9f2f85d1-cc5e-4d5c-a713-7ca0bc1e7819, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'ff889f61-c119-4ed8-b0b2-a93e5a53e158', u'ip_address': u'11.237.1.1'}], id=ecfb57fb-b610-4b45-8c4b-5d299d66bdb3, mac_address=fa:16:3e:96:4c:b8, name=, network_id=fa8b09ff-2ceb-47c6-940b-b3c51ea6addc, port_security_enabled=False, project_id=eca78b8359a74f9db5a1121725dbc3ec, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=eca78b8359a74f9db5a1121725dbc3ec, updated_at=2018-06-26T11:48:27Z
2018-06-26 13:48:30.942 3189 DEBUG neutron.agent.dhcp.agent [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Calling driver for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-26 13:48:30.944 3189 DEBUG neutron.agent.linux.dhcp [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Building host file: /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-26 13:48:30.947 3189 DEBUG neutron.agent.linux.dhcp [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Done building host file /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-26 13:48:30.951 3189 DEBUG neutron.agent.linux.utils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '7540'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:30.967 3189 DEBUG neutron.agent.linux.dhcp [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Reloading allocations for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-26 13:48:30.968 3189 DEBUG neutron.agent.linux.utils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-4', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:30.984 3189 DEBUG neutron.agent.linux.utils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-6', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:31.001 3189 DEBUG neutron.agent.linux.utils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:48:31.002 3189 DEBUG neutron.agent.linux.utils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:48:31.003 3189 DEBUG neutron.agent.linux.external_process [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] No process started for fa8b09ff-2ceb-47c6-940b-b3c51ea6addc disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-26 13:48:31.004 3189 DEBUG oslo_concurrency.lockutils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Releasing semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:48:31.823 3189 DEBUG oslo_concurrency.lockutils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Acquired semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:48:31.824 3189 INFO neutron.agent.dhcp.agent [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-06-26T11:48:26Z, description=, device_id=9f2f85d1-cc5e-4d5c-a713-7ca0bc1e7819, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'ff889f61-c119-4ed8-b0b2-a93e5a53e158', u'ip_address': u'11.237.1.1'}], id=ecfb57fb-b610-4b45-8c4b-5d299d66bdb3, mac_address=fa:16:3e:96:4c:b8, name=, network_id=fa8b09ff-2ceb-47c6-940b-b3c51ea6addc, port_security_enabled=False, project_id=eca78b8359a74f9db5a1121725dbc3ec, revision_number=6, security_groups=[], status=DOWN, tags=[], tenant_id=eca78b8359a74f9db5a1121725dbc3ec, updated_at=2018-06-26T11:48:31Z
2018-06-26 13:48:31.826 3189 DEBUG neutron.agent.dhcp.agent [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Calling driver for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-06-26 13:48:31.827 3189 DEBUG neutron.agent.linux.dhcp [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Building host file: /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:682
2018-06-26 13:48:31.833 3189 DEBUG neutron.agent.linux.dhcp [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Done building host file /var/lib/neutron/dhcp/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:721
2018-06-26 13:48:31.837 3189 DEBUG neutron.agent.linux.utils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '7540'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:31.851 3189 DEBUG neutron.agent.linux.dhcp [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Reloading allocations for network: fa8b09ff-2ceb-47c6-940b-b3c51ea6addc reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:511
2018-06-26 13:48:31.853 3189 DEBUG neutron.agent.linux.utils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-4', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:31.866 3189 DEBUG neutron.agent.linux.utils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc', 'ip', '-6', 'route', 'list', 'dev', 'tap29b08087-71'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-06-26 13:48:31.881 3189 DEBUG neutron.agent.linux.utils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:48:31.883 3189 DEBUG neutron.agent.linux.utils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Unable to access /var/lib/neutron/external/pids/fa8b09ff-2ceb-47c6-940b-b3c51ea6addc.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-06-26 13:48:31.884 3189 DEBUG neutron.agent.linux.external_process [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] No process started for fa8b09ff-2ceb-47c6-940b-b3c51ea6addc disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-06-26 13:48:31.884 3189 DEBUG oslo_concurrency.lockutils [req-73b5d6b9-3368-4bc8-9275-a2e2d95849f6 - - - - -] Releasing semaphore "dhcp-agent-network-lock-fa8b09ff-2ceb-47c6-940b-b3c51ea6addc" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:48:39.229 3189 DEBUG oslo_concurrency.lockutils [req-816ae208-c656-41cc-b914-cec45e2ad328 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Acquired semaphore "dhcp-agent-network-lock-3a89a4af-574f-492a-9eb4-eae63d51f625" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:48:39.230 3189 DEBUG oslo_concurrency.lockutils [req-816ae208-c656-41cc-b914-cec45e2ad328 836f42f7c613467f9b2bdc2271fe464f eca78b8359a74f9db5a1121725dbc3ec - - -] Releasing semaphore "dhcp-agent-network-lock-3a89a4af-574f-492a-9eb4-eae63d51f625" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:48:41.885 3189 DEBUG oslo_concurrency.lockutils [req-94213808-f091-4199-81ed-0cc83a7e7a9e - - - - -] Acquired semaphore "dhcp-agent-network-lock-3a89a4af-574f-492a-9eb4-eae63d51f625" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:48:41.886 3189 DEBUG oslo_concurrency.lockutils [req-94213808-f091-4199-81ed-0cc83a7e7a9e - - - - -] Releasing semaphore "dhcp-agent-network-lock-3a89a4af-574f-492a-9eb4-eae63d51f625" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-06-26 13:48:42.640 3189 DEBUG oslo_concurrency.lockutils [req-94213808-f091-4199-81ed-0cc83a7e7a9e - - - - -] Acquired semaphore "dhcp-agent-network-lock-3a89a4af-574f-492a-9eb4-eae63d51f625" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-06-26 13:48:42.641 3189 DEBUG oslo_concurrency.lockutils [req-94213808-f091-4199-81ed-0cc83a7e7a9e - - - - -] Releasing semaphore "dhcp-agent-network-lock-3a89a4af-574f-492a-9eb4-eae63d51f625" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
