2018-09-29 06:51:13.828 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 06:51:13.834 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 06:52:13.828 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 06:52:13.832 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 06:53:13.120 20579 DEBUG oslo_concurrency.lockutils [req-d62f6975-b67e-4989-879d-5635d1177c67 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:53:13.595 20579 DEBUG neutron.agent.dhcp.agent [req-13a1bbcc-fb4c-46ec-a8f6-b80762e8afe2 - - - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: enable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 06:53:13.598 20579 DEBUG neutron.agent.linux.utils [req-13a1bbcc-fb4c-46ec-a8f6-b80762e8afe2 - - - - -] Unable to access /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:53:13.599 20579 DEBUG neutron.agent.linux.dhcp [req-13a1bbcc-fb4c-46ec-a8f6-b80762e8afe2 - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c on network 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c does not yet exist. Checking for a reserved port. _setup_reserved_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1272
2018-09-29 06:53:13.601 20579 DEBUG neutron.agent.linux.dhcp [req-13a1bbcc-fb4c-46ec-a8f6-b80762e8afe2 - - - - -] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c on network 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c does not yet exist. Creating new one. _setup_new_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1293
2018-09-29 06:53:13.829 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 06:53:13.832 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 06:53:16.412 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.433 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'add', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.451 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'sysctl', '-w', 'net.ipv4.conf.all.promote_secondaries=1'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.487 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', 'link', 'set', 'lo', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.505 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'sysctl', '-w', 'net.ipv6.conf.default.accept_ra=0'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.525 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', 'link', 'set', 'tap714c0110-22', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.553 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-o', 'link', 'show', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.572 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-09-29 06:53:16.599 20579 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=None, port=tap714c0110-22) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 06:53:16.602 20579 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Transaction caused no change do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:114
2018-09-29 06:53:16.604 20579 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): AddPortCommand(bridge=br-int, may_exist=False, port=tap714c0110-22) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 06:53:16.605 20579 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=1): DbSetCommand(table=Port, col_values=(('tag', 4095),), record=tap714c0110-22) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 06:53:16.607 20579 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=2): DbSetCommand(table=Interface, col_values=(('type', 'internal'), ('external_ids', {'iface-id': u'714c0110-223d-4daf-bce9-15e101fd2b64', 'iface-status': 'active', 'attached-mac': u'fa:16:3e:33:1a:5b'})), record=tap714c0110-22) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 06:53:16.639 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tap714c0110-22', 'address', 'fa:16:3e:33:1a:5b'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.660 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.673 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'link', 'set', 'tap714c0110-22', 'netns', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.699 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', 'link', 'set', 'tap714c0110-22', 'mtu', '1450'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.713 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', 'link', 'set', 'tap714c0110-22', 'up'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.730 20579 DEBUG oslo_concurrency.lockutils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Acquired semaphore "iptables-qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:53:16.759 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'iptables-save'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.791 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'iptables-restore', '-n'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.863 20579 DEBUG neutron.agent.linux.iptables_manager [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] IPTablesManager.apply completed with success. 56 iptables commands were issued _apply_synchronized /usr/lib/python2.7/site-packages/neutron/agent/linux/iptables_manager.py:601
2018-09-29 06:53:16.864 20579 DEBUG oslo_concurrency.lockutils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Releasing semaphore "iptables-qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:53:16.866 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-o', 'link', 'show', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.883 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', 'addr', 'show', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.900 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'addr', 'add', '11.70.1.2/24', 'scope', 'global', 'dev', 'tap714c0110-22', 'brd', '11.70.1.255'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.916 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.929 20579 DEBUG neutron.agent.linux.dhcp [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Setting IPv4 gateway for dhcp netns on net 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c to 11.70.1.1 _set_default_route_ip_version /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1169
2018-09-29 06:53:16.931 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'replace', 'default', 'via', '11.70.1.1', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.946 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.958 20579 DEBUG neutron.agent.linux.dhcp [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Cleaning stale devices for network 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c _cleanup_stale_devices /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1374
2018-09-29 06:53:16.959 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.974 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'find', '/sys/class/net', '-maxdepth', '1', '-type', 'l', '-printf', '%f '] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:16.995 20579 DEBUG neutron.agent.linux.dhcp [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Building initial lease file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/leases _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:626
2018-09-29 06:53:16.997 20579 DEBUG neutron.agent.linux.dhcp [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Done building initial lease file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/leases with contents:
1538304796 fa:16:3e:33:1a:5b 11.70.1.2 * *
 _output_init_lease_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:654
2018-09-29 06:53:16.998 20579 DEBUG neutron.agent.linux.dhcp [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 06:53:16.999 20579 DEBUG neutron.agent.linux.dhcp [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 06:53:17.002 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Unable to access /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:53:17.003 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'dnsmasq', '--no-hosts', '--no-resolv', '--strict-order', '--except-interface=lo', '--pid-file=/var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/pid', '--dhcp-hostsfile=/var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host', '--addn-hosts=/var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/addn_hosts', '--dhcp-optsfile=/var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/opts', '--dhcp-leasefile=/var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/leases', '--dhcp-match=set:ipxe,175', '--bind-interfaces', '--interface=tap714c0110-22', '--dhcp-range=set:tag0,11.70.1.0,static,255.255.255.0,86400s', '--dhcp-option-force=option:mtu,1450', '--dhcp-lease-max=256', '--conf-file=', '--domain=openstacklocal'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:17.077 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:53:17.089 20579 DEBUG neutron.agent.linux.utils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:53:17.092 20579 DEBUG neutron.agent.linux.external_process [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 06:53:17.093 20579 DEBUG oslo_concurrency.lockutils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:53:17.095 20579 DEBUG oslo_concurrency.lockutils [req-d62f6975-b67e-4989-879d-5635d1177c67 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:53:17.654 20579 DEBUG neutron.agent.dhcp.agent [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 06:53:17.655 20579 DEBUG neutron.agent.linux.dhcp [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 06:53:17.659 20579 DEBUG neutron.agent.linux.dhcp [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 06:53:17.666 20579 DEBUG neutron.agent.linux.utils [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:17.685 20579 DEBUG neutron.agent.linux.dhcp [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] Reloading allocations for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 06:53:17.686 20579 DEBUG neutron.agent.linux.utils [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:17.707 20579 DEBUG neutron.agent.linux.utils [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:17.726 20579 DEBUG neutron.agent.linux.utils [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:53:17.727 20579 DEBUG neutron.agent.linux.utils [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:53:17.728 20579 DEBUG neutron.agent.linux.external_process [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 06:53:17.729 20579 DEBUG oslo_concurrency.lockutils [req-2de0cc89-a143-4b4d-bc68-9d541b6f37a6 - - - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:53:17.731 20579 DEBUG oslo_concurrency.lockutils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:53:17.732 20579 DEBUG neutron.agent.dhcp.agent [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Discarding stale port update: admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T10:53:13Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'd4ce5193-91e5-45ae-b5da-10d567168230', u'ip_address': u'11.70.1.2'}], id=714c0110-223d-4daf-bce9-15e101fd2b64, mac_address=fa:16:3e:33:1a:5b, name=, network_id=9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, port_security_enabled=False, project_id=76c8962164e44c1390bf836feb75a14c, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=76c8962164e44c1390bf836feb75a14c, updated_at=2018-09-29T10:53:14Z port_update_end /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:410
2018-09-29 06:53:17.734 20579 DEBUG oslo_concurrency.lockutils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:53:17.740 20579 DEBUG oslo_concurrency.lockutils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:53:17.741 20579 DEBUG neutron.agent.dhcp.agent [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Discarding stale port update: admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-29T10:53:13Z, description=, device_id=dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, device_owner=network:dhcp, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'd4ce5193-91e5-45ae-b5da-10d567168230', u'ip_address': u'11.70.1.2'}], id=714c0110-223d-4daf-bce9-15e101fd2b64, mac_address=fa:16:3e:33:1a:5b, name=, network_id=9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, port_security_enabled=False, project_id=76c8962164e44c1390bf836feb75a14c, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=76c8962164e44c1390bf836feb75a14c, updated_at=2018-09-29T10:53:15Z port_update_end /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:410
2018-09-29 06:53:17.742 20579 DEBUG oslo_concurrency.lockutils [req-c3f1cdb4-bac6-4617-9a99-d64eaa5ba301 - - - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:53:55.313 20579 DEBUG oslo_concurrency.lockutils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:53:55.316 20579 INFO neutron.agent.dhcp.agent [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T10:53:54Z, description=, device_id=c4002926-cfe2-4231-b1dd-518611e75763, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'd4ce5193-91e5-45ae-b5da-10d567168230', u'ip_address': u'11.70.1.1'}], id=413b6762-6726-462d-bb16-8017e7f3ee3a, mac_address=fa:16:3e:48:64:09, name=, network_id=9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, port_security_enabled=False, project_id=76c8962164e44c1390bf836feb75a14c, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=76c8962164e44c1390bf836feb75a14c, updated_at=2018-09-29T10:53:54Z
2018-09-29 06:53:55.319 20579 DEBUG neutron.agent.dhcp.agent [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 06:53:55.322 20579 DEBUG neutron.agent.linux.dhcp [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 06:53:55.326 20579 DEBUG neutron.agent.linux.dhcp [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 06:53:55.338 20579 DEBUG neutron.agent.linux.utils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Running command (rootwrap daemon): ['kill', '-HUP', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:55.358 20579 DEBUG neutron.agent.linux.dhcp [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Reloading allocations for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 06:53:55.360 20579 DEBUG neutron.agent.linux.utils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:55.377 20579 DEBUG neutron.agent.linux.utils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:55.395 20579 DEBUG neutron.agent.linux.utils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:53:55.396 20579 DEBUG neutron.agent.linux.utils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:53:55.398 20579 DEBUG neutron.agent.linux.external_process [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 06:53:55.399 20579 DEBUG oslo_concurrency.lockutils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:53:56.990 20579 DEBUG oslo_concurrency.lockutils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:53:56.991 20579 INFO neutron.agent.dhcp.agent [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T10:53:54Z, description=, device_id=c4002926-cfe2-4231-b1dd-518611e75763, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'd4ce5193-91e5-45ae-b5da-10d567168230', u'ip_address': u'11.70.1.1'}], id=413b6762-6726-462d-bb16-8017e7f3ee3a, mac_address=fa:16:3e:48:64:09, name=, network_id=9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, port_security_enabled=False, project_id=76c8962164e44c1390bf836feb75a14c, revision_number=3, security_groups=[], status=DOWN, tags=[], tenant_id=76c8962164e44c1390bf836feb75a14c, updated_at=2018-09-29T10:53:54Z
2018-09-29 06:53:56.993 20579 DEBUG neutron.agent.dhcp.agent [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 06:53:56.994 20579 DEBUG neutron.agent.linux.dhcp [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 06:53:56.996 20579 DEBUG neutron.agent.linux.dhcp [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 06:53:57.001 20579 DEBUG neutron.agent.linux.utils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Running command (rootwrap daemon): ['kill', '-HUP', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:57.019 20579 DEBUG neutron.agent.linux.dhcp [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Reloading allocations for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 06:53:57.021 20579 DEBUG neutron.agent.linux.utils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:57.039 20579 DEBUG neutron.agent.linux.utils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:53:57.059 20579 DEBUG neutron.agent.linux.utils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:53:57.061 20579 DEBUG neutron.agent.linux.utils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:53:57.062 20579 DEBUG neutron.agent.linux.external_process [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 06:53:57.064 20579 DEBUG oslo_concurrency.lockutils [req-77f1b05f-80d1-4434-b3e9-7b473d4e3cdc 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:54:00.341 20579 DEBUG oslo_concurrency.lockutils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:54:00.342 20579 INFO neutron.agent.dhcp.agent [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T10:53:54Z, description=, device_id=c4002926-cfe2-4231-b1dd-518611e75763, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'd4ce5193-91e5-45ae-b5da-10d567168230', u'ip_address': u'11.70.1.1'}], id=413b6762-6726-462d-bb16-8017e7f3ee3a, mac_address=fa:16:3e:48:64:09, name=, network_id=9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, port_security_enabled=False, project_id=76c8962164e44c1390bf836feb75a14c, revision_number=4, security_groups=[], status=DOWN, tags=[], tenant_id=76c8962164e44c1390bf836feb75a14c, updated_at=2018-09-29T10:53:56Z
2018-09-29 06:54:00.344 20579 DEBUG neutron.agent.dhcp.agent [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 06:54:00.346 20579 DEBUG neutron.agent.linux.dhcp [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 06:54:00.349 20579 DEBUG neutron.agent.linux.dhcp [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 06:54:00.354 20579 DEBUG neutron.agent.linux.utils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:00.373 20579 DEBUG neutron.agent.linux.dhcp [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Reloading allocations for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 06:54:00.374 20579 DEBUG neutron.agent.linux.utils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:00.397 20579 DEBUG neutron.agent.linux.utils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:00.419 20579 DEBUG neutron.agent.linux.utils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:54:00.421 20579 DEBUG neutron.agent.linux.utils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:54:00.422 20579 DEBUG neutron.agent.linux.external_process [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 06:54:00.423 20579 DEBUG oslo_concurrency.lockutils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:54:01.283 20579 DEBUG oslo_concurrency.lockutils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:54:01.285 20579 INFO neutron.agent.dhcp.agent [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-29T10:53:54Z, description=, device_id=c4002926-cfe2-4231-b1dd-518611e75763, device_owner=network:router_interface, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'd4ce5193-91e5-45ae-b5da-10d567168230', u'ip_address': u'11.70.1.1'}], id=413b6762-6726-462d-bb16-8017e7f3ee3a, mac_address=fa:16:3e:48:64:09, name=, network_id=9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, port_security_enabled=False, project_id=76c8962164e44c1390bf836feb75a14c, revision_number=6, security_groups=[], status=DOWN, tags=[], tenant_id=76c8962164e44c1390bf836feb75a14c, updated_at=2018-09-29T10:54:00Z
2018-09-29 06:54:01.288 20579 DEBUG neutron.agent.dhcp.agent [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 06:54:01.289 20579 DEBUG neutron.agent.linux.dhcp [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 06:54:01.291 20579 DEBUG neutron.agent.linux.dhcp [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 06:54:01.297 20579 DEBUG neutron.agent.linux.utils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Running command (rootwrap daemon): ['kill', '-HUP', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:01.322 20579 DEBUG neutron.agent.linux.dhcp [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Reloading allocations for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 06:54:01.325 20579 DEBUG neutron.agent.linux.utils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:01.349 20579 DEBUG neutron.agent.linux.utils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:01.373 20579 DEBUG neutron.agent.linux.utils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:54:01.375 20579 DEBUG neutron.agent.linux.utils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:54:01.377 20579 DEBUG neutron.agent.linux.external_process [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 06:54:01.378 20579 DEBUG oslo_concurrency.lockutils [req-f37804d8-726d-4c5b-b882-930f731508ec - - - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:54:09.098 20579 DEBUG oslo_concurrency.lockutils [req-0791336b-6a6c-4fdd-be50-3692db783c39 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Acquired semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:54:09.099 20579 DEBUG oslo_concurrency.lockutils [req-0791336b-6a6c-4fdd-be50-3692db783c39 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Releasing semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:54:12.897 20579 DEBUG oslo_concurrency.lockutils [req-bac426e4-2bd3-4fba-9e25-4246683d977d - - - - -] Acquired semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:54:12.898 20579 DEBUG oslo_concurrency.lockutils [req-bac426e4-2bd3-4fba-9e25-4246683d977d - - - - -] Releasing semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:54:13.828 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 06:54:13.833 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 06:54:14.126 20579 DEBUG oslo_concurrency.lockutils [req-bac426e4-2bd3-4fba-9e25-4246683d977d - - - - -] Acquired semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:54:14.127 20579 DEBUG oslo_concurrency.lockutils [req-bac426e4-2bd3-4fba-9e25-4246683d977d - - - - -] Releasing semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:54:34.943 20579 DEBUG oslo_concurrency.lockutils [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:54:34.944 20579 INFO neutron.agent.dhcp.agent [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T10:54:33Z, description=, device_id=dea51464-544e-4435-9ab5-66a769b851fe, device_owner=, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'd4ce5193-91e5-45ae-b5da-10d567168230', u'ip_address': u'11.70.1.8'}], id=48100587-71b8-40fc-85cb-5f2a464e92cf, mac_address=fa:16:3e:01:22:95, name=, network_id=9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, port_security_enabled=True, project_id=76c8962164e44c1390bf836feb75a14c, revision_number=3, security_groups=[u'abefb026-e516-4677-8865-387486ee6e1a'], status=DOWN, tags=[], tenant_id=76c8962164e44c1390bf836feb75a14c, updated_at=2018-09-29T10:54:34Z
2018-09-29 06:54:34.945 20579 DEBUG neutron.agent.dhcp.agent [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 06:54:34.946 20579 DEBUG neutron.agent.linux.dhcp [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 06:54:35.387 20579 DEBUG neutron.agent.linux.dhcp [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 06:54:35.395 20579 DEBUG neutron.agent.linux.utils [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Running command (rootwrap daemon): ['kill', '-HUP', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:35.470 20579 DEBUG neutron.agent.linux.dhcp [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Reloading allocations for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 06:54:35.581 20579 DEBUG neutron.agent.linux.utils [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:35.597 20579 DEBUG neutron.agent.linux.utils [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:35.619 20579 DEBUG neutron.agent.linux.utils [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:54:35.620 20579 DEBUG neutron.agent.linux.utils [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:54:35.621 20579 DEBUG neutron.agent.linux.external_process [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 06:54:35.622 20579 DEBUG oslo_concurrency.lockutils [req-3a4656c8-6284-48d1-ab62-ffdfb7b6742b 8ee34d538b0a48d6a7843e16b73b2228 76c8962164e44c1390bf836feb75a14c - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:54:37.067 20579 DEBUG oslo_concurrency.lockutils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:54:37.068 20579 INFO neutron.agent.dhcp.agent [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=, binding:vif_type=unbound, binding:vnic_type=normal, created_at=2018-09-29T10:54:33Z, description=, device_id=dea51464-544e-4435-9ab5-66a769b851fe, device_owner=compute:nova, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'd4ce5193-91e5-45ae-b5da-10d567168230', u'ip_address': u'11.70.1.8'}], id=48100587-71b8-40fc-85cb-5f2a464e92cf, mac_address=fa:16:3e:01:22:95, name=, network_id=9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, port_security_enabled=True, project_id=76c8962164e44c1390bf836feb75a14c, revision_number=4, security_groups=[u'abefb026-e516-4677-8865-387486ee6e1a'], status=DOWN, tags=[], tenant_id=76c8962164e44c1390bf836feb75a14c, updated_at=2018-09-29T10:54:36Z
2018-09-29 06:54:37.069 20579 DEBUG neutron.agent.dhcp.agent [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 06:54:37.072 20579 DEBUG neutron.agent.linux.dhcp [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 06:54:37.101 20579 DEBUG neutron.agent.linux.dhcp [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 06:54:37.109 20579 DEBUG neutron.agent.linux.utils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:37.124 20579 DEBUG neutron.agent.linux.dhcp [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Reloading allocations for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 06:54:37.125 20579 DEBUG neutron.agent.linux.utils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:37.147 20579 DEBUG neutron.agent.linux.utils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:37.169 20579 DEBUG neutron.agent.linux.utils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:54:37.169 20579 DEBUG neutron.agent.linux.utils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:54:37.170 20579 DEBUG neutron.agent.linux.external_process [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 06:54:37.171 20579 DEBUG oslo_concurrency.lockutils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:54:37.947 20579 DEBUG oslo_concurrency.lockutils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:54:37.949 20579 INFO neutron.agent.dhcp.agent [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Trigger reload_allocations for port admin_state_up=True, allowed_address_pairs=[], binding:host_id=localhost.localdomain, binding:profile=, binding:vif_details=datapath_type=system, ovs_hybrid_plug=True, port_filter=True, binding:vif_type=ovs, binding:vnic_type=normal, created_at=2018-09-29T10:54:33Z, description=, device_id=dea51464-544e-4435-9ab5-66a769b851fe, device_owner=compute:nova, extra_dhcp_opts=[], fixed_ips=[{u'subnet_id': u'd4ce5193-91e5-45ae-b5da-10d567168230', u'ip_address': u'11.70.1.8'}], id=48100587-71b8-40fc-85cb-5f2a464e92cf, mac_address=fa:16:3e:01:22:95, name=, network_id=9de1d8ca-eddf-4679-8a05-8ac6cc7d062c, port_security_enabled=True, project_id=76c8962164e44c1390bf836feb75a14c, revision_number=5, security_groups=[u'abefb026-e516-4677-8865-387486ee6e1a'], status=DOWN, tags=[], tenant_id=76c8962164e44c1390bf836feb75a14c, updated_at=2018-09-29T10:54:37Z
2018-09-29 06:54:37.951 20579 DEBUG neutron.agent.dhcp.agent [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 06:54:37.953 20579 DEBUG neutron.agent.linux.dhcp [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 06:54:37.964 20579 DEBUG neutron.agent.linux.dhcp [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 06:54:37.970 20579 DEBUG neutron.agent.linux.utils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:37.987 20579 DEBUG neutron.agent.linux.dhcp [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Reloading allocations for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 06:54:37.989 20579 DEBUG neutron.agent.linux.utils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:38.005 20579 DEBUG neutron.agent.linux.utils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:54:38.023 20579 DEBUG neutron.agent.linux.utils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:54:38.024 20579 DEBUG neutron.agent.linux.utils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:54:38.025 20579 DEBUG neutron.agent.linux.external_process [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 06:54:38.026 20579 DEBUG oslo_concurrency.lockutils [req-177c4a65-009f-46dd-94ae-0188291ce00b 84b85dc3831841e999b63e4879e07725 8961986b09aa454c91f8843d75e99a17 - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:55:05.592 20579 DEBUG oslo_concurrency.lockutils [req-977ceec8-cbcf-4c4d-b572-a759f0fdcf2a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:55:05.593 20579 DEBUG oslo_concurrency.lockutils [req-977ceec8-cbcf-4c4d-b572-a759f0fdcf2a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Releasing semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:55:06.524 20579 DEBUG oslo_concurrency.lockutils [req-977ceec8-cbcf-4c4d-b572-a759f0fdcf2a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:55:06.525 20579 DEBUG oslo_concurrency.lockutils [req-977ceec8-cbcf-4c4d-b572-a759f0fdcf2a 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Releasing semaphore "dhcp-agent-network-lock-7fc29900-2b68-444d-aebd-eb83e6248a3d" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 06:55:13.829 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 06:55:13.832 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 06:56:13.829 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 06:56:13.835 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 06:57:13.829 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 06:57:13.835 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 06:58:13.829 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 06:58:13.839 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.010s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 06:59:13.830 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 06:59:13.835 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 06:59:22.783 20579 DEBUG oslo_concurrency.lockutils [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 06:59:22.785 20579 DEBUG neutron.agent.dhcp.agent [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 06:59:22.787 20579 DEBUG neutron.agent.linux.utils [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'dhcp_release', 'tap714c0110-22', '11.70.1.8', 'fa:16:3e:01:22:95'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:59:22.818 20579 DEBUG neutron.agent.linux.dhcp [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 06:59:22.831 20579 DEBUG neutron.agent.linux.dhcp [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 06:59:22.851 20579 DEBUG neutron.agent.linux.utils [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:59:22.873 20579 DEBUG neutron.agent.linux.dhcp [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Reloading allocations for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 06:59:22.875 20579 DEBUG neutron.agent.linux.utils [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:59:22.905 20579 DEBUG neutron.agent.linux.utils [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 06:59:22.929 20579 DEBUG neutron.agent.linux.utils [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:59:22.931 20579 DEBUG neutron.agent.linux.utils [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 06:59:22.932 20579 DEBUG neutron.agent.linux.external_process [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 06:59:22.934 20579 DEBUG oslo_concurrency.lockutils [req-3e9312a4-cab7-4160-9588-1ac8b8efdc64 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 07:00:13.830 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 07:00:13.836 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 07:00:16.430 20579 DEBUG oslo_concurrency.lockutils [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 07:00:16.432 20579 DEBUG neutron.agent.dhcp.agent [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: reload_allocations call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 07:00:16.435 20579 DEBUG neutron.agent.linux.utils [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'dhcp_release', 'tap714c0110-22', '11.70.1.1', 'fa:16:3e:48:64:09'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 07:00:16.477 20579 DEBUG neutron.agent.linux.dhcp [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Building host file: /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:685
2018-09-29 07:00:16.484 20579 DEBUG neutron.agent.linux.dhcp [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Done building host file /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/host _output_hosts_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:724
2018-09-29 07:00:16.495 20579 DEBUG neutron.agent.linux.utils [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['kill', '-HUP', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 07:00:16.515 20579 DEBUG neutron.agent.linux.dhcp [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Reloading allocations for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c reload_allocations /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:514
2018-09-29 07:00:16.518 20579 DEBUG neutron.agent.linux.utils [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-4', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 07:00:16.541 20579 DEBUG neutron.agent.linux.utils [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['ip', 'netns', 'exec', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c', 'ip', '-6', 'route', 'list', 'dev', 'tap714c0110-22'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 07:00:16.564 20579 DEBUG neutron.agent.linux.utils [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 07:00:16.567 20579 DEBUG neutron.agent.linux.utils [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 07:00:16.570 20579 DEBUG neutron.agent.linux.external_process [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 07:00:16.573 20579 DEBUG oslo_concurrency.lockutils [req-ceae3d4b-f4cc-445a-a969-69398e269532 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 07:00:47.399 20579 DEBUG oslo_concurrency.lockutils [req-eb943f28-09a9-448d-93f6-0e7ea84f9430 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 07:00:47.401 20579 DEBUG neutron.agent.dhcp.agent [req-eb943f28-09a9-448d-93f6-0e7ea84f9430 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 07:00:47.405 20579 DEBUG neutron.agent.linux.utils [req-eb943f28-09a9-448d-93f6-0e7ea84f9430 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command (rootwrap daemon): ['kill', '-9', '28058'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 07:00:47.424 20579 DEBUG neutron.agent.linux.utils [req-eb943f28-09a9-448d-93f6-0e7ea84f9430 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Running command: ['ip', '-o', 'link', 'show', 'br-int'] create_process /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:92
2018-09-29 07:00:47.461 20579 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn command(idx=0): DelPortCommand(if_exists=True, bridge=br-int, port=tap714c0110-22) do_commit /usr/lib/python2.7/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
2018-09-29 07:00:47.530 20579 DEBUG neutron.agent.linux.utils [req-863693f7-9266-4bc6-b48c-5d7b41f6e72d - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 07:00:47.541 20579 DEBUG neutron.agent.linux.utils [req-863693f7-9266-4bc6-b48c-5d7b41f6e72d - - - - -] Running command (rootwrap daemon): ['ip', 'netns', 'delete', 'qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 07:00:47.556 20579 DEBUG oslo_concurrency.lockutils [req-863693f7-9266-4bc6-b48c-5d7b41f6e72d - - - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 07:00:56.403 20579 DEBUG neutron.agent.dhcp.agent [req-13e3c687-467c-4fd5-b282-eeb5fc27a518 - - - - -] resync (9de1d8ca-eddf-4679-8a05-8ac6cc7d062c): ['Agent port was deleted'] _periodic_resync_helper /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:256
2018-09-29 07:00:56.405 20579 INFO neutron.agent.dhcp.agent [req-13e3c687-467c-4fd5-b282-eeb5fc27a518 - - - - -] Synchronizing state
2018-09-29 07:00:57.323 20579 INFO neutron.agent.dhcp.agent [req-f50805bf-76db-419f-9c36-eb43d866cb29 - - - - -] All active networks have been fetched through RPC.
2018-09-29 07:00:57.328 20579 INFO neutron.agent.dhcp.agent [-] Starting network 7fc29900-2b68-444d-aebd-eb83e6248a3d dhcp configuration
2018-09-29 07:00:57.330 20579 INFO neutron.agent.dhcp.agent [-] Finished network 7fc29900-2b68-444d-aebd-eb83e6248a3d dhcp configuration
2018-09-29 07:00:57.332 20579 INFO neutron.agent.dhcp.agent [-] Starting network 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c dhcp configuration
2018-09-29 07:00:57.334 20579 DEBUG neutron.agent.dhcp.agent [-] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: enable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 07:00:57.340 20579 DEBUG neutron.agent.linux.utils [-] Unable to access /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 07:00:57.342 20579 DEBUG neutron.agent.linux.dhcp [-] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c on network 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c does not yet exist. Checking for a reserved port. _setup_reserved_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1272
2018-09-29 07:00:57.343 20579 DEBUG neutron.agent.linux.dhcp [-] DHCP port dhcpcd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c on network 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c does not yet exist. Creating new one. _setup_new_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1293
2018-09-29 07:01:02.178 20579 DEBUG neutron.agent.linux.dhcp [req-51b9eb2b-fc4e-4be5-acca-6b86a6867bdb - - - - -] Requested DHCP port with IPs on subnets set([u'd4ce5193-91e5-45ae-b5da-10d567168230']) but only got IPs on subnets set([]). setup_dhcp_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1346
2018-09-29 07:01:02.179 20579 DEBUG neutron.agent.linux.dhcp [req-51b9eb2b-fc4e-4be5-acca-6b86a6867bdb - - - - -] Cleaning stale devices for network 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c _cleanup_stale_devices /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1374
2018-09-29 07:01:02.180 20579 DEBUG neutron.agent.linux.utils [req-51b9eb2b-fc4e-4be5-acca-6b86a6867bdb - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 07:01:02.237 20579 DEBUG neutron.agent.dhcp.agent [req-51b9eb2b-fc4e-4be5-acca-6b86a6867bdb - - - - -] Error configuring DHCP port, scheduling resync: Subnet on port 0538d281-b5f1-490a-a31b-775e51e143c3 does not match the requested subnet d4ce5193-91e5-45ae-b5da-10d567168230. call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:153
2018-09-29 07:01:02.239 20579 INFO neutron.agent.dhcp.agent [req-51b9eb2b-fc4e-4be5-acca-6b86a6867bdb - - - - -] Finished network 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c dhcp configuration
2018-09-29 07:01:02.240 20579 INFO neutron.agent.dhcp.agent [req-f50805bf-76db-419f-9c36-eb43d866cb29 - - - - -] Synchronizing state complete
2018-09-29 07:01:02.241 20579 DEBUG oslo_concurrency.lockutils [req-64cd7d3c-d758-402f-87ba-88a568241764 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 07:01:02.855 20579 DEBUG neutron.agent.linux.utils [req-264e391b-fea3-45d4-9e28-df98a48c5159 - - - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 07:01:02.856 20579 DEBUG neutron.agent.linux.utils [req-264e391b-fea3-45d4-9e28-df98a48c5159 - - - - -] Unable to access /var/lib/neutron/external/pids/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c.pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 07:01:02.857 20579 DEBUG neutron.agent.linux.external_process [req-264e391b-fea3-45d4-9e28-df98a48c5159 - - - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 07:01:02.859 20579 DEBUG neutron.agent.dhcp.agent [req-264e391b-fea3-45d4-9e28-df98a48c5159 - - - - -] Calling driver for network: 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c action: disable call_driver /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:133
2018-09-29 07:01:02.865 20579 DEBUG neutron.agent.linux.utils [req-264e391b-fea3-45d4-9e28-df98a48c5159 - - - - -] Unable to access /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 07:01:02.867 20579 DEBUG neutron.agent.linux.utils [req-264e391b-fea3-45d4-9e28-df98a48c5159 - - - - -] Unable to access /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/pid get_value_from_file /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:254
2018-09-29 07:01:02.868 20579 DEBUG neutron.agent.linux.external_process [req-264e391b-fea3-45d4-9e28-df98a48c5159 - - - - -] No process started for 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c disable /usr/lib/python2.7/site-packages/neutron/agent/linux/external_process.py:126
2018-09-29 07:01:02.869 20579 DEBUG neutron.agent.linux.dhcp [req-264e391b-fea3-45d4-9e28-df98a48c5159 - - - - -] Unable to access /var/lib/neutron/dhcp/9de1d8ca-eddf-4679-8a05-8ac6cc7d062c/interface _get_value_from_conf_file /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:271
2018-09-29 07:01:02.870 20579 DEBUG neutron.agent.linux.dhcp [req-264e391b-fea3-45d4-9e28-df98a48c5159 - - - - -] No interface exists for network 9de1d8ca-eddf-4679-8a05-8ac6cc7d062c destroy /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:1487
2018-09-29 07:01:03.083 20579 DEBUG neutron.agent.linux.utils [req-cd0eacae-2350-406f-8fd4-ffe337105068 - - - - -] Running command (rootwrap daemon): ['ip', '-o', 'netns', 'list'] execute_rootwrap_daemon /usr/lib/python2.7/site-packages/neutron/agent/linux/utils.py:108
2018-09-29 07:01:03.103 20579 DEBUG neutron.agent.linux.dhcp [req-cd0eacae-2350-406f-8fd4-ffe337105068 - - - - -] Namespace already deleted: qdhcp-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c _destroy_namespace_and_port /usr/lib/python2.7/site-packages/neutron/agent/linux/dhcp.py:249
2018-09-29 07:01:03.104 20579 DEBUG oslo_concurrency.lockutils [req-cd0eacae-2350-406f-8fd4-ffe337105068 - - - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 07:01:03.107 20579 DEBUG oslo_concurrency.lockutils [req-51b9eb2b-fc4e-4be5-acca-6b86a6867bdb - - - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 07:01:03.107 20579 DEBUG oslo_concurrency.lockutils [req-51b9eb2b-fc4e-4be5-acca-6b86a6867bdb - - - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 07:01:03.108 20579 DEBUG oslo_concurrency.lockutils [req-51b9eb2b-fc4e-4be5-acca-6b86a6867bdb - - - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 07:01:03.109 20579 DEBUG oslo_concurrency.lockutils [req-51b9eb2b-fc4e-4be5-acca-6b86a6867bdb - - - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 07:01:04.905 20579 DEBUG oslo_concurrency.lockutils [req-64cd7d3c-d758-402f-87ba-88a568241764 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Acquired semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 07:01:04.906 20579 DEBUG oslo_concurrency.lockutils [req-64cd7d3c-d758-402f-87ba-88a568241764 18d1f960831c48728a925f03113105ef 0f250fa08c1944bb994337cb65fd7528 - - -] Releasing semaphore "dhcp-agent-network-lock-9de1d8ca-eddf-4679-8a05-8ac6cc7d062c" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 07:01:13.830 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" acquired by "neutron.agent.linux.external_process._check_child_processes" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 07:01:13.834 20579 DEBUG oslo_concurrency.lockutils [-] Lock "_check_child_processes" released by "neutron.agent.linux.external_process._check_child_processes" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 07:01:32.241 20579 DEBUG neutron.agent.dhcp.agent [req-f50805bf-76db-419f-9c36-eb43d866cb29 - - - - -] resync (9de1d8ca-eddf-4679-8a05-8ac6cc7d062c): [SubnetMismatchForPort(u'Subnet on port 0538d281-b5f1-490a-a31b-775e51e143c3 does not match the requested subnet d4ce5193-91e5-45ae-b5da-10d567168230.',)] _periodic_resync_helper /usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py:256
2018-09-29 07:01:32.242 20579 INFO neutron.agent.dhcp.agent [req-f50805bf-76db-419f-9c36-eb43d866cb29 - - - - -] Synchronizing state
2018-09-29 07:01:33.159 20579 INFO neutron.agent.dhcp.agent [req-2f1ba671-12c7-4a11-8860-eafba4d3acc3 - - - - -] All active networks have been fetched through RPC.
2018-09-29 07:01:33.161 20579 INFO neutron.agent.dhcp.agent [-] Starting network 7fc29900-2b68-444d-aebd-eb83e6248a3d dhcp configuration
2018-09-29 07:01:33.162 20579 INFO neutron.agent.dhcp.agent [-] Finished network 7fc29900-2b68-444d-aebd-eb83e6248a3d dhcp configuration
2018-09-29 07:01:33.163 20579 INFO neutron.agent.dhcp.agent [req-2f1ba671-12c7-4a11-8860-eafba4d3acc3 - - - - -] Synchronizing state complete
