2018-06-28 00:20:46.199 859 DEBUG nova.osapi_compute.wsgi.server [req-26251fc9-51e5-4cc4-918c-e09f59ee2d3e 6dc66ca5b9b04acabc59bdf6487de4e0 71ea52d094344aa8ab5e0e5b41870b26 - default default] (859) accepted ('10.0.20.46', 48260) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:20:46.726 859 DEBUG nova.api.openstack.wsgi [req-011a63e2-c7a4-4c1c-a9e8-98e3881f119f b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Azione: 'create', metodo chiamata: <function version_select at 0x7f8f88ec1848>, corpo: {"keypair": {"public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaKvRokI5t81lBaR5RixXyCWroNDffn1/6QXp6xqOjQc2vp1usrpmRrE5T/8n+hGi9vuaOC8keEkKhSPUUk1QsBl8pf0rzCrWd8LHUe8XrDFGMm92VrC191Y7olsr8DwlP4VAvRbOGufdZK0Xrx97i5R4Mvq7f6aBz47bvE+cEWPPsXnhtGWE4QpK+eZY+aIVDtallAu9O/VCZMHUhXfT91WhBhkkUIFXBCxcddAXlFRBb1nMtn4yKbim0mZ+zbLJ4iWeqOQdorVtJjFZowQt2QVHXOnVv19Tm37K9o0282PUMMrB83JOlPEB4H8tIr6lhJa3Jl2geQ6IC4Rb8z8BL root@localhost.localdomain\n", "name": "tempest-keypair-1530137972"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-06-28 00:20:46.842 859 DEBUG nova.quota [req-011a63e2-c7a4-4c1c-a9e8-98e3881f119f b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Getting quotas for project 05e2815a8542423ab1748094ef6c9f62. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-06-28 00:20:46.859 859 DEBUG nova.quota [req-011a63e2-c7a4-4c1c-a9e8-98e3881f119f b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Getting quotas for user b946f71dca6e4291b1ac0b91e97ca2eb and project 05e2815a8542423ab1748094ef6c9f62. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-06-28 00:20:47.024 859 INFO nova.osapi_compute.wsgi.server [req-011a63e2-c7a4-4c1c-a9e8-98e3881f119f b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "POST /v2.1/05e2815a8542423ab1748094ef6c9f62/os-keypairs HTTP/1.1" status: 200 len: 997 time: 0.8185830
2018-06-28 00:20:54.211 859 DEBUG nova.osapi_compute.wsgi.server [req-011a63e2-c7a4-4c1c-a9e8-98e3881f119f b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] (859) accepted ('10.0.20.46', 48282) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:20:54.724 859 DEBUG nova.api.openstack.wsgi [req-c322cbc8-4bee-42ad-8606-fa54b631e042 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<function version_select at 0x7f8f88da8f50>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:20:54.732 859 WARNING oslo_db.sqlalchemy.utils [req-c322cbc8-4bee-42ad-8606-fa54b631e042 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Unique keys not in sort_keys. The sorting order may be unstable.
2018-06-28 00:20:54.743 859 WARNING oslo_db.sqlalchemy.utils [req-c322cbc8-4bee-42ad-8606-fa54b631e042 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Unique keys not in sort_keys. The sorting order may be unstable.
2018-06-28 00:20:54.757 859 INFO nova.osapi_compute.wsgi.server [req-c322cbc8-4bee-42ad-8606-fa54b631e042 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/os-keypairs HTTP/1.1" status: 200 len: 966 time: 0.5426030
2018-06-28 00:21:04.351 859 DEBUG nova.api.openstack.wsgi [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f8975da90>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:21:04.364 859 DEBUG nova.compute.api [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 6, 27, 22, 16, 18, 86650, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:21:04.389 859 DEBUG oslo_concurrency.lockutils [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:21:04.390 859 DEBUG oslo_concurrency.lockutils [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:21:04.499 859 DEBUG nova.compute.api [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:21:04.500 859 DEBUG nova.compute.api [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Listing 1000 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:21:04.501 859 DEBUG oslo_concurrency.lockutils [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:21:04.502 859 DEBUG oslo_concurrency.lockutils [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:21:04.669 859 DEBUG nova.policy [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'd473e455e3b24776a524d2ea47d6e072', 'roles': [u'ResellerAdmin', u'admin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'0ca3103c90a24980adf86a98ed1a7af3', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:21:04.681 859 INFO nova.osapi_compute.wsgi.server [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] 10.0.20.46 "GET /v2.1/0ca3103c90a24980adf86a98ed1a7af3/servers/detail?all_tenants=True&changes-since=2018-06-27T22%3A16%3A18.086650%2B00%3A00 HTTP/1.1" status: 200 len: 413 time: 0.3707650
2018-06-28 00:22:35.971 861 DEBUG nova.api.openstack.wsgi [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f8975da90>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:22:35.982 861 DEBUG nova.compute.api [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 6, 27, 22, 17, 39, 706319, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:22:36.003 861 DEBUG oslo_concurrency.lockutils [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:22:36.004 861 DEBUG oslo_concurrency.lockutils [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:22:36.446 861 DEBUG nova.compute.api [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:22:36.448 861 DEBUG nova.compute.api [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Listing 1000 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:22:36.450 861 DEBUG oslo_concurrency.lockutils [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:22:36.451 861 DEBUG oslo_concurrency.lockutils [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:22:36.569 861 DEBUG nova.policy [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'd473e455e3b24776a524d2ea47d6e072', 'roles': [u'ResellerAdmin', u'admin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'0ca3103c90a24980adf86a98ed1a7af3', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:22:36.585 861 INFO nova.osapi_compute.wsgi.server [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] 10.0.20.46 "GET /v2.1/0ca3103c90a24980adf86a98ed1a7af3/servers/detail?all_tenants=True&changes-since=2018-06-27T22%3A17%3A39.706319%2B00%3A00 HTTP/1.1" status: 200 len: 413 time: 0.6357090
2018-06-28 00:23:14.288 857 DEBUG nova.osapi_compute.wsgi.server [req-5113df0b-a95e-44d5-9e51-e81f6ee56714 - - - - -] (857) accepted ('10.0.20.46', 51816) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:23:14.310 857 WARNING keystonemiddleware.auth_token [req-5113df0b-a95e-44d5-9e51-e81f6ee56714 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-06-28 00:23:16.498 857 DEBUG nova.api.openstack.wsgi [req-d56d70c5-5011-4e88-a627-f68ac178945d b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f8f89ae0510>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:16.539 857 DEBUG oslo_db.sqlalchemy.engines [req-d56d70c5-5011-4e88-a627-f68ac178945d b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:23:16.625 857 INFO nova.api.openstack.wsgi [req-d56d70c5-5011-4e88-a627-f68ac178945d b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] HTTP exception thrown: Impossibile trovare la tipologia m1.tiny.
2018-06-28 00:23:16.626 857 DEBUG nova.api.openstack.wsgi [req-d56d70c5-5011-4e88-a627-f68ac178945d b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Returning 404 to user: Impossibile trovare la tipologia m1.tiny. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 00:23:16.629 857 INFO nova.osapi_compute.wsgi.server [req-d56d70c5-5011-4e88-a627-f68ac178945d b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/flavors/m1.tiny HTTP/1.1" status: 404 len: 507 time: 2.3319552
2018-06-28 00:23:16.664 857 DEBUG nova.api.openstack.wsgi [req-cdb357a1-0b70-43c7-ae8a-b756bc83069f b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method FlavorsController.index of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f8f89bd4cd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:16.729 857 INFO nova.osapi_compute.wsgi.server [req-cdb357a1-0b70-43c7-ae8a-b756bc83069f b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/flavors HTTP/1.1" status: 200 len: 2106 time: 0.0749578
2018-06-28 00:23:16.763 857 DEBUG nova.api.openstack.wsgi [req-124af817-5dd1-478c-ad71-5ae706fa04c4 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f8f89ae0510>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:16.797 857 INFO nova.osapi_compute.wsgi.server [req-124af817-5dd1-478c-ad71-5ae706fa04c4 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0433991
2018-06-28 00:23:18.108 857 DEBUG nova.api.openstack.wsgi [req-51c9e761-184e-4f33-8f66-34b1ba820757 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Azione: 'create', metodo chiamata: <bound method ServersController.create of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f897f2850>>, corpo: {"server": {"name": "tempest-INSTANCE_SAMPLE-1530137972", "imageRef": "a1f1b252-a9d1-4a4b-aabc-7afab71bce18", "key_name": "tempest-keypair-1530137972", "flavorRef": "1", "max_count": 1, "min_count": 1, "networks": [{"uuid": "b7810ee6-0fce-44c0-ada0-a3035a09c9e4"}], "security_groups": [{"name": "b1b01735-2b85-4b38-b4b2-ad2b606c59e8"}]}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-06-28 00:23:18.231 857 DEBUG oslo_concurrency.lockutils [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:23:18.234 857 DEBUG oslo_concurrency.lockutils [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:23:18.264 857 DEBUG oslo_db.sqlalchemy.engines [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:23:18.289 857 DEBUG oslo_concurrency.lockutils [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:23:18.298 857 DEBUG oslo_concurrency.lockutils [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.009s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:23:18.325 857 DEBUG oslo_db.sqlalchemy.engines [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:23:18.389 857 WARNING nova.image.glance [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] No protocol specified in for api_server 'http://10.0.20.46:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-06-28 00:23:22.281 857 DEBUG nova.network.neutronv2.api [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] validate_networks() for [(u'b7810ee6-0fce-44c0-ada0-a3035a09c9e4', None, None, None)] validate_networks /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1692
2018-06-28 00:23:23.116 857 DEBUG nova.virt.hardware [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] emulator threads policy constraint: None get_emulator_threads_constraint /usr/lib/python2.7/site-packages/nova/virt/hardware.py:1289
2018-06-28 00:23:23.151 857 DEBUG nova.quota [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Getting quotas for project 05e2815a8542423ab1748094ef6c9f62. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-06-28 00:23:23.163 857 DEBUG nova.quota [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Getting quotas for user b946f71dca6e4291b1ac0b91e97ca2eb and project 05e2815a8542423ab1748094ef6c9f62. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-06-28 00:23:23.208 857 DEBUG nova.quota [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Getting quotas for project 05e2815a8542423ab1748094ef6c9f62. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-06-28 00:23:23.217 857 DEBUG nova.quota [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Getting quotas for user b946f71dca6e4291b1ac0b91e97ca2eb and project 05e2815a8542423ab1748094ef6c9f62. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-06-28 00:23:23.262 857 DEBUG nova.quota [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Getting quotas for project 05e2815a8542423ab1748094ef6c9f62. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-06-28 00:23:23.270 857 DEBUG nova.quota [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Getting quotas for user b946f71dca6e4291b1ac0b91e97ca2eb and project 05e2815a8542423ab1748094ef6c9f62. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-06-28 00:23:23.299 857 DEBUG nova.context [req-6fac1194-39c3-4b3e-b3bc-9278efc61235 - - - - -] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),72c9866c-097e-4830-88cc-fbc19314d896(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-06-28 00:23:23.300 857 DEBUG oslo_concurrency.lockutils [req-51c9e761-184e-4f33-8f66-34b1ba820757 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:23:23.301 857 DEBUG oslo_concurrency.lockutils [req-51c9e761-184e-4f33-8f66-34b1ba820757 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:23:23.302 857 DEBUG oslo_concurrency.lockutils [req-51c9e761-184e-4f33-8f66-34b1ba820757 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:23:23.303 857 DEBUG oslo_concurrency.lockutils [req-51c9e761-184e-4f33-8f66-34b1ba820757 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:23:23.639 857 DEBUG nova.quota [req-51c9e761-184e-4f33-8f66-34b1ba820757 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Getting quotas for project 05e2815a8542423ab1748094ef6c9f62. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-06-28 00:23:23.647 857 DEBUG nova.quota [req-51c9e761-184e-4f33-8f66-34b1ba820757 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Getting quotas for user b946f71dca6e4291b1ac0b91e97ca2eb and project 05e2815a8542423ab1748094ef6c9f62. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-06-28 00:23:23.673 857 DEBUG nova.compute.api [req-51c9e761-184e-4f33-8f66-34b1ba820757 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Going to run 1 instances... _provision_instances /usr/lib/python2.7/site-packages/nova/compute/api.py:891
2018-06-28 00:23:23.714 857 DEBUG nova.compute.api [req-51c9e761-184e-4f33-8f66-34b1ba820757 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='a1f1b252-a9d1-4a4b-aabc-7afab71bce18',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _bdm_validate_set_size_and_instance /usr/lib/python2.7/site-packages/nova/compute/api.py:1268
2018-06-28 00:23:23.978 857 INFO nova.osapi_compute.wsgi.server [req-51c9e761-184e-4f33-8f66-34b1ba820757 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "POST /v2.1/05e2815a8542423ab1748094ef6c9f62/servers HTTP/1.1" status: 202 len: 989 time: 5.8885589
2018-06-28 00:23:24.006 857 DEBUG nova.api.openstack.wsgi [req-0d19401a-bc50-4a16-9678-26bc359f973d b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f896fedd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:24.010 857 DEBUG nova.compute.api [req-0d19401a-bc50-4a16-9678-26bc359f973d b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 00:23:24.080 857 DEBUG nova.policy [req-0d19401a-bc50-4a16-9678-26bc359f973d b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:23:24.181 857 INFO nova.osapi_compute.wsgi.server [req-0d19401a-bc50-4a16-9678-26bc359f973d b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/9d619680-997f-49a0-abf8-15ebb8a187f6 HTTP/1.1" status: 200 len: 1857 time: 0.1843879
2018-06-28 00:23:24.241 857 DEBUG nova.api.openstack.wsgi [req-2b1f9fb3-c986-4119-a034-56b7cecc1d45 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f8f89ae0510>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:24.269 857 INFO nova.osapi_compute.wsgi.server [req-2b1f9fb3-c986-4119-a034-56b7cecc1d45 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0363278
2018-06-28 00:23:29.763 859 DEBUG nova.osapi_compute.wsgi.server [req-7cf183b7-ca0e-4fde-ada4-12f77bbff129 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] (859) accepted ('10.0.20.46', 51892) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:23:30.327 859 INFO nova.osapi_compute.wsgi.server [req-ce7d715d-c866-40c7-a009-5b9afaa54f53 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62 HTTP/1.1" status: 404 len: 382 time: 0.5611842
2018-06-28 00:23:30.354 859 DEBUG nova.api.openstack.wsgi [req-9d508eeb-d744-49bc-ba30-5df20d8b01f8 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8f89bd4950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:30.358 859 INFO nova.osapi_compute.wsgi.server [req-9d508eeb-d744-49bc-ba30-5df20d8b01f8 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0158489
2018-06-28 00:23:30.746 859 DEBUG nova.api.openstack.wsgi [req-0f00383f-2ec2-452a-b3aa-3a3fac8f8b93 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f897a8950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:30.756 859 DEBUG nova.compute.api [req-0f00383f-2ec2-452a-b3aa-3a3fac8f8b93 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', u'name': u'tempest-INSTANCE_SAMPLE-1530137972'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:23:30.797 859 DEBUG oslo_concurrency.lockutils [req-0f00383f-2ec2-452a-b3aa-3a3fac8f8b93 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:23:30.798 859 DEBUG oslo_concurrency.lockutils [req-0f00383f-2ec2-452a-b3aa-3a3fac8f8b93 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:23:30.887 859 DEBUG nova.compute.api [req-0f00383f-2ec2-452a-b3aa-3a3fac8f8b93 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:23:30.888 859 DEBUG nova.compute.api [req-0f00383f-2ec2-452a-b3aa-3a3fac8f8b93 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:23:30.890 859 DEBUG oslo_concurrency.lockutils [req-0f00383f-2ec2-452a-b3aa-3a3fac8f8b93 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:23:30.891 859 DEBUG oslo_concurrency.lockutils [req-0f00383f-2ec2-452a-b3aa-3a3fac8f8b93 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:23:31.021 859 INFO nova.osapi_compute.wsgi.server [req-0f00383f-2ec2-452a-b3aa-3a3fac8f8b93 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers?name=tempest-INSTANCE_SAMPLE-1530137972 HTTP/1.1" status: 200 len: 786 time: 0.2937908
2018-06-28 00:23:31.061 859 DEBUG nova.api.openstack.wsgi [req-c23f2566-3267-4e65-9221-e241485b7a76 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f896fedd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:31.067 859 DEBUG nova.compute.api [req-c23f2566-3267-4e65-9221-e241485b7a76 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 00:23:31.196 859 DEBUG nova.policy [req-c23f2566-3267-4e65-9221-e241485b7a76 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:23:32.225 859 INFO nova.osapi_compute.wsgi.server [req-c23f2566-3267-4e65-9221-e241485b7a76 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/9d619680-997f-49a0-abf8-15ebb8a187f6 HTTP/1.1" status: 200 len: 2242 time: 1.1796660
2018-06-28 00:23:43.943 866 DEBUG nova.osapi_compute.wsgi.server [req-5113df0b-a95e-44d5-9e51-e81f6ee56714 - - - - -] (866) accepted ('10.0.20.46', 51924) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:23:43.966 866 WARNING keystonemiddleware.auth_token [req-5113df0b-a95e-44d5-9e51-e81f6ee56714 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-06-28 00:23:46.325 866 INFO nova.osapi_compute.wsgi.server [req-4cbe6012-4b71-4eb8-9c0e-45790af11b44 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62 HTTP/1.1" status: 404 len: 382 time: 2.3721261
2018-06-28 00:23:46.358 866 DEBUG nova.api.openstack.wsgi [req-e487241c-4c2e-4ccb-839a-892c5d37aa2c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8f89bd4950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:46.362 866 INFO nova.osapi_compute.wsgi.server [req-e487241c-4c2e-4ccb-839a-892c5d37aa2c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0233099
2018-06-28 00:23:46.704 866 DEBUG nova.api.openstack.wsgi [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f897a8950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:46.723 866 DEBUG nova.compute.api [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', u'name': u'tempest-INSTANCE_SAMPLE-1530137972'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:23:46.772 866 DEBUG oslo_db.sqlalchemy.engines [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:23:46.854 866 DEBUG oslo_concurrency.lockutils [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:23:46.858 866 DEBUG oslo_concurrency.lockutils [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:23:46.888 866 DEBUG oslo_db.sqlalchemy.engines [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:23:47.026 866 DEBUG nova.compute.api [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),72c9866c-097e-4830-88cc-fbc19314d896(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-06-28 00:23:47.028 866 DEBUG nova.compute.api [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:23:47.029 866 DEBUG nova.compute.api [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:23:47.031 866 DEBUG oslo_concurrency.lockutils [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:23:47.041 866 DEBUG oslo_concurrency.lockutils [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.010s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:23:47.074 866 DEBUG oslo_db.sqlalchemy.engines [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:23:47.211 866 INFO nova.osapi_compute.wsgi.server [req-4ef7e6e1-08e7-48f1-8674-23354dbdaa94 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers?name=tempest-INSTANCE_SAMPLE-1530137972 HTTP/1.1" status: 200 len: 786 time: 0.5198269
2018-06-28 00:23:47.245 866 DEBUG nova.api.openstack.wsgi [req-0dafa25f-78e2-4e9a-b6a2-e872adde96dd b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f896fedd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:47.254 866 DEBUG nova.compute.api [req-0dafa25f-78e2-4e9a-b6a2-e872adde96dd b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 00:23:47.376 866 DEBUG nova.policy [req-0dafa25f-78e2-4e9a-b6a2-e872adde96dd b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:23:48.609 866 INFO nova.osapi_compute.wsgi.server [req-0dafa25f-78e2-4e9a-b6a2-e872adde96dd b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/9d619680-997f-49a0-abf8-15ebb8a187f6 HTTP/1.1" status: 200 len: 2242 time: 1.3789921
2018-06-28 00:23:59.476 866 DEBUG nova.osapi_compute.wsgi.server [req-0dafa25f-78e2-4e9a-b6a2-e872adde96dd b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] (866) accepted ('10.0.20.46', 51986) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:23:59.815 866 INFO nova.osapi_compute.wsgi.server [req-9fe56693-65d9-4713-8931-73629df27be3 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62 HTTP/1.1" status: 404 len: 382 time: 0.3363550
2018-06-28 00:23:59.843 866 DEBUG nova.api.openstack.wsgi [req-4ab8ae2b-8e1e-462b-a95d-43945d43f5cc b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8f89bd4950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:23:59.846 866 INFO nova.osapi_compute.wsgi.server [req-4ab8ae2b-8e1e-462b-a95d-43945d43f5cc b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0155110
2018-06-28 00:24:00.100 866 DEBUG nova.api.openstack.wsgi [req-7828b40f-207d-4ac3-a4ed-1c3e2cd87f29 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f897a8950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:24:00.107 866 DEBUG nova.compute.api [req-7828b40f-207d-4ac3-a4ed-1c3e2cd87f29 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', u'name': u'tempest-INSTANCE_SAMPLE-1530137972'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:24:00.538 866 DEBUG oslo_concurrency.lockutils [req-7828b40f-207d-4ac3-a4ed-1c3e2cd87f29 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:24:00.539 866 DEBUG oslo_concurrency.lockutils [req-7828b40f-207d-4ac3-a4ed-1c3e2cd87f29 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:24:00.614 866 DEBUG nova.compute.api [req-7828b40f-207d-4ac3-a4ed-1c3e2cd87f29 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:24:00.615 866 DEBUG nova.compute.api [req-7828b40f-207d-4ac3-a4ed-1c3e2cd87f29 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:24:00.617 866 DEBUG oslo_concurrency.lockutils [req-7828b40f-207d-4ac3-a4ed-1c3e2cd87f29 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:24:00.618 866 DEBUG oslo_concurrency.lockutils [req-7828b40f-207d-4ac3-a4ed-1c3e2cd87f29 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:24:00.710 866 INFO nova.osapi_compute.wsgi.server [req-7828b40f-207d-4ac3-a4ed-1c3e2cd87f29 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers?name=tempest-INSTANCE_SAMPLE-1530137972 HTTP/1.1" status: 200 len: 786 time: 0.6204090
2018-06-28 00:24:00.748 866 DEBUG nova.api.openstack.wsgi [req-4356c587-09bf-4f1e-827e-3939f28f09cf b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f896fedd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:24:00.754 866 DEBUG nova.compute.api [req-4356c587-09bf-4f1e-827e-3939f28f09cf b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 00:24:00.849 866 DEBUG nova.policy [req-4356c587-09bf-4f1e-827e-3939f28f09cf b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:24:01.715 866 INFO nova.osapi_compute.wsgi.server [req-4356c587-09bf-4f1e-827e-3939f28f09cf b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/9d619680-997f-49a0-abf8-15ebb8a187f6 HTTP/1.1" status: 200 len: 2242 time: 0.9809749
2018-06-28 00:24:14.768 863 DEBUG nova.osapi_compute.wsgi.server [req-5113df0b-a95e-44d5-9e51-e81f6ee56714 - - - - -] (863) accepted ('10.0.20.46', 53044) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:24:14.785 863 WARNING keystonemiddleware.auth_token [req-5113df0b-a95e-44d5-9e51-e81f6ee56714 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-06-28 00:24:16.797 863 INFO nova.osapi_compute.wsgi.server [req-0bc3e4fd-d66e-45c9-8b1c-3b95c6ad88fd b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62 HTTP/1.1" status: 404 len: 382 time: 2.0200360
2018-06-28 00:24:16.826 863 DEBUG nova.api.openstack.wsgi [req-2590ea26-b1c5-4694-a2f7-dfde4117f3ed b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8f89bd4950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:24:16.830 863 INFO nova.osapi_compute.wsgi.server [req-2590ea26-b1c5-4694-a2f7-dfde4117f3ed b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0183110
2018-06-28 00:24:17.144 863 DEBUG nova.api.openstack.wsgi [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f897a8950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:24:17.160 863 DEBUG nova.compute.api [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', u'name': u'tempest-INSTANCE_SAMPLE-1530137972'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:24:17.202 863 DEBUG oslo_db.sqlalchemy.engines [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:24:17.268 863 DEBUG oslo_concurrency.lockutils [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:24:17.272 863 DEBUG oslo_concurrency.lockutils [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:24:17.303 863 DEBUG oslo_db.sqlalchemy.engines [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:24:17.433 863 DEBUG nova.compute.api [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),72c9866c-097e-4830-88cc-fbc19314d896(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-06-28 00:24:17.436 863 DEBUG nova.compute.api [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:24:17.437 863 DEBUG nova.compute.api [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:24:17.439 863 DEBUG oslo_concurrency.lockutils [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:24:17.447 863 DEBUG oslo_concurrency.lockutils [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.008s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:24:17.476 863 DEBUG oslo_db.sqlalchemy.engines [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:24:17.614 863 INFO nova.osapi_compute.wsgi.server [req-322aaaa2-8d56-43bc-a69f-e1655fcca7a2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers?name=tempest-INSTANCE_SAMPLE-1530137972 HTTP/1.1" status: 200 len: 786 time: 0.4906950
2018-06-28 00:24:17.651 863 DEBUG nova.api.openstack.wsgi [req-eb438875-1ec3-41e4-a5a1-e49cdcc6ca90 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f896fedd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:24:17.660 863 DEBUG nova.compute.api [req-eb438875-1ec3-41e4-a5a1-e49cdcc6ca90 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 00:24:17.811 863 DEBUG nova.policy [req-eb438875-1ec3-41e4-a5a1-e49cdcc6ca90 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:24:19.071 863 INFO nova.osapi_compute.wsgi.server [req-eb438875-1ec3-41e4-a5a1-e49cdcc6ca90 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/9d619680-997f-49a0-abf8-15ebb8a187f6 HTTP/1.1" status: 200 len: 2242 time: 1.4363570
2018-06-28 00:24:34.136 861 DEBUG nova.osapi_compute.wsgi.server [req-81102a63-8196-4e81-adce-e4a18572b0d0 d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] (861) accepted ('10.0.20.46', 53080) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:24:34.693 861 INFO nova.osapi_compute.wsgi.server [req-1db1ed3b-e629-47d5-a323-c13531ec6146 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62 HTTP/1.1" status: 404 len: 382 time: 0.5523748
2018-06-28 00:24:34.722 861 DEBUG nova.api.openstack.wsgi [req-7d2c6b5f-9ca4-4b2c-8fec-0ea4c72ae905 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8f89bd4950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:24:34.726 861 INFO nova.osapi_compute.wsgi.server [req-7d2c6b5f-9ca4-4b2c-8fec-0ea4c72ae905 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0179329
2018-06-28 00:24:35.063 861 DEBUG nova.api.openstack.wsgi [req-c93dbc9d-b0db-4afc-b8d5-811bce9e3ae3 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f897a8950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:24:35.072 861 DEBUG nova.compute.api [req-c93dbc9d-b0db-4afc-b8d5-811bce9e3ae3 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', u'name': u'tempest-INSTANCE_SAMPLE-1530137972'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:24:35.117 861 DEBUG oslo_concurrency.lockutils [req-c93dbc9d-b0db-4afc-b8d5-811bce9e3ae3 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:24:35.118 861 DEBUG oslo_concurrency.lockutils [req-c93dbc9d-b0db-4afc-b8d5-811bce9e3ae3 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:24:35.231 861 DEBUG nova.compute.api [req-c93dbc9d-b0db-4afc-b8d5-811bce9e3ae3 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:24:35.233 861 DEBUG nova.compute.api [req-c93dbc9d-b0db-4afc-b8d5-811bce9e3ae3 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:24:35.235 861 DEBUG oslo_concurrency.lockutils [req-c93dbc9d-b0db-4afc-b8d5-811bce9e3ae3 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:24:35.236 861 DEBUG oslo_concurrency.lockutils [req-c93dbc9d-b0db-4afc-b8d5-811bce9e3ae3 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:24:35.379 861 INFO nova.osapi_compute.wsgi.server [req-c93dbc9d-b0db-4afc-b8d5-811bce9e3ae3 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers?name=tempest-INSTANCE_SAMPLE-1530137972 HTTP/1.1" status: 200 len: 786 time: 0.3368888
2018-06-28 00:24:35.419 861 DEBUG nova.api.openstack.wsgi [req-0b01ed78-b632-4b17-acb2-a1c1d124530a b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f896fedd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:24:35.426 861 DEBUG nova.compute.api [req-0b01ed78-b632-4b17-acb2-a1c1d124530a b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 00:24:35.553 861 DEBUG nova.policy [req-0b01ed78-b632-4b17-acb2-a1c1d124530a b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:24:36.604 861 INFO nova.osapi_compute.wsgi.server [req-0b01ed78-b632-4b17-acb2-a1c1d124530a b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/9d619680-997f-49a0-abf8-15ebb8a187f6 HTTP/1.1" status: 200 len: 2242 time: 1.2024190
2018-06-28 00:25:13.237 861 DEBUG nova.osapi_compute.wsgi.server [req-0b01ed78-b632-4b17-acb2-a1c1d124530a b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] (861) accepted ('10.0.20.46', 54208) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:25:13.676 861 DEBUG nova.api.openstack.wsgi [req-34505a63-cf1d-4f85-a1e1-30fce25e41b9 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f896fedd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:25:13.680 861 DEBUG nova.compute.api [req-34505a63-cf1d-4f85-a1e1-30fce25e41b9 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Failed to fetch instance by id tempest-INSTANCE_SAMPLE-1530137972 get /usr/lib/python2.7/site-packages/nova/compute/api.py:2329
2018-06-28 00:25:13.681 861 INFO nova.api.openstack.wsgi [req-34505a63-cf1d-4f85-a1e1-30fce25e41b9 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] HTTP exception thrown: Impossibile trovare l'istanza tempest-INSTANCE_SAMPLE-1530137972.
2018-06-28 00:25:13.682 861 DEBUG nova.api.openstack.wsgi [req-34505a63-cf1d-4f85-a1e1-30fce25e41b9 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Returning 404 to user: Impossibile trovare l'istanza tempest-INSTANCE_SAMPLE-1530137972. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 00:25:13.684 861 INFO nova.osapi_compute.wsgi.server [req-34505a63-cf1d-4f85-a1e1-30fce25e41b9 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/tempest-INSTANCE_SAMPLE-1530137972 HTTP/1.1" status: 404 len: 532 time: 0.4451220
2018-06-28 00:25:13.712 861 DEBUG nova.api.openstack.wsgi [req-5854bfcc-6d13-4b52-988f-a6b944d27383 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f897a8950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:25:13.718 861 DEBUG nova.compute.api [req-5854bfcc-6d13-4b52-988f-a6b944d27383 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', u'name': u'tempest-INSTANCE_SAMPLE-1530137972'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:25:13.746 861 DEBUG oslo_concurrency.lockutils [req-5854bfcc-6d13-4b52-988f-a6b944d27383 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:25:13.748 861 DEBUG oslo_concurrency.lockutils [req-5854bfcc-6d13-4b52-988f-a6b944d27383 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:25:13.822 861 DEBUG nova.compute.api [req-5854bfcc-6d13-4b52-988f-a6b944d27383 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:25:13.823 861 DEBUG nova.compute.api [req-5854bfcc-6d13-4b52-988f-a6b944d27383 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:25:13.825 861 DEBUG oslo_concurrency.lockutils [req-5854bfcc-6d13-4b52-988f-a6b944d27383 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:25:13.826 861 DEBUG oslo_concurrency.lockutils [req-5854bfcc-6d13-4b52-988f-a6b944d27383 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:25:13.906 861 INFO nova.osapi_compute.wsgi.server [req-5854bfcc-6d13-4b52-988f-a6b944d27383 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers?name=tempest-INSTANCE_SAMPLE-1530137972 HTTP/1.1" status: 200 len: 784 time: 0.2047200
2018-06-28 00:25:13.934 861 DEBUG nova.api.openstack.wsgi [req-e790ff21-f98a-4bc6-bb65-c5de6dd70675 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f896fedd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:25:13.940 861 DEBUG nova.compute.api [req-e790ff21-f98a-4bc6-bb65-c5de6dd70675 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 00:25:13.998 861 DEBUG nova.policy [req-e790ff21-f98a-4bc6-bb65-c5de6dd70675 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:25:14.696 861 INFO nova.osapi_compute.wsgi.server [req-e790ff21-f98a-4bc6-bb65-c5de6dd70675 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/9d619680-997f-49a0-abf8-15ebb8a187f6 HTTP/1.1" status: 200 len: 1857 time: 0.7715971
2018-06-28 00:25:14.727 861 DEBUG nova.api.openstack.wsgi [req-6b9badaa-ce21-48df-8c1e-39d7b5be9d99 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Azione: 'action', metodo chiamata: <function version_select at 0x7f8f897207d0>, corpo: {"addFloatingIp": {"address": "172.24.4.11"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-06-28 00:25:14.735 861 DEBUG nova.compute.api [req-6b9badaa-ce21-48df-8c1e-39d7b5be9d99 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 00:25:14.766 861 WARNING nova.api.openstack.compute.floating_ips [req-6b9badaa-ce21-48df-8c1e-39d7b5be9d99 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Info cache is InstanceInfoCache(created_at=<?>,deleted=<?>,deleted_at=<?>,instance_uuid=9d619680-997f-49a0-abf8-15ebb8a187f6,network_info=NetworkModel(),updated_at=<?>) during associate with no nw_info cache
2018-06-28 00:25:14.767 861 INFO nova.api.openstack.wsgi [req-6b9badaa-ce21-48df-8c1e-39d7b5be9d99 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] HTTP exception thrown: Instance network is not ready yet
2018-06-28 00:25:14.768 861 DEBUG nova.api.openstack.wsgi [req-6b9badaa-ce21-48df-8c1e-39d7b5be9d99 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Returning 400 to user: Instance network is not ready yet __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 00:25:14.770 861 INFO nova.osapi_compute.wsgi.server [req-6b9badaa-ce21-48df-8c1e-39d7b5be9d99 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "POST /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/9d619680-997f-49a0-abf8-15ebb8a187f6/action HTTP/1.1" status: 400 len: 499 time: 0.0568452
2018-06-28 00:25:24.541 861 DEBUG nova.osapi_compute.wsgi.server [req-6b9badaa-ce21-48df-8c1e-39d7b5be9d99 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] (861) accepted ('10.0.20.46', 54238) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:25:24.995 861 INFO nova.osapi_compute.wsgi.server [req-15587897-e773-4664-93f0-819649dd3390 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62 HTTP/1.1" status: 404 len: 382 time: 0.4513578
2018-06-28 00:25:25.024 861 DEBUG nova.api.openstack.wsgi [req-67fa28db-2531-425d-a5f9-1e8ff7aa29d2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7f8f89bd4950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:25:25.027 861 INFO nova.osapi_compute.wsgi.server [req-67fa28db-2531-425d-a5f9-1e8ff7aa29d2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0158560
2018-06-28 00:25:25.303 861 DEBUG nova.api.openstack.wsgi [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f8975da90>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:25:25.310 861 DEBUG nova.compute.api [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:25:25.340 861 DEBUG oslo_concurrency.lockutils [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:25:25.341 861 DEBUG oslo_concurrency.lockutils [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:25:25.411 861 DEBUG nova.compute.api [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:25:25.412 861 DEBUG nova.compute.api [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:25:25.413 861 DEBUG oslo_concurrency.lockutils [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:25:25.414 861 DEBUG oslo_concurrency.lockutils [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:25:25.566 861 DEBUG nova.policy [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:25:26.304 861 INFO nova.osapi_compute.wsgi.server [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/detail HTTP/1.1" status: 200 len: 2245 time: 1.0132921
2018-06-28 00:25:50.403 860 DEBUG nova.osapi_compute.wsgi.server [req-5113df0b-a95e-44d5-9e51-e81f6ee56714 - - - - -] (860) accepted ('10.0.20.46', 54326) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:25:50.426 860 WARNING keystonemiddleware.auth_token [req-5113df0b-a95e-44d5-9e51-e81f6ee56714 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-06-28 00:25:52.148 860 DEBUG nova.api.openstack.wsgi [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f8975da90>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:25:52.162 860 DEBUG nova.compute.api [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:25:52.212 860 DEBUG oslo_db.sqlalchemy.engines [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:25:52.279 860 DEBUG oslo_concurrency.lockutils [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:25:52.283 860 DEBUG oslo_concurrency.lockutils [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:25:52.304 860 DEBUG oslo_db.sqlalchemy.engines [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:25:52.448 860 DEBUG nova.compute.api [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),72c9866c-097e-4830-88cc-fbc19314d896(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-06-28 00:25:52.450 860 DEBUG nova.compute.api [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:25:52.450 860 DEBUG nova.compute.api [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:25:52.451 860 DEBUG oslo_concurrency.lockutils [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:25:52.457 860 DEBUG oslo_concurrency.lockutils [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.005s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:25:52.491 860 DEBUG oslo_db.sqlalchemy.engines [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 00:25:52.675 860 DEBUG nova.policy [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:25:54.047 860 INFO nova.osapi_compute.wsgi.server [req-c20b555f-9cd6-4d93-87a9-9b593dafcf5c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/detail HTTP/1.1" status: 200 len: 1860 time: 3.6346600
2018-06-28 00:26:04.759 857 DEBUG nova.osapi_compute.wsgi.server [req-2b1f9fb3-c986-4119-a034-56b7cecc1d45 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] (857) accepted ('10.0.20.46', 54392) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:26:05.281 857 DEBUG nova.api.openstack.wsgi [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f8975da90>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:26:05.290 857 DEBUG nova.compute.api [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:26:05.325 857 DEBUG oslo_concurrency.lockutils [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:26:05.326 857 DEBUG oslo_concurrency.lockutils [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:26:05.465 857 DEBUG nova.compute.api [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),72c9866c-097e-4830-88cc-fbc19314d896(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-06-28 00:26:05.466 857 DEBUG nova.compute.api [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:26:05.467 857 DEBUG nova.compute.api [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:26:05.468 857 DEBUG oslo_concurrency.lockutils [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:26:05.469 857 DEBUG oslo_concurrency.lockutils [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:26:05.633 857 DEBUG nova.policy [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:26:05.766 859 DEBUG nova.api.openstack.wsgi [req-84fe24cb-ad3c-44f3-ae14-81b15b7538ce d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f8975da90>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:26:05.777 859 DEBUG nova.compute.api [req-84fe24cb-ad3c-44f3-ae14-81b15b7538ce d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 6, 27, 22, 21, 4, 686233, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:26:05.802 859 DEBUG oslo_concurrency.lockutils [req-84fe24cb-ad3c-44f3-ae14-81b15b7538ce d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:26:05.803 859 DEBUG oslo_concurrency.lockutils [req-84fe24cb-ad3c-44f3-ae14-81b15b7538ce d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:26:05.883 859 DEBUG nova.compute.api [req-84fe24cb-ad3c-44f3-ae14-81b15b7538ce d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:26:05.884 859 DEBUG nova.compute.api [req-84fe24cb-ad3c-44f3-ae14-81b15b7538ce d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:26:05.886 859 DEBUG oslo_concurrency.lockutils [req-84fe24cb-ad3c-44f3-ae14-81b15b7538ce d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:26:05.886 859 DEBUG oslo_concurrency.lockutils [req-84fe24cb-ad3c-44f3-ae14-81b15b7538ce d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:26:06.059 859 DEBUG nova.policy [req-84fe24cb-ad3c-44f3-ae14-81b15b7538ce d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'd473e455e3b24776a524d2ea47d6e072', 'roles': [u'ResellerAdmin', u'admin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'0ca3103c90a24980adf86a98ed1a7af3', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:26:06.263 857 INFO nova.osapi_compute.wsgi.server [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/detail HTTP/1.1" status: 200 len: 1860 time: 1.4997439
2018-06-28 00:26:06.698 859 INFO nova.osapi_compute.wsgi.server [req-84fe24cb-ad3c-44f3-ae14-81b15b7538ce d473e455e3b24776a524d2ea47d6e072 0ca3103c90a24980adf86a98ed1a7af3 - default default] 10.0.20.46 "GET /v2.1/0ca3103c90a24980adf86a98ed1a7af3/servers/detail?all_tenants=True&changes-since=2018-06-27T22%3A21%3A04.686233%2B00%3A00 HTTP/1.1" status: 200 len: 1860 time: 1.4533861
2018-06-28 00:26:19.779 861 DEBUG nova.osapi_compute.wsgi.server [req-acc08590-14c7-45c0-910e-908f74dc7be2 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] (861) accepted ('10.0.20.46', 55458) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:26:20.467 861 DEBUG nova.api.openstack.wsgi [req-9a611c00-efbf-4601-b5aa-3f5713298945 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f8975da90>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:26:20.481 861 DEBUG nova.compute.api [req-9a611c00-efbf-4601-b5aa-3f5713298945 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:26:20.526 861 DEBUG oslo_concurrency.lockutils [req-9a611c00-efbf-4601-b5aa-3f5713298945 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:26:20.527 861 DEBUG oslo_concurrency.lockutils [req-9a611c00-efbf-4601-b5aa-3f5713298945 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:26:20.670 861 DEBUG nova.compute.api [req-9a611c00-efbf-4601-b5aa-3f5713298945 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:26:20.671 861 DEBUG nova.compute.api [req-9a611c00-efbf-4601-b5aa-3f5713298945 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:26:20.673 861 DEBUG oslo_concurrency.lockutils [req-9a611c00-efbf-4601-b5aa-3f5713298945 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:26:20.674 861 DEBUG oslo_concurrency.lockutils [req-9a611c00-efbf-4601-b5aa-3f5713298945 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:26:20.878 861 DEBUG nova.policy [req-9a611c00-efbf-4601-b5aa-3f5713298945 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:26:21.679 861 INFO nova.osapi_compute.wsgi.server [req-9a611c00-efbf-4601-b5aa-3f5713298945 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/detail HTTP/1.1" status: 200 len: 1860 time: 1.8938911
2018-06-28 00:26:31.969 857 DEBUG nova.osapi_compute.wsgi.server [req-88ca95ea-4549-4be6-9a22-c30db1a16306 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] (857) accepted ('10.0.20.46', 55482) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 00:26:32.580 857 DEBUG nova.api.openstack.wsgi [req-f0259223-ba12-4a17-aad6-ca38d4f7b194 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f896fedd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:26:32.584 857 DEBUG nova.compute.api [req-f0259223-ba12-4a17-aad6-ca38d4f7b194 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Failed to fetch instance by id tempest-INSTANCE_SAMPLE-1530137972 get /usr/lib/python2.7/site-packages/nova/compute/api.py:2329
2018-06-28 00:26:32.585 857 INFO nova.api.openstack.wsgi [req-f0259223-ba12-4a17-aad6-ca38d4f7b194 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] HTTP exception thrown: Impossibile trovare l'istanza tempest-INSTANCE_SAMPLE-1530137972.
2018-06-28 00:26:32.586 857 DEBUG nova.api.openstack.wsgi [req-f0259223-ba12-4a17-aad6-ca38d4f7b194 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Returning 404 to user: Impossibile trovare l'istanza tempest-INSTANCE_SAMPLE-1530137972. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 00:26:32.587 857 INFO nova.osapi_compute.wsgi.server [req-f0259223-ba12-4a17-aad6-ca38d4f7b194 b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/tempest-INSTANCE_SAMPLE-1530137972 HTTP/1.1" status: 404 len: 532 time: 0.6155500
2018-06-28 00:26:32.626 857 DEBUG nova.api.openstack.wsgi [req-feffdea7-622e-4fa5-8a6e-960212dfb42c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f897a8950>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:26:32.636 857 DEBUG nova.compute.api [req-feffdea7-622e-4fa5-8a6e-960212dfb42c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Searching by: {'deleted': False, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', u'name': u'tempest-INSTANCE_SAMPLE-1530137972'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 00:26:32.674 857 DEBUG oslo_concurrency.lockutils [req-feffdea7-622e-4fa5-8a6e-960212dfb42c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:26:32.676 857 DEBUG oslo_concurrency.lockutils [req-feffdea7-622e-4fa5-8a6e-960212dfb42c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:26:32.751 857 DEBUG nova.compute.api [req-feffdea7-622e-4fa5-8a6e-960212dfb42c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 00:26:32.754 857 DEBUG nova.compute.api [req-feffdea7-622e-4fa5-8a6e-960212dfb42c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Listing 999 instances in cell 72c9866c-097e-4830-88cc-fbc19314d896(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 00:26:32.756 857 DEBUG oslo_concurrency.lockutils [req-feffdea7-622e-4fa5-8a6e-960212dfb42c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 00:26:32.758 857 DEBUG oslo_concurrency.lockutils [req-feffdea7-622e-4fa5-8a6e-960212dfb42c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 00:26:32.884 857 INFO nova.osapi_compute.wsgi.server [req-feffdea7-622e-4fa5-8a6e-960212dfb42c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers?name=tempest-INSTANCE_SAMPLE-1530137972 HTTP/1.1" status: 200 len: 784 time: 0.2731841
2018-06-28 00:26:32.920 857 DEBUG nova.api.openstack.wsgi [req-f3629a08-e28f-4500-a8ff-8a2bb56efc9c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7f8f896fedd0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 00:26:32.925 857 DEBUG nova.compute.api [req-f3629a08-e28f-4500-a8ff-8a2bb56efc9c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 00:26:33.011 857 DEBUG nova.policy [req-f3629a08-e28f-4500-a8ff-8a2bb56efc9c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'b946f71dca6e4291b1ac0b91e97ca2eb', 'roles': [u'admin'], 'user_domain_id': u'54bea3aadc5044579351ab6f337f5e72', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'05e2815a8542423ab1748094ef6c9f62', 'project_domain_id': u'54bea3aadc5044579351ab6f337f5e72'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 00:26:33.678 857 INFO nova.osapi_compute.wsgi.server [req-f3629a08-e28f-4500-a8ff-8a2bb56efc9c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "GET /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/9d619680-997f-49a0-abf8-15ebb8a187f6 HTTP/1.1" status: 200 len: 1857 time: 0.7719731
2018-06-28 00:26:34.635 857 DEBUG nova.api.openstack.wsgi [req-eb399da1-602e-46b6-877c-9d056ae7085c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Azione: 'create', metodo chiamata: <bound method VolumeAttachmentController.create of <nova.api.openstack.compute.volumes.VolumeAttachmentController object at 0x7f8f895dce10>>, corpo: {"volumeAttachment": {"device": "/dev/vdb", "volumeId": "96da85cd-2fd7-4fbb-9719-5c30ebb39567"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-06-28 00:26:34.646 857 DEBUG nova.compute.api [req-eb399da1-602e-46b6-877c-9d056ae7085c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] [instance: 9d619680-997f-49a0-abf8-15ebb8a187f6] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 00:26:34.696 857 INFO nova.api.openstack.wsgi [req-eb399da1-602e-46b6-877c-9d056ae7085c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] HTTP exception thrown: Impossibile 'attach_volume' l'istanza 9d619680-997f-49a0-abf8-15ebb8a187f6 mentre si trova in vm_state building
2018-06-28 00:26:34.697 857 DEBUG nova.api.openstack.wsgi [req-eb399da1-602e-46b6-877c-9d056ae7085c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] Returning 409 to user: Impossibile 'attach_volume' l'istanza 9d619680-997f-49a0-abf8-15ebb8a187f6 mentre si trova in vm_state building __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 00:26:34.700 857 INFO nova.osapi_compute.wsgi.server [req-eb399da1-602e-46b6-877c-9d056ae7085c b946f71dca6e4291b1ac0b91e97ca2eb 05e2815a8542423ab1748094ef6c9f62 - 54bea3aadc5044579351ab6f337f5e72 54bea3aadc5044579351ab6f337f5e72] 10.0.20.46 "POST /v2.1/05e2815a8542423ab1748094ef6c9f62/servers/9d619680-997f-49a0-abf8-15ebb8a187f6/os-volume_attachments HTTP/1.1" status: 409 len: 583 time: 0.0819578
