2018-09-29 12:31:18.294 8466 DEBUG nova.osapi_compute.wsgi.server [req-37a9fcc8-6ded-4898-bd9c-11130f52a701 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] (8466) accepted ('10.0.20.25', 37720) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:31:18.881 8466 DEBUG nova.api.openstack.wsgi [req-6e459ec3-41e3-4304-b4f3-1c16362cd002 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Action: 'create', calling method: <function version_select at 0x7fb23d9f9320>, body: {"keypair": {"public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwh1BhXOxOhi1OsUvq0wGQUTISPk7mQW9cIJJyNoguikFhXE2kSs1GaJWgdrbntAYG10FpRIB/s0qgy6HDUT7dJ2T3qyhudAi4Z/HY7RH4yQclGt1Lf8M8AXDrSgKbomVx8k2oBHkdVkDVQU1mN4NikPADFUUpT5YKhFwIBLFyBUf+RtHyPXw2HY5ZXDiNvXD/vC3N60VwDDdxtrbkJoz/AtHjffqemmYCA26AswwGLmakyM+2b+uLIxwfCUtF1XN25v1yq62xZWeDj75LieToATA7BaTLKOA7wolLvbVTwLWhzvRifuZh7IzctIlCFLLJN2W9CY9wHwLbp6GCzH3f root@localhost.localdomain\n", "name": "tempest-keypair-1538238605"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-29 12:31:19.019 8466 DEBUG nova.quota [req-6e459ec3-41e3-4304-b4f3-1c16362cd002 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Getting quotas for project b7cb5a03bd1b45069394c794112dd4ee. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-29 12:31:19.031 8466 DEBUG nova.quota [req-6e459ec3-41e3-4304-b4f3-1c16362cd002 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Getting quotas for user be1a19cb07964dfe8835c001412bfa45 and project b7cb5a03bd1b45069394c794112dd4ee. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-29 12:31:19.182 8466 INFO nova.osapi_compute.wsgi.server [req-6e459ec3-41e3-4304-b4f3-1c16362cd002 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "POST /v2.1/b7cb5a03bd1b45069394c794112dd4ee/os-keypairs HTTP/1.1" status: 200 len: 997 time: 0.8810151
2018-09-29 12:31:27.626 8466 DEBUG nova.osapi_compute.wsgi.server [req-6e459ec3-41e3-4304-b4f3-1c16362cd002 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] (8466) accepted ('10.0.20.25', 37748) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:31:28.176 8466 DEBUG nova.api.openstack.wsgi [req-481116c6-2c97-4dfa-b4be-e882d8c5b204 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<function version_select at 0x7fb23d8d3e60>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:31:28.181 8466 WARNING oslo_db.sqlalchemy.utils [req-481116c6-2c97-4dfa-b4be-e882d8c5b204 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Unique keys not in sort_keys. The sorting order may be unstable.
2018-09-29 12:31:28.195 8466 WARNING oslo_db.sqlalchemy.utils [req-481116c6-2c97-4dfa-b4be-e882d8c5b204 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Unique keys not in sort_keys. The sorting order may be unstable.
2018-09-29 12:31:28.207 8466 INFO nova.osapi_compute.wsgi.server [req-481116c6-2c97-4dfa-b4be-e882d8c5b204 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/os-keypairs HTTP/1.1" status: 200 len: 966 time: 0.5794790
2018-09-29 12:32:32.693 8466 DEBUG nova.api.openstack.wsgi [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e21b690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:32:32.699 8466 DEBUG nova.compute.api [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 9, 29, 16, 27, 33, 520261, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-29 12:32:32.721 8466 DEBUG oslo_concurrency.lockutils [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:32:32.724 8466 DEBUG oslo_concurrency.lockutils [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:32:32.837 8466 DEBUG nova.compute.api [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-29 12:32:32.839 8466 DEBUG nova.compute.api [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-29 12:32:32.841 8466 DEBUG oslo_concurrency.lockutils [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:32:32.842 8466 DEBUG oslo_concurrency.lockutils [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:32:32.975 8466 DEBUG nova.policy [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'bae51265fb0f4505a811a9fab7e142f1', 'roles': [u'ResellerAdmin', u'admin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'671ea1986554476bbcaa620e00697d23', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-29 12:32:32.981 8466 INFO nova.osapi_compute.wsgi.server [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] 10.0.20.25 "GET /v2.1/671ea1986554476bbcaa620e00697d23/servers/detail?all_tenants=True&changes-since=2018-09-29T16%3A27%3A33.520261%2B00%3A00 HTTP/1.1" status: 200 len: 413 time: 0.3052309
2018-09-29 12:32:42.335 8463 DEBUG nova.api.openstack.wsgi [req-841083a7-dcd9-421c-bc01-49a97b19ef43 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e21b690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:32:42.344 8463 DEBUG nova.compute.api [req-841083a7-dcd9-421c-bc01-49a97b19ef43 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 9, 29, 16, 27, 42, 17617, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-29 12:32:42.370 8463 DEBUG oslo_concurrency.lockutils [req-841083a7-dcd9-421c-bc01-49a97b19ef43 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:32:42.371 8463 DEBUG oslo_concurrency.lockutils [req-841083a7-dcd9-421c-bc01-49a97b19ef43 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:32:42.475 8463 DEBUG nova.compute.api [req-841083a7-dcd9-421c-bc01-49a97b19ef43 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-29 12:32:42.476 8463 DEBUG nova.compute.api [req-841083a7-dcd9-421c-bc01-49a97b19ef43 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-29 12:32:42.478 8463 DEBUG oslo_concurrency.lockutils [req-841083a7-dcd9-421c-bc01-49a97b19ef43 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:32:42.479 8463 DEBUG oslo_concurrency.lockutils [req-841083a7-dcd9-421c-bc01-49a97b19ef43 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:32:42.626 8463 DEBUG nova.policy [req-841083a7-dcd9-421c-bc01-49a97b19ef43 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'bae51265fb0f4505a811a9fab7e142f1', 'roles': [u'ResellerAdmin', u'admin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'671ea1986554476bbcaa620e00697d23', 'project_domain_id': u'default'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-29 12:32:42.634 8463 INFO nova.osapi_compute.wsgi.server [req-841083a7-dcd9-421c-bc01-49a97b19ef43 bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] 10.0.20.25 "GET /v2.1/671ea1986554476bbcaa620e00697d23/servers/detail?all_tenants=True&changes-since=2018-09-29T16%3A27%3A42.017617%2B00%3A00 HTTP/1.1" status: 200 len: 413 time: 0.8723249
2018-09-29 12:33:54.450 8466 DEBUG nova.osapi_compute.wsgi.server [req-682b503b-a482-4a2e-8a91-0f23b10f03da bae51265fb0f4505a811a9fab7e142f1 671ea1986554476bbcaa620e00697d23 - default default] (8466) accepted ('10.0.20.25', 41228) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:33:54.999 8466 DEBUG nova.api.openstack.wsgi [req-340aaf67-fdcc-4c21-92ee-a533f696ef68 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7fb23e5a5090>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:33:55.086 8466 INFO nova.api.openstack.wsgi [req-340aaf67-fdcc-4c21-92ee-a533f696ef68 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] HTTP exception thrown: Flavor m1.tiny could not be found.
2018-09-29 12:33:55.087 8466 DEBUG nova.api.openstack.wsgi [req-340aaf67-fdcc-4c21-92ee-a533f696ef68 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Returning 404 to user: Flavor m1.tiny could not be found. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-29 12:33:55.090 8466 INFO nova.osapi_compute.wsgi.server [req-340aaf67-fdcc-4c21-92ee-a533f696ef68 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/flavors/m1.tiny HTTP/1.1" status: 404 len: 500 time: 0.6340542
2018-09-29 12:33:55.124 8466 DEBUG nova.api.openstack.wsgi [req-2acffe2e-60bb-4599-9969-530c7ba28d2f be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method FlavorsController.index of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7fb23e61a850>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:33:55.235 8466 INFO nova.osapi_compute.wsgi.server [req-2acffe2e-60bb-4599-9969-530c7ba28d2f be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/flavors HTTP/1.1" status: 200 len: 2106 time: 0.1201689
2018-09-29 12:33:55.276 8466 DEBUG nova.api.openstack.wsgi [req-6b02ff02-1946-4cb6-9f41-802a944d2680 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7fb23e5a5090>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:33:55.310 8466 INFO nova.osapi_compute.wsgi.server [req-6b02ff02-1946-4cb6-9f41-802a944d2680 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0436890
2018-09-29 12:33:56.765 8466 DEBUG nova.api.openstack.wsgi [req-825803db-0ef2-461d-891d-a0994efd6e73 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Action: 'create', calling method: <bound method ServersController.create of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e230450>>, body: {"server": {"name": "tempest-INSTANCE_SAMPLE-1538238605", "imageRef": "2bf8a8a2-e190-4363-bd91-93c82458b9ce", "key_name": "tempest-keypair-1538238605", "flavorRef": "1", "max_count": 1, "min_count": 1, "networks": [{"uuid": "7bac259f-f8bd-4417-a9a9-0b5a8f0173c2"}], "security_groups": [{"name": "d2f2d6ff-c20d-4497-bdf2-1ed524015a1b"}]}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-29 12:33:56.788 8466 DEBUG oslo_concurrency.lockutils [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:33:56.789 8466 DEBUG oslo_concurrency.lockutils [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:33:56.813 8466 DEBUG oslo_concurrency.lockutils [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:33:56.814 8466 DEBUG oslo_concurrency.lockutils [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:33:56.870 8466 WARNING nova.image.glance [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] No protocol specified in for api_server 'http://10.0.20.25:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-29 12:34:01.253 8466 DEBUG nova.network.neutronv2.api [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] validate_networks() for [(u'7bac259f-f8bd-4417-a9a9-0b5a8f0173c2', None, None, None)] validate_networks /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1692
2018-09-29 12:34:02.236 8466 DEBUG nova.virt.hardware [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] emulator threads policy constraint: None get_emulator_threads_constraint /usr/lib/python2.7/site-packages/nova/virt/hardware.py:1289
2018-09-29 12:34:02.273 8466 DEBUG nova.quota [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Getting quotas for project b7cb5a03bd1b45069394c794112dd4ee. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-29 12:34:02.279 8466 DEBUG nova.quota [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Getting quotas for user be1a19cb07964dfe8835c001412bfa45 and project b7cb5a03bd1b45069394c794112dd4ee. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-29 12:34:02.326 8466 DEBUG nova.quota [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Getting quotas for project b7cb5a03bd1b45069394c794112dd4ee. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-29 12:34:02.339 8466 DEBUG nova.quota [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Getting quotas for user be1a19cb07964dfe8835c001412bfa45 and project b7cb5a03bd1b45069394c794112dd4ee. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-29 12:34:02.379 8466 DEBUG nova.quota [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Getting quotas for project b7cb5a03bd1b45069394c794112dd4ee. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-29 12:34:02.390 8466 DEBUG nova.quota [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Getting quotas for user be1a19cb07964dfe8835c001412bfa45 and project b7cb5a03bd1b45069394c794112dd4ee. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-29 12:34:02.431 8466 DEBUG nova.context [req-9a7a1816-dd6c-477d-b0a7-6b3e88436269 - - - - -] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-09-29 12:34:02.433 8466 DEBUG oslo_concurrency.lockutils [req-825803db-0ef2-461d-891d-a0994efd6e73 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:02.434 8466 DEBUG oslo_concurrency.lockutils [req-825803db-0ef2-461d-891d-a0994efd6e73 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:02.435 8466 DEBUG oslo_concurrency.lockutils [req-825803db-0ef2-461d-891d-a0994efd6e73 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:02.436 8466 DEBUG oslo_concurrency.lockutils [req-825803db-0ef2-461d-891d-a0994efd6e73 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:02.470 8466 DEBUG nova.quota [req-825803db-0ef2-461d-891d-a0994efd6e73 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Getting quotas for project b7cb5a03bd1b45069394c794112dd4ee. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-29 12:34:02.477 8466 DEBUG nova.quota [req-825803db-0ef2-461d-891d-a0994efd6e73 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Getting quotas for user be1a19cb07964dfe8835c001412bfa45 and project b7cb5a03bd1b45069394c794112dd4ee. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-29 12:34:02.500 8466 DEBUG nova.compute.api [req-825803db-0ef2-461d-891d-a0994efd6e73 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Going to run 1 instances... _provision_instances /usr/lib/python2.7/site-packages/nova/compute/api.py:891
2018-09-29 12:34:02.568 8466 DEBUG nova.compute.api [req-825803db-0ef2-461d-891d-a0994efd6e73 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] [instance: fec64dc4-e0a6-4f42-9103-11836b0ea09e] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='2bf8a8a2-e190-4363-bd91-93c82458b9ce',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _bdm_validate_set_size_and_instance /usr/lib/python2.7/site-packages/nova/compute/api.py:1268
2018-09-29 12:34:02.916 8466 INFO nova.osapi_compute.wsgi.server [req-825803db-0ef2-461d-891d-a0994efd6e73 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "POST /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers HTTP/1.1" status: 202 len: 989 time: 6.1643081
2018-09-29 12:34:02.949 8466 DEBUG nova.api.openstack.wsgi [req-9302ebe1-efd3-46e8-a9c2-da2384d7cc23 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e13b9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:02.951 8466 DEBUG nova.compute.api [req-9302ebe1-efd3-46e8-a9c2-da2384d7cc23 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] [instance: fec64dc4-e0a6-4f42-9103-11836b0ea09e] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-29 12:34:03.039 8466 DEBUG nova.policy [req-9302ebe1-efd3-46e8-a9c2-da2384d7cc23 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'be1a19cb07964dfe8835c001412bfa45', 'roles': [u'admin'], 'user_domain_id': u'99ca94a49e9849b897c53c88ea044896', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b7cb5a03bd1b45069394c794112dd4ee', 'project_domain_id': u'99ca94a49e9849b897c53c88ea044896'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-29 12:34:03.143 8466 INFO nova.osapi_compute.wsgi.server [req-9302ebe1-efd3-46e8-a9c2-da2384d7cc23 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers/fec64dc4-e0a6-4f42-9103-11836b0ea09e HTTP/1.1" status: 200 len: 1857 time: 0.2093339
2018-09-29 12:34:03.256 8466 DEBUG nova.api.openstack.wsgi [req-75dc6deb-3669-4e4b-bd8b-3f5836a8fa38 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7fb23e5a5090>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:03.294 8466 INFO nova.osapi_compute.wsgi.server [req-75dc6deb-3669-4e4b-bd8b-3f5836a8fa38 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0451181
2018-09-29 12:34:08.148 8468 DEBUG nova.osapi_compute.wsgi.server [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] (8468) accepted ('10.0.20.25', 41340) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:34:08.168 8468 WARNING keystonemiddleware.auth_token [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-29 12:34:10.426 8468 INFO nova.osapi_compute.wsgi.server [req-f3ece665-72cb-4b51-84fe-1c542dbda01a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee HTTP/1.1" status: 404 len: 382 time: 2.2710569
2018-09-29 12:34:10.453 8468 DEBUG nova.api.openstack.wsgi [req-12e93687-8a82-4875-bfe3-64c92e3b2478 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7fb23e61a4d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:10.457 8468 INFO nova.osapi_compute.wsgi.server [req-12e93687-8a82-4875-bfe3-64c92e3b2478 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0130370
2018-09-29 12:34:11.040 8468 DEBUG nova.api.openstack.wsgi [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e264550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:11.047 8468 DEBUG nova.compute.api [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Searching by: {'deleted': False, 'project_id': u'b7cb5a03bd1b45069394c794112dd4ee', u'name': u'tempest-INSTANCE_SAMPLE-1538238605'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-29 12:34:11.085 8468 DEBUG oslo_db.sqlalchemy.engines [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:34:11.158 8468 DEBUG oslo_concurrency.lockutils [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:11.161 8468 DEBUG oslo_concurrency.lockutils [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:11.185 8468 DEBUG oslo_db.sqlalchemy.engines [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:34:11.328 8468 DEBUG nova.compute.api [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-29 12:34:11.329 8468 DEBUG nova.compute.api [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-29 12:34:11.330 8468 DEBUG nova.compute.api [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-29 12:34:11.332 8468 DEBUG oslo_concurrency.lockutils [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:11.356 8468 DEBUG oslo_concurrency.lockutils [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.024s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:11.377 8468 DEBUG oslo_db.sqlalchemy.engines [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:34:11.567 8468 INFO nova.osapi_compute.wsgi.server [req-aa609bfe-c29e-46d7-abb9-e998987ed5b5 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers?name=tempest-INSTANCE_SAMPLE-1538238605 HTTP/1.1" status: 200 len: 786 time: 0.5400450
2018-09-29 12:34:11.590 8468 DEBUG nova.api.openstack.wsgi [req-db3b7030-1d6f-41dc-8a33-081f0af6795a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e13b9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:11.592 8468 DEBUG nova.compute.api [req-db3b7030-1d6f-41dc-8a33-081f0af6795a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] [instance: fec64dc4-e0a6-4f42-9103-11836b0ea09e] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-29 12:34:11.991 8468 DEBUG oslo_concurrency.lockutils [req-db3b7030-1d6f-41dc-8a33-081f0af6795a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:11.993 8468 DEBUG oslo_concurrency.lockutils [req-db3b7030-1d6f-41dc-8a33-081f0af6795a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:12.204 8468 DEBUG nova.objects.instance [req-db3b7030-1d6f-41dc-8a33-081f0af6795a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lazy-loading 'services' on Instance uuid fec64dc4-e0a6-4f42-9103-11836b0ea09e obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-29 12:34:12.280 8468 DEBUG nova.policy [req-db3b7030-1d6f-41dc-8a33-081f0af6795a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'be1a19cb07964dfe8835c001412bfa45', 'roles': [u'admin'], 'user_domain_id': u'99ca94a49e9849b897c53c88ea044896', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b7cb5a03bd1b45069394c794112dd4ee', 'project_domain_id': u'99ca94a49e9849b897c53c88ea044896'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-29 12:34:15.542 8468 INFO nova.osapi_compute.wsgi.server [req-db3b7030-1d6f-41dc-8a33-081f0af6795a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers/fec64dc4-e0a6-4f42-9103-11836b0ea09e HTTP/1.1" status: 200 len: 2438 time: 3.9589481
2018-09-29 12:34:17.888 8468 DEBUG nova.osapi_compute.wsgi.server [req-db3b7030-1d6f-41dc-8a33-081f0af6795a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] (8468) accepted ('10.0.20.25', 41504) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:34:18.291 8468 DEBUG nova.api.openstack.wsgi [req-8c8c8d67-25c5-47fe-a01c-bf77a9f64a7d 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7fb23e3eb810>>, body: {"events": [{"tag": "a73554a0-d9d6-4009-828e-843dee47d454", "name": "network-changed", "server_uuid": "fec64dc4-e0a6-4f42-9103-11836b0ea09e"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-29 12:34:18.310 8468 DEBUG oslo_concurrency.lockutils [req-8c8c8d67-25c5-47fe-a01c-bf77a9f64a7d 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:18.311 8468 DEBUG oslo_concurrency.lockutils [req-8c8c8d67-25c5-47fe-a01c-bf77a9f64a7d 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:18.347 8468 INFO nova.api.openstack.compute.server_external_events [req-8c8c8d67-25c5-47fe-a01c-bf77a9f64a7d 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Creating event network-changed:a73554a0-d9d6-4009-828e-843dee47d454 for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e on localhost.localdomain
2018-09-29 12:34:18.518 8468 INFO nova.osapi_compute.wsgi.server [req-8c8c8d67-25c5-47fe-a01c-bf77a9f64a7d 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] 10.0.20.25 "POST /v2.1/671ea1986554476bbcaa620e00697d23/os-server-external-events HTTP/1.1" status: 200 len: 578 time: 0.6282098
2018-09-29 12:34:23.813 8470 DEBUG nova.osapi_compute.wsgi.server [req-94082af0-11ef-4643-866e-f24b99cfbffb c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] (8470) accepted ('10.0.20.25', 41544) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:34:24.041 8470 DEBUG nova.osapi_compute.wsgi.server [req-94082af0-11ef-4643-866e-f24b99cfbffb c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] (8470) accepted ('10.0.20.25', 41548) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:34:24.390 8470 DEBUG nova.api.openstack.wsgi [req-83f9c569-06d7-4739-939e-3dee3edaebd4 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7fb23e3eb810>>, body: {"events": [{"status": "completed", "tag": "a73554a0-d9d6-4009-828e-843dee47d454", "name": "network-vif-plugged", "server_uuid": "fec64dc4-e0a6-4f42-9103-11836b0ea09e"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-29 12:34:24.440 8470 DEBUG oslo_db.sqlalchemy.engines [req-83f9c569-06d7-4739-939e-3dee3edaebd4 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:34:24.492 8470 DEBUG oslo_concurrency.lockutils [req-83f9c569-06d7-4739-939e-3dee3edaebd4 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:24.499 8470 DEBUG oslo_concurrency.lockutils [req-83f9c569-06d7-4739-939e-3dee3edaebd4 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.008s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:24.526 8470 DEBUG oslo_db.sqlalchemy.engines [req-83f9c569-06d7-4739-939e-3dee3edaebd4 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:34:24.581 8470 INFO nova.osapi_compute.wsgi.server [req-faea9c06-d20b-4988-b44f-931cffb01a1e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee HTTP/1.1" status: 404 len: 382 time: 0.5371399
2018-09-29 12:34:24.611 8470 DEBUG nova.api.openstack.wsgi [req-2e3eb749-0fb0-42ae-a593-0fee6614aae7 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7fb23e61a4d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:24.615 8470 INFO nova.osapi_compute.wsgi.server [req-2e3eb749-0fb0-42ae-a593-0fee6614aae7 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0123429
2018-09-29 12:34:24.625 8470 INFO nova.api.openstack.compute.server_external_events [req-2e3eb749-0fb0-42ae-a593-0fee6614aae7 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Creating event network-vif-plugged:a73554a0-d9d6-4009-828e-843dee47d454 for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e on localhost.localdomain
2018-09-29 12:34:24.928 8470 INFO nova.osapi_compute.wsgi.server [req-2e3eb749-0fb0-42ae-a593-0fee6614aae7 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "POST /v2.1/671ea1986554476bbcaa620e00697d23/os-server-external-events HTTP/1.1" status: 200 len: 582 time: 1.1066091
2018-09-29 12:34:25.021 8470 DEBUG nova.api.openstack.wsgi [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e264550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:25.029 8470 DEBUG nova.compute.api [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Searching by: {'deleted': False, 'project_id': u'b7cb5a03bd1b45069394c794112dd4ee', u'name': u'tempest-INSTANCE_SAMPLE-1538238605'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-29 12:34:25.057 8470 DEBUG oslo_concurrency.lockutils [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:25.059 8470 DEBUG oslo_concurrency.lockutils [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:25.541 8470 DEBUG oslo_db.sqlalchemy.engines [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:34:25.663 8470 DEBUG nova.compute.api [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-29 12:34:25.665 8470 DEBUG nova.compute.api [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-29 12:34:25.666 8470 DEBUG nova.compute.api [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-29 12:34:25.669 8470 DEBUG oslo_concurrency.lockutils [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:25.670 8470 DEBUG oslo_concurrency.lockutils [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:25.782 8470 INFO nova.osapi_compute.wsgi.server [req-5f123642-fd3e-4357-b1b3-e681892e61d0 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers?name=tempest-INSTANCE_SAMPLE-1538238605 HTTP/1.1" status: 200 len: 786 time: 0.7796249
2018-09-29 12:34:25.816 8470 DEBUG nova.api.openstack.wsgi [req-327c56db-2e20-4f67-a66e-b9d027e2ca48 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e13b9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:25.818 8470 DEBUG nova.compute.api [req-327c56db-2e20-4f67-a66e-b9d027e2ca48 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] [instance: fec64dc4-e0a6-4f42-9103-11836b0ea09e] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-29 12:34:25.851 8470 DEBUG oslo_concurrency.lockutils [req-327c56db-2e20-4f67-a66e-b9d027e2ca48 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:25.852 8470 DEBUG oslo_concurrency.lockutils [req-327c56db-2e20-4f67-a66e-b9d027e2ca48 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:26.093 8470 DEBUG nova.objects.instance [req-327c56db-2e20-4f67-a66e-b9d027e2ca48 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lazy-loading 'services' on Instance uuid fec64dc4-e0a6-4f42-9103-11836b0ea09e obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-29 12:34:26.221 8470 DEBUG nova.policy [req-327c56db-2e20-4f67-a66e-b9d027e2ca48 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'be1a19cb07964dfe8835c001412bfa45', 'roles': [u'admin'], 'user_domain_id': u'99ca94a49e9849b897c53c88ea044896', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b7cb5a03bd1b45069394c794112dd4ee', 'project_domain_id': u'99ca94a49e9849b897c53c88ea044896'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-29 12:34:27.685 8470 INFO nova.osapi_compute.wsgi.server [req-327c56db-2e20-4f67-a66e-b9d027e2ca48 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers/fec64dc4-e0a6-4f42-9103-11836b0ea09e HTTP/1.1" status: 200 len: 2599 time: 1.8818400
2018-09-29 12:34:57.727 8465 DEBUG nova.osapi_compute.wsgi.server [req-59fea3b8-bfa5-453e-b0db-955add1700d8 c6076d0e968d46daaf0fc5019a0f8a15 bd8a53962fd64ffeab7f2932b0e688c5 - default default] (8465) accepted ('10.0.20.25', 42716) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:34:58.417 8465 DEBUG nova.api.openstack.wsgi [req-cb28d8ed-b4b6-43b0-a11d-afed7d2e13e6 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e13b9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:58.420 8465 DEBUG nova.compute.api [req-cb28d8ed-b4b6-43b0-a11d-afed7d2e13e6 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Failed to fetch instance by id tempest-INSTANCE_SAMPLE-1538238605 get /usr/lib/python2.7/site-packages/nova/compute/api.py:2329
2018-09-29 12:34:58.423 8465 INFO nova.api.openstack.wsgi [req-cb28d8ed-b4b6-43b0-a11d-afed7d2e13e6 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] HTTP exception thrown: Instance tempest-INSTANCE_SAMPLE-1538238605 could not be found.
2018-09-29 12:34:58.425 8465 DEBUG nova.api.openstack.wsgi [req-cb28d8ed-b4b6-43b0-a11d-afed7d2e13e6 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Returning 404 to user: Instance tempest-INSTANCE_SAMPLE-1538238605 could not be found. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-09-29 12:34:58.428 8465 INFO nova.osapi_compute.wsgi.server [req-cb28d8ed-b4b6-43b0-a11d-afed7d2e13e6 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers/tempest-INSTANCE_SAMPLE-1538238605 HTTP/1.1" status: 404 len: 530 time: 0.6974270
2018-09-29 12:34:58.465 8465 DEBUG nova.api.openstack.wsgi [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e264550>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:58.473 8465 DEBUG nova.compute.api [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Searching by: {'deleted': False, 'project_id': u'b7cb5a03bd1b45069394c794112dd4ee', u'name': u'tempest-INSTANCE_SAMPLE-1538238605'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-29 12:34:58.531 8465 DEBUG oslo_concurrency.lockutils [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:58.534 8465 DEBUG oslo_concurrency.lockutils [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:58.578 8465 DEBUG oslo_db.sqlalchemy.engines [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:34:58.730 8465 DEBUG nova.compute.api [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-09-29 12:34:58.732 8465 DEBUG nova.compute.api [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-29 12:34:58.733 8465 DEBUG nova.compute.api [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-29 12:34:58.734 8465 DEBUG oslo_concurrency.lockutils [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:58.741 8465 DEBUG oslo_concurrency.lockutils [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:58.767 8465 DEBUG oslo_db.sqlalchemy.engines [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:34:58.893 8465 INFO nova.osapi_compute.wsgi.server [req-49a161b3-5c12-4375-b1a7-5bf6a527781e be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers?name=tempest-INSTANCE_SAMPLE-1538238605 HTTP/1.1" status: 200 len: 784 time: 0.4407902
2018-09-29 12:34:58.933 8465 DEBUG nova.api.openstack.wsgi [req-31560b2b-b3b5-43d2-a0ce-9fd07586b839 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e13b9d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:34:58.935 8465 DEBUG nova.compute.api [req-31560b2b-b3b5-43d2-a0ce-9fd07586b839 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] [instance: fec64dc4-e0a6-4f42-9103-11836b0ea09e] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-29 12:34:59.506 8465 DEBUG oslo_concurrency.lockutils [req-31560b2b-b3b5-43d2-a0ce-9fd07586b839 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:34:59.507 8465 DEBUG oslo_concurrency.lockutils [req-31560b2b-b3b5-43d2-a0ce-9fd07586b839 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:34:59.784 8465 DEBUG nova.policy [req-31560b2b-b3b5-43d2-a0ce-9fd07586b839 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'be1a19cb07964dfe8835c001412bfa45', 'roles': [u'admin'], 'user_domain_id': u'99ca94a49e9849b897c53c88ea044896', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b7cb5a03bd1b45069394c794112dd4ee', 'project_domain_id': u'99ca94a49e9849b897c53c88ea044896'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-29 12:35:00.575 8478 DEBUG nova.metadata.wsgi.server [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] (8478) accepted ('10.0.20.25', 53334) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:00.662 8478 DEBUG oslo_db.sqlalchemy.engines [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:00.724 8478 DEBUG oslo_concurrency.lockutils [req-5b78393f-3187-420b-a880-4a047a9e2dac - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:00.732 8478 DEBUG oslo_concurrency.lockutils [req-5b78393f-3187-420b-a880-4a047a9e2dac - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.007s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:00.757 8478 DEBUG oslo_db.sqlalchemy.engines [req-5b78393f-3187-420b-a880-4a047a9e2dac - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:01.374 8465 INFO nova.osapi_compute.wsgi.server [req-31560b2b-b3b5-43d2-a0ce-9fd07586b839 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers/fec64dc4-e0a6-4f42-9103-11836b0ea09e HTTP/1.1" status: 200 len: 2206 time: 2.4521611
2018-09-29 12:35:01.406 8465 DEBUG nova.api.openstack.wsgi [req-0061a4d6-6453-458e-8a24-55d5b875571a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Action: 'action', calling method: <function version_select at 0x7fb23e18db18>, body: {"addFloatingIp": {"address": "172.24.4.3"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-29 12:35:01.408 8465 DEBUG nova.compute.api [req-0061a4d6-6453-458e-8a24-55d5b875571a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] [instance: fec64dc4-e0a6-4f42-9103-11836b0ea09e] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-09-29 12:35:01.419 8465 DEBUG oslo_concurrency.lockutils [req-0061a4d6-6453-458e-8a24-55d5b875571a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:01.420 8465 DEBUG oslo_concurrency.lockutils [req-0061a4d6-6453-458e-8a24-55d5b875571a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:01.524 8465 DEBUG oslo_concurrency.lockutils [req-0061a4d6-6453-458e-8a24-55d5b875571a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Acquired semaphore "refresh_cache-fec64dc4-e0a6-4f42-9103-11836b0ea09e" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2018-09-29 12:35:03.532 8465 DEBUG nova.network.neutronv2.api [req-0061a4d6-6453-458e-8a24-55d5b875571a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] [instance: fec64dc4-e0a6-4f42-9103-11836b0ea09e] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1315
2018-09-29 12:35:04.493 8467 DEBUG nova.osapi_compute.wsgi.server [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] (8467) accepted ('10.0.20.25', 42786) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:04.539 8467 WARNING keystonemiddleware.auth_token [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-09-29 12:35:04.967 8478 WARNING oslo_config.cfg [req-5b78393f-3187-420b-a880-4a047a9e2dac - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-29 12:35:04.970 8478 INFO nova.metadata.wsgi.server [req-5b78393f-3187-420b-a880-4a047a9e2dac - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/instance-id HTTP/1.1" status: 200 len: 127 time: 4.3767619
2018-09-29 12:35:05.663 8465 DEBUG nova.network.base_api [req-0061a4d6-6453-458e-8a24-55d5b875571a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] [instance: fec64dc4-e0a6-4f42-9103-11836b0ea09e] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "a73554a0-d9d6-4009-828e-843dee47d454", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [{"meta": {}, "version": 4, "type": "floating", "address": "172.24.4.3"}], "address": "11.40.1.11"}], "version": 4, "meta": {"dhcp_server": "11.40.1.2"}, "dns": [{"meta": {}, "version": 4, "type": "dns", "address": "8.8.4.4"}], "routes": [], "cidr": "11.40.1.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "11.40.1.1"}}], "meta": {"injected": false, "tenant_id": "b7cb5a03bd1b45069394c794112dd4ee", "mtu": 1450}, "id": "7bac259f-f8bd-4417-a9a9-0b5a8f0173c2", "label": "tempest-private-1538238605"}, "devname": "tapa73554a0-d9", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "datapath_type": "system", "ovs_hybrid_plug": true}, "address": "fa:16:3e:15:f4:a5", "active": true, "type": "ovs", "id": "a73554a0-d9d6-4009-828e-843dee47d454", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2018-09-29 12:35:05.699 8465 DEBUG oslo_concurrency.lockutils [req-0061a4d6-6453-458e-8a24-55d5b875571a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Releasing semaphore "refresh_cache-fec64dc4-e0a6-4f42-9103-11836b0ea09e" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2018-09-29 12:35:05.700 8465 INFO nova.osapi_compute.wsgi.server [req-0061a4d6-6453-458e-8a24-55d5b875571a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "POST /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers/fec64dc4-e0a6-4f42-9103-11836b0ea09e/action HTTP/1.1" status: 202 len: 411 time: 4.3033900
2018-09-29 12:35:05.999 8482 DEBUG nova.metadata.wsgi.server [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] (8482) accepted ('10.0.20.25', 53376) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:06.047 8482 DEBUG oslo_db.sqlalchemy.engines [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:06.084 8482 DEBUG oslo_concurrency.lockutils [req-30ea34d4-7c1d-4999-af1c-bf7110e5e0dd - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:06.091 8482 DEBUG oslo_concurrency.lockutils [req-30ea34d4-7c1d-4999-af1c-bf7110e5e0dd - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.007s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:06.109 8482 DEBUG oslo_db.sqlalchemy.engines [req-30ea34d4-7c1d-4999-af1c-bf7110e5e0dd - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:06.200 8467 DEBUG nova.api.openstack.wsgi [req-deaf61cd-11ce-4b33-a6a6-dce9a412796b 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Action: 'create', calling method: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7fb23e3eb810>>, body: {"events": [{"tag": "a73554a0-d9d6-4009-828e-843dee47d454", "name": "network-changed", "server_uuid": "fec64dc4-e0a6-4f42-9103-11836b0ea09e"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-09-29 12:35:06.229 8467 DEBUG oslo_db.sqlalchemy.engines [req-deaf61cd-11ce-4b33-a6a6-dce9a412796b 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:06.270 8467 DEBUG oslo_concurrency.lockutils [req-deaf61cd-11ce-4b33-a6a6-dce9a412796b 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:06.276 8467 DEBUG oslo_concurrency.lockutils [req-deaf61cd-11ce-4b33-a6a6-dce9a412796b 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:06.294 8467 DEBUG oslo_db.sqlalchemy.engines [req-deaf61cd-11ce-4b33-a6a6-dce9a412796b 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:06.363 8467 INFO nova.api.openstack.compute.server_external_events [req-deaf61cd-11ce-4b33-a6a6-dce9a412796b 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] Creating event network-changed:a73554a0-d9d6-4009-828e-843dee47d454 for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e on localhost.localdomain
2018-09-29 12:35:06.525 8467 INFO nova.osapi_compute.wsgi.server [req-deaf61cd-11ce-4b33-a6a6-dce9a412796b 1714b17d5c924b5299512c1217ca1d67 671ea1986554476bbcaa620e00697d23 - default default] 10.0.20.25 "POST /v2.1/671ea1986554476bbcaa620e00697d23/os-server-external-events HTTP/1.1" status: 200 len: 578 time: 1.9986219
2018-09-29 12:35:08.022 8482 WARNING oslo_config.cfg [req-30ea34d4-7c1d-4999-af1c-bf7110e5e0dd - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-29 12:35:08.025 8482 INFO nova.metadata.wsgi.server [req-30ea34d4-7c1d-4999-af1c-bf7110e5e0dd - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/public-keys HTTP/1.1" status: 200 len: 152 time: 2.0207231
2018-09-29 12:35:08.306 8482 DEBUG nova.metadata.wsgi.server [req-30ea34d4-7c1d-4999-af1c-bf7110e5e0dd - - - - -] (8482) accepted ('10.0.20.25', 53402) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:08.309 8482 DEBUG nova.api.metadata.handler [req-30ea34d4-7c1d-4999-af1c-bf7110e5e0dd - - - - -] Using cached metadata for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-29 12:35:08.313 8482 INFO nova.metadata.wsgi.server [req-30ea34d4-7c1d-4999-af1c-bf7110e5e0dd - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/public-keys/0/openssh-key HTTP/1.1" status: 200 len: 526 time: 0.0041201
2018-09-29 12:35:09.572 8483 DEBUG nova.metadata.wsgi.server [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] (8483) accepted ('10.0.20.25', 53414) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:09.656 8483 DEBUG oslo_db.sqlalchemy.engines [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:09.724 8483 DEBUG oslo_concurrency.lockutils [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:09.733 8483 DEBUG oslo_concurrency.lockutils [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.010s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:09.764 8483 DEBUG oslo_db.sqlalchemy.engines [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:12.176 8483 WARNING oslo_config.cfg [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-29 12:35:12.180 8483 INFO nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/instance-id HTTP/1.1" status: 200 len: 127 time: 2.5940831
2018-09-29 12:35:13.273 8486 DEBUG nova.metadata.wsgi.server [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] (8486) accepted ('10.0.20.25', 53432) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:13.322 8486 DEBUG oslo_db.sqlalchemy.engines [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:13.373 8486 DEBUG oslo_concurrency.lockutils [req-5c875bf6-ff56-42d1-9ce2-e04db4b4c433 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:13.381 8486 DEBUG oslo_concurrency.lockutils [req-5c875bf6-ff56-42d1-9ce2-e04db4b4c433 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.009s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:13.408 8486 DEBUG oslo_db.sqlalchemy.engines [req-5c875bf6-ff56-42d1-9ce2-e04db4b4c433 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:15.658 8486 WARNING oslo_config.cfg [req-5c875bf6-ff56-42d1-9ce2-e04db4b4c433 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-29 12:35:15.663 8486 INFO nova.metadata.wsgi.server [req-5c875bf6-ff56-42d1-9ce2-e04db4b4c433 - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/ami-launch-index HTTP/1.1" status: 200 len: 117 time: 2.3820050
2018-09-29 12:35:15.975 8483 DEBUG nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] (8483) accepted ('10.0.20.25', 53446) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:15.979 8483 DEBUG nova.api.metadata.handler [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] Using cached metadata for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-29 12:35:15.981 8483 INFO nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/instance-type HTTP/1.1" status: 200 len: 123 time: 0.0029371
2018-09-29 12:35:16.224 8465 DEBUG nova.osapi_compute.wsgi.server [req-0061a4d6-6453-458e-8a24-55d5b875571a be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] (8465) accepted ('10.0.20.25', 42876) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:16.291 8483 DEBUG nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] (8483) accepted ('10.0.20.25', 53452) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:16.295 8483 DEBUG nova.api.metadata.handler [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] Using cached metadata for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-29 12:35:16.297 8483 INFO nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/local-ipv4 HTTP/1.1" status: 200 len: 127 time: 0.0025151
2018-09-29 12:35:16.614 8479 DEBUG nova.metadata.wsgi.server [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] (8479) accepted ('10.0.20.25', 53454) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:16.699 8479 DEBUG oslo_db.sqlalchemy.engines [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:16.788 8479 DEBUG oslo_concurrency.lockutils [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:16.801 8479 DEBUG oslo_concurrency.lockutils [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.013s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:16.834 8479 DEBUG oslo_db.sqlalchemy.engines [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:16.856 8465 INFO nova.osapi_compute.wsgi.server [req-03e2edd3-24cb-4437-9067-9684057d36c4 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee HTTP/1.1" status: 404 len: 382 time: 0.6297271
2018-09-29 12:35:16.883 8465 DEBUG nova.api.openstack.wsgi [req-33a7efdf-f7b6-4bbd-bc68-79f44903a504 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7fb23e61a4d0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:35:16.888 8465 INFO nova.osapi_compute.wsgi.server [req-33a7efdf-f7b6-4bbd-bc68-79f44903a504 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0152450
2018-09-29 12:35:17.216 8465 DEBUG nova.api.openstack.wsgi [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7fb23e21b690>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-09-29 12:35:17.220 8465 DEBUG nova.compute.api [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Searching by: {'deleted': False, 'project_id': u'b7cb5a03bd1b45069394c794112dd4ee'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-09-29 12:35:17.242 8465 DEBUG oslo_concurrency.lockutils [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:17.243 8465 DEBUG oslo_concurrency.lockutils [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:17.398 8465 DEBUG nova.compute.api [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-09-29 12:35:17.400 8465 DEBUG nova.compute.api [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Listing 1000 instances in cell 7d2d29ce-c1fb-484d-a8c0-d22d93f3a902(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-09-29 12:35:17.402 8465 DEBUG oslo_concurrency.lockutils [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:17.403 8465 DEBUG oslo_concurrency.lockutils [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:17.570 8465 DEBUG oslo_concurrency.lockutils [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:17.572 8465 DEBUG oslo_concurrency.lockutils [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:17.588 8465 DEBUG nova.policy [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'be1a19cb07964dfe8835c001412bfa45', 'roles': [u'admin'], 'user_domain_id': u'99ca94a49e9849b897c53c88ea044896', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'b7cb5a03bd1b45069394c794112dd4ee', 'project_domain_id': u'99ca94a49e9849b897c53c88ea044896'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-09-29 12:35:18.561 8465 INFO nova.osapi_compute.wsgi.server [req-866fdc37-9a99-405d-a28f-f27f60f65c10 be1a19cb07964dfe8835c001412bfa45 b7cb5a03bd1b45069394c794112dd4ee - 99ca94a49e9849b897c53c88ea044896 99ca94a49e9849b897c53c88ea044896] 10.0.20.25 "GET /v2.1/b7cb5a03bd1b45069394c794112dd4ee/servers/detail HTTP/1.1" status: 200 len: 2719 time: 1.3539062
2018-09-29 12:35:19.372 8479 WARNING oslo_config.cfg [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-29 12:35:19.379 8479 INFO nova.metadata.wsgi.server [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/public-ipv4 HTTP/1.1" status: 200 len: 127 time: 2.7587159
2018-09-29 12:35:20.541 8481 DEBUG nova.metadata.wsgi.server [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] (8481) accepted ('10.0.20.25', 53486) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:20.614 8481 DEBUG oslo_db.sqlalchemy.engines [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:20.692 8481 DEBUG oslo_concurrency.lockutils [req-e47c9a5c-00c3-47a2-bf81-dcb4dc33ac37 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:20.708 8481 DEBUG oslo_concurrency.lockutils [req-e47c9a5c-00c3-47a2-bf81-dcb4dc33ac37 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.016s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:20.736 8481 DEBUG oslo_db.sqlalchemy.engines [req-e47c9a5c-00c3-47a2-bf81-dcb4dc33ac37 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:23.302 8481 WARNING oslo_config.cfg [req-e47c9a5c-00c3-47a2-bf81-dcb4dc33ac37 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-29 12:35:23.304 8481 INFO nova.metadata.wsgi.server [req-e47c9a5c-00c3-47a2-bf81-dcb4dc33ac37 - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/hostname HTTP/1.1" status: 200 len: 161 time: 2.7496440
2018-09-29 12:35:23.597 8479 DEBUG nova.metadata.wsgi.server [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] (8479) accepted ('10.0.20.25', 53498) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:23.600 8479 DEBUG nova.api.metadata.handler [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] Using cached metadata for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-29 12:35:23.602 8479 INFO nova.metadata.wsgi.server [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/local-hostname HTTP/1.1" status: 200 len: 161 time: 0.0030260
2018-09-29 12:35:24.182 8479 DEBUG nova.metadata.wsgi.server [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] (8479) accepted ('10.0.20.25', 53504) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:24.187 8479 DEBUG nova.api.metadata.handler [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] Using cached metadata for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-29 12:35:24.190 8479 INFO nova.metadata.wsgi.server [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/user-data HTTP/1.1" status: 404 len: 176 time: 0.0036190
2018-09-29 12:35:24.460 8483 DEBUG nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] (8483) accepted ('10.0.20.25', 53508) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:24.462 8483 DEBUG nova.api.metadata.handler [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] Using cached metadata for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-29 12:35:24.465 8483 INFO nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/block-device-mapping HTTP/1.1" status: 200 len: 124 time: 0.0029020
2018-09-29 12:35:25.095 8483 DEBUG nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] (8483) accepted ('10.0.20.25', 53514) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:25.100 8483 DEBUG nova.api.metadata.handler [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] Using cached metadata for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-29 12:35:25.103 8483 INFO nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/block-device-mapping/ami HTTP/1.1" status: 200 len: 119 time: 0.0039921
2018-09-29 12:35:25.398 8483 DEBUG nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] (8483) accepted ('10.0.20.25', 53516) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:25.403 8483 DEBUG nova.api.metadata.handler [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] Using cached metadata for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-29 12:35:25.406 8483 INFO nova.metadata.wsgi.server [req-20db0b03-6cdd-489a-bc52-3c25395a5afa - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/block-device-mapping/root HTTP/1.1" status: 200 len: 124 time: 0.0049641
2018-09-29 12:35:26.092 8479 DEBUG nova.metadata.wsgi.server [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] (8479) accepted ('10.0.20.25', 53522) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:26.096 8479 DEBUG nova.api.metadata.handler [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] Using cached metadata for instance fec64dc4-e0a6-4f42-9103-11836b0ea09e get_metadata_by_instance_id /usr/lib/python2.7/site-packages/nova/api/metadata/handler.py:78
2018-09-29 12:35:26.099 8479 INFO nova.metadata.wsgi.server [req-d0017590-7dc0-491a-92bd-b6399d0778a2 - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/public-hostname HTTP/1.1" status: 200 len: 161 time: 0.0037069
2018-09-29 12:35:26.410 8477 DEBUG nova.metadata.wsgi.server [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] (8477) accepted ('10.0.20.25', 53524) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-09-29 12:35:26.539 8477 DEBUG oslo_db.sqlalchemy.engines [req-63f0655d-4cd3-4181-adac-c463d2fff6f3 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:26.598 8477 DEBUG oslo_concurrency.lockutils [req-ae3aacc0-a163-49ae-9c9e-806545eed163 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-29 12:35:26.608 8477 DEBUG oslo_concurrency.lockutils [req-ae3aacc0-a163-49ae-9c9e-806545eed163 - - - - -] Lock "7d2d29ce-c1fb-484d-a8c0-d22d93f3a902" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.010s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-29 12:35:26.633 8477 DEBUG oslo_db.sqlalchemy.engines [req-ae3aacc0-a163-49ae-9c9e-806545eed163 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-29 12:35:28.804 8477 WARNING oslo_config.cfg [req-ae3aacc0-a163-49ae-9c9e-806545eed163 - - - - -] Option "dhcp_domain" from group "DEFAULT" is deprecated for removal (
nova-network is deprecated, as are any related configuration options.
).  Its value may be silently ignored in the future.
2018-09-29 12:35:28.808 8477 INFO nova.metadata.wsgi.server [req-ae3aacc0-a163-49ae-9c9e-806545eed163 - - - - -] 11.40.1.11,10.0.20.25 "GET /2009-04-04/meta-data/placement/availability-zone HTTP/1.1" status: 200 len: 120 time: 2.3795769
